### ISSUE TITLE
save: no error/warning on incorrectly provided path

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3566] opened 2019-07-29 16:21 UTC
unlike in https://github.com/datalad/datalad/issues/2505 where file was removed, here I had no file to start with, but save doesn't complain at all:

```shell
~ > datalad create /tmp/testds3 && cd /tmp/testds3 && touch correct && datalad save incorrect
[INFO   ] Creating a new annex repo at /tmp/testds3 
create(ok): /tmp/testds3 (dataset)                                               

/tmp/testds3 > echo $?
0

/tmp/testds3 > git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	correct

nothing added to commit but untracked files present (use "git add" to track)

/tmp/testds3 > datalad --version          
datalad 0.12.0rc4.dev248
```
expected behavior -- issue at least a warning or even crash with an error (--amending commits in hierarchy might be tricky) if some provided path is not known to git and does not exist.  

FTR: Behavior is good (in this particular respect ;)) in 0.11.x (0.11.5-307-g632fdc34b):

```shell
 > datalad create /tmp/testds4 && cd /tmp/testds4 && touch correct && datalad save incorrect                                                          
[INFO   ] Creating a new annex repo at /tmp/testds4          
create(ok): /tmp/testds4 (dataset)
[WARNING] path does not exist: /tmp/testds4/incorrect [save(/tmp/testds4/incorrect)] 
save(impossible): /tmp/testds4/incorrect [path does not exist: /tmp/testds4/incorrect]

/tmp/testds4 > echo $?
1
```

but fails to save the "removal"
```
/tmp/testds4 > datalad add -m adding correct 
add(ok): /tmp/testds4/correct (file)
save(ok): /tmp/testds4 (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)

/tmp/testds4 > datalad save incorrect           
[WARNING] path does not exist: /tmp/testds4/incorrect [save(/tmp/testds4/incorrect)] 
save(impossible): /tmp/testds4/incorrect [path does not exist: /tmp/testds4/incorrect]

/tmp/testds4 > rm correct

/tmp/testds4 > datalad save correct  
[WARNING] path does not exist: /tmp/testds4/correct [save(/tmp/testds4/correct)] 
save(impossible): /tmp/testds4/correct [path does not exist: /tmp/testds4/correct]
```

**Comment by kyleam** [comment] 2019-12-14 16:27
gh-3844 is a duplicate of this issue.  I'll close this one because gh-3844 has received a comment and has a bit of analysis about the underlying reason.

**Closed by kyleam** 2019-12-14 16:27 UTC
