### ISSUE TITLE
Git-annex 8.20210223 is broken in a Condor job 

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#5546] opened 2021-04-07 10:55 UTC
I haven't pinpointed where the issue is, so the title of the issue may be misleading, and it could be something on our cluster that is at fault.

After an upgrade to git-annex 8.20210223 a previously working workflow of mine crashes. The workflow executes a shell script with a datalad based analysis through condor. Once basically any datalad-related command is executed, ~git-annex~ git complains about not finding basic shell functionality:

```
+ datalad clone ria+file:///data/group/psyinf/myinputstore#32296733-7386-4e81-afcc-37eb33f34144 ds
Traceback (most recent call last):
  File "/usr/bin/datalad", line 11, in <module>
    load_entry_point('datalad==0.14.0', 'console_scripts', 'datalad')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/datalad/__init__.py", line 47, in <module>
    cfg = ConfigManager()
  File "/usr/lib/python3/dist-packages/datalad/config.py", line 274, in __init__
    self.reload(force=True)
  File "/usr/lib/python3/dist-packages/datalad/config.py", line 327, in reload
    self._stores[store_id] = self._reload(runargs)
  File "/usr/lib/python3/dist-packages/datalad/config.py", line 359, in _reload
    encoding='utf-8',
  File "/usr/lib/python3/dist-packages/datalad/config.py", line 717, in _run
    out = self._runner.run(self._config_cmd + args, **kwargs)
  File "/usr/lib/python3/dist-packages/datalad/cmd.py", line 413, in run
    **results,
datalad.support.exceptions.CommandError: CommandError: 'git --git-dir= config -z -l --show-origin' failed with exitcode 1 [err: '/usr/lib/git-annex.linux/git: 2: /usr/lib/git-annex.linux/git: readlink: not found
/usr/lib/git-annex.linux/git: 6: /usr/lib/git-annex.linux/git: dirname: not found
** cannot find base directory (I seem to be /usr/lib/git-annex.linux/git)']
```

This fails reliably, for all jobs, for common datalad operations (I have tried clone and create). Nevertheless, I can not reproduce this outside a Condor job. I have tried to trigger it on compute nodes that were affected outside a condor job, and I have tried to SSH into the job and trigger it in an interactive session - it works fine in these cases. The head node and compute nodes have the same annex version, but between the working state and the current broken state there was a system-wide git-annex update.

Current git-annex version:

```
git-annex version: 8.20210223-1~ndall+1
build flags: Assistant Webapp Pairing Inotify DBus DesktopNotify TorrentParser MagicMime Feeds Testsuite S3 WebDAV
dependency versions: aws-0.20 bloomfilter-2.0.1.0 cryptonite-0.25 DAV-1.3.3 feed-1.0.0.0 ghc-8.4.4 http-client-0.5.13.1 persistent-sqlite-2.8.2 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.0
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL X*
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs httpalso borg hook external
operating system: linux x86_64
supported repository versions: 8
upgrade supported from repository versions: 0 1 2 3 4 5 6 7
```

<details><summary>Here is the output of ``set`` inside the compute job:</summary>

```
BASH=/bin/bash
BASHOPTS=checkwinsize:cmdhist:complete_fullquote:extquote:force_fignore:globasciiranges:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_LINENO=([0]="0")
BASH_SOURCE=([0]="/var/lib/condor/execute/dir_3170/condor_exec.exe")
BASH_VERSINFO=([0]="5" [1]="0" [2]="3" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
BASH_VERSION='5.0.3(1)-release'
BATCH_SYSTEM=HTCondor
DATALAD_GET_SUBDATASET__SOURCE__CANDIDATE__101cat='ria+http://containers.ds.inm7.de#{id}'
DIRSTACK=()
DSLOCKFILE=/data/group/psyinf/ukb_workflow_template/forrest/.condor_datalad_lock
EUID=42000
GIT_AUTHOR_EMAIL=adina.wagner@t-online.de
GIT_AUTHOR_NAME='Adina Wagner'
GROUPS=()
HOSTNAME=cpu16
HOSTTYPE=x86_64
IFS=$' \t\n'
JOBID=14.463529
MACHTYPE=x86_64-pc-linux-gnu
OMP_NUM_THREADS=1
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:.
PIPESTATUS=([0]="0")
PPID=3170
PS4='+ '
PWD=/var/lib/condor/execute/dir_3170
SHELL=/usr/bin/zsh
SHELLOPTS=braceexpand:errexit:hashall:interactive-comments:nounset:xtrace
SHLVL=1
TEMP=/var/lib/condor/execute/dir_3170
TERM=dumb
TMP=/var/lib/condor/execute/dir_3170
TMPDIR=/var/lib/condor/execute/dir_3170
UID=42000
_=
_CHIRP_DELAYED_UPDATE_PREFIX='Chirp*'
_CONDOR_ANCESTOR_28450=28485:1614348909:2681609250
_CONDOR_ANCESTOR_28485=3170:1617789945:1009793848
_CONDOR_ANCESTOR_3170=3177:1617789945:612364609
_CONDOR_CHIRP_CONFIG=/var/lib/condor/execute/dir_3170/.chirp.config
_CONDOR_JOB_AD=/var/lib/condor/execute/dir_3170/.job.ad
_CONDOR_JOB_IWD=/var/lib/condor/execute/dir_3170
_CONDOR_JOB_PIDS=
_CONDOR_MACHINE_AD=/var/lib/condor/execute/dir_3170/.machine.ad
_CONDOR_SCRATCH_DIR=/var/lib/condor/execute/dir_3170
_CONDOR_SLOT=slot1_16
dssource=ria+file:///data/group/psyinf/myinputstore#32296733-7386-4e81-afcc-37eb33f34144
pushgitremote=/data/group/psyinf/myoutputstore/322/96733-7386-4e81-afcc-37eb33f34144
subid=sub-14
```
</details>

Does anyone have an idea how I can debug this, or an idea what may be the problem?

**Comment by mih** [comment] 2021-04-07 11:16
Note that this is the -standalone flavor:

```
% apt-cache policy git-annex-standalone
git-annex-standalone:
  Installed: 8.20210223-1~ndall+1
  Candidate: 8.20210223-1~ndall+1
  Version table:
 *** 8.20210223-1~ndall+1 500
        500 http://neurodebian.mirror.htc.inm7.de/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

we have test-upgraded from `git-annex (8.20200330-1~bpo10+1) ` (from Debian backports) to investigate a random stalling of a `git-annex get`.

**Comment by bpoldrack** [comment] 2021-04-07 12:01
At a first glance, looks a bit like `ConfigManager`'s default runner (not yet bound to a dataset!) doesn't correctly deal with the standalone bundle?

> not finding basic shell functionality:

Which would be? Doesn't look like `dirname` is missing, given the following message `cannot find base directory`.  I may be wrong, of course - it *is* rather confusing.

**Comment by bpoldrack** [comment] 2021-04-07 12:06
Environment also doesn't show any sign of adjustement by `GitRunner` (or do I just not spot it?)

**Comment by adswa** [comment] 2021-04-07 12:08
> At a first glance, looks a bit like ConfigManager's default runner (not yet bound to a dataset!) doesn't correctly deal with the standalone bundle?

How could I check if the default runner is at fault? Do I interpret the "not yet bound to a dataset" in your message correctly that the error may not surface when I run something inside of a dataset?

> Which would be? Doesn't look like dirname is missing, given the following message cannot find base directory. I may be wrong, of course - it is rather confusing.

But it also can not find ``readlink`` (``readlink: not found``), which is pretty weird on GNU/Linux, right?

**Comment by bpoldrack** [comment] 2021-04-07 12:14
> Do I interpret the "not yet bound to a dataset" in your message correctly that the error may not surface when I run something inside of a dataset?

No. What I meant is, that `ConfigManager` does instantiate its own runner (which still should be the right kind), when not bound to a dataset. But this is always the case on datalad startup - this part of hte tracceback:

```
File "/usr/lib/python3/dist-packages/datalad/__init__.py", line 47, in <module>
    cfg = ConfigManager()
```

It is weird, yes. But I interprete it as the path not being found rather than `readlink/dirname`, since the error message suggests that it's trying to do exactly what `dirname` should. Are you sure `/usr/lib/git-annex.linux/git` exists within the job?

**Comment by adswa** [comment] 2021-04-07 12:20
One thing that may be relevant:
Its not git-annex/Git per se that crashes (running ``git --version`` or ``git annex version`` is fine), but any command that uses datalad.

>Are you sure /usr/lib/git-annex.linux/git exists within the job?

Yes, I've submitted a job with a plain ``ls -l`` on that path, and it returns 
```
-rwxr-xr-x 1 root root 505 Feb 25 17:09 /usr/lib/git-annex.linux/git
```

**Comment by bpoldrack** [comment] 2021-04-07 12:21
So, to me looks like `GitWitlessRunner` comes to the conclusion that `/usr/lib/git-annex.linux/git` should be used as the git executable, but this is either wrong to begin with or it doesn't exist/is a broken symlink.

> -rwxr-xr-x 1 root root 505 Feb 25 17:09 /usr/lib/git-annex.linux/git

That's suspiciously small in my mind.

**Comment by mih** [comment] 2021-04-07 12:24
@bpoldrack you could look on juseless yourself. The file size is to be expected, it is the normal wrapper script. The point of this issue is that the *standalone* git-annex triggers the problem.

**Comment by adswa** [comment] 2021-04-07 12:25
> So, to me looks like GitWitlessRunner comes to the conclusion that /usr/lib/git-annex.linux/git should be used as the git executable, but this is either wrong to begin with 

But isn't the git-annex standalone the "standalone" version of git-annex because it includes a Git executable? 

> ... or it doesn't exist/is a broken symlink.

I've SSH'd into the job, and it seems fine:

```
condor_ssh_to_job 463553                                                                                              1 !
Welcome to slot1_11@cpu2.htc.inm7.de!
Your condor job is running with pid(s) 9847.
adina@cpu2 in /var/lib/condor/execute/dir_9843
❱ ls -l /usr/lib/git-annex.linux/git
-rwxr-xr-x 1 root root 505 Feb 25 17:09 /usr/lib/git-annex.linux/git
adina@cpu2 in /var/lib/condor/execute/dir_9843
❱ ls -lh /usr/lib/git-annex.linux/git
-rwxr-xr-x 1 root root 505 Feb 25 17:09 /usr/lib/git-annex.linux/git
adina@cpu2 in /var/lib/condor/execute/dir_9843
❱ /usr/lib/git-annex.linux/git 
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone     Clone a repository into a new directory
   init      Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add       Add file contents to the index
   mv        Move or rename a file, a directory, or a symlink
   restore   Restore working tree files
   rm        Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect    Use binary search to find the commit that introduced a bug
   diff      Show changes between commits, commit and working tree, etc
   grep      Print lines matching a pattern
   log       Show commit logs
   show      Show various types of objects
   status    Show the working tree status

grow, mark and tweak your common history
   branch    List, create, or delete branches
   commit    Record changes to the repository
   merge     Join two or more development histories together
   rebase    Reapply commits on top of another base tip
   reset     Reset current HEAD to the specified state
   switch    Switch branches
   tag       Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch     Download objects and refs from another repository
   pull      Fetch from and integrate with another repository or a local branch
   push      Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
See 'git help git' for an overview of the system.

```

**Comment by adswa** [comment] 2021-04-07 12:26
> Can you execute that explicitly, @adswa ? So, rather than tring just git --version, what about /usr/lib/git-annex.linux/git --version?

Also tried it in a script submitted as a job, works fine

**Comment by bpoldrack** [comment] 2021-04-07 12:36
Yes, @mih - just had a look. Wasn't used to that script. Explains the error message as well - so forget what I said ;-)

However, all the more reason to believe that there's something wrong with `GitWitlessRunner` somehow damaging the env.

**Comment by yarikoptic** [comment] 2021-04-07 13:24
sorry if I have missed this part of investigation, but since standalone does not come with it
```
$> dpkg -L git-annex-standalone | grep -e readlink -e dirname
```
I wonder if coreutils is installed on the system, to provide those:
```
$> dpkg -L coreutils | grep -e dirname -e readlink
/bin/readlink
/usr/bin/dirname
/usr/share/man/man1/dirname.1.gz
/usr/share/man/man1/readlink.1.gz
```
if they are available system wide, then indeed smth (could as well be git-annex standalone shim) screwing up PATH?

**Comment by bpoldrack** [comment] 2021-04-07 13:27
> if they are available system wide, then indeed smth (could as well be git-annex standalone shim) screwing up PATH?

It's available systemwide. So screwing up PATH somehow is what I'm looking for, but I can't find where we'd do it wrong in `cmd.py` and `config.py`.

**Comment by bpoldrack** [comment] 2021-04-07 13:59
> could as well be git-annex standalone shim

Don't think so. It's the wrapper script itself (`/usr/lib/git-annex.linux/git`) that fails before calling `runshell`. So, it's us somehow calling it w/ wrong/screwed PATH, I think.

**Comment by yarikoptic** [comment] 2021-04-07 14:10
> > could as well be git-annex standalone shim
> 
> Don't think so. It's the wrapper script itself (`/usr/lib/git-annex.linux/git`) that fails before calling `runshell`. So, it's us somehow calling it w/ wrong/screwed PATH, I think.

are you certain it is not a nested (within runshell) call to `git`? (I am not sure if such thing can happen, just throwing "smart ideas" ;) )

**Comment by bpoldrack** [comment] 2021-04-07 14:16
Well - no, not certain it's not a nested call. :)

However, apparently doesn't happen outside of a condor job. Which speaks against a simple PATH issue (correct PATH handling would be crucial outside, too). And if `runshell` would screw things up in this standalone build, it should happen outside condor job as well.

**Comment by adswa** [comment] 2021-04-07 14:25
FTR, if it got lost in the details in the issue description, the ``PATH`` in the condor job is ``PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:.``

**Comment by bpoldrack** [comment] 2021-04-07 14:33
Yes, @adswa. But we call `git-config` from within datalad. And the idea was that we not correctly prepend that PATH with the path to the standalone bundle, but replace instead (or something similar), thereby killing the PATH (or parts thereof) you just quoted and ultimately loosing `/usr/bin`.

**Comment by bpoldrack** [comment] 2021-04-07 14:41
Observation:

I can't for the love of god get the log messages from `GitRunnerBase._check_git_path()`, which should state what git we are trying to use. Using log level 1 I don't get either one. Neither locally on master nor on juseless.

**Comment by adswa** [comment] 2021-04-13 06:33
I haven't gotten any further in narrowing this down and I also could not create a minimal reproducer, but @aqw and I just checked that a change to the previous git-annex version fixes this.
So we can observe the failure with the with: git-annex-standalone 8.20210223-1~ndall+1
And the workflow succeeds with: git-annex 8.20200330-1~bpo10+1.

**Comment by bpoldrack** [comment] 2021-04-15 10:37
> So we can observe the failure with the with: git-annex-standalone 8.20210223-1~ndall+1
And the workflow succeeds with: git-annex 8.20200330-1~bpo10+1.

To clarify: So you not only switched version but also standalone vs "standard", right?

**Comment by adswa** [comment] 2021-04-15 10:50
yes

**Comment by yarikoptic** [comment] 2021-04-20 16:29
issue boiled down to have no `PATH` exported (not just set) in `code/participant_job`. IMHO nothing to be fixed on git-annex or datalad end. Closing. please reopen if disagree

**Closed by yarikoptic** 2021-04-20 16:29 UTC

**Comment by mih** [comment] 2021-04-20 16:51
I am fine to have this closed, but I don't understand the solution. `code/participant_job` is a shell script that calls other shell scripts. Condor sets up an env that has `PATH` set. Why does it need to export `PATH` to be in effect, but not `GIT_AUTHOR_NAME` or `TMPDIR` which are also used -- the former set by the job (successfully) and the latter by condor settings (also successfully).

**Comment by yarikoptic** [comment] 2021-04-20 18:12
> Condor sets up an env that has PATH set.

it sets it but doesn't export.  So it is available ONLY within the `code/participant_job` namespace and not within commands which are executed by it (since not exported).

demo:
```
$> cat command.sh 
#!/bin/bash
set -x
blah=buga
set | grep blah
export | grep blah
echo "command blah=$blah"
./subcommand.sh
1 74056.....................................:Tue 20 Apr 2021 02:12:33 PM EDT:.
lena:/tmp
$> cat subcommand.sh 
#!/bin/bash

echo "blah=${blah}"
1 74057.....................................:Tue 20 Apr 2021 02:12:35 PM EDT:.
lena:/tmp
$> bash command.sh 
+ blah=buga
+ set
+ grep blah
blah=buga
+ export
+ grep blah
+ echo 'command blah=buga'
command blah=buga
+ ./subcommand.sh
blah=
```

**Comment by yarikoptic** [comment] 2021-04-20 18:16
>  but not GIT_AUTHOR_NAME or TMPDIR which are also used

you do prescribe (and I guess that is what condor exports) them explicitly, while completely overloading the rest (due to that setenv=True?) of the environment in code/process.condor_submit
```
environment = "\
  JOBID=$(subject).$(Cluster) \
  DSLOCKFILE=$ENV(PWD)/.condor_datalad_lock \
  DATALAD_GET_SUBDATASET__SOURCE__CANDIDATE__101cat='ria+http://containers.ds.inm7.de#{id}' \
  GIT_AUTHOR_NAME='Yaroslav Halchenko' \
  GIT_AUTHOR_EMAIL='debian@onerussian.com' \
  "
```
so those are available inside the job script exported:
```
$> cat /tmp/export-withincondor 
declare -x BATCH_SYSTEM="HTCondor"
declare -x DATALAD_GET_SUBDATASET__SOURCE__CANDIDATE__101cat="ria+http://containers.ds.inm7.de#{id}"
declare -x DSLOCKFILE="/mnt/btrfs/scrap/tmp/condor-annex-gotcha/processing-workflow/forrest/.condor_datalad_lock"
declare -x GIT_AUTHOR_EMAIL="debian@onerussian.com"
declare -x GIT_AUTHOR_NAME="Yaroslav Halchenko"
declare -x JOBID="01.1998"
declare -x OLDPWD
declare -x OMP_NUM_THREADS="1"
declare -x PWD="/mnt/btrfs/scrap/tmp/condor-annex-gotcha/processing-workflow/forrest"
declare -x SHLVL="1"
declare -x TEMP="/var/lib/condor/execute/dir_54491"
declare -x TMP="/var/lib/condor/execute/dir_54491"
declare -x TMPDIR="/var/lib/condor/execute/dir_54491"
declare -x _CHIRP_DELAYED_UPDATE_PREFIX="Chirp*"
declare -x _CONDOR_ANCESTOR_54491="54507:1618935803:2445902237"
declare -x _CONDOR_ANCESTOR_7458="7532:1618928019:2534314531"
declare -x _CONDOR_ANCESTOR_7532="54491:1618935800:3893131616"
declare -x _CONDOR_CHIRP_CONFIG="/var/lib/condor/execute/dir_54491/.chirp.config"
declare -x _CONDOR_JOB_AD="/var/lib/condor/execute/dir_54491/.job.ad"
declare -x _CONDOR_JOB_IWD="/mnt/btrfs/scrap/tmp/condor-annex-gotcha/processing-workflow/forrest"
declare -x _CONDOR_JOB_PIDS=""
declare -x _CONDOR_MACHINE_AD="/var/lib/condor/execute/dir_54491/.machine.ad"
declare -x _CONDOR_SCRATCH_DIR="/var/lib/condor/execute/dir_54491"
declare -x _CONDOR_SLOT="slot1"
```

**Comment by yarikoptic** [comment] 2021-04-20 18:38
But you made me wonder @mih : how does `datalad` find `git-annex`?
I have checked -- it gets `None` for the PATH in os.environ.  

<details>
<summary>and here is how to reproduce the issue without condor:</summary> 

```shell
$> ( unset PATH; /usr/bin/datalad clone ///; )
Traceback (most recent call last):
  File "/usr/bin/datalad", line 11, in <module>
    load_entry_point('datalad==0.14.0', 'console_scripts', 'datalad')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/datalad/__init__.py", line 47, in <module>
    cfg = ConfigManager()
  File "/usr/lib/python3/dist-packages/datalad/config.py", line 274, in __init__
    self.reload(force=True)
  File "/usr/lib/python3/dist-packages/datalad/config.py", line 327, in reload
    self._stores[store_id] = self._reload(runargs)
  File "/usr/lib/python3/dist-packages/datalad/config.py", line 359, in _reload
    encoding='utf-8',
  File "/usr/lib/python3/dist-packages/datalad/config.py", line 717, in _run
    out = self._runner.run(self._config_cmd + args, **kwargs)
  File "/usr/lib/python3/dist-packages/datalad/cmd.py", line 413, in run
    **results,
datalad.support.exceptions.CommandError: CommandError: 'git --git-dir= config -z -l --show-origin' failed with exitcode 1 [err: '/usr/lib/git-annex.linux/git: 2: /usr/lib/git-annex.linux/git: readlink: not found
/usr/lib/git-annex.linux/git: 6: /usr/lib/git-annex.linux/git: dirname: not found
** cannot find base directory (I seem to be /usr/lib/git-annex.linux/git)']

```
</details>

which note is different from

<details>
<summary>setting PATH=</summary> 

```shell
$> PATH= /usr/bin/datalad clone ///
Traceback (most recent call last):
  File "/usr/bin/datalad", line 11, in <module>
    load_entry_point('datalad==0.14.0', 'console_scripts', 'datalad')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/datalad/__init__.py", line 47, in <module>
    cfg = ConfigManager()
  File "/usr/lib/python3/dist-packages/datalad/config.py", line 274, in __init__
    self.reload(force=True)
  File "/usr/lib/python3/dist-packages/datalad/config.py", line 327, in reload
    self._stores[store_id] = self._reload(runargs)
  File "/usr/lib/python3/dist-packages/datalad/config.py", line 359, in _reload
    encoding='utf-8',
  File "/usr/lib/python3/dist-packages/datalad/config.py", line 717, in _run
    out = self._runner.run(self._config_cmd + args, **kwargs)
  File "/usr/lib/python3/dist-packages/datalad/cmd.py", line 388, in run
    env=env,
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/datalad/cmd.py", line 104, in run_async_cmd
    transport, protocol = await proc
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1533, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 190, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.7/asyncio/base_subprocess.py", line 37, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 763, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

```
</details>

so may be the smart Python subprocess sets/uses some default PATH to figure out where to find the executable if not PATH is set in os.environ?

**Comment by yarikoptic** [comment] 2021-04-20 18:45
gy -- it is "smart" DataLad which manages to use smart Python to get that far due to use of find_executable!
```shell
$> ( unset PATH; /usr/bin/python3 -c 'from distutils.spawn import find_executable; print(find_executable("git"))'; )
/usr/bin/git

$> ( unset PATH; /usr/bin/python3 -c 'from distutils.spawn import find_executable; print(find_executable("git-annex"))'; )
/usr/bin/git-annex
```

which we use by default in https://github.com/datalad/datalad/blob/master/datalad/cmd.py#L534  and thus set (effectively export) to point to `/usr/bin`.

**Comment by yarikoptic** [comment] 2021-04-20 18:49
and if you have system wide `git` or set `DATALAD_USE_DEFAULT_GIT=1` (also a smart one to use find_executable), we would use/export `/usr/bin` which would find all needed pieces. (all above from code review, not actually trying but makes sense).
So - mystery resolved: it works for you with system wide one thanks to pixie dust we provide with DataLad, and in principle should have not (due to PATH amputation).  To confirm or disprove my assessment, try to run some other command than smart `datalad` which executes some external command and does not do some magical `PATH` defaults/tune ups.

**Comment by yarikoptic** [comment] 2021-04-20 18:51
we could add more pixie dust by adding `/usr/bin` if it is not present in `PATH` (on Linux/OSX) but I would really prefer we do not.

**Comment by adswa** [comment] 2021-04-21 06:04
So this would be fixed (we switched git-annex versions again, can't try it out) by setting ``PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin`` in the environment?

**Comment by yarikoptic** [comment] 2021-04-21 11:39
It could
