### ISSUE TITLE
datalad push fails to push data on first try to Gin

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#5143] opened 2020-11-11 11:31 UTC
Discovered in a hacking session with @lnnrtwttkhn:
A ``datalad push`` does not push data on first attempt to a Gin remote, ``datalad publish`` does, though.

```
(handbook) adina@muninn in /tmp
❱ datalad create myds          
[INFO   ] Creating a new annex repo at /tmp/myds 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /tmp/myds (dataset)
(handbook) adina@muninn in /tmp
❱ cd myds
(handbook) adina@muninn in /tmp/myds on git:master
❱ echo 123456 > README 
(handbook) adina@muninn in /tmp/myds on git:master
❱ datalad save -m "annex README"
add(ok): README (file)                                                                                                             
save(ok): . (dataset)                                                           
action summary:                                                                 
  add (ok: 1)
  save (ok: 1)
(handbook) adina@muninn in /tmp/myds on git:master
❱ datalad siblings add -s gin --url git@gin.g-node.org:/adswa/annexreadme.git
[INFO   ] Could not enable annex remote gin. This is expected if gin is a pure Git remote, or happens if it is not accessible. 
[WARNING] Could not detect whether gin carries an annex. If gin is a pure Git remote, this is expected.  
.: gin(-) [git@gin.g-node.org:/adswa/annexreadme.git (git)]
(handbook) adina@muninn in /tmp/myds on git:master
# first attempt: No data is pushed
❱ datalad push --to gin
publish(ok): . (dataset) [refs/heads/master->gin:refs/heads/master [new branch]]
publish(ok): . (dataset) [refs/heads/git-annex->gin:refs/heads/git-annex [new branch]]
(handbook) adina@muninn in /tmp/myds on git:master
# second attempt: Now data is pushed
❱ datalad push --to gin
copy(ok): README (file) [to gin...]                                             
copy(ok): README.md (file) [to gin...]                                          
publish(ok): . (dataset) [refs/heads/git-annex->gin:refs/heads/git-annex a26a676..5837d48]              
```

Now with publish:

```
❱datalad create anothertest
[INFO   ] Creating a new annex repo at /tmp/anothertest 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /tmp/anothertest (dataset)
(handbook) adina@muninn in /tmp
❱ cd anothertest
(handbook) adina@muninn in /tmp/anothertest on git:master
❱ echo 12345634 > README
(handbook) adina@muninn in /tmp/anothertest on git:master
❱ datalad save -m "annex README"
add(ok): README (file)                                                          
save(ok): . (dataset)                                                           
action summary:                                                                 
  add (ok: 1)
  save (ok: 1)
(handbook) adina@muninn in /tmp/anothertest on git:master
❱ datalad siblings add -s gin --url git@gin.g-node.org:/adswa/testpublish.git
[INFO   ] Could not enable annex remote gin. This is expected if gin is a pure Git remote, or happens if it is not accessible. 
[WARNING] Could not detect whether gin carries an annex. If gin is a pure Git remote, this is expected.  
.: gin(-) [git@gin.g-node.org:/adswa/testpublish.git (git)]
(handbook) adina@muninn in /tmp/anothertest on git:master
❱ datalad publish --to gin --transfer-data all
[INFO   ] Publishing Dataset(/tmp/anothertest) data to gin 
publish(ok): README (file)                                                      
[INFO   ] Publishing Dataset(/tmp/anothertest) to gin 
publish(ok): . (dataset) [pushed to gin: ['e80edf5..91638bb', '[new branch]']]  
action summary:
  publish (ok: 2)
```

**Comment by mih** [comment] 2020-11-11 11:41
I can replicate the `push` behavior. Data is pushed on third attempt. Looking further.

**Comment by mih** [comment] 2020-11-11 12:12
Trying to replicate this part:

```
❱ datalad siblings add -s gin --url git@gin.g-node.org:/adswa/annexreadme.git
[INFO   ] Could not enable annex remote gin. This is expected if gin is a pure Git remote, or happens if it is not accessible. 
[WARNING] Could not detect whether gin carries an annex. If gin is a pure Git remote, this is expected.  
/gin.g-node.org/lnnrtwttkhn/gin-remote-test.git
```

Debug log tells me:

```
[INFO   ] Could not enable annex remote gin3. This is expected if gin3 is a pure Git remote, or happens if it is not accessible. 
[DEBUG  ] Exception was: CommandError: 'git annex enableremote -c annex.dotfiles=true -c 'remote.gin.annex-ssh-options=-o ControlMaster=auto -S /home/mih/.cache/datalad/sockets/d23394af' -c 'remote.gin2.annex-ssh-options=-o ControlMaster=auto -S /home/mih/.cache/datalad/sockets/d23394af' -c 'remote.gin3.annex-ssh-options=-o ControlMaster=auto -S /home/mih/.cache/datalad/sockets/d23394af' -c annex.retry=3 -c 'remote.gin3.annex-ssh-options=-o ControlMaster=auto -S /home/mih/.cache/datalad/sockets/d23394af' gin3' failed with exitcode 1 under /tmp/gintest [out: 'enableremote gin3 failed'] [err: 'Unable to parse git config from gin2
| GIN: Repository does not exist or you do not have access
| CommandError: 'ssh -o ControlPath=/home/mih/.cache/datalad/sockets/d23394af git@gin.g-node.org 'git-upload-pack '"'"'/mih/dummy2.git'"'"''' failed with exitcode 1
| fatal: Could not read from remote repository.
| 
| Please make sure you have the correct access rights
| and the repository exists.
| git-annex: enableremote: 1 failed'] [cmd.py:run:514] 
```

I don't even understand where it need to run `enableremote` in this case, nor why it must warn about it.

**Comment by mih** [comment] 2020-11-11 13:04
> I don't even understand where it need to run `enableremote` in this case, nor why it must warn about it.

OK, confirmed that the `siblings` call does not do anything useful, and these "INFO" and "WARNING" bits are just pointless distractions:

Here is the exact same behavior (copy on 3rd attempt) without `siblings` and its errors.

```
% datalad create myds
create(ok): /tmp/myds (dataset)
% cd myds
myds (git)-[master] % echo 123456 > README
myds (git)-[master] % datalad save -m "annex README"
add(ok): README (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
myds (git)-[master] % git remote add gin git@gin.g-node.org:/mih/myds.git
myds (git)-[master] % datalad push --to gin
publish(ok): . (dataset) [refs/heads/master->gin:refs/heads/master [new branch]]            
publish(ok): . (dataset) [refs/heads/git-annex->gin:refs/heads/git-annex [new branch]]      
myds (git)-[master] % datalad push --to gin
myds (git)-[master] % datalad push --to gin
copy(ok): README (file) [to gin...]                                                         
publish(ok): . (dataset) [refs/heads/git-annex->gin:refs/heads/git-annex 1eb5b94..5b72f45]  
```

**Comment by mih** [comment] 2020-11-11 13:11
One change that happens between the 2nd and 3rd `push` is this addition to the local `.git/config`:

```diff
--- ../cfg2.txt 2020-11-11 14:08:43.691422493 +0100
+++ ../cfg3.txt 2020-11-11 14:08:54.559447746 +0100
@@ -32,6 +32,7 @@
 hub.oauthtoken=12e...
 hub.username=mih
 push.default=simple
+remote.gin.annex-uuid=a9eee9f8-2e6f-480e-b9d8-ac1d0ba2d2f5
 remote.gin.fetch=+refs/heads/*:refs/remotes/gin/*
 remote.gin.url=git@gin.g-node.org:/mih/myds.git
 url.git@github.com:.insteadof=github:
```

**Comment by mih** [comment] 2020-11-11 13:31
So my current reading of the chicken bones is this:

1. copying data is prevented when there is no `remote.<name>.annex-uuid` config available locally -- for this use case this cannot be initially, because there is nothing on the remote end by an empty repo.
2. however, the local git-annex branch is pushed.
3. I don't know why the second push is needed. It probably causes a `fetch` rather late in the run that bring down the remote `git-annex` branch info in some state that isn't achieved by the first push.
4. Once the second push has done its magic (maybe only affecting the remote end?), `git annex sync` runs (`AnnexRepo.localsync()`) which sets up the remote properly.
5. With all the pieces being in place now, `push` finds the proper conditions, and works.

I suspect that we need to handle this "first-contact" situation more explicitly. But it unclear to my which minimal intervention would be sufficient.

**Comment by mih** [comment] 2020-11-11 14:04
OK, turns it out is completely sufficient to have 

```
myds (git)-[master] % git remote add gin git@gin.g-node.org:/mih/myds.git
```

followed by an additional

```
git annex sync --no-push --no-pull --no-commit --no-resolvemerge --no-content
```

which is (`AnnexRepo.localsync()`), before the initial

```
myds (git)-[master] % datalad push --to gin
```

The sync will initialize the UUID config locally, and `push` will work out of the box.

So we could consider amending this check:

https://github.com/datalad/datalad/blob/157d4d0245d6557f7343cf755d0ea1c5ea1140cd/datalad/core/distributed/push.py#L725-L739

and have it run a `localsync()` whenever it doesn't see `annex-uuid` being set, but has already passed the `annex-ignore` check.

**Comment by mih** [comment] 2020-11-11 14:19
I have pushed a fix for this behavior to https://github.com/datalad/datalad/pull/5148 -- please have a look, if you get the chance.

**Closed** 2020-11-13 15:49 UTC
