### ISSUE TITLE
[question] DataLad Questions Set 1: Relationship to Git Annex

### ISSUE THREAD

**Issue by vsoch** [datalad/datalad#2824] opened 2018-09-13 21:26 UTC
This will be the first of a series of questions around datalad, posted here for better modularity and discussion separate from the Github issue where it originated https://github.com/datalad/datalad/issues/2814

This question is focused around:

> How do I create a superdataset?

Which I realized requires answering:

> What is the relationship to git annex?

## What is git annex?
My understanding thus far of datalad is that it adds more functionality to git-annex, which is basically like a set of symbolic links to datasets across different places. I can collaborate on datasets that would be too big to put contents into a Github repository (meaning .git) and alongside the .git repository create a git-annex that keeps a key/value store of the files themselves. Git annex, like git, has an understanding of a set of "remotes" - but these remotes are different because they can span from a USB stick to cloud storage. In the walkthrough for git-annex, it has me create a git repo too. Does this mean that the two are typically used alongside one another? If using git annex, would I issue commands to just git-annex and git, or just git-annex? 
 - To really understand what is going on with datalad, I'd like to have an understanding of how it's using git and git annex (separately or together). Example commands would probably suffice here for what happens when you do each of datalads various commands.
 - It seems that .git + .git-annex is most of the underlying functionality, and datalad is the driver for useful tools like search, install, etc.? 
 - Does datalad bring the entire metadata setup, or is this part of git annex too?
  - Then why should a user interact with datalad as an additional dependency?
 - If I use datalad, and datalad eventually goes away, do I still get power to use git-annex? What do I lose? 

## What is a superdataset
The core of this question is:

> How does Github relate to DataLad?

Datalad (if I understand correctly) defines a superdataset as a collection of datasets, where each dataset is a folder with an annex in a github repository. It seems like this means we have one upper level git folder, and then each subfolder (a submodle?) has had the git-annex init called within. 

 - This means that Github is being used for version control of git annex?
 -  There is no "Github equivalent for just Git Annex" outside of this? 
 - If a user doesn't have datalad, how would a git-annex be shared or otherwise version controlled?
 - I want to understand how the [Github repository here](https://github.com/datalad/datasets.datalad.org) relates to files on some local machine, some storage, and then the [web interface here](http://datasets.datalad.org/?dir=/adhd200/RawDataBIDS/NeuroIMAGE). I want to understand this enough so I can answer the question **how do I create my own superdataset?**

I did find datalad on the list of public repositories page (https://git-annex.branchable.com/publicrepos/) that somewhat suggested this last idea! 

So looking at the Github repository for datalad superdataset, I see a bunch of folders with submodules to other folders, and a .datalad file and a bunch of meta.json (I think to describe the metadata for each linked folder?) Does this mean that the git-annex part is still not represented here, but used in some way by datalab to parse and then obtain the annex? What I don't understand is how this repository turns into the datalab portal where I can click through datasets. The underlying questions are "How do I make this myself" and "how much of this is relying on datalab, vs, is just git annex?" and "how is git really involved aside from storing metadata about datalad?

**Comment by yarikoptic-gitmate** [comment] 2018-09-13 21:27
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/18 (git-annex diff), https://github.com/datalad/datalad/issues/2328 (--all (or just --git-annex-options?) for datalad drop), https://github.com/datalad/datalad/issues/1974 (Datalad adds to annex files that were already in git), https://github.com/datalad/datalad/issues/2648 (Git annex init fail on /// from datalad.org on Windows), and https://github.com/datalad/datalad/issues/451 (git annex -J2 for content to come from datalad-archives fails).

**Comment by yarikoptic** [comment] 2018-09-14 03:09
I think I've answered at least some aspects in other, more focused questions, so let me just give a quick answer to the main question:

**how do I create my own superdataset?**

See our definition for the superdataset in the [glossary](http://docs.datalad.org/en/latest/glossary.html) and then the answer is
- step 1: **create  (or take existing) a dataset** --  `datalad create mysuperdatasetlocation`
- step 2: you have choices.  Assuming that you did `cd mysuperdatasetlocation` you could
  - **create a new subdataset**, which would in effect finally make your current dataset a "superdataset" -- `datalad create -d . myfirstsub`
  - **install an existing dataset as a subdataset of this one** -- `datalad install -d . URL` (e.g. `datalad install -d . ///openfmri/ds000001` to make ds000001 a subdataset of your current ont)
  - **move some existing repository under your new superdataset, and add it as a subdataset** -- `datalad add -d . mysubrepo` (note that it must not be `--bare`, see #2820 )

something like this .

As for the rest, consider
- git-annex is an addition to git to version control largefiles within git
- datalad is an addition to git and (optionally) git-annex, to 
   - make it easier to operate on hierarchies/collections of datasets somewhat bluring the boundaries between them
     - many operations are recursive (install, get, ...)
     - you can specify full path within some (sub)dataset and we invoke git/git-annex under appropriate path
   - make it easy to automatically create and update datasets from existing websites/servers (that [`crawler` extension](https://github.com/datalad/datalad-crawler/))
   - take more advantages from git/git-annex as for e.g.
     - recording provenance of commands execution and being able to replay them, see [datalad run/rerun](http://docs.datalad.org/en/latest/generated/man/datalad-run.html)
     - https://github.com/datalad/datalad-container
     - ...

WE NEED TO WRITE THAT DAMN PAPER PRESENTING DATALAD to the masses.  Your questions are great source of ideas for what questions that we need to answer with it ;-)

**Comment by mih** [comment] 2018-09-14 05:41
Here is my take on your core questions.

> What is the relationship to git annex?

Great! DataLad uses git-annex for file content tracking and transport logistics. You already seem to have a good idea what git-annex is, so I will just say that it offers an astonishing range of functionality that DataLad tries to expose in full.

Apart from that there is one major difference: Both git and git annex are made to work with a single repository at a time. Even things like git submodules (that DataLad uses internally) do not change this much (if you doubt that, try to find out what you need to do to bring a hierarchy of submodules back into a clean state after placing a new file in a random subdirectory). One of the key advantages that DataLad brings to the table is that it tries really hard to make the boundaries between repositories vanish from a user's point of via. Most core commands have a `--recursive` option that will discover and traverse any subdatasets and do-the-right-thing (TM). For example, `datalad add. --recursive` will solve the above example, no matter what was changed/added, no matter where in a tree of subdatasets.

Another useful feature is that DataLad provides users with the ability to act on "virtual" file paths. For example, if your software needs datafiles for a unit test, but you carry them in a Git submodule, due to size or other issues: you can simply say `datalad get somepath_to_submodule/some_path_to_file`
and DataLad will discover if there are any subdatasets to install at a particular version to eventually provide the file content. Here is a real example from a real test:

https://github.com/psychoinformatics-de/remodnav/blob/master/remodnav/tests/test_detect.py#L92

This line (plus the DataLad import) is all you need to make you uni test battery robust against changes in file hosting, version, etc. And it will also effectively become a caching layer, as DataLad won't download things twice if not needed. There is not need to a user how to setup and initialize the data submodule, it all happens by requesting the needed file.

That being said, apart from the algorithmic magic, DataLad absolutely minimizes the use of unique/idiosyncratic functionality/implementations, but uses standard Git/git-annex functionality to achieve its goals. If DataLad should vanish at some point in the future, you'll be an agony due to the loss in convenience, but you will loose nothing else, incl. access to local or remote resources.

> How does Github relate to DataLad?

DataLad can make good use of Github, if you have figured out storage for your large files otherwise. On our website is a demo that shows how you can make DataLad automatically publish file content to one location and afterward push an update to Github, such that users can install directly from Github and seemingly also obtain large file content from Github -- but really it is DataLad orchestrating git-annex to perform its magic in the background: https://www.datalad.org/for/data-publication (last demo on this page).

Github is also capable of resolving submodule/subdataset links to other Github repos, which makes for a nice UI. Here is a dataset that contains retinotopic maps computed for all participants in out http://studyforrest.org project.

https://github.com/psychoinformatics-de/studyforrest-data-retinotopy

For proper reproducibility we want to track all input data that those are computed from, and you can find them all listed here:

https://github.com/psychoinformatics-de/studyforrest-data-retinotopy/tree/master/src

One click gets you to the exact version of the inputs that you will need to see.

> How do I create a superdataset?

There is no difference between a mere dataset and a superdataset. A superdataset is defined by the fact that it has subdatasets. There are two ways to add subdatasets:

- create a new one: `datalad create -d . new_subds`
- install an existing one: `datalad install -d . new_subds`

In both cases the `-d .` instructs DataLad to "register" the created/installed Git repo as a submodule/subdataset with the parent (identified by its path `.`).

Otherwise there is no conceptual or technical difference between a dataset, subdataset, or superdataset.

**Comment by vsoch** [comment] 2018-09-14 13:41
The `dl.get()` is really powerful! You could maintain datasets of entire testing data / functions and then just grab them when needed :)

> If DataLad should vanish at some point in the future, you'll be an agony due to the loss in convenience, but you will loose nothing else, incl. access to local or remote resources.

This is very important so I'm highlighting it again here.

> ... if you have figured out storage for your large files otherwise.

Oy, this is definitely a continued problem, always. "Who pays for the storage and where is it and what do you mean it's going to take months to transfer?"

Okay definitely add a note about the superdataset just being akin to a submodule, for some reason I missed this in my reading!

## Metadata
okay so just to clarify on this - if I want to set up metadata for a dataset I would:

define some extractor (maybe I need to write a new one even) and then add it to the `.datalad/config`
```
[datalad "metadata"]
  nativetype = exif
  nativetype = xmp
```
That helps datalad just know what exactors to expect to use across the dataset? And I would put the `.datalad/config` at any root of a dataset (superdataset or dataset within) but within a specific folder of a dataset (or would that automatically define it as another dataset?)

So if there is some missing / not valid metadata that the extractor tries to extract, it just reports an error and moves on. And technically if I wanted validation before extraction, I could write this into my extractor? And technically, this extractor script can just be used to do anything that requires parsing over a tree of files?

And the function that actually does this walking of the tree is the [aggregate-metadata](http://docs.datalad.org/en/latest/generated/man/datalad-aggregate-metadata.html#man-datalad-aggregate-metadata). Does it  (given the listing of types in the `.datalad/config`) know how to filter, based on extension, or does it just loop through and try them all listed against all file content (so for the above example, two loops, on the first try reading in file as exif, for the second, as xmp). How does this relate to the meta.json files found in the subdirectories (are those the summaries at those particular roots, or are they generated for a specific folder or file?)

And then once extraction runs, this means the "summary of metadata" is complete. Then I could run:

```
datalad -f json metadata --get-aggregates
```
to get a summary of the metadata in json. I'm thinking this would be an easy way in some CI, let's say we validate a metadata submission, we could then (when merged) run this function to generate an updated tree that feeds into a visualization of the dataset on Github pages.

**Comment by yarikoptic** [comment] 2018-09-14 14:53
> The `dl.get()` is really powerful! You could maintain datasets of entire testing data / functions and then just grab them when needed :)
> 
> > If DataLad should vanish at some point in the future, you'll be an agony due to the loss in convenience, but you will loose nothing else, incl. access to local or remote resources.
> 
> This is very important so I'm highlighting it again here.

yes, that is the beauty of distributed VCS to some degree - that you will have all the data needed to either provide alternative "implementation" or a conversion to some other comparable framework.

DataLad itself adds little to nothing to standard git/git-annex in terms of internal structures/standards.  We rely on git submodules for composition, we rely on git-annex for data logistics.  We barely add a single config file (`.datalad/config`) with a UUID to identify dataset, which is somewhat optional.  Only extracted metadata is genuine to DataLad, but that one is just a collection of .json files - so still readable etc.

Digging deeper, even if git-annex goes away, its data stored in git-annex branch is stored in very simple files, with clear [well described structure](https://git-annex.branchable.com/internals/) -- just checkout `git-annex` branch to see/navigate it.  So I could see someone providing some basic lightweight implementations if e.g. it is desired to only get the files content.

So I think you indeed should be safe on that end

**Comment by yarikoptic** [comment] 2018-09-14 14:54
> Okay definitely add a note about the superdataset just being akin to a submodule, for some reason I missed this in my reading!

Somewhat opposite -- the `subdataset` IS a submodule.  `superdataset` is the "parent" repository having that submodule.

**Comment by yarikoptic** [comment] 2018-09-14 15:15
> ## Metadata
> okay so just to clarify on this - if I want to set up metadata for a dataset I would:
> 
> define some extractor (maybe I need to write a new one even) and then add it to the `.datalad/config`
> 
> ```
> [datalad "metadata"]
>   nativetype = exif
>   nativetype = xmp
> ```
> That helps datalad just know what exactors to expect to use across the dataset?

Not "across" but "within", otherwise correct ;)

>  And I would put the `.datalad/config` at any root of a dataset (superdataset or dataset within) but within a specific folder of a dataset (or would that automatically define it as another dataset?)

We do not inherit those settings within subdatasets.  I.e. if `superdataset` defines those extractors, they will be applied only to that superdataset.  You will need to define the same (or different) extractors in each subdataset as well.

> So if there is some missing / not valid metadata that the extractor tries to extract, it just reports an error and moves on. And technically if I wanted validation before extraction, I could write this into my extractor? 

yes

> And technically, this extractor script can just be used to do anything that requires parsing over a tree of files?

extractor has access to the list of files known to repository in `self.files`.  Then it could do with them whatever it wants - filter, process, whatever. See e.g. https://github.com/datalad/datalad/blob/master/datalad/metadata/extractors/exif.py#L47

> And the function that actually does this walking of the tree is the [aggregate-metadata](http://docs.datalad.org/en/latest/generated/man/datalad-aggregate-metadata.html#man-datalad-aggregate-metadata). Does it (given the listing of types in the `.datalad/config`) know how to filter, based on extension, or does it just loop through and try them all listed against all file content (so for the above example, two loops, on the first try reading in file as exif, for the second, as xmp).

it is up to extractor - see above referenced code.  And yes - `aggregate-metadata` traverses (if `-r`) the entire tree. Otherwise you could just run it in the super dataset with `--incremental` to absorb metadata from immediate children subdatasets.

> How does this relate to the meta.json files found in the subdirectories (are those the summaries at those particular roots, or are they generated for a specific folder or file?)

first I got confused what `meta.json` we are talking about but then realized that we have not pointed you to the big change which happened in [0.10.0](https://github.com/datalad/datalad/blob/master/CHANGELOG.md#0100-jun-09-2018----the-release)  release:  metadata support was completely redone.

- `meta.json`, which are stored under `.datalad/meta` (such as [this](http://datasets.datalad.org/.datalad/meta/meta.json)) are the **old** extracted (by pre-0.10 versions) metadata.  It provided metadata only at the level of a dataset, with an optimism of being able to harmonize it across different "parsers" (we called them, instead of extractors, see e.g. that [old codebase](https://github.com/datalad/datalad/tree/0.9.x/datalad/metadata/parsers)).  **Forget about those!**, although we do keep them available from http://datasets.datalad.org so older datalad versions could still perform their search etc
- **new** (current) extracted metadata is available under `.datalad/metadata` (more documentation TODO: #2831).  Have a look e.g. at our [superdataset's](http://datasets.datalad.org/.datalad/metadata/) and look into [aggregate_v1.json](http://datasets.datalad.org/.datalad/metadata/aggregate_v1.json) which is just an index pointing to the corresponding metadata files stored under `objects` there per each path. One file `ds-` for high level dataset metadata, and `cn-` for all the gory details per each file.  Some of those files are xz compressed, so I have a little jq-based helper to view them conveniently:
```bash
jql ()
{   
    # using ucat from unp package to just "do the right thing"
    for f in "$@"; do
        ucat "$f" | jq -C . | less -R
    done
}
```

> And then once extraction runs, this means the "summary of metadata" is complete. Then I could run:
> 
> ```
> datalad -f json metadata --get-aggregates
> ```
> to get a summary of the metadata in json.

yeap -- pretty much that aggregate_v1.json I mentioned above.

>  I'm thinking this would be an easy way in some CI, let's say we validate a metadata submission, we could then (when merged) run this function to generate an updated tree that feeds into a visualization of the dataset on Github pages.

sure, could be done.

**Comment by mih** [comment] 2019-10-05 09:07
Closing "question"-type issue with a response, and no further activity.

**Closed by mih** 2019-10-05 09:07 UTC
Labels: documentation, question
