### ISSUE TITLE
Accessing a vanished(?) tarball gives cryptic error

### ISSUE THREAD

**Issue by loj** [datalad/datalad#3321] opened 2019-04-12 07:40 UTC
Demo (unclear if interpretation is correct)

```
% datalad get sub04111/anat/mprage_skullstripped.nii.gz
[WARNING] Running get resulted in stderr output: git-annex: get: 1 failed
 
[ERROR  ] not available; Try making some of these repositories available:;     ccec1cce-6820-4a71-8041-7abd4d6603ac -- yoh@smaug:/mnt/datasets/datalad/crawl/indi/fcon1000/AnnArbor_a;         f998b99f-33bf-4631-bd02-f72fe3489d9e -- datalad-archives; ; (Note that these git remotes have annex-ignore set: origin) [get(/home/loj/AnnArbor_a/sub04111/anat/mprage_skullstripped.nii.gz)] 
get(error): /home/loj/AnnArbor_a/sub04111/anat/mprage_skullstripped.nii.gz (file) [not available; Try making some of these repositories available:;   ccec1cce-6820-4a71-8041-7abd4d6603ac -- yoh@smaug:/mnt/datasets/datalad/crawl/indi/fcon1000/AnnArbor_a;         f998b99f-33bf-4631-bd02-f72fe3489d9e -- datalad-archives; ; (Note that these git remotes have annex-ignore set: origin)]
```

It seems to be unable to access/download the tarball with the files, but it doesn't clearly state that, nor does it provide a URL to be used for further investigation.

**Comment by mih** [comment] 2019-04-13 08:28
This is a bit puzzling. I can reproduce the error. I think we could improve the reporting with info from the progress reports. For this looks like this:

```
[INFO] PROGRESS-JSON: {"command":"get","wanted":[{"here":false,"uuid":"00000000-0000-0000-0000-000000000001","description":"web"},{"here":false,"uuid":"ccec1cce-6820-4a71-8041-7abd4d6603ac","description":"yoh@smaug:/mnt/datasets/datalad/crawl/indi/fcon1000/AnnArbor_a"}],"note":"from web...\nUnable to access these remotes: web\nTry making some of these repositories available:\n\t00000000-0000-0000-0000-000000000001 -- web\n \tccec1cce-6820-4a71-8041-7abd4d6603ac -- yoh@smaug:/mnt/datasets/datalad/crawl/indi/fcon1000/AnnArbor_a\n","skipped":[],"success":false,"key":"MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar","file":null} 
```

Which states the annex key of the needed tarball. Based on this I can figure out the link:

```
% git annex whereis --key MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar
whereis MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar (2 copies) 
        00000000-0000-0000-0000-000000000001 -- web
        ccec1cce-6820-4a71-8041-7abd4d6603ac -- yoh@smaug:/mnt/datasets/datalad/crawl/indi/fcon1000/AnnArbor_a

  web: http://www.nitrc.org/frs/downloadlink.php/1992
```

When I try to acces this URL on NITRC I get failures with `wget` and `chrome`, but a manual download in Firefox actually obtains the file. So the tarball is not gone, it is just difficult to access. The `wget` report:

```
% wget http://www.nitrc.org/frs/downloadlink.php/1992
--2019-04-13 10:15:13--  http://www.nitrc.org/frs/downloadlink.php/1992
Resolving www.nitrc.org (www.nitrc.org)... 132.239.16.23
Connecting to www.nitrc.org (www.nitrc.org)|132.239.16.23|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.nitrc.org/frs/downloadlink.php/1992 [following]
--2019-04-13 10:15:13--  https://www.nitrc.org/frs/downloadlink.php/1992
Connecting to www.nitrc.org (www.nitrc.org)|132.239.16.23|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: ftp://www.nitrc.org/fcon_1000/htdocs/AnnArbor_a.tar [following]
--2019-04-13 10:15:15--  ftp://www.nitrc.org/fcon_1000/htdocs/AnnArbor_a.tar
           => ‘1992’
Connecting to www.nitrc.org (www.nitrc.org)|132.239.16.23|:21... connected.
Error in server response. Closing.
Retrying.

--2019-04-13 10:15:16--  ftp://www.nitrc.org/fcon_1000/htdocs/AnnArbor_a.tar
  (try: 2) => ‘1992’
Connecting to www.nitrc.org (www.nitrc.org)|132.239.16.23|:21... connected.
Error in server response. Closing.
Retrying.

(da capo al fine...)
```

Trying a while later successfully downloads the file with the exact same command:

```
% wget http://www.nitrc.org/frs/downloadlink.php/1992
--2019-04-13 10:20:34--  http://www.nitrc.org/frs/downloadlink.php/1992
Resolving www.nitrc.org (www.nitrc.org)... 132.239.16.23
Connecting to www.nitrc.org (www.nitrc.org)|132.239.16.23|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.nitrc.org/frs/downloadlink.php/1992 [following]
--2019-04-13 10:20:35--  https://www.nitrc.org/frs/downloadlink.php/1992
Connecting to www.nitrc.org (www.nitrc.org)|132.239.16.23|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: ftp://www.nitrc.org/fcon_1000/htdocs/AnnArbor_a.tar [following]
--2019-04-13 10:20:37--  ftp://www.nitrc.org/fcon_1000/htdocs/AnnArbor_a.tar
           => ‘1992’
Connecting to www.nitrc.org (www.nitrc.org)|132.239.16.23|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /fcon_1000/htdocs ... done.
==> SIZE AnnArbor_a.tar ... 1602406400
==> PASV ... done.    ==> RETR AnnArbor_a.tar ... done.
Length: 1602406400 (1.5G) (unauthoritative)

...
```

However, no luck via git-annex (ever):

```
% git annex get -d --key MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar
[2019-04-13 10:24:59.570542778] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","symbolic-ref","-q","HEAD"]
[2019-04-13 10:24:59.573524249] process done ExitSuccess
[2019-04-13 10:24:59.57362291] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","refs/heads/master"]
[2019-04-13 10:24:59.576054235] process done ExitSuccess
get MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar [2019-04-13 10:24:59.576370763] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","git-annex"]
[2019-04-13 10:24:59.578447506] process done ExitSuccess
[2019-04-13 10:24:59.578520539] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--hash","refs/heads/git-annex"]
[2019-04-13 10:24:59.580387786] process done ExitSuccess
[2019-04-13 10:24:59.580568384] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","log","refs/heads/git-annex..6af40c3ad0394b980da48d80c2c37eb39c133272","--pretty=%H","-n1"]
[2019-04-13 10:24:59.582737928] process done ExitSuccess
[2019-04-13 10:24:59.587882349] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch"]
[2019-04-13 10:24:59.58840079] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)"]
(from web...) 
[2019-04-13 10:24:59.60943286] Request {
  host                 = "www.nitrc.org"
  port                 = 80
  secure               = False
  requestHeaders       = [("Accept-Encoding","identity"),("User-Agent","git-annex/7.20190322+git7-g66b265826-1~ndall+1")]
  path                 = "/frs/downloadlink.php/1992"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}

download failed: Found

  Unable to access these remotes: web

  Try making some of these repositories available:
        00000000-0000-0000-0000-000000000001 -- web
        ccec1cce-6820-4a71-8041-7abd4d6603ac -- yoh@smaug:/mnt/datasets/datalad/crawl/indi/fcon1000/AnnArbor_a
failed
[2019-04-13 10:25:01.525050967] process done ExitSuccess
[2019-04-13 10:25:01.525673764] process done ExitSuccess
git-annex: get: 1 failed
```

This diagnosis is not really trustworthy as NITRC seem to be sensitive to repeated requests and issues 503 responses relatively quickly.

Dunno what we can do, besides asking NITRC.

**Comment by kyleam** [comment] 2019-04-16 15:05
On my end, I've been able to reliably download from https://www.nitrc.org/frs/downloadlink.php/1992 with wget and  `curl -L` (including with `--max-redirs 10`, which I believe matches http-conduit's redirect settings).  Perhaps there is something that can be tweaked on the git-annex/http-conduit end to make this work.

**Comment by yarikoptic** [comment] 2019-04-16 15:13
I have forgot the intricacies of NITRC handling... trying to reestablish the knowledge:

<details>
<summary>NITRC provides the actual files via ftp</summary>

```shell
$> wget -S http://www.nitrc.org/frs/downloadlink.php/1992
--2019-04-16 11:04:50--  http://www.nitrc.org/frs/downloadlink.php/1992
Resolving www.nitrc.org (www.nitrc.org)... 132.239.16.23
Connecting to www.nitrc.org (www.nitrc.org)|132.239.16.23|:80... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 302 Found
  Date: Tue, 16 Apr 2019 15:04:51 GMT
  Server: Apache/2.2.15 (CentOS)
  Location: https://www.nitrc.org/frs/downloadlink.php/1992
  Content-Length: 310
  Keep-Alive: timeout=2, max=100
  Connection: Keep-Alive
  Content-Type: text/html; charset=iso-8859-1
Location: https://www.nitrc.org/frs/downloadlink.php/1992 [following]
--2019-04-16 11:04:51--  https://www.nitrc.org/frs/downloadlink.php/1992
Connecting to www.nitrc.org (www.nitrc.org)|132.239.16.23|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 302 Found
  Date: Tue, 16 Apr 2019 15:04:53 GMT
  Server: Apache/2.2.15 (CentOS)
  X-Powered-By: PHP/5.3.3
  Set-Cookie: PHPSESSID=7d2ai82i3s1fkjmid4mre1rda5; path=/
  Expires: Thu, 19 Nov 1981 08:52:00 GMT
  Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
  Pragma: no-cache
  Location: ftp://www.nitrc.org/fcon_1000/htdocs/AnnArbor_a.tar
  Content-Length: 0
  Keep-Alive: timeout=2, max=100
  Connection: Keep-Alive
  Content-Type: text/html; charset=UTF-8
Location: ftp://www.nitrc.org/fcon_1000/htdocs/AnnArbor_a.tar [following]
--2019-04-16 11:04:53--  ftp://www.nitrc.org/fcon_1000/htdocs/AnnArbor_a.tar
           => ‘1992’
Connecting to www.nitrc.org (www.nitrc.org)|132.239.16.23|:21... connected.
220 (vsFTPd 2.2.2)
Logging in as anonymous ... 
--> USER anonymous

331 Please specify the password.
--> PASS Turtle Power!

230 Login successful.
--> SYST

215 UNIX Type: L8
--> PWD

257 "/"
--> TYPE I

200 Switching to Binary mode.
--> CWD /fcon_1000/htdocs

250 Directory successfully changed.
--> SIZE AnnArbor_a.tar

213 1602406400
--> PASV

227 Entering Passive Mode (132,239,16,23,97,58).
--> RETR AnnArbor_a.tar

150 Opening BINARY mode data connection for AnnArbor_a.tar (1602406400 bytes).
Length: 1602406400 (1.5G) (unauthoritative)

1992                                       0%[                                                                                ] 628.12K   135KB/s 
...
```
</details>

For that, internally in datalad "use" `requests_ftp` module (not available in debian), which we apparently do not require by default ATM at all (unless `pip install datalad[downloaders-extra]`) .  But `datalad` special remote is not added/enabled in such datasets.   I guess it is because older git-annex used wget/curl which did all needed magic and current "haskell" implementation doesn't have such support....
and I can't remember what is the option/environment variable to instruct git annex to try wget/curl instead of built-in downloader so we could verify that it is the culprit. @joeyh ?

**Comment by kyleam** [comment] 2019-04-16 15:33
> and I can't remember what is the option/environment variable to instruct git annex to try wget/curl instead of built-in downloader so we could verify that it is the culprit.

It works for me via curl.  You can test it with

```
git config annex.security.allowed-http-addresses all
git config annex.web-options '-L --progress-bar'
git annex addurl https://www.nitrc.org/frs/downloadlink.php/1992 
```

**Comment by mih** [comment] 2019-04-17 15:42
> It works for me via curl.

I can confirm the observation. What do we do now to fix the datasets on http://datasets.datalad.org ?

**Comment by yarikoptic** [comment] 2019-04-17 19:54
The original problem had nothing to do with datasets.datalad.org and requires fix in git annex IMHO. As a workaround we could either host a copy of data, or  make it available through datalad special remote which in full installation could download it instead of internal git annex downloader

**Comment by mih** [comment] 2019-04-25 06:09
I can confirm that setting this puts everything back into the clear:

```
git config annex.security.allowed-http-addresses all
git config annex.web-options '-L --progress-bar'
```

**Comment by yarikoptic** [comment] 2019-05-09 20:42
ok, filed against git-annex https://git-annex.branchable.com/bugs/regression__58___http_downloads_redirecting_to_ftp_are_no_longer_supported/?updated

**Comment by mih** [comment] 2019-05-14 18:16
Thx for filing this upstream!

**Comment by yarikoptic** [comment] 2019-05-30 21:49
FWIW -- with the super fresh annex (7.20190507+git126-g5d681a3ce-1~ndall+1, uploaded to -devel of neurodebian) seems to be mitigated, thanks @joeyh :
```shell
(git-annex)hopa:~/datalad/indi/fcon1000/AnnArbor_a[master]
$> git annex get -d --key MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar
[2019-05-30 17:40:52.006587875] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","symbolic-ref","-q","HEAD"]
[2019-05-30 17:40:52.017505967] process done ExitSuccess
[2019-05-30 17:40:52.017629063] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","refs/heads/master"]
[2019-05-30 17:40:52.024290305] process done ExitSuccess
get MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar [2019-05-30 17:40:52.024792868] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","git-annex"]
[2019-05-30 17:40:52.029533324] process done ExitSuccess
[2019-05-30 17:40:52.029626001] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--hash","refs/heads/git-annex"]
[2019-05-30 17:40:52.033550583] process done ExitSuccess
[2019-05-30 17:40:52.033754211] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","log","refs/heads/git-annex..78344bac22c0fe171b8207aa89f797925dad4138","--pretty=%H","-n1"]
[2019-05-30 17:40:52.03890939] process done ExitSuccess
[2019-05-30 17:40:52.039768948] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch"]
[2019-05-30 17:40:52.040199121] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)"]
(from web...) 
[2019-05-30 17:40:52.108285388] Request {
  host                 = "www.nitrc.org"
  port                 = 80
  secure               = False
  requestHeaders       = [("Accept-Encoding","identity"),("User-Agent","git-annex/7.20190507+git126-g5d681a3ce-1~ndall+1")]
  path                 = "/frs/downloadlink.php/1992"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}

[2019-05-30 17:40:56.674588776] call: curl ["--resolve","*:21:[132.239.16.23]","--ftp-skip-pasv-ip","--max-redirs","0","-sS","-f","-L","-C","-","--user-agent","git-annex/7.20190507+git126-g5d681a3ce-1~ndall+1","--proto","-all,ftp,http,https","-o",".git/annex/tmp/MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar","ftp://www.nitrc.org/fcon_1000/htdocs/AnnArbor_a.tar"]
2%    24.77 MiB         1 MiB/s 17m45s^C
```

**Comment by mih** [comment] 2019-05-31 10:21
Cool, let's close it then.

**Closed by mih** 2019-05-31 10:21 UTC
Labels: git-annex
