### ISSUE TITLE
A way to specify None as a value for a config variable via env var

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5653] opened 2021-05-11 14:24 UTC
This is a continuation of the #1842 which was closed with the "clarification" that empty string as a value for env var is just that - an empty string regardless of what constraints/defaults etc.

But we have not reached a conclusion on how env var could instruct to reset an already set value (e.g. via `datalad -c ` or in some config file) to `None`.

And we already have some "variability" in how we handle `None` among config variables, e.g. some explicitly declare `"none"` to be allowed value, one defaults to `"None"` as a string, and some just set default to `None`:
```shell
$> git grep  -i none datalad/interface/common_cfg.py 
datalad/interface/common_cfg.py:from datalad.support.constraints import EnsureNone
datalad/interface/common_cfg.py:    'datalad.tests.nonetwork': {
datalad/interface/common_cfg.py:        # None keeps the default behavior
datalad/interface/common_cfg.py:        'default': 'None',
datalad/interface/common_cfg.py:        'default': None,
datalad/interface/common_cfg.py:        'default': None,
datalad/interface/common_cfg.py:        'default': None,
datalad/interface/common_cfg.py:        'type': EnsureChoice('tqdm', 'tqdm-ipython', 'log', 'none'),
```
so it seems that the original "motivation" for #1842 is still there: we might want to "straighten out" on either allowed values for config variables with explicit `"none"`, or do provide some special treatment for a value in env var to instruct value to be set to None (well - empty string is a logical choice unless there is `| EnsureStr` or `| EnsureChoice('')`).

Also relates to currently absent analogy for being able to specify `None` in CLI (https://github.com/datalad/datalad/pull/5640) which insofar seems to boil down to deficiency of options specification which we might also want to harmonize a bit or do allow for `None` specification e.g. as proposed by #5640

**Comment by mih** [comment] 2022-07-20 09:52
I am looking at this topic again. Here is my angle:

`git-config` has no concept of `None`. It distinguishes strings, bools, integers, colors and paths as value types (see `git-config(1)`).

From my POV, an empty string is not a valid unconditional indicator for `None` (think e.g. `section.message-prefix=''`). The closest to `None` seems to be an unset variable.

For the use-case where a config item is set to a non-`None` value, and needs be overridden, we have several layers to look at:

#### `ConfigManager`

This seems to work "just fine" already:

```python
In [1]: from datalad import cfg
In [2]: cfg.get('user.name')
Out[2]: 'Michael Hanke'
In [3]: cfg.overrides['user.name'] = None
In [4]: cfg.reload()
In [5]: cfg.get('user.name')
In [6]: repr(cfg.get('user.name'))
Out[6]: 'None'
```

#### `datalad -c` CLI override

This does not work at present

```sh
% datalad configuration get user.name
Michael Hanke
% datalad -c user.name= configuration get user.name
[ERROR  ] Configuration override without section/variable or value assignment (must be 'section.variable=value'): ['user.name='] 
% datalad -c user.name configuration get user.name
[ERROR  ] Configuration override without section/variable or value assignment (must be 'section.variable=value'): ['user.name'] 
% datalad -c :user.name configuration get user.name
[ERROR  ] Configuration override without section/variable or value assignment (must be 'section.variable=value'): [':user.name'] 
% datalad -c user.name=aa configuration get user.name
aa
```

This is easy to fix, however, by changing `datalad.cli.helpers._parse_overrides_from_cmdline()` to accept the syntax implemented by `datalad credentials` to unset properties (i.e. `-c :user.name`).

### ENV config overrides

This is also working already:

```
% datalad configuration get user.name 
Michael Hanke
% DATALAD_CONFIG_OVERRIDES_JSON='{"user.name": "other"}' \
    datalad -f '{value}' configuration get user.name
other
% DATALAD_CONFIG_OVERRIDES_JSON='{"user.name": null}' \
  datalad -f '{value}' configuration get user.name
None
```

Given that the issue is asking for a way to set a config item to `None` via the environment, I am closing this issue as fixed now.

I will open a more targeted issue about implementing support for this for `datalad -c ...` too, in a few minutes.

I am pinging https://github.com/datalad/datalad/issues/6851 here, because it relates to the way unset config items are being reported.

**Closed by mih** 2022-07-20 09:52 UTC
Labels: UX, cmd-config(urgation)
