### ISSUE TITLE
Clarifying datalad remove

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4830] opened 2020-08-24 21:25 UTC
#### What is the problem?
`datalad remove [SUBDATASET]` removes a subdataset but does not unregister it. No commit is posted, and I can install the subdataset again with `datalad install [SUBDATASET]`. To properly remove the dataset I have to do `datalad remove -d . [SUBDATASET]`. This produces a commit and successfuly unregisters the subdataset.

I just wanted to confirm that all the above is correct and as intended. If yes, maybe [the documentation](http://docs.datalad.org/en/stable/generated/man/datalad-remove.html) should be a little more clear about the difference with and without using `-d .`.

_This command can remove subdatasets and paths, including non-empty directories, from datasets. Removing a component implies dropping present content and uninstalling associated subdatasets. Subsequently, the component is “unregistered” from the respective dataset. This means that the component is no longer present on the file system._

#### What steps will reproduce the problem?
No need.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.13.1

#### Is there anything else that would be useful to know in this context?
No

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Yes.

**Comment by kyleam** [comment] 2020-08-25 14:38
> I just wanted to confirm that all the above is correct and as intended.

While it'd be good for others to chime in, my impression from looking into this for gh-3920 was that it was intended.

> If yes, maybe [the documentation](http://docs.datalad.org/en/stable/generated/man/datalad-remove.html) should be a little more clear about the difference with and without using `-d .`.

Indeed.

**Comment by mih** [comment] 2022-03-17 05:10
I am closing this now. How `remove` is behaving changes in 0.16 after #6111. In summary, more safe by default.

**Closed by mih** 2022-03-17 05:10 UTC
Labels: documentation, cmd-remove
