### ISSUE TITLE
`test_clone.test_reckless` randomly(?) failing on macos

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5794] opened 2021-07-17 09:36 UTC
```
======================================================================
FAIL: datalad.core.distributed.tests.test_clone.test_reckless(True,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/runner/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/datalad/tests/utils.py", line 739, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/Users/runner/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/datalad/tests/utils.py", line 739, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/Users/runner/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/datalad/tests/utils.py", line 739, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/Users/runner/hostedtoolcache/Python/3.6.14/x64/lib/python3.6/site-packages/datalad/core/distributed/tests/test_clone.py", line 449, in check_reckless
    & stat.S_IWGRP)
AssertionError: None
```

Example: https://github.com/datalad/datalad/pull/5792/checks?check_run_id=3086140124 (but seen before)

**Comment by yarikoptic** [comment] 2021-07-17 11:53
Duplicate of https://github.com/datalad/datalad/issues/5759
Should be fixed in next git annex release although iirc Joey also recommended to tune our test as well

**Closed by yarikoptic** 2021-07-17 11:53 UTC
