### ISSUE TITLE
Incomplete list of results upon rev-create ?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3234] opened 2019-03-17 13:55 UTC
it could be "by design"?  

```shell
$> datalad rev-create -d . subds1/subsubds5
[INFO   ] Creating a new annex repo at /tmp/superds/subds1/subsubds5 
create(ok): subds1/subsubds5 (dataset)                                                                                                                                          
action summary:
  add (ok: 1)
  create (ok: 1)
  save (ok: 2)

$> datalad --version
datalad 0.12.0rc1.dev77
```
I do not see reflection of those add/save actions - had to browse `git log` and/or see `git status` to see that updated state of subds was saved within my super.

**Comment by mih** [comment] 2019-03-18 06:08
What do you want to see in addition? The individual lines for each action? That is a logger's task and likely those 'OK' results don't have one attached. Can be added, of course, but it is unclear to me if that is the topic here.

**Comment by yarikoptic** [comment] 2019-03-18 13:14
I was under impression (could be an incorrect one, or even may be changed after I have whined) that all the events which are summarized are also listed, not only for the initial command. If it is not true, that is ok, I will just keep it in mind and see if I don't catch inconstancy there other way around.

**Comment by kyleam** [comment] 2019-03-18 14:31
There's a result filter in place here:

https://github.com/datalad/datalad/blob/39d38b69347afda485e9db3c2b60f6c4bd84af38/datalad/core/local/create.py#L98-L101

**Comment by kyleam** [comment] 2019-03-20 15:31
OK, I don't think there is any mystery here.  And the behavior is the same between `create` and `rev-create` (see below), so I'll close this.  Please re-open if I'm mistaken or if the issue is changing to a request to drop the filter.


```
% datalad create -d. a
[INFO   ] Creating a new annex repo at /tmp/dl-MX6hZxb/a 
create(ok): a (dataset)
action summary:
  add (notneeded: 2, ok: 1)
  create (ok: 1)
  save (ok: 1)

% datalad rev-create -d. b
[INFO   ] Creating a new annex repo at /tmp/dl-MX6hZxb/b 
create(ok): b (dataset)                                                                                  
action summary:
  create (ok: 1)
  save (ok: 1)
```

**Closed by kyleam** 2019-03-20 15:31 UTC
