### ISSUE TITLE
save submodule    does not commit modified submodule 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1700] opened 2017-08-09 20:54 UTC
first encountered with current master and then tested with dev-master (94d832a107a1b8fabf5435d89d49fac0a242d416) -- the same story -- submodule with new commits is not saved even though pointed to 

```shell
(git)smaug:/mnt/btrfs/datasets/datalad/crawl[master]git
$> datalad save -m "Added initial subdataset with sherlock for MIND-2017" workshops
save(notneeded): /mnt/btrfs/datasets/datalad/crawl/workshops (dataset)
(dev)2 14886.....................................:Wed 09 Aug 2017 04:51:19 PM EDT:.
(git)smaug:/mnt/btrfs/datasets/datalad/crawl[master]git
$> git status --ignore-submodules=dirty
On branch master
Your branch is up-to-date with 'datalad-public/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   workshops (new commits)
```

it **does** save it (as part of all modifications) if I do not provide any path (although I thought '-u' would be needed for that generally)

**Comment by mih** [comment] 2017-08-11 10:12
I can replicate. Will create a test first.

**Comment by mih** [comment] 2017-08-11 10:25
This is not a bug. At least not a bug in the code.

The reason for this behavior is this: Most commands eat an arbitrary number of paths. `save` will take any paths and save them. If you don't say what to save into, it will save whatever is necessary to make anything that you gave as a path argument to be clean at the end. So in your case, it finds `workshops` to be clean, and informs you about it.

This following commands would all do the job:

```
datalad save
datalad save .
datalad save -d . -m "Added initial subdataset with sherlock for MIND-2017" workshops
datalad save -S workshops
```

In `dev-master` `--all-updated` is the default behavior -- it won't touch untracked content unless given as an explicit path.

PS: While everything I said above is true, I just found, while lecturing you, that `-S` in addition does things that it should not do. I guess I deserve that....

**Comment by mih** [comment] 2017-08-29 07:47
This is on record now. Closing.

**Closed by mih** 2017-08-29 07:47 UTC
Labels: for our information
