### ISSUE TITLE
No access to RIA data, after cloning from Gitlab

### ISSUE THREAD

**Issue by anikfal** [datalad/datalad#7122] opened 2022-10-27 16:22 UTC
Access to RIA data by `ria+ssh://[user@]hostname:/absolute/path/to/ria-store` is OK. I can get any data by `datalad get`. However after cloning the same dataset from Gitlab, `datalad get` cannot get the data, showing the error below:
> get(error): 2001120100_ml.grb (file) [not available; (Note that these git remotes have annex-ignore set: origin)]

I also set the required configuration (`git config -f .datalad/config "datalad.get.subdataset-source-candidate-origin" "ria+http://store.datalad.org#{id}"`), but it did not help.

Datalad 0.17.2
OS: Fedora-36

**Comment by adswa** [comment] 2022-10-28 05:50
Hi, thanks for the issue! The problem you are facing sounds like a configuration issue - the clone on Gitlab doesn't seem to know about the existence of the RIA store on your server. Not sure why, but should be fixable once we figured out the details. Pinging @bpoldrack here, too.
My immediate questions are:
What is the structure of your published dataset: Is it a superdataset with subdatasets, or a single dataset? Is the data on the server you mentioned, or does it live on other hardware (eg, cloud infrastructure)?
Do you remember how you created the sibling on GitLab? (e.g., from where?)
In a dataset where file retrieval fails, what does ``git remote -v`` output?
Concerning the prospective users/consumers of the data, do they have access to your server (e.g., scientists in an institute), or would they not be able to perform the same ssh call that you included as an example in your issue (e.g., scientists from other labs, the general public, ...)

> I also set the required configuration (git config -f .datalad/config "datalad.get.subdataset-source-candidate-origin" "ria+http://store.datalad.org#{id}"), but it did not help.

I can see why you assumed the setting had to be set (the documentation in the handbook needs improvement urgently), but it is in one or more ways wrong. One is that ``http://store.datalad.org/`` is a webserver @yarikoptic set up in dartmouth, it hosts all kind of data, and especially for github.com/datalad-datasets/human-connectome-project-openaccess it hosts a few thousand subdatasets. Its not a generic placeholder - unless the two of you know eachother, store.datalad.org is a webserver unrelated to your own hardware and with no connection to your data. 
The second reason is that setting a configuration of this kind is not required for all usecases (and I don't know your setup well enough to judge that yet). Setting it is required when your dataset on Gitlab contains subdatasets from a RIA store that only live in a RIA store (and not, for example, as individual clones on GitLab as well). If its not a hierarchy of datasets, you don't need to set it.

It would be nice to learn a few details about your data and then figure out what needs to be done exactly. Thx in advance!

**Comment by bpoldrack** [comment] 2022-10-28 06:42
Agree with @adswa's assessment:
> the clone on Gitlab doesn't seem to know about the existence of the RIA store on your server.

Either the existence of the store to begin with or the current data content of it are unknown to the clone on Gitlab. This would suggest that at least the `git-annex` branch of it is not updated. So, a `datalad push` to GitLab from a clone of the store seems likely to fix that.

**Comment by anikfal** [comment] 2022-10-28 11:07
Thank you very much. I think the documentation lacks examples regarding ssh-accessible HPC servers.

My major issue is access to dataset installed on an HPC server by a simple `git clone` or `datalad clone` from a remote git repository (Gitlab) as a sibling, and then `datalad get` any required data. Not by `ria+ssh://[user@]hostname:/absolute/path/to/ria-store` which is okay, but unfamiliar to the users.
The users have SSH access to the HPC server as well as to the dataset, but I do not want them to deal with datalad details and server issues.

**Structure of the published dataset:**
- Installed on an HPC server, with SSH access to all users 
- A super-dataset with a sub-dataset. Both filled with some data
- The sibling on Gitlab has been created by `datalad siblings add -d . --name sibling_name --url git@gitlab.jsc.fz-juelich.de:myuser/repo_name.git`. Before that, I created the Gitlab repository manually (not by `datalad create-sibling-gitlab`)
- After `datalad create-sibling-ria`, I committed `datalad push --to ria_store` and `datalad push --to gitlab_repo`. Everything seemed okay.

**Cloning dataset directly from the HPC server (this is okay):**
The command `datalad clone ria+ssh://myuser@jureca.fz-juelich.de:/absolute/path/to/ria-store#~alias_name` can effectively clone the dataset in my local, and I can get any data with `datalad get`.

`git remote -v`
> mydataset-backup	/absolute/path/to/ria-store/122/89a76-0bc5-4410-95b4-2e23b074a0eb (fetch)
> mydataset-backup	/absolute/path/to/ria-store/122/89a76-0bc5-4410-95b4-2e23b074a0eb (push)
> mydataset-backup-storage
> gitlab_repo	git@gitlab.jsc.fz-juelich.de:myuser/gitlab_repo.git (fetch)
> gitlab_repo	git@gitlab.jsc.fz-juelich.de:myuser/gitlab_repo.git (push)

RIA directories are identified as one of the siblings.

**Cloning dataset from its Gitlab sibling (Clone is okay, but getting HPC data is not possible):**
The simple `git clone https://gitlab.jsc.fz-juelich.de/myuser/gitlab_repo.git` (clone only with https) can clone the dataset, in the same way as `datalad clone ria+ssh`. However, `datalad get` cannot get any data, showing the error bellow:
>  get(error): 2001120100_ml.grb (file) [not available; (Note that these git remotes have annex-ignore set: origin)]

`git remote -v`
> origin	git@gitlab.jsc.fz-juelich.de:myuser/gitlab_repo.git (fetch)
> origin	git@gitlab.jsc.fz-juelich.de:myuser/gitlab_repo.git (push)

As you see, unlike the direct clone from the HPC server, for this case (clone from Gitlab), the output of `git remote -v` only shows the Gitlab repo, and no RIA directories in the HPC server are identified.

How can I make connection between the Gitlab sibling with the RIA store, so getting data will be possible after cloning from Gitlab?

PS. There are some other issues that I think they're better to be discussed as separate issues.

**Comment by adswa** [comment] 2022-10-28 14:43
Thx! That's indeed strange, usually the special remote is automatically linked. I also tried a toy example on our GitLab instance and couldn't reproduce this so far. Just to check @bpoldrack's hypothesis about the git-annex branch too, could you run ``git branch`` inside of the dataset cloned from GitLab? 

> PS. There are some other issues that I think they're better to be discussed as separate issues.

Yes, please open as many issues as needed. We're happy to take a look at them also in a video call, we have [weekly office hours on Thursdays at 4pm](git@jugit.fz-juelich.de:adswa/riasibling.git) for such things. And I see you're at the JSC so we at least have some knowledge about that infrastructure.

**Comment by bpoldrack** [comment] 2022-10-28 14:44
> How can I make connection between the Gitlab sibling with the RIA store, so getting data will be possible after cloning from Gitlab?

`datalad create-sibling-ria` should have set that connection by configuring the git-annex special remote to `autoenable=true`, so that when one clones the dataset, one would automatically have that connection. So, it seems something about that special remote config went wrong and it is not enabled in the clone from gitlab. In principle your approach is exactly right.

Can we see the output of `git cat-file -p git-annex:remote.log` in both cloen (from gitlab vs from HPC)?

**Comment by matrss** [comment] 2022-10-28 15:02
> The simple `git clone https://gitlab.jsc.fz-juelich.de/myuser/gitlab_repo.git` (clone only with https) can clone the dataset, ...

I don't think special remotes will be autoenabled if you are using `git clone` instead of `datalad clone`. This might be your issue.

**Comment by bpoldrack** [comment] 2022-10-28 15:06
@matrss: Yes, indeed! Good catch. If you use `git clone` that would require a subsequent `git annex init`, @anikfal

**Comment by bpoldrack** [comment] 2022-10-28 15:14
@anikfal 

There's another potential issue lurking here:
> ria+ssh://myuser@jureca.fz-juelich.de:/absolute/path/to/ria-store#~alias_name

If you set up the RIA sibling with a SSH URL that does contain a username, then this is the URL that wil be stored with the special remote. Meaning: This will be the only user able to enable this special remote. DataLad does not make a guess, that this wasn't what you meant. But in all likelyhood what you want to set for the special remote (via `create-sibling-ria`) is `ria+ssh://@jureca.fz-juelich.de:/absolute/path/to/ria-store` as the store URL. And have users use `~/.ssh/config` to set their username for jureca. You can fix that by running `git annex enableremote url=ria+ssh://@jureca.fz-juelich.de:/absolute/path/to/ria-store` in a clone and push back (because that will be stored in the git-annex branch).

**Comment by anikfal** [comment] 2022-10-28 17:57
There are some warnings after adding the Gitlab repository as a sibling of the HPC dataset:

`datalad siblings add -d . --name gitlab_repo --url https://gitlab.jsc.fz-juelich.de/my_user/repo_name.git`
> [INFO   ] Could not enable annex remote gitlab_repo. This is expected if gitlab_repo is a pure Git remote, or happens if it is not accessible. 
> [WARNING] Could not detect whether gitlab_repo carries an annex. If gitlab_repo is a pure Git remote, this is expected. Remote was marked by annex as annex-ignore. Edit .git/config to reset if you think that was done by mistake due to absent connection etc 
> .: gitlab_repo(-) [https://gitlab.jsc.fz-juelich.de/nikfal1/aaadata_riatest.git (git)]

However, I always ignore the above warnings. Is it a serious issue?

-----

@adswa 
> could you run `git branch` inside of the dataset cloned from GitLab?

Output of `git branch`:
>   git-annex
>   \* master

@bpoldrack 
> Can we see the output of `git cat-file -p git-annex:remote.log` in both clones (from gitlab vs from HPC)?

Output of `git cat-file -p git-annex:remote.log` in the clone from Gitlab:

> 2f5a287d-eb94-412a-b742-ef9bb38df6cc archive-id=12289a76-0bc5-4420-95b4-2e23b034a0eb autoenable=true encryption=none externaltype=ora name=myria-backup-storage type=external url=ria+ssh://myuser@jureca.fz-juelich.de:/absolute/path/to/ria-store timestamp=1666940813.181018s

Output of `git cat-file -p git-annex:remote.log` in the clone from HPC:

> 
2f5a287d-eb94-412a-b742-ef9bb38df6cc archive-id=12289a76-0bc5-4420-95b4-2e23b034a0eb autoenable=true encryption=none externaltype=ora name=myria-backup-storage type=external url=ria+file:/absolute/path/to/ria-store timestamp=1666696399.814563s

@matrss 

> I don't think special remotes will be autoenabled if you are using `git clone` instead of `datalad clone`. This might be your issue.

My previous comment was mistyped, and I actually meant `datalad clone`. However, to be sure, I repeated `datalad clone`, and reached to the same problem.

**Comment by bpoldrack** [comment] 2022-10-29 18:21
> However, I always ignore the above warnings. Is it a serious issue?

No. That is okay. It would be relevant if you expect the hosting to be annex-aware (like GIN).

**Comment by bpoldrack** [comment] 2022-10-29 18:28
So, the special remote config looks right and has autoenable set. That would suggest, that there should be an error message during `clone`, when annex/datalad try to enable it. It would be good to see what `clone` says.
However, you can also do that after the fact by calling `git annex enableremote myria-backup-store`. Since clone appears to not succeed with that, I'd expect an error message, that should help.

**Comment by anikfal** [comment] 2022-10-31 12:44
@adswa 
> I can see why you assumed the setting had to be set (the documentation in the handbook needs improvement urgently), but it is in one or more ways wrong. One is that `http://store.datalad.org/` is a webserver

I actually meant `git config -f .datalad/config "datalad.get.subdataset-source-candidate-origin" "ria+ssh://myuser@server_ip:server_port/absolute/path/to/ria-store#~ria_alias"`

**Comment by anikfal** [comment] 2022-10-31 13:49
@bpoldrack 
Yes, `datalad clone` from Gitlab shows some errors. But since the same errors are repeated by `datalad clone ria+ssh` (and `datalad get` works for this case), I always ignored them. The errors are as below:

**`datalad clone` from Gitlab (`datalad get` doesn't work)**

`datalad clone git@gitlab.jsc.fz-juelich.de:nikfal1/sebal_datalad.git`
> [INFO   ] Unable to parse git config from origin                                                                                                                                              
> [INFO   ] Remote origin does not have git-annex installed; setting annex-ignore                                                                                                               
> |   This could be a problem with the git-annex installation on the remote. Please make sure that git-annex-shell is available in PATH when you ssh into the remote. Once you have fixed the git-annex installation, run: git annex enableremote origin 
> [INFO   ] RIA store unavailable. -caused by- file:/data/app/data/app/ria-layout-version not found. -caused by- [Errno 2] No such file or directory: '/data/app/ria-layout-version' 
> [INFO   ] RIA store unavailable. -caused by- file:/data/app/test_datalad_ria/data/app/test_datalad_ria/ria-layout-version not found. -caused by- [Errno 2] No such file or directory: '/data/app/test_datalad_ria/ria-layout-version' 
> install(ok): /home/anikfal/1test_temp/sebal_datalad (dataset)

**`datalad clone` from RIA (`datalad get` works)**

`datalad clone ria+ssh://myuser@138.201.133.138:3031/data/app/test_datalad_ria#~detect_ria_sibling`

> [INFO   ] RIA store unavailable. -caused by- file:/data/app/data/app/ria-layout-version not found. -caused by- [Errno 2] No such file or directory: '/data/app/ria-layout-version'            
> [INFO   ] RIA store unavailable. -caused by- file:/data/app/test_datalad_ria/data/app/test_datalad_ria/ria-layout-version not found. -caused by- [Errno 2] No such file or directory: '/data/app/test_datalad_ria/ria-layout-version' 
> [INFO   ] Reconfigured detect-ria-sibling-backup-storage for ria+ssh://myuser@138.201.133.138:3031/data/app/test_datalad_ria 
> [INFO   ] Configure additional publication dependency on "detect-ria-sibling-backup-storage" 
> configure-sibling(ok): . (sibling)
> install(ok): /home/anikfal/1test_temp/detect_ria_sibling (dataset)
> action summary:
>   configure-sibling (ok: 1)
>   install (ok: 1)

I don't know why the path to `ria-layout-version` is duplicated. This problem is repeated in both clones from Gitlab and RIA.
I mean the path in the line below:
> store unavailable. -caused by- file:/data/app/test_datalad_ria/data/app/test_datalad_ria/ria-layout-version

is supposed to be:
> file:/data/app/test_datalad_ria/ria-layout-version

**For your information:**
I also repeated the procedure in some other (non JSC) server, since I thought it might be due to some security limitations. But I reached to the same issue.

**Comment by bpoldrack** [comment] 2022-10-31 16:14
@anikfal 
> I don't know why the path to ria-layout-version is duplicated.

The duplication was a bug (recently fixed in datalad's master branch), but only affected the error reporting. The actual error is about the correct path. And that appears to be the issue, although it's not instantly obvious to me why it works in the other case.
The missing files are a problem suggesting that something wasn't right with the `create-sibling-ria` calls. They should have created those files.
I'm a bit confused, though. Those error messages point to `/data/app/test_datalad_ria` as well as `/data/app` to be the root dir of the RIA store. That can't be simultaneously true. Did you use both paths with `create-sibling-ria`?
I'll try some approaches to reproduce this. However, it may be beneficial for both of us, to just have a screen share session and go through it. So, if that's ok for you, either join the office hour on Thu or let me know when it's better for you - I can offer pretty much anytime Wed-Fri, if you like.

**Comment by anikfal** [comment] 2022-11-02 17:29
After cloning the dataset from Gitlab, if I replace `.git` directory with that cloned from RIA, `datalad get` can retrieve data from HPC server.

The contents of `.git/config`, `.git/objects`, and `.git/refs` are different in the two clones.
For example:

**`.git/config` in the clone from Gitlab:**

> [core]
>         repositoryformatversion = 0
>         filemode = true
>         bare = false
>         logallrefupdates = true
> [remote "origin"]
>         url = git@gitlab.jsc.fz-juelich.de:myuser/myrepo.git
>         fetch = +refs/heads/*:refs/remotes/origin/*
>         annex-ignore = true
> [branch "master"]
>         remote = origin
>         merge = refs/heads/master
> [annex]
>         uuid = 06df19f9-4a10-4e95-bfcb-f696b8e252c6
>         version = 8
> [filter "annex"]
>         smudge = git-annex smudge -- %f
>         clean = git-annex smudge --clean -- %f

**`.git/config` in the clone from RIA:**

> [core]
>         repositoryformatversion = 0
>         filemode = true
>         bare = false
>         logallrefupdates = true
> [remote "origin"]
>         url = ssh://myuser@138.201.133.138:3031/data/app/test_datalad_ria/alias/detect_ria_sibling
>         fetch = +refs/heads/*:refs/remotes/origin/*
>         annex-ignore = true
>         datalad-publish-depends = detect-ria-sibling-backup-storage
> [branch "master"]
>         remote = origin
>         merge = refs/heads/master
> [annex]
>         uuid = 4bcc6d35-3156-4d30-9c83-005fadedb777
>         version = 8
> [filter "annex"]
>         smudge = git-annex smudge -- %f
>         clean = git-annex smudge --clean -- %f
> [datalad "get"]
>         subdataset-source-candidate-200origin = "ria+ssh://myuser@138.201.133.138:3031/data/app/test_datalad_ria#{id}"
> [remote "detect-ria-sibling-backup-storage"]
>         annex-externaltype = ora
>         annex-uuid = 2d1aa1e1-aede-45a7-b508-a758a229bbe5
>         skipFetchAll = true
>         annex-cost = 200.0
>         annex-availability = GloballyAvailable

**Comment by bpoldrack** [comment] 2022-11-03 10:23
> if I replace .git directory with that cloned from RIA

Well, yes - that way you effectively make it a clone from RIA. `.git` **is** the repository.

> I'll join the Thursday's meeting

Do you have the link, @anikfal?

**Comment by anikfal** [comment] 2022-11-03 10:31
> Do you have the link, @anikfal?

Yes I have it. The matrix chat room I suppose.

**Comment by bpoldrack** [comment] 2022-11-03 10:33
@anikfal 
> Yes I have it. The matrix chat room I suppose.

Yes, Jitsi link in its description

**Comment by bpoldrack** [comment] 2022-11-03 16:53
Ok. Solved in Datalad Office Hour. Should have seen that earlier:

The special remote had the `file://` URL stored in its config. When cloning from the RIA store via SSH, `datalad clone` could realize that it should automatically reconfigure the special remote to use the SSH URL. However, when cloning from GitLab, `clone` only has the not-working `file` URL and the GitLab URL - nothing it could derive a working SSH URL from.

Solution is, of course, to have the dataset in the store be configured for the access method that should be shared with "outside" clones. (Reconfiguration would then happen the other way around when one clones from the store via a `ria+file` URL).

**Closed by bpoldrack** 2022-11-03 16:53 UTC

**Comment by anikfal** [comment] 2022-11-04 10:08
> I don't think special remotes will be autoenabled if you are using `git clone` instead of `datalad clone`. This might be your issue.

Now that the problem is solved, even after `git clone` (instead of `datalad clone`), `datalad get` works and data can be retrieved from the HPC server.
