### ISSUE TITLE
SSHManager is claiming to close connections that aren't open

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1236] opened 2017-01-28 12:49 UTC
This demo dataset has two configured remotes (both via SSH), but I only publish to one. However, the other (non-existing) control master "github" appears in several commands, and is also claimed to be closed at the end. This is confusing and should not happen. If there is an actual connection attempt (that I cannot see ATM), it would even worse.

This is something that already came up in #530 -- a long time ago in a galaxy far far away.

````
% datalad -l debug publish --to kumo 
[DEBUG  ] Resolved input path arguments: [] 
[DEBUG  ] Evaluating 1 dataset publication candidate(s) 
[DEBUG  ] Attempt to publish 1 datasets 
[DEBUG  ] Try starting control master by calling:
| ['ssh', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=15m', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/kumo', 'kumo', 'exit'] 
[DEBUG  ] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'sync', '--debug', '-c', 'remote.kumo.annex-ssh-options=-o ControlMaster=auto -S /home/mih/.cache/datalad/sockets/kumo', '-c', 'remote.github.annex-ssh-options=-o ControlMaster=auto -S /home/mih/.cache/datalad/sockets/github.com']
| cwd: /tmp/demoannex 
[DEBUG  ] Running: ['ssh', '-O', 'check', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/kumo', 'kumo']
| cwd: None 
[INFO   ] [up to date]
|  
[INFO   ] Publishing <Dataset path=/tmp/demoannex> to kumo 
[DEBUG  ] Running: ['ssh', '-O', 'check', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/kumo', 'kumo']
| cwd: None 
No handlers could be found for logger "git.remote"
|  
[INFO   ] Publishing data of dataset <Dataset path=/tmp/demoannex> ... 
[DEBUG  ] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'copy', '--debug', '-c', 'remote.kumo.annex-ssh-options=-o ControlMaster=auto -S /home/mih/.cache/datalad/sockets/kumo', '-c', 'remote.github.annex-ssh-options=-o ControlMaster=auto -S /home/mih/.cache/datalad/sockets/github.com', '--to=kumo']
| cwd: /tmp/demoannex 
1 item was published:
Dataset: /tmp/demoannex

[DEBUG  ] Closing 2 SSH connections... 
[DEBUG  ] Running: ['ssh', '-O', 'stop', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/github.com', 'github.com']
| cwd: None 
[DEBUG  ] Running: ['ssh', '-O', 'stop', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/kumo', 'kumo']
| cwd: None 
````

**Comment by mih** [comment] 2017-02-09 19:32
FTR: Still happening with current master:

````
[DEBUG  ] Closing 2 SSH connections... 
[DEBUG  ] Running: ['ssh', '-O', 'stop', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/5f9602bf21b60aa7bd8bc12a64491f7a', 'git@github.com']
| cwd: None 
[DEBUG  ] Failed to run ['ssh', '-O', 'stop', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/5f9602bf21b60aa7bd8bc12a64491f7a', 'git@github.com'] under None. Exit code=255. out= err=Control socket connect(/home/mih/.cache/datalad/sockets/5f9602bf21b60aa7bd8bc12a64491f7a): No such file or directory
|  
[DEBUG  ] Running: ['ssh', '-O', 'stop', '-o', 'ControlPath=/home/mih/.cache/datalad/sockets/747501b3584c118d95811f2c756f2a9f', 'kumo.ovgu.de']
| cwd: None 
````

There is no SSH connection to github being opened before. There is no socket either, but it still wants to close one.

**Comment by bpoldrack** [comment] 2017-02-10 07:29
Well, from my point of view the issue is not, that `SSHManager` wants to close it. That's okay. It tries to make sure, all known connections are closed. The call fails, but this failure is intentionally ignored, since it's the desired result anyway. No error message, no exception - all fine.

But the question is: How the github connection got te be registered with the `SSHManager`, if you say it was never opened? I'd love to see how you produce this, because I don't believe it's true ;-)
There is exactly one way `SSHManager` gets to know about a connection and this is `SSHManager.get_connection()`. While it might not have been opened before, at the very least it was requested.

**Comment by bpoldrack** [comment] 2017-02-10 07:35
Now, that I wrote it, I'm confident to know where this comes from! ;-)

The repo in question is an annex and it has a github remote, right?
Therefore, the connection instance was requested, but never opened.

Leaves the question: What you want it to look like? Change the wording of the `Closing X connections ...` message? Take additional effort to first check whether it's open, instead of just trying to close and be fine with failure? Something else?

**Comment by mih** [comment] 2017-02-10 08:00
In particular as we are moving towards selective content publishing, I'd consider it suspicious to see a connection to a server being closed that I did not want to have anything published to.

I would simply assume less in the messages, and perform cheap tests to avoid useless actions. At present, it knows that it could make an attempt to close a maximum of 2 connections (and logs that as if they would actually be in use), but users should not care about that. Moreover, it tries to close a connection although the socket file it knows about isn't actually present. Even if a connection to this server would anyhow be open, it could not be closed by the call it performs -- so why bother?

**Comment by bpoldrack** [comment] 2017-02-10 08:29
> but users should not care about that

Well, yes. That's why it is logged at debug level.

As for "cheap checks": Of course we could check for the existence of the expected socket before. On the other hand this still wouldn't be a fully valid check on whether there's something to close - that's what `ssh -O check` is for. So, theoretically it could still technically fail to close the connection. And calling `ssh -O check` certainly isn't "cheap" in comparison to the actual close call. The other way around the failing call isn't something expensive, that's done several times. Right now it's a one time thing when the datalad process ends.

To me it looks more like the question "What should be logged at what level?" and/or "What wording is least confusing and most informative?"
May be all (or most) of the logging from `Runner` should not be done at debug level and the message from `SSHManager` should just read "Closing SSH connections" without mentioning a potentially confusing number?

**Comment by mih** [comment] 2017-02-10 08:32
All I am saying is: There is no point in calling `ssh -O stop` for a connection where there is no socket file.

**Closed** 2017-02-13 23:39 UTC
Labels: bug, bug-regression
