### ISSUE TITLE
inside ro singularity container

### ISSUE THREAD

**Issue by satra** [datalad/datalad#1445] opened 2017-03-31 03:00 UTC
```
$ datalad install -r -g ///workshops/nipype-2017/ds000114 
[INFO   ] Installing dataset at /data/ds000114 from http://datasets.datalad.org/workshops/nipype-2017/ds000114 
Exception ignored in: <bound method AnnexRepo.__del__ of <AnnexRepo path=/data/ds000114 (<class 'datalad.support.annexrepo.AnnexRepo'>)>>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/datalad/support/annexrepo.py", line 268, in __del__
    super(AnnexRepo, self).__del__()
  File "/opt/conda/lib/python3.5/site-packages/datalad/support/gitrepo.py", line 654, in __del__
    self.repo.index.write()
  File "/opt/conda/lib/python3.5/site-packages/git/index/base.py", line 212, in write
    stream = lfd.open(write=True, stream=True)
  File "/opt/conda/lib/python3.5/site-packages/gitdb/util.py", line 314, in open
    raise IOError("Lock at %r could not be obtained" % self._lockfilepath())
OSError: Lock at '/data/ds000114/.git/index.lock' could not be obtained
```

**Comment by yarikoptic** [comment] 2017-03-31 03:07
Is /data writable? Do you have that container somewhere to grab from?

**Comment by satra** [comment] 2017-03-31 03:14
@post public key on doc?

**Comment by yarikoptic** [comment] 2017-03-31 04:20
sent via email

**Comment by yarikoptic** [comment] 2017-03-31 12:54
not sure where I can find a singularity image over there and some recent commands in the history didn't work out, e.g.
```shell
[satra@eofe7 ~]$ /home/cnh/singularity_test/usr/local/bin/singularity shell -B data:/data -i -p -c workshops\:latest-complete/
ERROR  : Container not found: workshops:latest-complete/
ABORT  : Retval = 255
```

**Comment by satra** [comment] 2017-03-31 13:16
links/satra/test/

**Comment by yarikoptic** [comment] 2017-03-31 13:49
thanks... I was not that lucky :-(
```shell
satra@eofe7:/data$ datalad install -r -g -s ///workshops/nipype-2017/ds000114 ds000114-temp
[INFO   ] Installing dataset at /data/ds000114-temp from http://datasets.datalad.org/workshops/nipype-2017/ds000114 
[INFO   ] Getting 1 items of dataset <Dataset path=/data/ds000114-temp> ... 
[INFO   ] Actually getting 227 files 
1 installed item is available at                                                 
<Dataset path=/data/ds000114-temp>                                               
satra@eofe7:/data$ cd ds000114
satra@eofe7:/data/ds000114$ git annex get .
satra@eofe7:/data/ds000114$ datalad get .
[INFO   ] Getting 1 items of dataset <Dataset path=/data/ds000114> ... 
Got nothing new
```
so smells like some race condition somewhere then

**Comment by yarikoptic** [comment] 2017-04-12 02:56
I will close it for now since couldn't reproduce then but let's remember about it ;)

**Closed by yarikoptic** 2017-04-12 02:56 UTC
