### ISSUE TITLE
Distributing data to the public in USB hard drives

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4774] opened 2020-07-28 03:23 UTC
#### What is the problem?
We are getting ready to distribute our data to partners and collaborators. Usually, the way we distribute data is through USB hard drives. We do not use cloud services and do not have decent internet bandwidth to go online. I like to ask a few questions on this process, in case you can provide any tips.

1. What is the best way to copy the data to the external HDD? Shall I `cd` inside the USB drive and do something like `datalad clone --get-data`? Perhaps a dumb way would be to `cp -L` and forget about datalad, which will make all symlinks as files, but this would lose the entire datalad advantage. To be clear, our collaborators know nothing about datalad, they are just expecting data from us. So we can't ask them to learn datalad. My understanding is that this is not a problem because from a user perspective the datasets would look just like folders with readable files in them. Moreover, I like the idea of version tagging the data we send out; this way researchers can check the version of the data they have with simple git/datalad commands.

1. Some subdatasets I have are larger than the HDD storage capacity. So, I need to find a way to split the data (or sub-subdatasets) into multiple HDDs. Is there a way to do this easily or shall we just make up scripts that keep checking the remaining storage? But then how would the recipient of the data deal with putting back the data in a single dataset/folder?

3. Lastly, this is more like an exercise, but let me ask since I am here. Let's suppose I have a parent dataset A and two subdatasets B1 and B2. I want to distribute B1 but not B2; better if  the data recipient does not notice at all the empty B2 folder. What is the best way to do this, shall I just clone A and manually `get` B1 under A while ignoring B2? Probably, B2 will still be in the config file, but at least would not be visible as an empty folder.

#### What steps will reproduce the problem?
NA

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
I think I am at 0.13 now, can bring any version needed.

#### Is there anything else that would be useful to know in this context?
NA

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Would not be here if I didn't. :)

**Comment by yarikoptic** [comment] 2020-07-29 00:16
Do you want those use drives to be used solely for transfer (so could be tarballs) or usable as is? (Well, in case 2. as is is unlikely so I proceed with as is). But overall

1. sounds like a way, but since crippled file system on USB ( unlikely you would like to format then as ext2/3), probably set those clones into annex.thin mode before getting data into them (I guess, didn't try yet) 

2. If users could use datalad, they could add drives as remotes. Just give each part USB drive a unique top level directory, then users install from any of them, add others as siblings and fetch needed data to local drive. If that unique directory matches drive part name, they would know which drive to insert from git annex whereis.

3. Sounds like a way, but I guess in the long run we could come up with some tags/metadata per subdataset and allow to specify some desired expression upon install/clone/get to limit which subdatasets would be processed and which ignored - so like annex wanted but at the subdataset level.

**Comment by dorianps** [comment] 2020-07-29 04:18
@yarikoptic  thanks for the recommendations.

1. From our point of view, the drives are needed only to transfer the data to the destination lab, not for that lab to keep the data stored in those drives. So, in principle we can tarball things if that helps, but I have never compressed datasets before and don't know if decompressing can be done without datalad (reminder, the destination lab is not familiar with datalad). I believe our drives use FAT32 but will check if we can make them ext3. What is the concern with FAT32, is it any lack of permissions concept or the lack of symlinks (pardon my ignorance on the matter)?
As for `annex thin`, I have never used it before and I will need to dig a little more on what does it do.

2. I like the challenge of building USB drives as remotes in datasets, but probably not trivial to achieve without playing around with our master dataset location (not a fan of adding remotes each time we need to send data to someone). On the other hand, the recipients of the data very likely will not know what is or how to use datalad. That's why I need the data to be ready for consumption without any datalad knowledge, and later the researchers can become more familiar with the git/datalad metadata in it.

3. The "filter" idea is interesting. For now, I will just leave the unwanted subdataset uninstalled in the USB drive.

**Comment by dorianps** [comment] 2020-08-12 03:31
Hello again. I ran a test to see if placing data in USB drives would work. The drive appears to have filesystem `HPFS/NTFS/exFAT`.

The good news is that datalad understands automatically when the filesystem does not support symlinks, and sets `git annex adjust --unlock` by itself (I was planning to do that myself).

```
[dorian@mri asset-1234]$ datalad install --recursive --source $MYDATASET
[INFO   ] Filesystem allows writing to files whose write bit is not set.
|   Detected a crippled filesystem.
[INFO   ] Disabling core.symlinks.
[INFO   ] Scanning for unlocked files (this may take some time)
[INFO   ] Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.
[INFO   ] Updating files:   0% (27/2708)
...
[INFO   ] Updating files: 100% (2708/2708), done.
[INFO   ] Switched to branch 'adjusted/master(unlocked)'
install(ok): /run/media/dorian/asset-1234/sub-S123456789 (dataset)
[INFO   ] Installing Dataset(/run/media/dorian/asset-1234/sub-S123456789) to get /run/media/dorian/asset-1234/sub-S123456789 recursively
```

I had to set `git config annex.thin true` to avoid all the files being doubled in the drive. This worked on my drive, but from what I read online it will not work on FAT filesystems.

There is a strange outcome I cannot explain. When I check the size of the entire dataset with `du -sh .` the size is 2.6Gb. As a sanity check, I checked each regular subfolder, and they are of the correct size (~300Mb each). This makes me think the data is unlocked and there is no second copy in `.git//anex/objects` as it should be with these settings `adjust --unlocked; annex.thin=TRUE`. But when I check the size of the `.git` folder itself (`du sh .git`) that is also 2.5Gb, which seems to suggest the content of the file is still in annex folders. I also checked the overall HDD storage, and that is filled with 3Gb only, which means there is no way there are two copies of the same files in there. At this point, I am not sure how is the size of the data counted and why `.git` seems to contain the entire file content while the content is out there in the regular folders. Any idea?

**Comment by dorianps** [comment] 2020-08-12 03:39
And one more question, please.

If I go inside the USB drive (remember, it has `adjust --unlock; annex.thin=TRUE) and I update datasets, then get the data. Am I correct assuming that all the old content of the data is gone, and I will have in the USB just the latest files/contents that I updated and pulled from the [origin]? In other words, this configuration will not keep any old data in the USB drive?

**Comment by yarikoptic** [comment] 2020-08-14 03:38
Hi @dorianps -- thank you very much for the updates and please accept my apologies for being silent here (I can promise - I was loud in other places ;)).

> ... tarball things if that helps, but I have never compressed datasets before and don't know if decompressing can be done without datalad ...

`datalad export-archive` generates a regular tar/zip-ball, no trace of git is left.  But in your case I wonder if it would not require some additional option to create a collection of archives, e.g. one per each folder (subject) so you could distribute them across multiple sticks if full dataset tarball wouldn't fit into a single stick (at least according to wikipedia exFat virtually has no upper file size limit you could hit, which is already good news)

Re mystery of sizes: if I got the "problem" correctly - the only possible way is some kind of "hard links". https://docs.microsoft.com/en-us/windows/win32/fileio/filesystem-functionality-comparison says that NTFS has both hard and soft (yet to learn what they are) and exFat has none ;)  May be hints (including python3.8 `os.path.samefile`) from https://stackoverflow.com/questions/41941401/how-to-find-out-if-a-folder-is-a-hard-link-and-get-its-real-path could be used to reveal if a file and corresponding key under .git/annex/objects (which I guess is what takes .git/ space) are links to the same inode (if it is really an NTFS) on the stick.

NB lots of dumps of failed attempts with exfat deleted

<details>
<summary>Here I reproduced it using our little <a href="https://github.com/datalad/datalad/blob/master/tools/eval_under_testloopfs">tools/eval_under_testloopfs</a> helper!  Indeed they are some kinds of hardlinks:</summary> 

```shell
$> DATALAD_TESTS_TEMP_FSSIZE=200 DATALAD_TESTS_TEMP_FS=ntfs ./eval_under_testloopfs bash
I: ntfs of 200:  /home/yoh/.tmp/datalad-fs-jas4j
200+0 records in
200+0 records out
206438400 bytes (206 MB, 197 MiB) copied, 0.101707 s, 2.0 GB/s
The partition start sector was not specified for /dev/loop1 and it could not be obtained automatically.  It has been set to 0.
The number of sectors per track was not specified for /dev/loop1 and it could not be obtained automatically.  It has been set to 0.
The number of heads was not specified for /dev/loop1 and it could not be obtained automatically.  It has been set to 0.
Cluster size has been automatically set to 4096 bytes.
To boot from a device, Windows needs the 'partition start sector', the 'sectors per track' and the 'number of heads' to be set.
Windows will not be able to boot from this device.
Initializing device with zeroes: 100% - Done.
Creating NTFS volume structures.
mkntfs completed successfully. Have a nice day.
I: running bash
I: New layout of history files also found.
   Please remove/propagate old history into new
(git)/home/yoh/proj/datalad/datalad-maint:tools[debian]
#1 !1511 [0].....................................:Thu Aug 13 23:30:42:.
lena:~/proj/datalad/datalad-maint/tools
$> cd /home/yoh/.tmp/datalad-fs-jas4j
total 0

#3 !1513 [0].....................................:Thu Aug 13 23:30:50:.
lena:~/.tmp/datalad-fs-jas4j
*$> df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop1      197M  2.5M  195M   2% /home/yoh/.tmp/datalad-fs-jas4j

#4 !1514 [0].....................................:Thu Aug 13 23:30:52:.
lena:~/.tmp/datalad-fs-jas4j
$> datalad install ///openneuro/ds000001
[INFO   ] Filesystem allows writing to files whose write bit is not set.                                         
|   Detected a crippled filesystem.                                                                              
[INFO   ] Disabling core.symlinks. 
[INFO   ] Scanning for unlocked files (this may take some time) 
[INFO   ] Entering an adjusted branch where files are unlocked as this filesystem does not support locked files. 
[INFO   ] Updating files:  25% (20/80) 
[INFO   ] Updating files:  26% (21/80) 
[INFO   ] Updating files:  27% (22/80) 
[INFO   ] Updating files:  28% (23/80) 
[INFO   ] Updating files:  30% (24/80) 
[INFO   ] Updating files:  31% (25/80) 
[INFO   ] Updating files:  32% (26/80) 
[INFO   ] Updating files:  33% (27/80) 
[INFO   ] Updating files:  35% (28/80) 
[INFO   ] Updating files:  36% (29/80) 
[INFO   ] Updating files:  37% (30/80) 
[INFO   ] Updating files:  38% (31/80) 
[INFO   ] Updating files:  40% (32/80) 
[INFO   ] Updating files:  41% (33/80) 
[INFO   ] Updating files:  42% (34/80) 
[INFO   ] Updating files:  43% (35/80) 
[INFO   ] Updating files:  45% (36/80) 
[INFO   ] Updating files:  46% (37/80) 
[INFO   ] Updating files:  47% (38/80) 
[INFO   ] Updating files:  48% (39/80) 
[INFO   ] Updating files:  50% (40/80) 
[INFO   ] Updating files:  51% (41/80) 
[INFO   ] Updating files:  52% (42/80) 
[INFO   ] Updating files:  53% (43/80) 
[INFO   ] Updating files:  55% (44/80) 
[INFO   ] Updating files:  56% (45/80) 
[INFO   ] Updating files:  57% (46/80) 
[INFO   ] Updating files:  58% (47/80) 
[INFO   ] Updating files:  60% (48/80) 
[INFO   ] Updating files:  61% (49/80) 
[INFO   ] Updating files:  62% (50/80) 
[INFO   ] Updating files:  63% (51/80) 
[INFO   ] Updating files:  65% (52/80) 
[INFO   ] Updating files:  66% (53/80) 
[INFO   ] Updating files:  67% (54/80) 
[INFO   ] Updating files:  68% (55/80) 
[INFO   ] Updating files:  70% (56/80) 
[INFO   ] Updating files:  71% (57/80) 
[INFO   ] Updating files:  72% (58/80) 
[INFO   ] Updating files:  73% (59/80) 
[INFO   ] Updating files:  75% (60/80) 
[INFO   ] Updating files:  76% (61/80) 
[INFO   ] Updating files:  77% (62/80) 
[INFO   ] Updating files:  78% (63/80) 
[INFO   ] Updating files:  80% (64/80) 
[INFO   ] Updating files:  81% (65/80) 
[INFO   ] Updating files:  82% (66/80) 
[INFO   ] Updating files:  83% (67/80) 
[INFO   ] Updating files:  85% (68/80) 
[INFO   ] Updating files:  86% (69/80) 
[INFO   ] Updating files:  87% (70/80) 
[INFO   ] Updating files:  88% (71/80) 
[INFO   ] Updating files:  90% (72/80) 
[INFO   ] Updating files:  91% (73/80) 
[INFO   ] Updating files:  92% (74/80) 
[INFO   ] Updating files:  93% (75/80) 
[INFO   ] Updating files:  95% (76/80) 
[INFO   ] Updating files:  96% (77/80) 
[INFO   ] Updating files:  97% (78/80) 
[INFO   ] Updating files:  98% (79/80) 
[INFO   ] Updating files: 100% (80/80) 
[INFO   ] Updating files: 100% (80/80), done. 
[INFO   ] Switched to branch 'adjusted/master(unlocked)' 
[INFO   ] access to 1 dataset sibling s3-PRIVATE not auto-enabled, enable with:
| 		datalad siblings -d "/home/yoh/.tmp/datalad-fs-jas4j/ds000001" enable -s s3-PRIVATE 
install(ok): /home/yoh/.tmp/datalad-fs-jas4j/ds000001 (dataset)

#5 !1515 [0].....................................:Thu Aug 13 23:31:05:.
lena:~/.tmp/datalad-fs-jas4j
$> cd ds000001/
total 7
1 CHANGES*                   0 sub-01/  0 sub-05/  0 sub-09/  0 sub-13/  1 task-balloonanalogrisktask_bold.json*
1 dataset_description.json*  0 sub-02/  0 sub-06/  0 sub-10/  0 sub-14/
1 participants.tsv*          0 sub-03/  0 sub-07/  0 sub-11/  0 sub-15/
4 README*                    0 sub-04/  0 sub-08/  0 sub-12/  0 sub-16/
(git)/home/yoh/.tmp/datalad-fs-jas4j/ds000001:[adjusted/master(unlocked)]
#6 !1516 [0].....................................:Thu Aug 13 23:31:12:.
lena:~/.tmp/datalad-fs-jas4j/ds000001
$> git config annex.thin true
(git)/home/yoh/.tmp/datalad-fs-jas4j/ds000001:[adjusted/master(unlocked)]
#7 !1517 [0].....................................:Thu Aug 13 23:31:16:.
lena:~/.tmp/datalad-fs-jas4j/ds000001
$> grep thin .git/config
	thin = true
(git)/home/yoh/.tmp/datalad-fs-jas4j/ds000001:[adjusted/master(unlocked)]
#8 !1518 [0].....................................:Thu Aug 13 23:31:18:.
lena:~/.tmp/datalad-fs-jas4j/ds000001
$> datalad get sub-01/func/sub-01_task-balloonanalogrisktask_run-01_bold.nii.gz 
get(ok): /home/yoh/.tmp/datalad-fs-jas4j/ds000001/sub-01/func/sub-01_task-balloonanalogrisktask_run-01_bold.nii.gz (file) [from s3-PUBLIC...]
(git)/home/yoh/.tmp/datalad-fs-jas4j/ds000001:[adjusted/master(unlocked)]
#9 !1519 [0].....................................:Thu Aug 13 23:31:33:.
lena:~/.tmp/datalad-fs-jas4j/ds000001
$> du -scm .
47	.
47	total
(git)/home/yoh/.tmp/datalad-fs-jas4j/ds000001:[adjusted/master(unlocked)]
#10 !1520 [0].....................................:Thu Aug 13 23:31:35:.
lena:~/.tmp/datalad-fs-jas4j/ds000001

```
</details>

```
$> ls -ldi sub-01/func/sub-01_task-balloonanalogrisktask_run-01_bold.nii.gz .git/annex/objects/354/149/MD5E-s47241449--433b12536427334ded8e10eeb4a62d00.nii.gz/MD5E-s47241449--433b12536427334ded8e10eeb4a62d00.nii.gz 
308 46136 -rwxrwxrwx 2 yoh root 47241449 Aug 13 23:31 .git/annex/objects/354/149/MD5E-s47241449--433b12536427334ded8e10eeb4a62d00.nii.gz/MD5E-s47241449--433b12536427334ded8e10eeb4a62d00.nii.gz*
308 46136 -rwxrwxrwx 2 yoh root 47241449 Aug 13 23:31 sub-01/func/sub-01_task-balloonanalogrisktask_run-01_bold.nii.gz*
```

The first number is the inode -- and it is the same for both key and the file!

You might need to add to your instructions to people to avoid copying also .git/ to their drives though ;-)  I wonder if .git/annex/objects could even simply be wiped out as the final step to possibly avoid people transferring it as well (I am afraid they would copy entire folder, along with .git/) -- sure annex would not be entirely happy after, but hey -- it is not the purpose here, right?  and `git-annex` branch would still have information about checksums etc.

**Comment by dorianps** [comment] 2020-08-15 00:52
@yarikoptic thanks for checking things out. I did not know about the export archive option, that will be useful in the future. Best of that also adds at least the current commit/tag for each dataset to give some sort of tracking to the recipient.

Yet, I am planning to not use tarballs for distributing. There are a few reasons for that. First, a plain folder structure makes it very easy for anyone to check the data without needing unpacking. Second, it allows people to DATALAD GET only the files they need on their computer (this is a great advantage of using datalad). Third, a full clone of datalad gives commits and tags, and allows anyone to know what version of the data they have. And last, I am hoping to educate some of the collaborators to get acquainted with datalad, because it's a really neat tool for data exchange. Datalad can also open new opportunities for us, like having a collaborator save new subdatasets of processed data with their pipeline and send us back those data, which we can easily integrate with the rest of the data.

One question remains pending. If I update a dataset in the USB drive, will I wipe out the old contents and keep only the latest files (given the above thin option)?

Thank you.

**Comment by yarikoptic** [comment] 2020-08-15 00:57
The answer to the question - I don't think so. It would need to be followed by annex find unused + drop --unused (sorry don't remember from top of the head the exact commands). I think it would be useful in general - worth a new issue for update, unless we have one already ;-)

**Comment by dorianps** [comment] 2020-08-31 15:36
Hello again everyone.

I have started filling the first HDD with datalad datasets. The problem I am encountering is an extremely slow speed. The USB drive is an Apricorn Padlock 3.0.

For a dataset of 120Gb with 24,000 files, it took 6-7 hours to `datalad install` and 17 hours to complete `datalad get`. 

I am now putting another dataset of 1.3Tb composed of ~400 subdatasets containing freesurfer data. I finished `datalad install` in maybe a day) and now I am doing `datalad get . --recursive`. The process is again very slow. In 11 hours I have managed to put in the drive about 50Gb (around 15 subdatasets). With this pace, I will need to wait 20+ days to fill the drive with the remaining data.

I am wondering if datalad is using some parallelization in the backend which is impairing the drives ability to go faster. Is that the case? Any tip on how to make things go faster?

This is the first drive I am filling using datalad, and it's also kind of a test for long term feasibility. So far, it does not look like using datalad to fill drives to ship to collabroators is a good idea.

P.s. In all honesty, I cannot exclude that something is going on with the server. The server itself seemed unresponsive a couple of times on regular commands. However, there is no load on the server, I am prectically the only user currently. I ran a couple of tests of IO writing speed on the internal drive array and all seems ok.

**Comment by dorianps** [comment] 2020-08-31 15:45
Sorry, a couple of info to know:

1. I use annex.thin = TRUE, and this is a drive that does not allow symlinks. So datalad switches to an adjusted(unlcocked) branch.
2. During the installation of a dataset, a lot of time is spent in `Updating files`. I think this step converts files into ASCII with the .git/annex location in it.

**Comment by yarikoptic** [comment] 2020-08-31 16:26
The only immediate idea is: smudge filtering is slow.  I do not think it really serializes them, but IIRC @joeyh did submit some improvements to `git` which were accepted making it "tollerable" but some improvements didn't make it.  So overall it could be slow.  Looking at `top` etc to see what is taking time or is it IO blocked could be of help here.  Also having a "reproducible" script mimicing your setup (we could provide our own datasets with data ;)) could help to replicate and analyze on our end.
Also you could try locally where you know that speeds should be fast etc.

**Comment by dorianps** [comment] 2020-08-31 17:00
I can stop the ongoing `datalad get` and run tests if needed. This seems indeed a limitation of the drive's IO. Even running `ls` on a folder takes many seconds as datalad is running.

I am running commands manually, no script currently, but roughly here is what I run:
```
datalad install --source ORIGDATASET --recursive
cd DATASET
git config annex.thin true
git submodules foreach 'git config annex.thin true`
datalad get . --recursive
```

The tests I could run are these two:
1. the IO limtis of the drive with:
```
## Use the dd command to measure throughput (write speed) 
dd if=/dev/zero of=/PATH/test1.img bs=1G count=1 oflag=dsync
## Use the dd command to measure latency 
dd if=/dev/zero of=/PATH/test2.img bs=512 count=1000 oflag=dsync
```
2. Repeat all the datalad commands above within the server storage. In this case, the source and destination will be on the same storage, but it should still be way faster then the copy on the USB drive.
 
Happy to know if @joeyh  has any more tips. 
<details><summary>Here is the full environment datalad wtf:</summary>

```
Failed to import duecredit due to No module named 'duecredit'
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## datalad
  - full_version: 0.13.1
  - version: 0.13.1
## dependencies
  - annexremote: 1.4.2
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 7.20191114-g49d738f
  - cmd:bundled-git: 2.23.0
  - cmd:git: 2.23.0
  - cmd:system-git: 2.18.0
  - cmd:system-ssh: 7.4p1
  - git: 3.1.2
  - gitdb: 4.0.5
  - humanize: 2.4.0
  - iso8601: 0.1.12
  - keyring: 21.2.1
  - keyrings.alt: 3.4.0
  - msgpack: 1.0.0
  - requests: 2.23.0
  - wrapt: 1.12.1
## environment
  - LANG: en_US.UTF-8
  - PATH: [REMOVED]
## extensions
  - container:
    - description: Containerized environments
    - entrypoints:
      - datalad_container.containers_add.ContainersAdd:
        - class: ContainersAdd
        - load_error: None
        - module: datalad_container.containers_add
        - names:
          - containers-add
          - containers_add
      - datalad_container.containers_list.ContainersList:
        - class: ContainersList
        - load_error: None
        - module: datalad_container.containers_list
        - names:
          - containers-list
          - containers_list
      - datalad_container.containers_remove.ContainersRemove:
        - class: ContainersRemove
        - load_error: None
        - module: datalad_container.containers_remove
        - names:
          - containers-remove
          - containers_remove
      - datalad_container.containers_run.ContainersRun:
        - class: ContainersRun
        - load_error: None
        - module: datalad_container.containers_run
        - names:
          - containers-run
          - containers_run
    - load_error: None
    - module: datalad_container
    - version: 0.5.2
  - metalad:
    - description: DataLad semantic metadata command suite
    - entrypoints:
      - datalad_metalad.aggregate.Aggregate:
        - class: Aggregate
        - load_error: None
        - module: datalad_metalad.aggregate
        - names:
          - meta-aggregate
          - meta_aggregate
      - datalad_metalad.dump.Dump:
        - class: Dump
        - load_error: None
        - module: datalad_metalad.dump
        - names:
          - meta-dump
          - meta_dump
      - datalad_metalad.extract.Extract:
        - class: Extract
        - load_error: None
        - module: datalad_metalad.extract
        - names:
          - meta-extract
          - meta_extract
    - load_error: None
    - module: datalad_metalad
    - version: 0.2.0
  - neuroimaging:
    - description: Neuroimaging tools
    - entrypoints:
      - datalad_neuroimaging.bids2scidata.BIDS2Scidata:
        - class: BIDS2Scidata
        - load_error: None
        - module: datalad_neuroimaging.bids2scidata
        - names:
          - bids2scidata
    - load_error: None
    - module: datalad_neuroimaging
    - version: 0.2.3
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions:
    - aws-0.21.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.1.0
    - ghc-8.6.5
    - http-client-0.5.14
    - persistent-sqlite-2.9.3
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - operating system: linux x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions:
    - 7
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  - version: 7.20191114-g49d738f
## location
  - path: /home/dp
  - type: directory
## metadata_extractors
  - annex:
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio:
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - bids:
    - load_error: None
    - module: datalad_neuroimaging.extractors.bids
    - version: None
  - datacite:
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - dicom:
    - load_error: None
    - module: datalad_neuroimaging.extractors.dicom
    - version: None
  - exif:
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage:
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image:
    - load_error: No module named 'PIL' [image.py:<module>:16]
    - module: datalad.metadata.extractors.image
  - metalad_annex:
    - load_error: None
    - module: datalad_metalad.extractors.annex
    - version: None
  - metalad_core:
    - load_error: None
    - module: datalad_metalad.extractors.core
    - version: None
  - metalad_custom:
    - load_error: None
    - module: datalad_metalad.extractors.custom
    - version: None
  - metalad_runprov:
    - load_error: None
    - module: datalad_metalad.extractors.runprov
    - version: None
  - nidm:
    - load_error: None
    - module: datalad_neuroimaging.extractors.nidm
    - version: None
  - nifti1:
    - load_error: None
    - module: datalad_neuroimaging.extractors.nifti1
    - version: None
  - xmp:
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python
  - implementation: CPython
  - version: 3.6.8
## system
  - distribution: CentOS Linux/7.8.2003/Core
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 268
  - name: Linux
  - release: 3.10.0-1127.13.1.el7.x86_64
  - type: posix
  - version: #1 SMP Tue Jun 23 15:46:38 UTC 2020
```

</details> 

P.s. Another issue with checking progress of `datalad get` it just keeps updating the progress bar with no idea what subdataset is working on (version 0.13.1). But I should open another issue about this.

**Comment by dorianps** [comment] 2020-09-03 23:34
Just an update. In 3-4 days of ongoing work there is only ~250Gb transferred in the drive. The expectation is still that this process will take 20 days for 1.3Tb of transfer. This is extremely slow. I think you guys should look at adding some trick to avoid the overhead of datalad operations on external drives. But the first problem is to find what is causing the slow `datalad get` operation. Anyone can test this locally among the developers using a USB drive?

**Comment by dorianps** [comment] 2020-09-27 16:39
An update. The file getting process (`datalad get`) finally finished after about 28-30 days of working for (1.3Tb copied on USB drive). I am not sure what is the bottleneck, but this process is clearly not feasible in the long run. I can try rsync or cp on the same type of drive to see if that is faster than datalad.

**Comment by yarikoptic** [comment] 2020-09-27 20:14
Sorry for staying silent. Yes, overhead from datalad/git annex in such use case is acknowledged, but I am not sure if there is an easy way out. I think it relates to discussion/my desires expressed on https://git-annex.branchable.com/tips/unlocked_files/#comment-61c89927302f45f49d1d28522adff465 . (Attn @joeyh ) Meanwhile rsync would need to be the way out :-/

**Comment by yarikoptic** [comment] 2022-11-08 16:59
since not clear what/if could be done on datalad side, I will just close this issue. But feel welcome to reopen or open a new one

**Closed by yarikoptic** 2022-11-08 16:59 UTC
Labels: question, answered
