### ISSUE TITLE
Failure to run `datalad run` in singularity image

### ISSUE THREAD

**Issue by chrhaeusler** [datalad/datalad#2321] opened 2018-03-19 13:41 UTC
```
$ datalad --dbg run <mycommand>
Traceback (most recent call last):
  File "/usr/local/bin/datalad", line 8, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/datalad/cmdline/main.py", line 348, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/usr/local/lib/python2.7/dist-packages/datalad/interface/base.py", line 424, in call_from_parser
    ret = list(ret)
  File "/usr/local/lib/python2.7/dist-packages/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/usr/local/lib/python2.7/dist-packages/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/usr/local/lib/python2.7/dist-packages/datalad/interface/run.py", line 118, in __call__
    from datalad.tests.utils import ok_clean_git
  File "/usr/local/lib/python2.7/dist-packages/datalad/tests/utils.py", line 39, in <module>
    from nose.tools import \
ImportError: No module named nose.tools
()
```

DataLad is installed via the current singularity image.

**Comment by kyleam** [comment] 2018-03-19 14:07
I've yet to try this myself, but two quick thoughts:

  * `ok_clean_git` shouldn't be used outside tests (at least in its current form) because tests/utils imports nose, but nose is only listed as a test dependency.  Currently, run/rerun seem to be the only non-test files that use `ok_clean_git`.

    I think that should be fixed, but I don't think it's the cause of the issue here since the Singularity recipe uses the "full" set of dependencies.

  * I'm surprised your backtrace shows py2.7.  I thought DataLad's Singularity image only had py3.

**Comment by kyleam** [comment] 2018-03-19 14:20
I'm unable to reproduce the issue when pulling the latest Singularity image.  Running

```
singularity pull --hash shub://datalad/datalad:fullmaster
singularity shell -B /tmp:/tmp --pwd /tmp -c 740104be24b0fe3c9d9e1a3f18b5c601.simg
git config --global user.name test
git config --global user.email test@example.com
datalad create runtest
cd runtest
datalad run 'echo blah >foo'
```

works for me.

And I only see Python 3 in the container:

```
$ singularity exec 740104be24b0fe3c9d9e1a3f18b5c601.simg ls /usr/local/lib
python3.5
```

**Comment by mih** [comment] 2018-03-19 14:26
Thanks for the quick response. After some interim period of madness we found a stale datalad entrypoint script in the path outside the singularity image that was the culprit. All cool inside.

**Closed by mih** 2018-03-19 14:26 UTC
