### ISSUE TITLE
Cannot 'get' dataset (MPI-Leipzig Mind Brain Body)

### ISSUE THREAD

**Issue by sofievalk** [datalad/datalad#4970] opened 2020-09-28 14:47 UTC
#### What is the problem?

I can clone the dataset to the directory (1), but then fail to get the files of specific subject (2)
1) datalad clone git@github.com:OpenNeuroDatasets/ds000221.git MPI-Leipzig_Mind-Brain-Body
2) datalad get sub-010002/ses-01/anat/

#### What steps will reproduce the problem?

```
bash-3.2$ datalad clone git@github.com:OpenNeuroDatasets/ds000221.git MPI-Leipzig_Mind-Brain-Body
[INFO   ] Scanning for unlocked files (this may take some time)                                                                                                                               
[INFO   ] Unable to parse git config from origin                                                                                                                                              
[INFO   ] [ERROR] [Errno 32] Broken pipe [sshrun.py:__call__:124] (BrokenPipeError) 
[INFO   ] Remote origin does not have git-annex installed; setting annex-ignore
|   This could be a problem with the git-annex installation on the remote. Please make sure that git-annex-shell is available in PATH when you ssh into the remote. Once you have fixed the git-annex installation, run: git annex enableremote origin 
[INFO   ] access to 1 dataset sibling s3-PRIVATE not auto-enabled, enable with:
| 		datalad siblings -d "/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body" enable -s s3-PRIVATE 
install(ok): /Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body (dataset)
bash-3.2$ cd MPI-Leipzig_Mind-Brain-Body
bash-3.2$ du -sh
 47M	.
bash-3.2$ datalad status --annex
7605 annex'd files (390.5 GB recorded total size)
nothing to save, working tree clean
bash-3.2$ datalad get sub-010002/ses-01/anat/
Total (0 ok, 7 failed out of 7):   0%|                                                                                                                            | 0.00/62.4M [00:00<?, ?B/s][WARNING] Running get resulted in stderr output: git-annex: get: 7 failed
 
[ERROR  ] not available; Try making some of these repositories available:;      28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;    aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin) [get(/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_T2w.nii.gz)] 
get(error): /Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_T2w.nii.gz (file) [not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin) [get(/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-lowres_FLAIR.nii.gz)] 
get(error): /Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-lowres_FLAIR.nii.gz (file) [not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin) [get(/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-mp2rage_T1map.nii.gz)] 
get(error): /Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-mp2rage_T1map.nii.gz (file) [not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin) [get(/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-mp2rage_T1w.nii.gz)] 
get(error): /Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-mp2rage_T1w.nii.gz (file) [not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin) [get(/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-mp2rage_defacemask.nii.gz)] 
get(error): /Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-mp2rage_defacemask.nii.gz (file) [not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin) [get(/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_inv-1_mp2rage.nii.gz)] 
get(error): /Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_inv-1_mp2rage.nii.gz (file) [not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin)]
[ERROR  ] not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin) [get(/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_inv-2_mp2rage.nii.gz)] 
get(error): /Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_inv-2_mp2rage.nii.gz (file) [not available; Try making some of these repositories available:; 	28c530ed-f3a7-4b2c-9b69-689bd944115d -- root@2a4b3dd14ab0:/datalad/ds000221;  	aacfea15-a1cf-4990-8707-331aeddeeaf6 -- s3-PUBLIC; ; (Note that these git remotes have annex-ignore set: origin)]
[WARNING] could not get some content in /Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat ['/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_T2w.nii.gz', '/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-lowres_FLAIR.nii.gz', '/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-mp2rage_T1map.nii.gz', '/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-mp2rage_T1w.nii.gz', '/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-mp2rage_defacemask.nii.gz', '/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_inv-1_mp2rage.nii.gz', '/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_inv-2_mp2rage.nii.gz'] [get(/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat)] 
get(impossible): /Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat (directory) [could not get some content in /Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat ['/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_T2w.nii.gz', '/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-lowres_FLAIR.nii.gz', '/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-mp2rage_T1map.nii.gz', '/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-mp2rage_T1w.nii.gz', '/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_acq-mp2rage_defacemask.nii.gz', '/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_inv-1_mp2rage.nii.gz', '/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body/sub-010002/ses-01/anat/sub-010002_ses-01_inv-2_mp2rage.nii.gz']]
action summary:
  get (error: 7, impossible: 1)
```

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

0.13.3

#### Is there anything else that would be useful to know in this context?

No

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)

Uhm not really (I can do the tutorial)

**Comment by adswa** [comment] 2020-09-28 15:02
Adding an attempt to enable the remote

````
$ datalad siblings -d “/Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body” enable -s s3-PRIVATE 
CommandError: ’git-annex enableremote -c annex.dotfiles=true -c ‘remote.origin.annex-ssh-options=-o ControlMaster=auto -S /Users/sofievalk/Library/Caches/datalad/sockets/df6bb6f2’ -c annex.retry=3 s3-PRIVATE’ failed with exitcode 1 under /Users/sofievalk/myanalysis/MPI-Leipzig_Mind-Brain-Body
enableremote s3-PRIVATE 
failed
git-annex: Unknown remote type S3 (pick from: git gcrypt p2p bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs hook external)
git-annex: enableremote: 1 failed
````

and Sofies ``git annex info``:

```
git-annex version: 8.20200810
build flags: Assistant Webapp Pairing WebDAV FsEvents TorrentParser MagicMime Feeds Testsuite
dependency versions: bloomfilter-2.0.1.0 cryptonite-0.27 DAV-1.3.4 feed-1.3.0.1 ghc-8.6.5 http-client-0.7.1 persistent-sqlite-2.10.6.2 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.1.0
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL X*
remote types: git gcrypt p2p bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs hook external
operating system: darwin x86_64
supported repository versions: 8
upgrade supported from repository versions: 0 1 2 3 4 5 6 7
local repository version: 8
```

**Comment by adswa** [comment] 2020-09-28 15:10
Has anyone seen this before? A recent git-annex version that does not have support for S3 special remotes? It was installed on Mac via ``brew install git-annex``.

**Comment by kyleam** [comment] 2020-09-28 15:12
I don't know about macos builds of git-annex, but ,based on what's shown above, it certainly looks like that is the issue.

**Comment by kyleam** [comment] 2020-09-28 15:26
It looks like s3 flag was added to the build 20 days ago: https://github.com/Homebrew/homebrew-core/commit/1b56a7e3e4ecbcee5d4eaaf793c610d7f14993e5

I'm not sure how homebrew updates work, but S3 should be in the build flags if you're pulling in that variant (assuming that commit worked liked it was supposed to).

**Comment by yarikoptic** [comment] 2020-09-28 16:07
Note that you don't want s3-private but s3-public. Although it won't actually deal with s3 but use public http urls for that remote, most likely you indeed need annex build with s3 support. 
I think this issue is troubleshooted to the cause, and no action is needed on datalad side, so I will close it. Reopen if disagree

**Closed by yarikoptic** 2020-09-28 16:07 UTC

**Comment by adswa** [comment] 2020-09-28 16:13
Thank you for digging this up @kyleam. Yes, it can be closed.
