### ISSUE TITLE
Tests added in gh-3009 may fail

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3023] opened 2018-11-28 16:48 UTC
Presumably it's flaky since the failure wasn't observed in that PR.

https://travis-ci.org/datalad/datalad/jobs/460830538#L2749

```
======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(True,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 423, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/support/tests/test_annexrepo.py", line 2476, in check_commit_annex_commit_changed
    , untracked=['untracked']
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 219, in ok_clean_git
    eq_(sorted(index_modified_), sorted(index_modified))
AssertionError: ['tobechanged-annex', 'tobechanged-git', 'willnotgetshort'] != ['tobechanged-annex', 'tobechanged-git']
======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(False,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 423, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/support/tests/test_annexrepo.py", line 2476, in check_commit_annex_commit_changed
    , untracked=['untracked']
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 219, in ok_clean_git
    eq_(sorted(index_modified_), sorted(index_modified))
AssertionError: ['tobechanged-annex', 'tobechanged-git', 'willnotgetshort'] != ['tobechanged-annex', 'tobechanged-git']
```

**Comment by yarikoptic** [comment] 2018-11-28 16:58
is it failing some times or reproducible? for 3.5 or for all?

**Comment by kyleam** [comment] 2018-11-28 17:04
> is it failing some times or reproducible?

First sentence of my post: "Presumably it's flaky since the failure wasn't observed in that PR."

> for 3.5 or for all?

I've linked to the Travis run where I've observed it.

**Comment by yarikoptic** [comment] 2018-11-28 17:39
> > is it failing some times or reproducible?
> 
> First sentence of my post: "Presumably it's flaky since the failure wasn't observed in that PR."
> 
> > for 3.5 or for all?
> 
> I've linked to the Travis run where I've observed it.

if failure was not observed in that PR, where was it observed?  flaky is not necessarily the same as "not reproducible in the same environment".

we could play the words&references game (ATM have no time for that) or I would just appreciate if issue was self-sufficiently described.

**Comment by kyleam** [comment] 2018-11-28 18:08
> if failure was not observed in that PR, where was it observed?

My "that PR" refers to gh-3009, the only PR mentioned before, but I suppose that you're reading it as the unrelated and unreferenced PR that is connected to the linked Travis run.  I should have spelled out gh-3009 again explicitly.

> flaky is not necessarily the same as "not reproducible in the same environment".

Sure, it's possible that something in the Travis environment could have changed between gh-3009 and the linked Travis run.  That's why I only presume it is flaky.

> we could play the words&references game (ATM have no time for that)

I don't play word games.  I try to communicate clearly and concisely; I sometimes fail.

**Comment by yarikoptic** [comment] 2018-11-28 20:19
grr.. because I've merged #3021 now can't rerun that failing run :-/  Let's see if this issue emerges again in active PRs

**Comment by yarikoptic** [comment] 2018-11-28 22:51
resurfaced, only one of them, again with python 3.5.6: https://travis-ci.org/datalad/datalad/jobs/460931101#L2750 (will restart now)

**Comment by yarikoptic** [comment] 2018-11-29 01:12
Just now spotted that failures are in v6 mode! Didn't check yet locally

**Comment by yarikoptic** [comment] 2018-11-29 02:01
here is how it looks in a "bad" state -- the `willnotgetshort` is in typechange relative to index:
```
$> git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	typechange: tobechanged-annex
	modified:   tobechanged-git
	modified:   willnotgetshort

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	untracked

no changes added to commit (use "git add" and/or "git commit -a")
(dev3) 1 15576 [1].....................................:Wed 28 Nov 2018 08:49:40 PM EST:.
(git-annex)hopa:…tmp/datalad_temp_tree_check_commit_annex_commit_changedm9mvn6gw[master]git
$> git show
commit 996e1940baf9046e1de06aca8b0f8163e7e7627f (HEAD -> master)
Author: DataLad Tester <test@example.com>
Date:   Wed Nov 28 20:33:28 2018 -0500

    message

diff --git a/alwaysbig b/alwaysbig
deleted file mode 120000
index bf55fb8..0000000
--- a/alwaysbig
+++ /dev/null
@@ -1 +0,0 @@
-.git/annex/objects/50/4M/SHA256E-s10--bf2cb58a68f684d95a3b78ef8f661c9a4e5b09e82cc8f9cc88cce90528caeb27/SHA256E-s10--bf2cb58a68f684d95a3b78ef8f661c9a4e5b09e82cc8f9cc88cce90528caeb27
\ No newline at end of file
diff --git a/alwaysbig b/alwaysbig
new file mode 100644
index 0000000..830a99e
--- /dev/null
+++ b/alwaysbig
@@ -0,0 +1 @@
+/annex/objects/SHA256E-s11--28cb017dfc99073aa1b47c1b30f413e3ce774c4991eb4158de50f9dbb36d8043
diff --git a/willnotgetshort b/willnotgetshort
deleted file mode 120000
index 178308f..0000000
--- a/willnotgetshort
+++ /dev/null
@@ -1 +0,0 @@
-.git/annex/objects/6f/xQ/SHA256E-s10--6d2fe32dc4249ef7e7359c6d874fffbbf335e832e49a2681236e1b686af78794/SHA256E-s10--6d2fe32dc4249ef7e7359c6d874fffbbf335e832e49a2681236e1b686af78794
\ No newline at end of file
diff --git a/willnotgetshort b/willnotgetshort
new file mode 100644
index 0000000..dd6df3b
--- /dev/null
+++ b/willnotgetshort
@@ -0,0 +1 @@
+/annex/objects/SHA256E-s1--3e23e8160039594a33894f6564e1b1348bbd7a0088d42c4acb73eeaed59c009d
```
in a good run there is no typechange.
I am not yet strong about all the git linkfiles and annex commiting them instead of symlinks... (probably something also to explicitly test for later on) and how things differ with a "good" run where there is no type change reported by status but both show identical index (?) content for that file:
```shell
$> git ls-files -s willnotgetshort    
100644 dd6df3b5b8a2c92bf2eb230070b0a64feebd9f5b 0	willnotgetshort

$> git show dd6df3b5b8a2c92bf2eb230070b0a64feebd9f5b
/annex/objects/SHA256E-s1--3e23e8160039594a33894f6564e1b1348bbd7a0088d42c4acb73eeaed59c009d
```

what am I missing @kyleam @joeyh et al?

**Comment by yarikoptic** [comment] 2018-11-29 02:18
ha ha -- reverting f5d6a6f5cecb85ab6bee5d4fe11e09ec8555d3aa and then doing the same index manipulations in v6 mode to also avoids this issue and also makes the regular symlinks (locked files?) to be committed (due to explicit "git annex add" I guess which we do if files are provided to commit), which I would have liked more in general for consistency of operation (I am yet trying not to think about trying to explain newbies the difference between committing a symlink and then some git link, and only in v7 mode)

**Closed** 2018-12-02 04:07 UTC
