### ISSUE TITLE
Converting a git repo into a dataset fails with -f

### ISSUE THREAD

**Issue by ddeepwel** [datalad/datalad#6984] opened 2022-08-24 20:24 UTC
### What is the problem?

Converting an existing git repo into a datalad dataset requires `--force` rather than `-f` which fails. Based on the error message, it looks like `-f` links to the wrong flag.

### What steps will reproduce the problem?

```
mkdir newdataset
cd newdataset
git init
datalad create -f
datalad create --force
```

The `datalad create -f` fails with 
```
usage: datalad [-c (:name|name=value)] [-C PATH] [--cmd] [-l LEVEL] [--on-failure {ignore,continue,stop}] [--report-status {success,failure,ok,notneeded,impossible,error}] [--report-type {dataset,file}]
               [-f {generic,json,json_pp,tailored,disabled,'<template>'}] [--dbg] [--idbg] [--version]
datalad: error: argument -f/--output-format: expected one argument
```

### DataLad information

datalad 0.17.3

**Comment by yarikoptic** [comment] 2022-08-24 20:58
duplicate of #6814 being fixed by #6980

**Closed by yarikoptic** 2022-08-24 20:58 UTC
