### ISSUE TITLE
Annex'd files present but not available when using it

### ISSUE THREAD

**Issue by just-meng** [datalad/datalad#6973] opened 2022-08-22 11:04 UTC
### What is the problem?

Hi all, 

I have a dataset on a hard drive that I regularly push to gin and pull onto another computer. It used to be just fine, until last week when all annexed files became unavailable. Datalad still thinks that the files are present:
```
jiame@RAZOR MINGW64 /my_dataset (adjusted/master(unlocked))
$ datalad status --annex all
120 annex'd files (54.9 GB/54.9 GB present/total size)

```
But in my file system there are only few KB of files, and when I try to open a file in ImageJ or suite2p, it becomes clear that the content is not available:
![image](https://user-images.githubusercontent.com/108482432/185905647-d19e6573-93eb-4485-8417-9e5256303c01.png)

`datalad get a-specific-file` won't do anything.

Important to note that the data was actually generated on this hard drive and had been used before.

### DataLad information

datalad 0.17.1
Windows 11

### Additional context

The problem might have happened at the same time when I switched the USB-C hub, and the harddrive suddently showed up under F:/ and not E:/ anymore. Could this be related to my problem?

### Have you had any success using DataLad before?

Yes, it was working perfectly fine before last week.

**Comment by adswa** [comment] 2022-08-22 11:26
Hi! Can you maybe post the output of running ``git annex whereis <file>`` on an affected file?

It would also be helpful if can run ``datalad wtf`` in that dataset and post the output here.

**Comment by adswa** [comment] 2022-08-22 12:36
Thx much for the additional info! I'm in a train at the moment, but will try to reproduce this on a windows system when I'm home

**Comment by adswa** [comment] 2022-08-22 15:02
I tried briefly to reproduce this and failed so far. I created a dataset on drive D:, pushed its content to a sibling on Gin and dropped the local files, then remounted the dataset under drive F:/ - but `datalad status --annex` and `datalad get <file>` all behaved sane. Could you try to run a `git annex -v -d drop <filename>` and a `git annex -v -d get <filename>` and post the output here? 
Could you also run a `git annex fsck` and report what it says?

**Comment by just-meng** [comment] 2022-08-22 15:12
```
$ git annex -v -d drop 220303A_Ai9xSim/22-04-24_DMT/meanImg.tif
[2022-08-22 17:06:39.9189256] (Utility.Process) process [16088] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","symbolic-ref","-q","HEAD"]
[2022-08-22 17:06:39.9430513] (Utility.Process) process [16088] done ExitSuccess
[2022-08-22 17:06:39.9623257] (Utility.Process) process [22088] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","refs/heads/adjusted/master(unlocked)"]
[2022-08-22 17:06:40.9885619] (Utility.Process) process [22088] done ExitSuccess
[2022-08-22 17:06:41.0087967] (Utility.Process) process [20260] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","ls-files","--stage","-z","--","220303A_Ai9xSim/22-04-24_DMT/meanImg.tif"]
[2022-08-22 17:06:41.028067] (Utility.Process) process [20740] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2022-08-22 17:06:41.0463476] (Utility.Process) process [2444] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2022-08-22 17:06:41.0639018] (Utility.Process) process [22444] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2022-08-22 17:06:41.2986356] (Utility.Process) process [13136] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","write-tree"]
[2022-08-22 17:06:42.1333056] (Utility.Process) process [13136] done ExitSuccess
[2022-08-22 17:06:42.1530692] (Utility.Process) process [16208] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/annex/last-index"]
[2022-08-22 17:06:42.2214473] (Utility.Process) process [16208] done ExitSuccess
[2022-08-22 17:06:42.2215543] (Database.Keys) reconcileStaged start
[2022-08-22 17:06:42.2410851] (Utility.Process) process [10664] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2022-08-22 17:06:42.2584225] (Utility.Process) process [19908] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2022-08-22 17:06:42.2820676] (Utility.Process) process [21860] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","-c","diff.external=","diff","822512687f1584c110ade473f9d72cf29bea7cdd","ba5c079238e56faf12a5d03824898a4125427bc1","--raw","-z","--no-abbrev","-G/annex/objects/","--no-renames","--ignore-submodules=all","--no-ext-diff"]
[2022-08-22 17:06:42.4538146] (Utility.Process) process [21860] done ExitSuccess
[2022-08-22 17:06:42.4817173] (Utility.Process) process [19908] done ExitSuccess
[2022-08-22 17:06:42.4817173] (Utility.Process) process [10664] done ExitSuccess
[2022-08-22 17:06:42.6084733] (Utility.Process) process [11992] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","update-ref","refs/annex/last-index","ba5c079238e56faf12a5d03824898a4125427bc1"]
[2022-08-22 17:06:42.7155589] (Utility.Process) process [11992] done ExitSuccess
[2022-08-22 17:06:42.7155589] (Database.Keys) reconcileStaged end
[2022-08-22 17:06:42.7696199] (Utility.Process) process [14412] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","check-attr","-z","--stdin","annex.backend","annex.largefiles","annex.numcopies","annex.mincopies","--"]
[2022-08-22 17:06:42.8465462] (Utility.Process) process [4240] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","git-annex"]
[2022-08-22 17:06:42.8963984] (Utility.Process) process [4240] done ExitSuccess
[2022-08-22 17:06:42.905552] (Utility.Process) process [2040] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/heads/git-annex"]
[2022-08-22 17:06:42.9345066] (Utility.Process) process [2040] done ExitSuccess
[2022-08-22 17:06:42.9451868] (Utility.Process) process [21800] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","log","refs/heads/git-annex..a36cb84a03cc4f08204da8ebaffda46b45c8ec1e","--pretty=%H","-n1"]
[2022-08-22 17:06:43.0231611] (Utility.Process) process [21800] done ExitSuccess
[2022-08-22 17:06:43.0344736] (Utility.Process) process [7596] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","hash-object","-w","--stdin-paths","--no-filters"]
[2022-08-22 17:06:43.0461761] (Utility.Process) process [11904] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
[2022-08-22 17:06:43.0568176] (Utility.Process) process [12296] feed: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","update-index","-z","--index-info"]
[2022-08-22 17:06:43.0646813] (Utility.Process) process [18028] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","diff-index","--raw","-z","-r","--no-renames","-l0","--cached","refs/heads/git-annex","--"]
[2022-08-22 17:06:43.1025846] (Utility.Process) process [18028] done ExitSuccess
[2022-08-22 17:06:43.1083395] (Utility.Process) process [12296] done ExitSuccess
drop 220303A_Ai9xSim/22-04-24_DMT/meanImg.tif (locking gin...)
  You have enabled concurrency, but git-annex is not able to use ssh connection caching. This may result in multiple ssh processes prompting for passwords at the same time.

  annex.sshcaching is not set to true
[2022-08-22 17:06:43.2073304] (Utility.Process) process [15572] chat: ssh ["git@gin.g-node.org","-T","git-annex-shell 'p2pstdio' '/jwu/ds_preliminary_psychedelics_suite2p.git' '--debug' '417389c9-336b-4e4f-b181-3763bd5fe205' --uuid 1360954f-2322-4c13-ba22-76239fc417eb"]
[2022-08-22 17:06:44.1087578] (P2P.IO) [ssh connection Just 15572] [ThreadId 3] P2P < AUTH-SUCCESS 1360954f-2322-4c13-ba22-76239fc417eb
[2022-08-22 17:06:44.1108021] (P2P.IO) [ssh connection Just 15572] [ThreadId 3] P2P > VERSION 1
[2022-08-22 17:06:44.1470382] (P2P.IO) [ssh connection Just 15572] [ThreadId 3] P2P < VERSION 1
[2022-08-22 17:06:44.1480374] (P2P.IO) [ssh connection Just 15572] [ThreadId 3] P2P > LOCKCONTENT MD5E-s1048848--58556760a92aa25146a9f0a11615a76c.tif
[2022-08-22 15:06:40.590620676] [ThreadId 4] P2P < VERSION 1
[2022-08-22 15:06:40.590811905] [ThreadId 4] P2P > VERSION 1
[2022-08-22 17:06:44.1824244] (P2P.IO) [ssh connection Just 15572] [ThreadId 3] P2P < SUCCESS
[2022-08-22 17:06:44.1827858] (Command.Drop) Dropping from here proof: Just (SafeDropProof (NumCopies 1) (MinCopies 1) [LockedCopy UUID "1360954f-2322-4c13-ba22-76239fc417eb"] (Just (ContentRemovalLock (MkKey {keyData = Key {keyName = "58556760a92aa25146a9f0a11615a76c.tif", keyVariety = MD5Key (HasExt True), keySize = Just 1048848, keyMtime = Nothing, keyChunkSize = Nothing, keyChunkNum = Nothing}, keySerialization = "MD5E-s1048848--58556760a92aa25146a9f0a11615a76c.tif"}))))
[2022-08-22 15:06:40.619156917] [ThreadId 4] P2P < LOCKCONTENT MD5E-s1048848--58556760a92aa25146a9f0a11615a76c.tif
[2022-08-22 15:06:40.620080298] [ThreadId 4] P2P > SUCCESS
[2022-08-22 17:06:44.2033527] (P2P.IO) [ssh connection Just 15572] [ThreadId 3] P2P > UNLOCKCONTENT
[2022-08-22 17:06:44.2075966] (Annex.Branch) read 02d\230\MD5E-s1048848--58556760a92aa25146a9f0a11615a76c.tif.log
[2022-08-22 15:06:40.683096069] [ThreadId 4] P2P < UNLOCKCONTENT
[2022-08-22 17:06:44.2401883] (Annex.Branch) set 02d\230\MD5E-s1048848--58556760a92aa25146a9f0a11615a76c.tif.log
ok
[2022-08-22 17:06:44.2451771] (Utility.Process) process [11904] done ExitSuccess
[2022-08-22 17:06:44.2485168] (Utility.Process) process [14412] done ExitSuccess
[2022-08-22 17:06:44.2496805] (Utility.Process) process [22444] done ExitSuccess
[2022-08-22 17:06:44.2505311] (Utility.Process) process [2444] done ExitSuccess
[2022-08-22 17:06:44.2505311] (Utility.Process) process [20740] done ExitSuccess
[2022-08-22 17:06:44.2505311] (Utility.Process) process [20260] done ExitSuccess
[2022-08-22 17:06:44.4657372] (Utility.Process) process [14840] feed: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","update-index","-z","--index-info"]
[2022-08-22 17:06:44.6001576] (Utility.Process) process [14840] done ExitSuccess
[2022-08-22 17:06:44.6061848] (Utility.Process) process [20020] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/heads/git-annex"]
[2022-08-22 17:06:44.6242083] (Utility.Process) process [20020] done ExitSuccess
(recording state in git...)
[2022-08-22 17:06:44.6478632] (Utility.Process) process [15548] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
[2022-08-22 17:06:44.6534785] (Utility.Process) process [7868] feed: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","update-index","-z","--index-info"]
[2022-08-22 17:06:44.6627583] (Utility.Process) process [20112] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","diff-index","--raw","-z","-r","--no-renames","-l0","--cached","refs/heads/git-annex","--"]
[2022-08-22 17:06:44.7824816] (Utility.Process) process [20112] done ExitSuccess
[2022-08-22 17:06:44.792015] (Utility.Process) process [7868] done ExitSuccess
[2022-08-22 17:06:44.8419138] (Utility.Process) process [14056] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","write-tree"]
[2022-08-22 17:06:46.3039981] (Utility.Process) process [14056] done ExitSuccess
[2022-08-22 17:06:46.3238006] (Utility.Process) process [22496] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","commit-tree","3b480c07a1c1394e1bc1e729860dce65c8c9a11b","--no-gpg-sign","-p","refs/heads/git-annex"]
[2022-08-22 17:06:46.5236792] (Utility.Process) process [22496] done ExitSuccess
[2022-08-22 17:06:46.5329255] (Utility.Process) process [15968] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","update-ref","refs/heads/git-annex","c6ba9afcd60bb462de4e2ea2369174bd810d4400"]
[2022-08-22 17:06:46.6097935] (Utility.Process) process [15968] done ExitSuccess
[2022-08-22 17:06:46.7312013] (Utility.Process) process [15548] done ExitSuccess
[2022-08-22 17:06:46.7341911] (Utility.Process) process [7596] done ExitSuccess
```

```
$ git annex -v -d get 220303A_Ai9xSim/22-04-24_DMT/meanImg.tif
[2022-08-22 17:07:42.7289807] (Utility.Process) process [11652] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","symbolic-ref","-q","HEAD"]
[2022-08-22 17:07:42.7514199] (Utility.Process) process [11652] done ExitSuccess
[2022-08-22 17:07:42.7582644] (Utility.Process) process [8344] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","refs/heads/adjusted/master(unlocked)"]
[2022-08-22 17:07:42.78562] (Utility.Process) process [8344] done ExitSuccess
[2022-08-22 17:07:42.8290412] (Utility.Process) process [22104] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","ls-files","--stage","-z","--","220303A_Ai9xSim/22-04-24_DMT/meanImg.tif"]
[2022-08-22 17:07:42.8425093] (Utility.Process) process [7080] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2022-08-22 17:07:42.8579027] (Utility.Process) process [15552] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2022-08-22 17:07:42.8748246] (Utility.Process) process [8128] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch=%(objectname) %(objecttype) %(objectsize)","--buffer"]
get 220303A_Ai9xSim/22-04-24_DMT/meanImg.tif [2022-08-22 17:07:42.9313897] (Utility.Process) process [1976] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","git-annex"]
[2022-08-22 17:07:42.9525362] (Utility.Process) process [1976] done ExitSuccess
[2022-08-22 17:07:42.9574376] (Utility.Process) process [5252] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/heads/git-annex"]
[2022-08-22 17:07:42.9795043] (Utility.Process) process [5252] done ExitSuccess
[2022-08-22 17:07:42.987136] (Utility.Process) process [13384] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","log","refs/heads/git-annex..c6ba9afcd60bb462de4e2ea2369174bd810d4400","--pretty=%H","-n1"]
[2022-08-22 17:07:43.0109298] (Utility.Process) process [13384] done ExitSuccess
[2022-08-22 17:07:43.0226047] (Utility.Process) process [15560] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","hash-object","-w","--stdin-paths","--no-filters"]
[2022-08-22 17:07:43.035323] (Utility.Process) process [16196] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
[2022-08-22 17:07:43.0448411] (Utility.Process) process [19204] feed: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","update-index","-z","--index-info"]
[2022-08-22 17:07:43.0574748] (Utility.Process) process [13556] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","diff-index","--raw","-z","-r","--no-renames","-l0","--cached","refs/heads/git-annex","--"]
[2022-08-22 17:07:43.0934952] (Utility.Process) process [13556] done ExitSuccess
[2022-08-22 17:07:43.1028844] (Utility.Process) process [19204] done ExitSuccess
(from gin...)

  You have enabled concurrency, but git-annex is not able to use ssh connection caching. This may result in multiple ssh processes prompting for passwords at the same time.

  annex.sshcaching is not set to true
[2022-08-22 17:07:44.3027768] (Utility.Process) process [19500] chat: ssh ["git@gin.g-node.org","-T","git-annex-shell 'p2pstdio' '/jwu/ds_preliminary_psychedelics_suite2p.git' '--debug' '417389c9-336b-4e4f-b181-3763bd5fe205' --uuid 1360954f-2322-4c13-ba22-76239fc417eb"]
[2022-08-22 17:07:45.0266908] (P2P.IO) [ssh connection Just 19500] [ThreadId 3] P2P < AUTH-SUCCESS 1360954f-2322-4c13-ba22-76239fc417eb
[2022-08-22 17:07:45.0266908] (P2P.IO) [ssh connection Just 19500] [ThreadId 3] P2P > VERSION 1
[2022-08-22 17:07:45.0635539] (P2P.IO) [ssh connection Just 19500] [ThreadId 3] P2P < VERSION 1
[2022-08-22 17:07:45.0648327] (P2P.IO) [ssh connection Just 19500] [ThreadId 3] P2P > GET 0 220303A_Ai9xSim/22-04-24_DMT/meanImg.tif MD5E-s1048848--58556760a92aa25146a9f0a11615a76c.tif
[2022-08-22 15:07:41.506565115] [ThreadId 4] P2P < VERSION 1
[2022-08-22 15:07:41.506738408] [ThreadId 4] P2P > VERSION 1
[2022-08-22 15:07:41.534649538] [ThreadId 4] P2P < GET 0 220303A_Ai9xSim/22-04-24_DMT/meanImg.tif MD5E-s1048848--58556760a92aa25146a9f0a11615a76c.tif
[2022-08-22 17:07:45.1253699] (P2P.IO) [ssh connection Just 19500] [ThreadId 3] P2P < DATA 1048848
[2022-08-22 15:07:41.569143301] [ThreadId 4] P2P > DATA 1048848
94%   959.53 KiB      700 KiB/s 0s [2022-08-22 15:07:41.941790625] [ThreadId 4] P2P > VALID
100%  1 MiB           624 KiB/s 0s [2022-08-22 17:07:46.6706029] (P2P.IO) [ssh connection Just 19500] [ThreadId 3] P2P < VALID
[2022-08-22 17:07:46.6706029] (P2P.IO) [ssh connection Just 19500] [ThreadId 3] P2P > SUCCESS
[2022-08-22 17:07:46.6837085] (Utility.Process) process [16196] done ExitSuccess
[2022-08-22 17:07:46.6932] (Utility.Process) process [15560] done ExitSuccess
[2022-08-22 15:07:43.141423254] [ThreadId 4] P2P < SUCCESS
[2022-08-22 17:07:46.7328754] (Utility.Process) process [21824] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","write-tree"]
[2022-08-22 17:07:46.7815715] (Utility.Process) process [21824] done ExitSuccess
[2022-08-22 17:07:46.7889667] (Utility.Process) process [14584] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/annex/last-index"]
[2022-08-22 17:07:46.8112589] (Utility.Process) process [14584] done ExitSuccess
[2022-08-22 17:07:46.8304138] (Utility.Process) process [11724] call: cp ["-a","--no-preserve=xattr",".git\\annex\\objects\\02d\\230\\MD5E-s1048848--58556760a92aa25146a9f0a11615a76c.tif\\MD5E-s1048848--58556760a92aa25146a9f0a11615a76c.tif",".git\\annex\\othertmp\\t.0\\t"]
[2022-08-22 17:07:46.8903188] (Utility.Process) process [11724] done ExitSuccess
[2022-08-22 17:07:46.9048698] (Annex.Branch) read 02d\230\MD5E-s1048848--58556760a92aa25146a9f0a11615a76c.tif.log
[2022-08-22 17:07:46.9117054] (Utility.Process) process [1144] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
[2022-08-22 17:07:46.9911911] (Annex.Branch) set 02d\230\MD5E-s1048848--58556760a92aa25146a9f0a11615a76c.tif.log
ok
[2022-08-22 17:07:46.9986862] (Utility.Process) process [1144] done ExitSuccess
[2022-08-22 17:07:47.0016146] (Utility.Process) process [8128] done ExitSuccess
[2022-08-22 17:07:47.0016146] (Utility.Process) process [15552] done ExitSuccess
[2022-08-22 17:07:47.0021931] (Utility.Process) process [7080] done ExitSuccess
[2022-08-22 17:07:47.0021931] (Utility.Process) process [22104] done ExitSuccess
(recording state in git...)
[2022-08-22 17:07:47.2389394] (Utility.Process) process [2840] feed: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","-c","core.safecrlf=false","update-index","-q","--refresh","-z","--stdin"]
[2022-08-22 17:07:47.5549143] (Utility.Process) process [15508] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)"]
[2022-08-22 17:07:47.5933842] (Utility.Process) process [17264] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch"]
[2022-08-22 17:07:47.6381667] (Utility.Process) process [18760] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","write-tree"]
[2022-08-22 17:07:47.6571632] (Utility.Process) process [18760] done ExitFailure 128
[2022-08-22 17:07:47.6581594] (Database.Keys) reconcileStaged start (in conflict)
[2022-08-22 17:07:47.6657401] (Utility.Process) process [4044] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--hash","refs/annex/last-index"]
[2022-08-22 17:07:47.6847561] (Utility.Process) process [4044] done ExitSuccess
[2022-08-22 17:07:47.6921302] (Utility.Process) process [8652] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2022-08-22 17:07:47.7014732] (Utility.Process) process [19752] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2022-08-22 17:07:47.7107624] (Utility.Process) process [12436] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","-c","diff.external=","diff","ba5c079238e56faf12a5d03824898a4125427bc1","--staged","--raw","-z","--no-abbrev","-G/annex/objects/","--no-renames","--ignore-submodules=all","--no-ext-diff"]
[2022-08-22 17:07:47.7384449] (Utility.Process) process [12436] done ExitSuccess
[2022-08-22 17:07:47.7436933] (Utility.Process) process [19752] done ExitSuccess
[2022-08-22 17:07:47.7436933] (Utility.Process) process [8652] done ExitSuccess
[2022-08-22 17:07:47.7436933] (Database.Keys) reconcileStaged end
[2022-08-22 17:07:47.8805373] (Utility.Process) process [17264] done ExitSuccess
[2022-08-22 17:07:47.8829378] (Utility.Process) process [15508] done ExitSuccess
[2022-08-22 17:07:47.9499472] (Utility.Process) process [2840] done ExitSuccess
[2022-08-22 17:07:47.9784266] (Utility.Process) process [14228] feed: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","update-index","-z","--index-info"]
[2022-08-22 17:07:47.9790731] (Utility.Process) process done ExitSuccess
[2022-08-22 17:07:47.999957] (Utility.Process) process [5840] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","hash-object","-w","--stdin-paths","--no-filters"]
[2022-08-22 17:07:48.1549422] (Utility.Process) process [14228] done ExitSuccess
[2022-08-22 17:07:48.1629507] (Utility.Process) process [1252] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/heads/git-annex"]
[2022-08-22 17:07:48.1824156] (Utility.Process) process [1252] done ExitSuccess
[2022-08-22 17:07:48.1887699] (Utility.Process) process [9776] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
[2022-08-22 17:07:48.1959464] (Utility.Process) process [14000] feed: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","update-index","-z","--index-info"]
[2022-08-22 17:07:48.2073293] (Utility.Process) process [15820] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","diff-index","--raw","-z","-r","--no-renames","-l0","--cached","refs/heads/git-annex","--"]
[2022-08-22 17:07:48.3688503] (Utility.Process) process [15820] done ExitSuccess
[2022-08-22 17:07:48.3750369] (Utility.Process) process [14000] done ExitSuccess
[2022-08-22 17:07:48.4414644] (Utility.Process) process [20580] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","write-tree"]
[2022-08-22 17:07:48.7427767] (Utility.Process) process [20580] done ExitSuccess
[2022-08-22 17:07:48.7626439] (Utility.Process) process [1288] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","commit-tree","90cac1e4086f11d2666c72a73fb9ddfbb7c81444","--no-gpg-sign","-p","refs/heads/git-annex"]
[2022-08-22 17:07:48.9353706] (Utility.Process) process [1288] done ExitSuccess
[2022-08-22 17:07:48.9508054] (Utility.Process) process [10624] call: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","update-ref","refs/heads/git-annex","1b1ae7bc4ee3d6e13bdf1ea64dd9e96e3ead0e77"]
[2022-08-22 17:07:49.0523375] (Utility.Process) process [10624] done ExitSuccess
[2022-08-22 17:07:49.1357759] (Utility.Process) process [9776] done ExitSuccess
[2022-08-22 17:07:49.1402044] (Utility.Process) process [5840] done ExitSuccess

```

```
$ git annex fsck
fsck 220303A_Ai9xSim/22-04-24_DMT/dff.pkl (fixing link) (fixing worktree content) (checksum...) ok
fsck 220303A_Ai9xSim/22-04-24_DMT/fissa/prepared.npz (fixing link) (fixing worktree content) (checksum...) ok
fsck 220303A_Ai9xSim/22-04-24_DMT/fissa/separated.npz (fixing link) (fixing worktree content) (checksum...) ok
fsck 220303A_Ai9xSim/22-04-24_DMT/meanImg.tif (checksum...) ok
...
```

**Comment by just-meng** [comment] 2022-08-22 15:21
The particular file I did `datalad drop` and `datalad get` on is now available!

Also `git annex fsck` seems to be fixing my problem. The proper file size is being displayed in my file system after the `fsck` is done for the file. Tried with one of the files, it could be loaded in python!

**Comment by just-meng** [comment] 2022-08-22 15:44
The command has run through, and things look fine now! The contents of the files are available again without drop & get. If you have any idea what has caused the problem, I would love to know. In any case, thanks Adina for solving the problem!

**Comment by just-meng** [comment] 2022-08-22 16:00
A subsequent `datalad status` shows that the symlinks of the annex'd files are modified.

```
$ datalad status
 modified: 220303A_Ai9xSim\22-04-24_DMT\dff.pkl (symlink)
 modified: 220303A_Ai9xSim\22-04-24_DMT\fissa\prepared.npz (symlink)
 modified: 220303A_Ai9xSim\22-04-24_DMT\fissa\separated.npz (symlink)
 modified: 220303A_Ai9xSim\22-04-24_DMT\meanImg.tif (symlink)
 ...
```

**Comment by adswa** [comment] 2022-08-23 07:33
Good to know that your dataset is back in a usable state! I agree it would be very good to figure out the cause of it. Something that strikes me as odd is seeing symlinks in the status report in your dataset, given that this dataset lives on an NTFS file system. Can you check which branch you are on (``master`` or ``adjusted/master(unlocked)``)? ``git status`` should tell you. @yarikoptic did you happen to see something like this before?

**Comment by adswa** [comment] 2022-08-23 07:52
oh, and could you report the output of ``cat .git/config`` (executed in the root of your dataset)?

**Comment by bpoldrack** [comment] 2022-11-30 17:27
Just noticed, that we didn't follow up on this one.

So, from my POV: What you showed in the very beginning does not look like the files disappeared really but that the symlinks were replaced by "link-files" - text files containing the relative path to the target instead of having actual symlinks. This is can be used on file systems that don't support symlinks. Given that `fsck` fixed your probem and theat you ended up with modifications of the symlinks, it seems to me, that with your Hub Switch for a moment the file system's capabilities weren't correctly identified (or actually changed), which put the repository into a mode with those text files instead. Ultimately your setup seems to support symlinks though, so `fsck` changed that back.

Could that be the case, @just-meng ? Anything that rings a bell with this as in: "Oh, yeah, I also had to do X with that new USB-Hub" or something like that?

**Comment by just-meng** [comment] 2022-12-07 10:44
I've noticed that the USB-Hub connection to my laptop is unstable. Often devices connected to it won't charge or show up.

**Comment by bpoldrack** [comment] 2022-12-07 11:21
> I've noticed that the USB-Hub connection to my laptop is unstable. Often devices connected to it won't charge or show up.

That may be an issue indeed, when the interruption is happening during execution of datalad/git-annex. Hard to reproduce a short interrupt that doesn't lead to complete crash, though.

**Comment by adswa** [comment] 2023-03-02 10:45
I'm closing this issue as it seems there were a few plausible explanations, and further interactions in the office hour also pinpoint to the filesystem this used to run on. But please feel free to reopen this or open new issues if problems persist or reoccur. :)

**Closed by adswa** 2023-03-02 10:45 UTC
