### ISSUE TITLE
test_decompress_file: `OSError: [Errno 39] Directory not empty` 

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5819] opened 2021-07-26 06:14 UTC
Failed in https://github.com/datalad/datalad/pull/5817
```
======================================================================
1758ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
1759----------------------------------------------------------------------
1760Traceback (most recent call last):
1761  File "/tmp/dl-miniconda-icyz1owz/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
1762    self.test(*self.arg)
1763  File "/tmp/dl-miniconda-icyz1owz/lib/python3.9/site-packages/datalad/tests/utils.py", line 585, in _wrap_with_tree
1764    return t(*(arg + (d,)), **kw)
1765  File "/tmp/dl-miniconda-icyz1owz/lib/python3.9/site-packages/datalad/tests/test_archives.py", line 78, in check_decompress_file
1766    decompress_file(op.join(path, fn_archive_obscure_ext), outdir,
1767  File "/tmp/dl-miniconda-icyz1owz/lib/python3.9/site-packages/datalad/support/archives.py", line 99, in decompress_file
1768    rmdir(widow_dir)
1769  File "/tmp/dl-miniconda-icyz1owz/lib/python3.9/site-packages/datalad/utils.py", line 472, in rmdir
1770    os.rmdir(path)
1771OSError: [Errno 39] Directory not empty: '/tmp/nfsmount/datalad-tx4q15os/simple-extracted/ |;&%b5{}\'"ΔЙקم๗あ .dbtc '
```

**Comment by yarikoptic** [comment] 2021-07-26 13:02
I think it is a duplicate of #4496 (I see `/tmp/nfsmount/` in the path)

**Closed by yarikoptic** 2021-07-26 13:02 UTC
