### ISSUE TITLE
siblings remove -s nonexisting  produces no output

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2423] opened 2018-04-15 01:32 UTC
#### What is the problem?

```shell
$> datalad siblings remove -s nonexisting
$> datalad -l 2 siblings remove -s nonexisting 
...
[Level 9] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'remote', 'remove', 'nonexisting'] 
[Level 11] Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'remote', 'remove', 'nonexisting'] under '/home/yoh/datalad/openfmri/ds000001'. Exit code=128. out= err=fatal: No such remote: nonexisting
|  
[Level 8] Using existing Git repository at /home/yoh/datalad/openfmri/ds000001 
[Level 5] Exiting 

```
IMHO it should say something at least if not to exit with non-0 exit code

my foo in those status yields is non existent so I will leave it to the gurus of this

**Comment by adswa** [comment] 2021-10-18 11:20
This looks like #4249 was a duplicate of this, and has been fixed in https://github.com/datalad/datalad/pull/4257.

```
❱ datalad siblings remove -s diggah
Warning: No sibling "diggah" in dataset /tmp/hcp
```

**Closed by adswa** 2021-10-18 11:20 UTC
