### ISSUE TITLE
Novel failure of automagic IO in PY3?!

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2239] opened 2018-02-27 07:35 UTC
I switched to using PY3 as default interpreter for my manual datalad use. I found this failure that is new to me. There is a bug in search (also), because it is retrieving metadata blobs, after the search is completed on a search index that was build from those blobs (impossible situation), but the rest is wrong too.

```
% datalad -f '{metadata.dicom.Series.SoftwareVersions}' search 'yx11*'
[INFO   ] Query completed in 0.019776070999796502 sec. Reporting up to 20 top matches. 
[INFO   ] AutomagicIO: retrieving file content of /tmp/cbbs/.datalad/metadata/objects/c6/cn-7157eaf044d0accf2d4eab735c57fa.xz 
[INFO   ] AutomagicIO: retrieving file content of /tmp/cbbs/.datalad/metadata/objects/6b/cn-0703be2f4e11c5e7601b718de60832.xz                                                                                                                             
[INFO   ] AutomagicIO: retrieving file content of /tmp/cbbs/.datalad/metadata/objects/f4/cn-76c7f4b0a4970e65b44eaa9c8bfed4.xz                                                                                                                             
[INFO   ] AutomagicIO: retrieving file content of /tmp/cbbs/.datalad/metadata/objects/67/cn-b9c0b92a94f43e59e922242ae3fd57.xz                                                                                                                             
[INFO   ] AutomagicIO: retrieving file content of /tmp/cbbs/.datalad/metadata/objects/e8/cn-03ef9c78f0bcaa2f25000e91937747.xz                                                                                                                             
[INFO   ] AutomagicIO: retrieving file content of /tmp/cbbs/.datalad/metadata/objects/00/cn-0c5233f5de8ed73b76c91d97ee006a.xz                                                                                                                             
Exception ignored in: <bound method AnnexRepo.__del__ of <AnnexRepo path=/tmp/cbbs (<class 'datalad.support.annexrepo.AnnexRepo'>)>>                                                                                                                      
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 311, in __del__
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3257, in close
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3402, in close
  File "/home/mih/env/datalad3-dev/lib/python3.6/os.py", line 1016, in fdopen
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <bound method BatchedAnnexes.__del__ of {"info:annex_options:['--bytes']:json:True:path:/tmp/cbbs:git_options:['-c', 'receive.autogc=0', '-c', 'gc.auto=0']:annex_cmd:info": BatchedAnnex(annex_cmd=['info'], annex_options=['--bytes', '--json'], git_options=<<['-c', 'receive.autogc...>>, output_proc=<function>, path='/tmp/cbbs')}>
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3260, in __del__
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3257, in close
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3402, in close
  File "/home/mih/env/datalad3-dev/lib/python3.6/os.py", line 1016, in fdopen
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <bound method BatchedAnnex.__del__ of BatchedAnnex(annex_cmd=['info'], annex_options=['--bytes', '--json'], git_options=<<['-c', 'receive.autogc...>>, output_proc=<function>, path='/tmp/cbbs')>
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3396, in __del__
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3402, in close
  File "/home/mih/env/datalad3-dev/lib/python3.6/os.py", line 1016, in fdopen
ImportError: sys.meta_path is None, Python is likely shutting down
datalad -f '{metadata.dicom.Series.SoftwareVersions}' search 'yx11*'  4.66s user 0.77s system 55% cpu 9.804 total
```

**Comment by yarikoptic** [comment] 2018-02-27 13:59
ho ho -- this is indeed a new one, haven't seen it yet and as far as I see not really automagic mode specific (if related at all).  I guess there we could avoid doing fdopen/close dance if sys.meta_path is None  but not sure if that wouldn't breed zombies.

I think also that we need a more generic solution to not rely on `__del__` to do closing/clean up.  Since we have all those singletons, I guess it could be some `atexit` registered callback to del (or to come up with .close) them all up explicitly before passing the kill switch to python itself

is it reproducible using search on that previously reaggregated dataset with new metadata?

**Comment by bpoldrack** [comment] 2018-02-27 15:51
Without looking into it, I want to express my concern that `atexit` isn't really a good solution. While this might work out well for CLI, it's certainly not sufficient for python API in general. When using the latter, one needs to be able to get rid of those instances at runtime without an army of annex batch mode zombies ...

**Comment by yarikoptic** [comment] 2018-02-27 16:07
It will not replace `__del__` invocations, it will just invoke them BEFORE the Python itself goes down upon exit -- all those errors you see above or we saw before on various occasions are because upon exit the order of destructors invocations is not predictable, and thus atexit is advisable to do all housekeeping cleanup first before python itself commits suicide

**Comment by yarikoptic** [comment] 2018-03-04 17:04
@mih -- so is it really resulting in failure (non-0 exit code?)
is it reproducible only with automagic code decoration or would go away if you disable automagic there (all files would be there anyways on 2nd rerun I guess)

**Comment by mih** [comment] 2018-03-05 12:06
Just hit this again. I am 98% sure that all metadata blobs were retrieved locally, still it fetched them and then dies. But indeed, as @yarikoptic spectulated, no non-zero exit code.

It is important to note that this is not running any code in `search`. Maybe related to what is going on in #2262 

```
% datalad metadata openfmri
/tmp/hotnewshit/openfmri (dataset): datalad_core,frictionless_datapackage
[INFO   ] AutomagicIO: retrieving file content of /tmp/hotnewshit/.datalad/metadata/objects/d0/cn-9fde1d3c2d3df7e2e48ce5ab910b72.xz 
/tmp/hotnewshit/openfmri/datapackage.json (file):                                                                            
/tmp/hotnewshit/openfmri/scripts/redo_bucket (file):                                                                         
/tmp/hotnewshit/openfmri/scripts/redo_bucket_recrawl (file): 
Exception ignored in: <bound method AnnexRepo.__del__ of <AnnexRepo path=/tmp/hotnewshit (<class 'datalad.support.annexrepo.AnnexRepo'>)>>
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 311, in __del__
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3257, in close
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3402, in close
  File "/home/mih/env/datalad3-dev/lib/python3.6/os.py", line 1016, in fdopen
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <bound method BatchedAnnexes.__del__ of {"info:annex_options:['--bytes']:json:True:path:/tmp/hotnewshit:git_options:['-c', 'receive.autogc=0', '-c', 'gc.auto=0']:annex_cmd:info": BatchedAnnex(annex_cmd=['info'], annex_options=['--bytes', '--json'], git_options=<<['-c', 'receive.autogc...>>, output_proc=<function>, path='/tmp/hotnewshit')}>
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3260, in __del__
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3257, in close
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3402, in close
  File "/home/mih/env/datalad3-dev/lib/python3.6/os.py", line 1016, in fdopen
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <bound method BatchedAnnex.__del__ of BatchedAnnex(annex_cmd=['info'], annex_options=['--bytes', '--json'], git_options=<<['-c', 'receive.autogc...>>, output_proc=<function>, path='/tmp/hotnewshit')>
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3396, in __del__
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3402, in close
  File "/home/mih/env/datalad3-dev/lib/python3.6/os.py", line 1016, in fdopen
ImportError: sys.meta_path is None, Python is likely shutting down

(datalad3-dev) mih@meiner /tmp/hotnewshit (git)-[master] % datalad metadata openfmri
/tmp/hotnewshit/openfmri (dataset): datalad_core,frictionless_datapackage
/tmp/hotnewshit/openfmri/datapackage.json (file): 
/tmp/hotnewshit/openfmri/scripts/redo_bucket (file): 
/tmp/hotnewshit/openfmri/scripts/redo_bucket_recrawl (file): 
```

**Comment by yarikoptic** [comment] 2018-03-05 14:51
so this was with the version right before automagicio got kicked out from metadata?  just want to know what to try with to reproduce

**Comment by yarikoptic** [comment] 2018-03-05 15:11
couldn't reproduce with python3.6 I have:
```shell
$> datalad metadata openfmri
[INFO   ] Actually getting 1 files 
/home/yoh/datalad-meta6-4/openfmri (dataset): datalad_core,frictionless_datapackage                             
/home/yoh/datalad-meta6-4/openfmri/datapackage.json (file):                                                     
/home/yoh/datalad-meta6-4/openfmri/scripts/redo_bucket (file): 
/home/yoh/datalad-meta6-4/openfmri/scripts/redo_bucket_recrawl (file): 

$> python --version
Python 3.6.4
```
and datalad 0.9.1-930-gca4b86b6 (commit right before automagicio was stripped)

**Comment by yarikoptic** [comment] 2018-03-05 15:14
even after I dropped all metadata annexes, and reran `metadata` command which fetched some of them (I saw a progressbar for a sec)

**Comment by yarikoptic** [comment] 2018-03-05 15:16
ok - went back even more to 0.9.1-929-gd4cf4d8b, so now I see automagicio INFO msgs but still do not observe that `__del__` screw ups:
```shell
$> datalad metadata openfmri                         
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/datalad-meta6-4/.datalad/metadata/objects/d0/ds-9fde1d3c2d3df7e2e48ce5ab910b72 
/home/yoh/datalad-meta6-4/openfmri (dataset): datalad_core,frictionless_datapackage                             
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/datalad-meta6-4/.datalad/metadata/objects/d0/cn-9fde1d3c2d3df7e2e48ce5ab910b72.xz 
/home/yoh/datalad-meta6-4/openfmri/datapackage.json (file):                                                     
/home/yoh/datalad-meta6-4/openfmri/scripts/redo_bucket (file):                                                  
/home/yoh/datalad-meta6-4/openfmri/scripts/redo_bucket_recrawl (file): 
```

**Comment by yarikoptic** [comment] 2018-03-05 15:22
grrr... even with `$> datalad -f '{metadata.dicom.Series.SoftwareVersions}' search 'yx11*'` which fetched lots of metadata files I have not observed that behavior :-/  My python is better behaving than the german one :-P   but I wish we could track it down -- IMHO it is not about automagicio anyhow but about our reliance on `__del__` "sane" invocations

**Comment by yarikoptic** [comment] 2020-03-04 18:05
I think that the problematic automagicio is no longer used for metadata pulling (it is done explicitly), so this issue no longer manifests itself:
```
$> datalad -f '{metadata.dicom.Series.SoftwareVersions}' search 'yx11*'
[INFO   ] no hits 
(dev3) 1 33164.....................................:Wed 04 Mar 2020 01:04:30 PM EST:.
(git-annex)lena:~/datalad[master]git
$> datalad metadata openfmri
/home/yoh/datalad/openfmri (dataset): datalad_core,frictionless_datapackage
(dev3) 1 33165.....................................:Wed 04 Mar 2020 01:04:54 PM EST:.
(git-annex)lena:~/datalad[master]git
$> datalad --version
datalad 0.12.2.dev355
```

**Closed by yarikoptic** 2020-03-04 18:05 UTC
