### ISSUE TITLE
`run`: anyhow exclude "inputs" from outputs?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2923] opened 2018-10-15 19:31 UTC
The use case:  in a chat with @effigies and @nellh on how to possibly organize openneuro derivatives, @nellh expressed desire to use `datalad run` and I tried to recommend our YODA organization where we would do something like

```
datalad create derivative-ds
datalad install -d derivative-ds --source URL-to-raw-dataset sourcedata
datalad (containers-)run --input derivative-ds/sourcedata --output derivative-ds/ bids-app bids-app-params
```
The point is that input is a subfolder within derivative-ds/, which we do not really want to unlock as part of the `output` and then the derivative-ds, but we would like to be able to say that everything produced in that dataset is produced by that command (e.g. fmriprep, etc).

May be it would somehow just work out because sourcedata/ is the subdataset, so it would not get unlocked recursively?

**Comment by kyleam** [comment] 2018-10-15 20:07
> anyhow exclude "inputs" from outputs?

No, there's currently no option to do that.

> May be it would somehow just work out because sourcedata/ is the subdataset, so it would not get unlocked recursively?

Yes, this setup should work because unlock isn't called recursively.  

(The scenario you describe wasn't the reason I chose a non-recursive unlock.  I just went with it as the more conservative choice that could be revisited if someone argued for the recursive variant.)

**Comment by yarikoptic** [comment] 2018-10-15 20:31
Cool, so ATM it would work because it is not recursive... but I can see that in some cases it would require recursive unlocking, so do you think that some additional option/way (exclusions for --input/output, e.g. `--output '^sourcedata` or even `--output '^{inputs}'`) could/should be implemented?

**Comment by yarikoptic** [comment] 2018-10-15 20:35
FWIW, initially I have used `!` instead of `^` as to exclusion, since I incorrectly remembered it being used by gitk as a way to exclude file paths, but it is `!`, quoting from IRC:
```
14:46  rafasc: yoh_: try gitk ... -- ':!path_to_exclude'
14:47  rafasc: yoh_: or ':(exclude)path/to/exclude'
```

**Comment by kyleam** [comment] 2018-10-15 21:33
> I tried to recommend our YODA organization where we would do something like

And YODA's separate "outputs" directory has to be dropped?

> but I can see that in some cases it would require recursive unlocking

Sure.  With a couple of *nested* input subdatasets, listing them out would be OK, but it could quickly become unmanageable.  I would like to see the case made with actual dataset examples, though.

> so do you think that some additional option/way (exclusions for --input/output, e.g. --output '^sourcedata or even --output '^{inputs}') could/should be implemented?

Certainly could, and I'm not opposed to providing a way to do this.  I'm not sure what the best approach is.  I'm not thrilled about bloating the format string with more minilanguage inventions and wonder whether the less general approach of adding a flag to run which means "filter inputs from the set of outputs" would be preferable.

> FWIW, initially I have used ! instead of ^ as to exclusion, since I incorrectly remembered it being used by gitk as a way to exclude file paths, but it is !, quoting from IRC:

`:^`, `:!`, and `:(exclude)` all mean the same thing.  See pathspec's entry of `man gitglossary`.

**Comment by yarikoptic** [comment] 2018-10-16 14:43
> > I tried to recommend our YODA organization where we would do something like
> 
> And YODA's separate "outputs" directory has to be dropped?

AFAIK YODA is a principle of keeping everything under git/git-annex and modular organization. Layouts we can suggest are not the only ones to follow.  Here it is a different layout - BIDS dataset, which defines 'sourcedata' as the input used to generate a given dataset.  I am just trying to address that use case.

> > but I can see that in some cases it would require recursive unlocking
> 
> Sure. With a couple of _nested_ input subdatasets, listing them out would be OK, but it could quickly become unmanageable. I would like to see the case made with actual dataset examples, though.

I guess ATM I don't have it, but I can see where both `bids_raw` and `fmriprepped` datasets would be needed for an analysis, where `fmriprepped` wouldn't have all needed files, some of which would reside in the bids_raw, which could be under `fmriprepped/sourcedata` or at the same level, depending on organization

> > so do you think that some additional option/way (exclusions for --input/output, e.g. --output '^sourcedata or even --output '^{inputs}') could/should be implemented?
> 
> Certainly could, and I'm not opposed to providing a way to do this. I'm not sure what the best approach is. I'm not thrilled about bloating the format string with more minilanguage inventions and wonder whether the less general approach of adding a flag to run which means "filter inputs from the set of outputs" would be preferable.

yes, I initially thought to suggest such a dedicated option as well, but I felt that more flexible and more generic way to exclude subpaths could be of greater benefit, e.g. where it is easier to say "take all files as inputs but theses" instead of demanding to list them all out explicitly while trying to avoid unnecessary ones (to avoid needless `get`) or simply "incorrect" (like here - input to be treated also as output).

**Comment by yarikoptic** [comment] 2018-10-16 14:49
> I don't think this is a valid use case. There should always be multiple inputs and a single output dataset. Any deviation from that, that I can think of, can be organized in a way that is "multiple inputs, single output". If that is not the case, an output dataset cannot possibly have a clear link to all its inputs, hence any computation can not be reproducible (other than by chance, or some constraint that is outside the scope of any dataset). Both situation should be avoided.

I really do not see why we should artificially restrict to have only a single output dataset - would only repel potential users and limit use cases. We already include in a subdataset's run record the original superdataset from which `run` was executed. Having outputs in multiple subdatasets nohow IMHO makes it less reproducible. May be I am missing the point?
The potential use case could be me having the "study_analysis.sh" script which produces output in both `preprocessed_data/` and `analysis_results/` or may be `analysis_results` and `analysis_results/preprocessed` sub-datasets. Another, more realistic usecase could be having too large of a "results" subdataset to hold all the subjects' results (HCP), so we might need to modularize it further (per subject).  Then results would fall into subdatasets per each subject.  Having "only one output dataset" would make it impossible.

**Comment by mih** [comment] 2018-10-16 15:40
None of these points contradict what I said, as far as I can see.

**Comment by yarikoptic** [comment] 2018-10-16 16:14
Then I am not sure what your points are

**Comment by mih** [comment] 2018-10-16 16:33
My single point is that any situation with more than one output ds is invalid, if you want to have reproducibility for every output dataset.

> We already include in a subdataset's run record the original superdataset from which run was executed.

And the reason for that is that only the root dataset has functional linkage to any input dataset.
If you write outputs into another dataset, that dataset will not have all the information to reproduce its content.

You could somehow translate this, I am sure. But you could also simply have the output dataset be the root dataset -- **for a particular computation**.

Compartmentalization is easily possible with a single output dataset -- just have multiple datasets with the same set of inputs, but each be the root dataset for the relevant operation. The datasets in the studyforrest project are highly compartmentalized, but never more than one output dataset at a time was needed.

Nothing prevents putting one or more of those "output datasets" into another dataset.

That being said, I do not oppose flexible description of input. I am just saying that the particular motivation you stated does not make this change a requirement.

**Comment by mih** [comment] 2019-10-05 09:09
Closing "question"-type issue with a response, and no further activity.

**Closed by mih** 2019-10-05 09:09 UTC
Labels: question
