### ISSUE TITLE
datalad download-url from remote

### ISSUE THREAD

**Issue by ddeepwel** [datalad/datalad#6928] opened 2022-08-08 20:22 UTC
### What is the problem?

I am attempting to download a file from a remote server using download-url. It is my understanding that ftp is for local transfers only and there is currently no sftp or ssh option. 

### What steps will reproduce the problem?

I run the command:
datalad download-url --nosave ftp:myusername@remoteserver:/path/to/download.zip
which returns the following error:
download_url(error): /path/to/ (file) [AccessFailedError(Failed to establish a new session 1 times. )]

### Datalad information

datalad version: 0.17.2
on macbook

### Additional context

There appeared to be a previous question about this in issue #2369

**Comment by yarikoptic** [comment] 2022-08-08 21:01
if we push ssh/sftp issue aside, for pure `ftp` you might have success if you install `requests-ftp` https://pypi.org/project/requests-ftp/#:~:text=Requests%2DFTP%20is%20an%20implementation,on%20a%20few%20ugly%20hacks.  but then you better not include username/password into url but I am not sure what credentials mechanism that would use, not sure if ever tried authenticated ftp with datalad.

**Comment by ddeepwel** [comment] 2022-08-08 21:10
Thanks @yarikoptic. As suggested, I installed `requests-ftp` and I still received the file transfer error. I tried `datalad download-url ftp://path/to/file.zip` which gave the same access failed error message

**Comment by ddeepwel** [comment] 2022-08-11 18:46
I just looked up requests-ftp, and I was surprised to see how underdeveloped it is. The project description does not give much confidence on its utility. Here's an excerpt from [requests-ftp](https://pypi.org/project/requests-ftp/):

> Requests-FTP is an implementation of a very stupid FTP transport adapter for use with the awesome [Requests](https://github.com/kennethreitz/requests) Python library.
> This library is not intended to be an example of Transport Adapters best practices. This library was cowboyed together in about 4 hours of total work, has no tests, and relies on a few ugly hacks. Instead, it is intended as both a starting point for future development and a useful example for how to implement transport adapters.

I am happy to create another method for pulling files from remote servers, if that is something the developers of Datalad are interested in.

**Comment by yarikoptic** [comment] 2022-08-11 19:06
yes, requests-ftp was just a hack and we never needed to look at it really besides only few cases where some data was provided from public ftp:// urls (no user/password auth needed).

first let's may be figure out if plain `git-annex` supports them, via `git annex addurl`. Also see https://git-annex.branchable.com/bugs/regression__58___http_downloads_redirecting_to_ftp_are_no_longer_supported/ for possible hints.

**Comment by ddeepwel** [comment] 2022-08-30 16:36
I've found a way to make git-annex via `git annex addurl` to download files using the sftp protocol (see [this link](https://git-annex.branchable.com/forum/Use_addurl_with_a_file_on_an_HPC_cluster/#comment-7541a85a5d847d2d24e4ddf2de60d85f)). However, datalad still limits the possible protocols. How do I enable a new protocol and configure it to automatically use git-annex?

**Comment by yarikoptic** [comment] 2022-08-30 19:36
> However, datalad still limits the possible protocols.

please elaborate! I thought it just "would not care to try what it cannot do", but also you could just `git remote remove datalad` to "disable" datalad remote if you see it somehow interfering.

**Comment by ddeepwel** [comment] 2022-08-30 22:24
Ah right!
I can run `git annex addurl "sftp://hpc.institution.edu:/path/to/testfile.txt" --file testfile.txt` to download the file, but the datalad equivalent (`datalad download-url -m "add new file" -O testfile.txt "sftp://hpc.institution.edu:/path/to/testfile.txt"`) fails because of the sftp protocol. 

Here's the error:
`[ERROR  ] Do not know how to handle url sftp://hpc.institution.edu:/path/to/testfile.txt for scheme sftp. Known: dict_keys(['http', 'https', 'shub', 'ftp', 's3']) (ValueError)`

**Comment by mih** [comment] 2022-11-18 09:27
The original #2369 has now been addressed via `ssh://` URL support via https://github.com/datalad/datalad-next/pull/124.

**Comment by mih** [comment] 2022-11-18 15:54
From my POV we can close this.

**Comment by ddeepwel** [comment] 2022-11-22 22:51
Thanks! I gave this a test using datalad-next but received an error when running `datalad download-url -m "add new file" -O testfile.txt "sftp://hpc.institution.edu:/path/to/testfile.txt"` from the virtual environment with datalad-next. It was the same error as above. Not sure if I need to do anything else after the installation and configuring git-annex

**Comment by mih** [comment] 2022-11-23 06:33
Sorry for having been vague. The corresponding command would be

`datalad download ssh://hpc.institution.edu/path/to/testfile.txt`

Please note `ssh://` not `sftp://`. Direct `sftp` support might come later. The equivalent of `-O` would be a JSON-encoded mapping to a filename, or a single whitespace separated argument:

`datalad download '{"ssh://hpc.institution.edu/path/to/testfile.txt", "testfile.txt"}`

`datalad download 'ssh://hpc.institution.edu/path/to/testfile.txt testfile.txt'`

(`download` can take any number of URL (mappings) at once).

**Comment by ddeepwel** [comment] 2022-11-23 21:51
Apologies, but I am still having difficulties.
When I run `datalad download ...` I receive the message `datalad: Unknown command 'download'.  See 'datalad --help'.` Is there a way to check that datalad-next is available and linked with datalad correctly within my virtual environment?

**Comment by adswa** [comment] 2022-11-24 06:44
>  Is there a way to check that datalad-next is available and linked with datalad correctly within my virtual environment?

If you run ``datalad --help`` you should see one section of commands for each correctly installed extension.For example, I have three extensions in my virtualenv, ``deprecated``, ``next``, and ``gooey``, and they are listed as the last three sections of commands:

```
datalad --help     
Usage: datalad [global-opts] command [command-opts]
 
Comprehensive data management solution
 
[general docstring]
 
*Essential commands*
 
  create
      Create a new dataset from scratch
  save
      Save the current state of a dataset

 ...
 [lots of other commands/sections]
 ...
 
*Plumbing commands*
 
  create-test-dataset
      Create test (meta-)dataset
  sshrun
      Run command on remote machines via SSH
  shell-completion
      Display shell script for enabling shell completion for DataLad
 
*Deprecated functionality*
 
  ls
      List summary information about URLs and dataset(s)
  publish
      Publish a dataset to a known sibling
      Publish a dataset to a known sibling
  annotate-paths
      Analyze and act upon input paths
  search
      Search dataset metadata
  metadata
      Metadata reporting for files and entire datasets
  extract-metadata
      Run one or more of DataLad's metadata extractors on a dataset or file
  aggregate-metadata
      Aggregate metadata of one or more datasets for later query
 
*Gooey (GUI)*
 
  gooey
      DataLad GUI
  gooey-askpass
      Internal helper for datalad-gooey
  gooey-lsdir
      Internal helper for datalad-gooey
  gooey-status-light
      Internal helper for datalad-gooey
 
*What is next in DataLad*
 
  credentials
      Credential management and query
  create-sibling-webdav
      Create a sibling(-tandem) on a WebDAV server
  tree
      Visualize directory and dataset hierarchies
  download
      Download from URLs
 
*General information*
 
Detailed usage information for individual commands is available via command-specific --help, i.e.: datalad
<command> --help
 
 
*Global options*
  -c (:name|name=value)
[...]
```

If an extension is only partially installed/fails to be loaded although it was found, you would likely see a warning about it at the top, e.g.,

```
datalad --help
[WARNING] Could not load extension 'next': ImportError(cannot import name 'anInterface' from 'datalad.interface.utils' (/home/adina/env/magma/lib/python3.10/site-packages/datalad/interface/utils.py)) 
```

Because there hasn't been a release of `next` since `download` was introduced, you would currently need to install the package from its ``main`` branch, e.g. with
```
pip install git+https://github.com/datalad/datalad-next.git@main 
```
Otherwise, you might have the ``next`` extension, but only a version that doesn't yet know the ``download`` command.

**Comment by mih** [comment] 2022-11-24 09:24
Just for the record, if you want to have a structured report, run `datalad wtf -S extensions`

**Comment by ddeepwel** [comment] 2022-11-25 18:39
Thanks all! I had installed datalad-next from pypi which did not include the newest updates. After fixing this I was able to get the command to work.

I had expected the downloaded file to be automatically added to git annex and to have a reference to the remote file (as would be done by `datalad download-url` or `git annex addurl`). When I look at my files with `git annex whereis`, `git annex list`, or `datalad status` the file is not any different than if I had just ran an scp to copy the file. It would be very nice to have the downloaded file automatically registered with its source.

**Comment by mih** [comment] 2022-11-26 09:15
Yes, that is correct, and also the desired behavior of `download()`. There will likely be *no* feature to make `download` add a file to an annex, or register a URL for a key. The reason for that is that we have the `addurls()` command, which can do all this in a much more flexible manner that can even work without downloading file content in some cases.

With the upcoming `datalad-next` release, `addurls()` should be able to use the download functionality you just tested internally, and thereby achieve what you were asking for -- but without having to duplicate such a feature in `download()`. I filed a dedicated issue to make sure this combination will be documented (link above).

**Comment by ddeepwel** [comment] 2022-11-26 22:53
Excellent! Using `addurls` for the goal I mentioned is entirely suitable. I appreciate all your work!

**Comment by bpoldrack** [comment] 2022-11-29 09:30
Seems to me this is a problem solved. Feel free to reopen if that is a misjudgment.

**Closed by bpoldrack** 2022-11-29 09:30 UTC
Labels: fix-implemented, cmd-download-url
