### ISSUE TITLE
datalad reports to close SSH connections it doesn't own (on irrelevant to ssh operation command)

### ISSUE THREAD

**Issue by debanjum** [datalad/datalad#530] opened 2016-06-10 20:58 UTC
also error reported in #529 
as you can see datalad reports trying to close some SSH Connection.  We didn't even ask for one to be created to start with.  Yarik wonders if "ssh manager initiation" should finally move under support/sshmanager.py -- why bother initiating/deinitiating anything which is not even relevant for this run?

```shell
(venv-tests)debanjum@smaug:/mnt/datasets/datalad/crawl/openfmri/ds000001$ datalad ls -l 1 .
2016-06-10 16:52:31,009 [DEBUG  ] Using existing Git repository at /mnt/datasets/datalad/crawl/openfmri/ds000001 (gitrepo.py:391)
2016-06-10 16:52:31,162 [Level 5] Removing temp file: /tmp/tmpvCHL0e (utils.py:260)
.  [Errno 13] Permission denied: '/mnt/datasets/datalad/crawl/openfmri/ds000001/.git/config.lock' [util.py:_obtain_lock_or_raise:545]
2016-06-10 16:52:31,165 [DEBUG  ] Closing 1 SSH connections... (sshconnector.py:179)
2016-06-10 16:52:31,165 [DEBUG  ] Running: ['ssh', '-O', 'stop', '-S', u'/home/debanjum/.config/datalad/datasets.datalad.org', u'datasets.datalad.org'] (cmd.py:352)
 (cmd.py:352):52:31,214 [DEBUG  ] stderr| Control socket connect(/home/debanjum/.config/datalad/datasets.datalad.org): No such file or directory
2016-06-10 16:52:31,215 [DEBUG  ] Failed to run ['ssh', '-O', 'stop', '-S', u'/home/debanjum/.config/datalad/datasets.datalad.org', u'datasets.datalad.org'] under None. Exit code=255. out= err=Control socket connect(/home/debanjum/.config/datalad/datasets.datalad.org): No such file or directory
|  (cmd.py:296)
(venv-tests)debanjum@smaug:/mnt/datasets/datalad/crawl/openfmri/ds000001$ datalad --version
datalad 0.2.dev302
```

**Comment by debanjum** [comment] 2016-06-10 21:07
the problem is that even if I don't give a damn about ssh, it every time tries to rewrite the configuration:   it must at least check first if that setting is not yet set, in particular to the same value!

```python
        # Note: set ssh options before any possible invocation of git-annex
        # Temporary approach to ssh connection sharing:
        # Register every ssh remote with the corresponding control master.
        # Issues:
        # - currently overwrites existing ssh config of the remote
        # - request SSHConnection instance and write config even if no
        #   connection needed (but: connection is not actually created/opened)
        # - no solution for a ssh url of a file (annex addurl)
        for r in self.get_remotes():
            for url in [self.get_remote_url(r),
                        self.get_remote_url(r, push=True)]:
                # XXX replace with proper test for ssh location identifier
                if url is not None and url.startswith('ssh:'):
                    c = ssh_manager.get_connection(url)
                    writer = self.repo.config_writer()
                    writer.set_value("remote \"%s\"" % r,
                                     "annex-ssh-options",
                                     "-o ControlMaster=auto"
                                     " -S %s" % c.ctrl_path)
                    writer.release()
```
and probably this one could use new 'RI' guesser to see if this url is an SSHRI or URL with .scheme=='ssh'.

**Comment by debanjum** [comment] 2016-06-10 21:12
@hanke, @bpoldrack I wonder if any of this should be done during/by "create-publication-target*" scripts instead? Now I would be scared to run datalad in some of my repos in fear of it modifying my precious .git/config.  Wasn't the purpose of this control primarily for publishing?  (this was all Yarik, don't kick Debanjum)

**Comment by yarikoptic** [comment] 2016-06-14 14:08
so @hanke, @bpoldrack -- any ideas on your end?

**Comment by hanke** [comment] 2016-06-14 18:56
thinking ....

**Comment by hanke** [comment] 2016-06-14 19:02
So I wonder under which conditions this actually happens. I created a test dataset with an SSH remote and I don't see that. Could you provide some more infos on that?

**Comment by yarikoptic** [comment] 2016-06-14 19:21
I've showed conditions in the original report -- it was a user, with R/O permissions to the dataset, doing something (`datalad ls`) which doesn't require SSH at all BUT uses the AnnexRepo instance which in constructor starts doing its rewrite (which it can't theoretically but I don't see it failing really here, but failing to lock) of .git/config for every SSH remote.
So overall condition is having a repository with an ssh remote configured.

**Comment by yarikoptic** [comment] 2016-06-14 19:22
and you might 'not see' it since it just does its rewrite without failing... try to do under another user which can read but can't write to your repo

**Comment by hanke** [comment] 2016-06-14 19:28
Cool, could replicate it now. In general watch #548

**Comment by hanke** [comment] 2016-06-14 19:42
Here is what I think:

1. `ssh_connector` log message is wrong. it is not closing a connection, but removing it from the list of things to track. it should likely just STFU in this case.
2. `ssh_manager` in this case is only (ab)used to generate the control master path. This could become a dedicated function that doesn't trigger any connection related code at all.
3. Writing the config should catch any permission exception and simply leave a msg in the logs (debug) that it cannot set this. While it is not nice, not having this setting should not be a showstopper in any case.
4. I am not convinced that there is a better place for this (yet). At least `publish` and `create...target` should need this info. However, a compromise might be to add another kwarg to `__init__` like `configure_remotes` that needs to be `True` in order to run this code. This way, we would keep it here, but minimize its impact (by default) in all cases where we don't know we need it.

@bpoldrack What do you think?

**Comment by bpoldrack** [comment] 2016-06-14 20:28
Okay, I see.

This all is about two mistakes a made, I think. But I don't think it is by any means a design issue. Just something, I didn't realize. ;)

In general: 
Of course we should check whether we already have a fitting entry in config and write the very same thing again. But it's more difficult to figure out, how to avoid it being done within the constructor. The issue is: AnnexRepo doesn't know, whether or not the code it is used in needs an SSH connection. Instead the actual connections are requested, when they are needed (by annex). And at this point annex itself needs to know, what connection to use. Furthermore an connection created by a datalad-independent call to git annex would currently be shared with us. Which is only the case, if we have a "correct" config. Annex doesn't have a general setting for passing a parameter to SSH, that can be derived from the hostname. It doesn't work like git with GIT_SSH env. variable. Instead, we need the entire call to SSH written to the config file. For just annex itself, that is all fine, since it uses shared connections anyway. But these are used on a per repo basis. If we want to share connections across repos, between git and annex and may be even between SSH calls for remote command execution on the one hand and repo operations on the hand, then we need to write these settings at a point, where don't know yet, whether we will need them.

But: without an actual SSH operation, there should be no connection, of course. And it is not intended, that there is any.

Re @hanke :
1. Nope. Or let's say: Yes and no. log is not wrong. It should indeed close the connections, not just stop keeping track of them. If it doesn't really close them or closes something, that it didn't create, then this is a bug, but not a design issue, I think. But nevertheless you are also right. Because in the case of not using any connection, the log message is wrong. In that case no connection was created, so it tries closing something, that doesn't need to be closed and the remaining effect is just to stop keeping track. So, the message should change, I guess.

2. Kind of yes. In this case it is supposed to just figure out the path(s). But it is not supposed to trigger any connection related code, right. Again, if it actually does it, it's a bug. But I don't see, how this is enforced by design. Therefore I currently see no advantage in moving it to a function outside the class. As long as `open()` is not called, all should be fine and not different to having a dedicated function.

3. Yes, agree. Showstopper - it could lead to additional credential request, in case the actual datalad command is using several repositories.

4. See section "in general". I don't see a better place either. It might work to have an additional `kwarg`, but I don't think we know even at the toplevel, whether we need it. Consider a proxy for `git annex get`. Do we want to predict which remotes annex uses to get everything and whether or not this will involve some SSH? I don't think so. We don't want to replicate and maintain annex' inner logic.

Summary:

I don't think "we" (meaning the toplevel command) really know, whether we need an SSH connection. So we should not make assumptions, that may lead to be spammed with credential questions.

- let closing "look better"
- if we cannot write to config, we simply don't and the user has to live with whatever that leads to.
- don't stupidly try to write, if the very same is already in there
- double check we don't create sockets, that we don't need (which should be the case already)

**Comment by bpoldrack** [comment] 2016-06-14 20:44
May be an additional try to describe, how it supposed to work in case of annex:

What we do in the constructor is to tell annex the path to SSH controlmasters to use. Not only the directory to use but also the name of the actual controlmaster. Let's say the "pattern". Additionally we tell annex: If you need an SSH connections use this pattern to either create a controlmaster or use it, in case it is already there. Anything else is then done by annex on its own.
Therefore annex now uses connections, that we created before (may be due an SSH remote command or a git SSH request). And the other way around, we can use the connections, that annex creates, because it uses our pattern.

**Comment by bpoldrack** [comment] 2016-06-15 11:38
@yarikoptic Do you have an example where your "precious config" conflicts with the rewrite?

**Comment by yarikoptic** [comment] 2016-06-15 12:02
What do you mean by a conflict?  I never said conflict ;-) do you have a conflict if you open office document, close it, and then realize that document git saved with some changes?
The point is that datalad always modifies a config even when not going to do anything needing that option. Imho should be done lazily only when explicitly asked or needed (push, pull, fetch, publish, add sibling, annex info)

**Comment by yarikoptic** [comment] 2016-06-15 12:03
And checking the value first... only in prepare target possibly overriding

**Comment by bpoldrack** [comment] 2016-06-15 13:07
Nah. Of course we don't need to modify, if we don't actually are going to change something. Check.

But: As I pointed out above, we cannot wait for being explicitly asked. Because we are not going to be asked.

**Comment by yarikoptic** [comment] 2016-06-15 23:48
If all interaction with annex and git is channeled through out API we know precisely which commands might would need the control master.
Anyways, control of the ssh control is of primary importance for publish*, correct? So why not to do it there, while even allowing those few commands of annex or git needing ssh proceed on their own, unless that remote was explicitly setup by us for publishing or may be during install? Constructor of our Repos is imho really not the place to unconditionally augment configuration of existing repositories

**Comment by bpoldrack** [comment] 2016-06-16 10:35
How do you know whether an `annex get` for example will need SSH?
What about `update`?
What about code, using just our datalad API? It could combine several `fetch`, `pull`, `push`, `annex whatever`. This would lead to an authentication mess. I really don't see, how "we" know, when it is needed.

**Comment by bpoldrack** [comment] 2016-06-16 12:26
To be clear: We can do it the way, you imagine. But this means to not provide the feature of using shared connections via simply using datalad API, but instead care for it within each every piece of code, that wants to make use of it.
The only advantage, I can see, is to not touch .git/config at all. But since we now only touch it, if there is no `annex-ssh-options` for that remote already and we are allowed to write, I don't get what's the issue with doing it and therefore providing the "feature" more easily.

**Comment by yarikoptic** [comment] 2016-09-20 14:10
at least I am not observing failures ATM when 'datalad ls ro-dataset', so closing

**Closed by yarikoptic** 2016-09-20 14:10 UTC
Labels: bug
