### ISSUE TITLE
AnnexJsonProtocol cannot handle large JSON lines

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5393] opened 2021-01-30 11:06 UTC
Due to a coding error I have (erm, it turns out there is no coding error -- see below).

```
[git-annex] % wc -l < uuid.log
34869
```

This file is 3.8M. git-annex in general, and `git annex info --json` in particular, happily works with this, but not DataLad.

```
% python3 -c "import datalad.api as dl; dl.Dataset('.').repo.repo_info()"
...
[ERROR] Received undecodable JSON output
...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/datalad/support/annexrepo.py", line 2460, in repo_info
    assert(len(json_records) == 1)
AssertionError
```

This seems due to the implementation of the `AnnexJsonProtocol`. `git annex info --json` will report all of this information in a single line. With 3.8MB of text, we seem to hit a buffer limit and only attempt to process an incomplete JSON records, and eventually blow when nothing intelligible comes back from the protocol.

**Comment by mih** [comment] 2021-01-30 19:02
FTR: It turns out that it is not a lean operation to declare 32k annex remotes dead. The drive I did this on only had 20GB of space -- not enough for `.git` (started at 346MB). I think I will try to manually modify the annex branch.

**Comment by mih** [comment] 2021-01-30 20:46
and it turns even further out that this was unavoidable -- even if I would have used `datalad clone --reckless ephemeral`.

Even after `git annex dead here` a simple `git annex get` will modify a key's log to record the availability in the dead remote.

The `git annex init` in each clone will modify `uuid.log` and record the (ephemeral) clone -- even if that `init` runs implictly by calling `git annex dead here` as the very first thing.

So making 32k clones and pushing back to origin will add 32k lines to `uuid.log` (and ultimately let datalad crash -- which it should not, of course).

The only way to make this work and leave no cruft behind seems to be by adding a new feature to `push`. It would need to:

- perform `annex copy --to` as usual
- then remove information on the dead `here` remote from the annex branch `uuid.log` and all key logs
- commit an update
- and only then push the `git-annex` branch

Anything that accumulates cruft at `origin` will increasingly slow down the cloning and eventually bring things to a standstill (see above that after 32k clones, it took 33x longer to clone than in the beginning or after cleanup).

**Comment by yarikoptic** [comment] 2021-03-15 18:21
FTR, @snastase channeled a bug report on getting the same error while `get`ing data from ///labs/hasson/narratives/derivatives/fmriprep (datalad version 0.14.0 and git-annex version 8.20210223)  . Details are yet to be discovered.  Meanwhile running `datalad install -g ///labs/hasson/narratives/derivatives/fmriprep` on smaug (although my default config sets annex to do some parallel -J so might behave a bit different; it is 1.8TB so might take awhile ;) )

**Comment by yarikoptic** [comment] 2021-03-16 17:44
Got more information, seems to confirm that we can fail even with "large" (thus not needing "huge") json lines since they get read in "chunks" instead of "until the end of line".

Could reproduced on aforementioned dataset while providing wrong/bogus credentials to git-annex (I think it is a separate issue that it tries to go with credentials instead of public http urls, [reported to @joeyh]()https://git-annex.branchable.com/bugs/presence_of_AWS_creds_ruins_access_to_public_urls/?updated):

<details>
<summary>you will see that we get two of the "undecodable JSON" ERROR messages logged - first for beginning and then for the "tail" of that json record:</summary> 

```shell
(git-annex)lena:/tmp/fmriprep[master]git-annex
$> AWS_ACCESS_KEY_ID=X AWS_SECRET_ACCESS_KEY=Y datalad get sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz 
[ERROR  ] Received undecodable JSON output: b'{"command":"get","wanted":[{"here":false,"uuid":"4d79a724-9e8c-4cce-b030-f712eed3e131","description":"snastase@scotty.pni.Princeton.EDU:/mnt/bucket/labs/hasson/snastase/smaug/narratives/derivatives/fmriprep"},{"here":false,"uuid":"5f96664f-23ba-4c25-8e75-9ca24fcd46f5","description":"nastase@smaug:/mnt/datasets/incoming/nastase/narratives/derivatives/fmriprep"}],"note":"from fcp-indi...\\nUnable to access these remotes: fcp-indi","success":false,"input":["sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz"],"key":"MD5E-s91557--2592b75d942895a6f423dcc1e262af48.nii.gz","error-messages":["  HttpExceptionRequest Request {","    host                 = \\"fcp-indi.s3.amazonaws.com\\"","    port                 = 80","    secure               = False","    requestHeaders       = [(\\"Date\\",\\"Tue, 16 Mar 2021 17:23:42 GMT\\"),(\\"Authorization\\",\\"<REDACTED>\\")]","    path                 = \\"/data/Projects/narratives/derivatives/fmriprep/sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz\\"","    queryString          = \\"\\"","    method               = \\"GET\\"","    proxy                = Nothing","    rawBody              = False","    redirectCount        = 10","    responseTimeout      = ResponseTimeoutDefault","    requestVersion       = HTTP/1.1","  }","   (StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = \\"Forbidden\\"}, responseVersion = HTTP/1.1, responseHeaders = [(\\"x-amz-request-id\\",\\"GX953W5SG3YBPA6Y\\"),(\\"x-amz-id-2\\",\\"c4G9B5YiQzI0+xe+xV/p0lRGPIOVmzitZijlLEqO1Rcjc9bp699/yDtp47hZeA1aN/hllflmtrs=\\"),(\\"Content-Type\\",\\"application/xml\\"),(\\"Transfer-Encoding\\",\\"chunked\\"),(\\"Date\\",\\"Tue, 16 Mar 2021 17:23:41 GMT\\"),(\\"Server\\",\\"AmazonS3\\")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose\' = ResponseClose}) \\"<?xml version=\\\\\\"1.0\\\\\\" encoding=\\\\\\"UTF-8\\\\\\"?>\\\\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>X</AWSAccessKeyId><RequestId>GX953W5SG3YBPA6Y</RequestId><HostId>c4G9B5YiQzI0+xe+xV/p0lRGPIOVmzitZijlLEqO1Rcjc9bp699/yDtp47hZeA1aN/hllflmtrs=</HostId></Error>\\")","  HttpExceptionRequest Request {","    host                 = \\"fcp-indi.s3.amazonaws.com\\"","    port                 = 80","    secure               = False","    requestHeaders       = [(\\"Date\\",\\"Tue, 16 Mar 2021 17:23:43 GMT\\"),(\\"Authorization\\",\\"<REDACTED>\\")]","    path                 = \\"/data/Projects/narratives/derivatives/fmriprep/sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz\\"","    queryString          = \\"\\"","    method               = \\"GET\\"","    proxy                = Nothing","    rawBody              = False","    redirectCount        = 10","    responseTimeout      = ResponseTimeoutDefault","    requestVersion       = HTTP/1.1","  }","   (StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = \\"Forbidden\\"}, responseVersion = HTTP/1.1, responseHeaders = [(\\"x-amz-request-id\\",\\"A9QDC3JPS06FNGW2\\"),(\\"x-amz-id-2\\",\\"YlEQ9J2ZtqdiAKtQowkK461sCt8UcuJ4nGNP6/11AneRIiIQRxIvCg8FlYZgCoM5h57YsW9qdlg=\\"),(\\"Content-Type\\",\\"application/xml\\"),(\\"Transfer-Encoding\\",\\"chunked\\"),(\\"Date\\",\\"Tue, 16 Mar 2021 17:23:42 GMT\\"),(\\"Server\\",\\"AmazonS3\\")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose\' = ResponseClose}) \\"<?xml version=\\\\\\"1.0\\\\\\" encoding=\\\\\\"UTF-8\\\\\\"?>\\\\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>X</AWSAccessKeyId><RequestId>A9QDC3JPS06FNGW2</RequestId><HostId>YlEQ9J2ZtqdiAKtQowkK461sCt8UcuJ4nGNP6/11AneRIiIQRxIvCg8FlYZgCoM5h57YsW9qdlg=</HostId></Error>\\")","  HttpExceptionRequest Request {","    host                 = \\"fcp-indi.s3.amazonaws.com\\"","    port                 = 80","    secure               = False","    requestHeaders       = [(\\"Date\\",\\"Tue, 16 Mar 2021 17:23:45 GMT\\"),(\\"Authorization\\",\\"<REDACTED>\\")]","    path           ' 
[ERROR  ] Received undecodable JSON output: b'      = \\"/data/Projects/narratives/derivatives/fmriprep/sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz\\"","    queryString          = \\"\\"","    method               = \\"GET\\"","    proxy                = Nothing","    rawBody              = False","    redirectCount        = 10","    responseTimeout      = ResponseTimeoutDefault","    requestVersion       = HTTP/1.1","  }","   (StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = \\"Forbidden\\"}, responseVersion = HTTP/1.1, responseHeaders = [(\\"x-amz-request-id\\",\\"T1GANZVT74Q3BQPY\\"),(\\"x-amz-id-2\\",\\"tiMJ3INeInoRXLYDX7mOgkEtJrMwtAi/vVDlSrZfMCbV1sDMsiQbI4R2U+B9SBv+9TOIDdKDMcU=\\"),(\\"Content-Type\\",\\"application/xml\\"),(\\"Transfer-Encoding\\",\\"chunked\\"),(\\"Date\\",\\"Tue, 16 Mar 2021 17:23:44 GMT\\"),(\\"Server\\",\\"AmazonS3\\")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose\' = ResponseClose}) \\"<?xml version=\\\\\\"1.0\\\\\\" encoding=\\\\\\"UTF-8\\\\\\"?>\\\\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>X</AWSAccessKeyId><RequestId>T1GANZVT74Q3BQPY</RequestId><HostId>tiMJ3INeInoRXLYDX7mOgkEtJrMwtAi/vVDlSrZfMCbV1sDMsiQbI4R2U+B9SBv+9TOIDdKDMcU=</HostId></Error>\\")"],"file":"sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz"}\n' 
CommandError: 'git -c diff.ignoreSubmodules=none annex get --json --json-error-messages --json-progress -c annex.dotfiles=true -c annex.retry=3 -- sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz' failed with exitcode 1 under /tmp/fmriprep
git-annex: get: 1 failed

```
</details>

<details>
<summary>here is a direct invocation for git-annex with `wc` which shows that there is a single line of 2277 bytes</summary> 

```shell
(git-annex)lena:/tmp/fmriprep[master]git-annex
$> AWS_ACCESS_KEY_ID=X AWS_SECRET_ACCESS_KEY=Y git annex get --json --json-error-messages sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz 2>/dev/null | wc
      1     101    2277
(dev3) 1 65898.....................................:Tue 16 Mar 2021 01:29:09 PM EDT:.
(git-annex)lena:/tmp/fmriprep[master]git-annex
$> AWS_ACCESS_KEY_ID=X AWS_SECRET_ACCESS_KEY=Y git annex get --json --json-error-messages sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz 2>/dev/null     
{"command":"get","wanted":[{"here":false,"uuid":"4d79a724-9e8c-4cce-b030-f712eed3e131","description":"snastase@scotty.pni.Princeton.EDU:/mnt/bucket/labs/hasson/snastase/smaug/narratives/derivatives/fmriprep"},{"here":false,"uuid":"5f96664f-23ba-4c25-8e75-9ca24fcd46f5","description":"nastase@smaug:/mnt/datasets/incoming/nastase/narratives/derivatives/fmriprep"}],"note":"from fcp-indi...\nUnable to access these remotes: fcp-indi","success":false,"input":["sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz"],"key":"MD5E-s91557--2592b75d942895a6f423dcc1e262af48.nii.gz","error-messages":["  HttpExceptionRequest Request {","    host                 = \"fcp-indi.s3.amazonaws.com\"","    port                 = 80","    secure               = False","    requestHeaders       = [(\"Date\",\"Tue, 16 Mar 2021 17:29:21 GMT\"),(\"Authorization\",\"<REDACTED>\")]","    path                 = \"/data/Projects/narratives/derivatives/fmriprep/sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz\"","    queryString          = \"\"","    method               = \"GET\"","    proxy                = Nothing","    rawBody              = False","    redirectCount        = 10","    responseTimeout      = ResponseTimeoutDefault","    requestVersion       = HTTP/1.1","  }","   (StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = \"Forbidden\"}, responseVersion = HTTP/1.1, responseHeaders = [(\"x-amz-request-id\",\"D1QMYRDK2Q39ZTPY\"),(\"x-amz-id-2\",\"jUHf1OBe22ykzV8MiFPll9TH+UK3DXa6XLOUDjeOg+KrAoDUpZQqUpJbvPuvuLbnC0cIvrmsjEI=\"),(\"Content-Type\",\"application/xml\"),(\"Transfer-Encoding\",\"chunked\"),(\"Date\",\"Tue, 16 Mar 2021 17:29:21 GMT\"),(\"Server\",\"AmazonS3\")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>X</AWSAccessKeyId><RequestId>D1QMYRDK2Q39ZTPY</RequestId><HostId>jUHf1OBe22ykzV8MiFPll9TH+UK3DXa6XLOUDjeOg+KrAoDUpZQqUpJbvPuvuLbnC0cIvrmsjEI=</HostId></Error>\")"],"file":"sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz"}

```
</details>

**Comment by yarikoptic** [comment] 2021-03-16 19:27
<details>
<summary>Marking as a regression since 0.13.7 which uses old runner I guess was not effected</summary> 

```shell
$> AWS_ACCESS_KEY_ID=X AWS_SECRET_ACCESS_KEY=Y datalad get sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
[WARNING] Running get resulted in stderr output: git-annex: get: 1 failed
 
[ERROR  ] HttpExceptionRequest Request {
| host                 = "fcp-indi.s3.amazonaws.com"
| port                 = 80
| secure               = False
| requestHeaders       = [("Date","Tue, 16 Mar 2021 19:26:25 GMT"),("Authorization","<REDACTED>")]
| path                 = "/data/Projects/narratives/derivatives/fmriprep/sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz"
| queryString          = ""
| method               = "GET"
| proxy                = Nothing
| rawBody              = False
| redirectCount        = 10
| responseTimeout      = ResponseTimeoutDefault
| requestVersion       = HTTP/1.1
| }
| (StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, responseVersion = HTTP/1.1, responseHeaders = [("x-amz-request-id","B6011FDEPT72AXXG"),("x-amz-id-2","+qNBfCgSEzX096+bnEgxzvxR8hoIqJUrTuKF3yQzMoH9+IBWEL7EzXPyACkV/QCMuLWXzTS+g2w="),("Content-Type","application/xml"),("Transfer-Encoding","chunked"),("Date","Tue, 16 Mar 2021 19:26:25 GMT"),("Server","AmazonS3")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>X</AWSAccessKeyId><RequestId>B6011FDEPT72AXXG</RequestId><HostId>+qNBfCgSEzX096+bnEgxzvxR8hoIqJUrTuKF3yQzMoH9+IBWEL7EzXPyACkV/QCMuLWXzTS+g2w=</HostId></Error>")
| HttpExceptionRequest Request {
| host                 = "fcp-indi.s3.amazonaws.com"
| port                 = 80
| secure               = False
| requestHeaders       = [("Date","Tue, 16 Mar 2021 19:26:27 GMT"),("Authorization","<REDACTED>")]
| path                 = "/data/Projects/narratives/derivatives/fmriprep/sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz"
| queryString          = ""
| method               = "GET"
| proxy                = Nothing
| rawBody              = False
| redirectCount        = 10
| responseTimeout      = ResponseTimeoutDefault
| requestVersion       = HTTP/1.1
| }
| (StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, responseVersion = HTTP/1.1, responseHeaders = [("x-amz-request-id","Q63TEFF9XF4PA0RG"),("x-amz-id-2","wM/6M90UD7TUdeZfqzsNOx/9agFiXMdNj0WcKWyqz664svkdmmwrXmyfKTbXyTCvPCIPh6CQPZg="),("Content-Type","application/xml"),("Transfer-Encoding","chunked"),("Date","Tue, 16 Mar 2021 19:26:26 GMT"),("Server","AmazonS3")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>X</AWSAccessKeyId><RequestId>Q63TEFF9XF4PA0RG</RequestId><HostId>wM/6M90UD7TUdeZfqzsNOx/9agFiXMdNj0WcKWyqz664svkdmmwrXmyfKTbXyTCvPCIPh6CQPZg=</HostId></Error>")
| HttpExceptionRequest Request {
| host                 = "fcp-indi.s3.amazonaws.com"
| port                 = 80
| secure               = False
| requestHeaders       = [("Date","Tue, 16 Mar 2021 19:26:29 GMT"),("Authorization","<REDACTED>")]
| path                 = "/data/Projects/narratives/derivatives/fmriprep/sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz"
| queryString          = ""
| method               = "GET"
| proxy                = Nothing
| rawBody              = False
| redirectCount        = 10
| responseTimeout      = ResponseTimeoutDefault
| requestVersion       = HTTP/1.1
| }
| (StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, responseVersion = HTTP/1.1, responseHeaders = [("x-amz-request-id","HYTZPNM04BMRVDM6"),("x-amz-id-2","8mjLgRpI9YnLJ/CwUt12d0du4PHho2K+FQu4RXkXXNIpC19VygbrDPwrSmELbbcnB2UWJeMfTao="),("Content-Type","application/xml"),("Transfer-Encoding","chunked"),("Date","Tue, 16 Mar 2021 19:26:28 GMT"),("Server","AmazonS3")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>X</AWSAccessKeyId><RequestId>HYTZPNM04BMRVDM6</RequestId><HostId>8mjLgRpI9YnLJ/CwUt12d0du4PHho2K+FQu4RXkXXNIpC19VygbrDPwrSmELbbcnB2UWJeMfTao=</HostId></Error>") [get(/tmp/fmriprep/sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz)] 
get(error): sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz (file) [HttpExceptionRequest Request {
host                 = "fcp-indi.s3.amazonaws.com"
port                 = 80
secure               = False
requestHeaders       = [("Date","Tue, 16 Mar 2021 19:26:25 GMT"),("Authorization","<REDACTED>")]
path                 = "/data/Projects/narratives/derivatives/fmriprep/sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz"
queryString          = ""
method               = "GET"
proxy                = Nothing
rawBody              = False
redirectCount        = 10
responseTimeout      = ResponseTimeoutDefault
requestVersion       = HTTP/1.1
}
(StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, responseVersion = HTTP/1.1, responseHeaders = [("x-amz-request-id","B6011FDEPT72AXXG"),("x-amz-id-2","+qNBfCgSEzX096+bnEgxzvxR8hoIqJUrTuKF3yQzMoH9+IBWEL7EzXPyACkV/QCMuLWXzTS+g2w="),("Content-Type","application/xml"),("Transfer-Encoding","chunked"),("Date","Tue, 16 Mar 2021 19:26:25 GMT"),("Server","AmazonS3")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>X</AWSAccessKeyId><RequestId>B6011FDEPT72AXXG</RequestId><HostId>+qNBfCgSEzX096+bnEgxzvxR8hoIqJUrTuKF3yQzMoH9+IBWEL7EzXPyACkV/QCMuLWXzTS+g2w=</HostId></Error>")
HttpExceptionRequest Request {
host                 = "fcp-indi.s3.amazonaws.com"
port                 = 80
secure               = False
requestHeaders       = [("Date","Tue, 16 Mar 2021 19:26:27 GMT"),("Authorization","<REDACTED>")]
path                 = "/data/Projects/narratives/derivatives/fmriprep/sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz"
queryString          = ""
method               = "GET"
proxy                = Nothing
rawBody              = False
redirectCount        = 10
responseTimeout      = ResponseTimeoutDefault
requestVersion       = HTTP/1.1
}
(StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, responseVersion = HTTP/1.1, responseHeaders = [("x-amz-request-id","Q63TEFF9XF4PA0RG"),("x-amz-id-2","wM/6M90UD7TUdeZfqzsNOx/9agFiXMdNj0WcKWyqz664svkdmmwrXmyfKTbXyTCvPCIPh6CQPZg="),("Content-Type","application/xml"),("Transfer-Encoding","chunked"),("Date","Tue, 16 Mar 2021 19:26:26 GMT"),("Server","AmazonS3")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>X</AWSAccessKeyId><RequestId>Q63TEFF9XF4PA0RG</RequestId><HostId>wM/6M90UD7TUdeZfqzsNOx/9agFiXMdNj0WcKWyqz664svkdmmwrXmyfKTbXyTCvPCIPh6CQPZg=</HostId></Error>")
HttpExceptionRequest Request {
host                 = "fcp-indi.s3.amazonaws.com"
port                 = 80
secure               = False
requestHeaders       = [("Date","Tue, 16 Mar 2021 19:26:29 GMT"),("Authorization","<REDACTED>")]
path                 = "/data/Projects/narratives/derivatives/fmriprep/sub-001/anat/sub-001_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz"
queryString          = ""
method               = "GET"
proxy                = Nothing
rawBody              = False
redirectCount        = 10
responseTimeout      = ResponseTimeoutDefault
requestVersion       = HTTP/1.1
}
(StatusCodeException (Response {responseStatus = Status {statusCode = 403, statusMessage = "Forbidden"}, responseVersion = HTTP/1.1, responseHeaders = [("x-amz-request-id","HYTZPNM04BMRVDM6"),("x-amz-id-2","8mjLgRpI9YnLJ/CwUt12d0du4PHho2K+FQu4RXkXXNIpC19VygbrDPwrSmELbbcnB2UWJeMfTao="),("Content-Type","application/xml"),("Transfer-Encoding","chunked"),("Date","Tue, 16 Mar 2021 19:26:28 GMT"),("Server","AmazonS3")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>X</AWSAccessKeyId><RequestId>HYTZPNM04BMRVDM6</RequestId><HostId>8mjLgRpI9YnLJ/CwUt12d0du4PHho2K+FQu4RXkXXNIpC19VygbrDPwrSmELbbcnB2UWJeMfTao=</HostId></Error>")]
(
```
</details>

**Closed** 2021-03-19 14:27 UTC
Labels: regression, severity-important
