### ISSUE TITLE
Pointless warnings from download-url

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#3199] opened 2019-03-06 09:01 UTC
#### What is the problem?
`download-url` spits out warnings about a missing cookie db, when there is none needed.

#### What steps will reproduce the problem?
Run the following in a fresh dataset with a sub dir `some`:
```
% datalad download-url https://github.com/datalad/example-dicom-functional/raw/master/events.tsv --path some/events.tsv --message "Add events from github"
[INFO   ] Downloading 'https://github.com/datalad/example-dicom-functional/raw/master/events.tsv' into '/tmp/test-demo/some/events.tsv' 
[WARNING] Failed to open cookies DB /home/ben/.config/datalad/cookies: db type could not be determined [__init__.py:open:88] 
[WARNING] Failed to check for having a cookie for https://github.com/datalad/example-dicom-functional/raw/master/events.tsv: argument of type 'NoneType' is not iterable [cookies.py:__contains__:89] 
```

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

0.12.0rc1

**Comment by yarikoptic** [comment] 2019-03-07 23:45
Yeah, cookies storage must have been redone years back to not use pickling. In your case it was probably saved with a different version of python

**Comment by bpoldrack** [comment] 2019-03-08 10:00
Ah - that might be the case. I'll try deleting the existing one. But apart from that, my point was that it wasn't necessary in two ways: First of all, it checks that cookie-db regardless. Not all downloads need that in the first place. And second: Once it knows it cannot open it (and proceeds nevertheless), it then tries again to access the db and files a second warning about the same thing. So, I think there's more to do than not using pickling.

**Comment by bpoldrack** [comment] 2021-01-19 10:59
I think those pointless checks are still the case, but I don't feel particularly enlightened about everything downloaders/providers/etc.

Do you have an idea whether those call paths changed, @yarikoptic?

**Comment by yarikoptic** [comment] 2021-01-19 18:03
cookies DB is pretty much orthogonal to the rest of downloaders/providers/etc... overall the warning probably due to a switch from python2 to 3 (so should not happen on any recent use cases)?  Or you do observe it often in the wild?

as it is coded ATM, I believe we always want to open cookies db for a URL to consider for download, just in the case it was some authenticated session and we have a cookie from it.

**Comment by adswa** [comment] 2021-12-10 15:26
Yay, this doesn't reproduce anymore (``0.15.3+396.gdb33d3e81``):

```
❱ datalad download-url https://github.com/datalad/example-dicom-functional/raw/master/events.tsv --path some/events.tsv --message "Add events from github"
[INFO   ] Downloading 'https://github.com/datalad/example-dicom-functional/raw/master/events.tsv' into '/tmp/new/some/events.tsv' 
download_url(ok): /tmp/new/some/events.tsv (file)                               
add(ok): some/events.tsv (file)                                                 
save(ok): . (dataset)                                                           
action summary:                                                                 
  add (ok: 1)
  download_url (ok: 1)
  save (ok: 1)
```

Closing, but please reopen if it does still happen for others.

**Closed by adswa** 2021-12-10 15:26 UTC
