### ISSUE TITLE
Absolute vs relative paths for 'dataset' and 'path' argument in DataLad's API (install)

### ISSUE THREAD

**Issue by manuelakuhn** [datalad/datalad#5529] opened 2021-03-25 10:17 UTC
I am using the datalad python api (datalad version 0.14.0 and python 3.8.7) and when I try to install a dataset inside another one, I cannot do it without actively changing into the outer dataset itself:

```python
>>> import datalad.api
>>> datalad.api.create("my_dataset")
[INFO   ] Creating a new annex repo at /tmp/datalad-tests/my_dataset
[INFO   ] Scanning for unlocked files (this may take some time)
Dataset('/tmp/datalad-tests/my_dataset')
>>> datalad.api.create("my_inner_dataset")
[INFO   ] Creating a new annex repo at /tmp/datalad-tests/my_inner_dataset
[INFO   ] Scanning for unlocked files (this may take some time)
Dataset('/tmp/datalad-tests/my_inner_dataset')
>>> datalad.api.install(path="inner", source="/tmp/datalad-tests/my_inner_dataset", dataset="/tmp/datalad-tests/my_dataset")
[ERROR  ] clone target path '/tmp/datalad-tests/inner' not in specified target dataset 'Dataset(/tmp/datalad-tests/my_dataset)' [install(/tmp/datalad-tests/inner)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/datalad-tests/virtualenv/lib64/python3.8/site-packages/datalad/interface/utils.py", line 482, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/tmp/datalad-tests/virtualenv/lib64/python3.8/site-packages/datalad/interface/utils.py", line 470, in return_func
    results = list(results)
  File "/tmp/datalad-tests/virtualenv/lib64/python3.8/site-packages/datalad/interface/utils.py", line 455, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'install',
  'message': ("clone target path '%s' not in specified target dataset '%s'",
              PosixPath('/tmp/datalad-tests/inner'),
              Dataset('/tmp/datalad-tests/my_dataset')),
  'path': '/tmp/datalad-tests/inner',
  'refds': '/tmp/datalad-tests/my_dataset',
  'source_url': '/tmp/datalad-tests/my_inner_dataset',
  'status': 'error',
  'type': 'dataset'}]
```
but doing this works
```python
>>> import os
>>> os.chdir("my_dataset")
>>> datalad.api.install(path="inner", source="/tmp/datalad-tests/my_inner_dataset", dataset="/tmp/datalad-tests/my_dataset")
[INFO   ] Scanning for unlocked files (this may take some time)
Dataset('/tmp/datalad-tests/my_dataset/inner')
```

According to the documentation here <http://docs.datalad.org/en/stable/generated/datalad.api.install.html#datalad.api.install>
```
dataset (Dataset or None, optional) – specify the dataset to perform the install operation on. If no dataset is given, an attempt is made to identify the dataset in a parent directory of the current working directory and/or the path given. [Default: None]
```
shouldn't this command work from outside of the dataset, or do I understand something wrong here?

The same behaviour I see with `datalad.api.uninstall` and `datalad.api.hirni_import_dcm`

**Comment by bpoldrack** [comment] 2021-03-25 11:31
> shouldn't this command work from outside of the dataset, or do I understand something wrong here?

The command works from outside the dataset. The problem here is to determine where the relative path `"inner"` you passed to the function is relative to. With that call, `install` is regarding it as relative to your CWD rather than relative to your dataset. And the result is a path outside of the dataset, which then can't work.

Now, the question is when is a relative path resolved using CWD and when using the given dataset's root? Generally, given a dataset is passed, it should do what you did expect - resolving against the dataset. However, that happens only if `dataset` is a `Dataset` instance.
I'm not sure this is exactly what it should be currently, because `install` is quite old and didn't get a lot of attention recently. So - not saying this is not a bug, just need a moment to figure whether it's `install` that is an exception here.

Anyways: There are several things you can do, that should work exactly as you wanted:

1. Pass in the `Dataset` instance you got from `create` instead of its path:
     ```
     ds = datalad.api.create("my_dataset")
     ...
     datalad.api.install(path="inner", source="/tmp/datalad-tests/my_inner_dataset", dataset=ds)
     ```
2. Go the more object oriented way:
     ```
     ds = datalad.api.create("my_dataset")
     ...
     ds.install(path="inner", source="/tmp/datalad-tests/my_inner_dataset")
     ```
3. Apart from that, for simple one-dataset uses, `clone` is the leaner command, that can do the same thing:
    ```
     ds = datalad.api.create("my_dataset")
     ...
     ds.clone(path="inner", source="/tmp/datalad-tests/my_inner_dataset")
     ```

**Comment by manuelakuhn** [comment] 2021-03-25 12:33
I know that the example I gave is somewhat artificial, but I tried to do a minimal example from the problem I ran into. But still thank you for the tips!

I used a string as dataset parameter because this is how it is written in the documentation examples:
```python
install(dataset='.',
          source='https://github.com/datalad-datasets/longnow-podcasts.git')
```
By using the dataset object directly it works. In the documentation it indeed says that dataset should be a `Dataset or None` but this can easily overlooked from a users perspective when at the same time the example uses a string. I still think the path should either work the same way or throw an error. Let's see what your investigation will find out :-)

Thank you also for the hint with the object-oriented approach. That I did not see in the documentation at all.

**Comment by bpoldrack** [comment] 2021-03-25 12:48
> but I tried to do a minimal example from the problem I ran into.

Thanks for that! At the very least it is a documentation issue. We are not incredibly clear about this.

> I still think the path should either work the same way or throw an error. 

Same way: Not necessarily. That's the issue with using the very same function via command line and with the fact that you can also use a relative path for `dataset`. Now you can pass in two relative paths. If that would work "the same way", then the path for `dataset` would necessarily be interpreted as relative to CWD, while `path` in the exact same call would then be resolved against the dataset. Seems confusing, too. ;-)

> Thank you also for the hint with the object-oriented approach. That I did not see in the documentation at all.

Generally true for all commands including extensions. Any command is available as a `Dataset` method (replacing `-` from command line name of the command by `_`)

**Comment by manuelakuhn** [comment] 2021-03-26 09:00
> Same way: Not necessarily. That's the issue with using the very same function via command line and with the fact that you can also use a relative path for dataset. Now you can pass in two relative paths. If that would work "the same way", then the path for `dataset` would necessarily be interpreted as relative to CWD, while `path` in the exact same call would then be resolved against the `dataset`. Seems confusing, too. ;-)

Yes, I agree, for relative paths there is no easy/not confusing way to solve it, but at least for absolut paths it is pretty clear what is meant. So if you want my opinion on that, in regards of usability I would be in favor that you either do not allow strings at all (and change the example in the documentation) or allow it and fix the behaviour for absolute paths.

A thought in addition: Could the main confusion not be avoided by focusing the API documentation and examples more on the object oriented approach? There it is clear on which `dataset` it is operated which removes one additional hurdle for not experienced users.

**Comment by kyleam** [comment] 2021-03-26 14:17
> Could the main confusion not be avoided by focusing the API documentation and examples more on the object oriented approach?

Hmm, I don't know.  Perhaps it's just trading one confusion for another, but I still lean towards using the unbound api command calls so that the python and command-line snippets are one-to-one matches.

Here's some past discussion of this:
<https://github.com/datalad/datalad/pull/4091#discussion_r371454318>

That led to e63aa86:

```
DOC: examples: Consistently use unbound Python commands

The Python examples have a mix of dataset-bound method calls and
unbound calls (i.e., calls to datalad.api functions).  While the
dataset-bound calls are useful in general, using unbound calls in the
examples has the following benefits:

  * There are fewer unrepresented steps.

    The snippets aren't complete examples; they don't have setup code
    and the paths are placeholders.  With both unbound and bound
    methods, there are implied imports.  With the bound methods, there
    are additional missing pieces regarding what `ds` is, how the
    dataset was created, and what path it points to.

  * Unbound methods share the command-line path handling logic.

    A dataset string sent in through an unbound command should trigger
    the same relative path handling as the command line.  Using the
    unbound methods results in snippet pairs that are a closer match.
    The only assumption necessary is that the snippets are executed
    from the same current working directory.

On the other hand, a downside of _not_ using bound methods in the
examples is that users won't learn that bound methods exist through
the examples.  But snippets probably aren't a good means of
demonstrating this anyway, at least with their current capabilities.

[...]
```

**Comment by adswa** [comment] 2022-01-24 08:22
Hey, this issue hasn't seen much activity for more than 6 months, and what I take away from reading it is that while there can be some confusion about path handling, a change of examples to the object-oriented approach is less favourable due to the points Kyle mentioned above, and switching how relative and absolute paths are treated in the Python API is less favourable because it would cause a mismatch to the CLI and other commands. So both approaches would merely change one confusion to a different one. I thus lean towards closing this issue, re-titling it to "Absolute vs relative paths for 'dataset' and 'path' argument in DataLad's API" , and tagging it with a "question" label to make it more findable. However, if I read it wrong or there is a pressing need for change, please feel free to reopen and re-title it.

**Closed by adswa** 2022-01-24 08:22 UTC
Labels: question, answered, cmd-install
