### ISSUE TITLE
Best practice to backup?

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#4369] opened 2020-04-01 20:51 UTC
#### What is the problem?
I need to backup the entire superdataset routinely (including file content) on another server via ssh. I think doing a datalad publish/push should be sufficient for this. Two questions:
1. Does the remote server need to have datalad or git/git-annex installed, or is my local datalad sufficient just to push files and set the correct file permissions in the remote?
2. Is this the best way to do the backup, or do you suggest something else? I was doing backups via rclone before, but I lose file permissions in the remote, and it would not be a usable datalad backup until I restore files via rclone.

#### What steps will reproduce the problem?
NA

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.12.4

#### Is there anything else that would be useful to know in this context?
I checked the documentation a bit, looks like RIA is not what I need.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
Sure.

**Comment by yarikoptic** [comment] 2020-04-02 03:53
for a full backup, use something like
```
datalad create-sibling --annex-wanted anything -r myserver:/path/to/backup
datalad publish --to=myserver -r
```
subsequently you can use
```
datalad publish --to=myserver -r --since= --missing=inherit
```
which would then
- due to `--since=` - traverse only the subdatasets which had seen any commits in the current branch (thus it would not react to any new annexed content which you might have gotten) -- to speed up `publish` if your hierarchy is large
- `--missing=inherit` - so for new subdatasets you have added since previous publish it would create one on your server, and inherit settings (like that `wanted`) from its parent

Overall example:
```
$> datalad create-test-dataset --spec 2 --seed 1 testds
[INFO   ] Generating repo of class <class 'datalad.support.annexrepo.AnnexRepo'> under /tmp/testds 
[INFO   ] Generating repo of class <class 'datalad.support.annexrepo.AnnexRepo'> under /tmp/testds/d0/d1/r0 
[INFO   ] Generating repo of class <class 'datalad.support.gitrepo.GitRepo'> under /tmp/testds/d0/d1/d2/r1 
3 installed items are available at
/tmp/testds
/tmp/testds/d0/d1/r0
/tmp/testds/d0/d1/d2/r1
(dev3) 1 13457.....................................:Wed 01 Apr 2020 11:43:21 PM EDT:.
lena:/tmp
$> cd testds
d0/  file583.dat
(dev3) 1 13458.....................................:Wed 01 Apr 2020 11:43:24 PM EDT:.
(git-annex)lena:/tmp/testds[master]
$> echo content > d0/d1/r0/deep                       
(dev3) 1 13459.....................................:Wed 01 Apr 2020 11:43:41 PM EDT:.
(git-annex)lena:/tmp/testds[master]
$> datalad save -r -m "added some annexed content"
add(ok): deep (file)
save(ok): d0/d1/r0 (dataset)
add(ok): d0/d1/r0 (file)
save(ok): . (dataset)                                                                                                                                                                                                              
action summary:
  add (ok: 2)
  save (notneeded: 1, ok: 2)
(dev3) 1 13460.....................................:Wed 01 Apr 2020 11:43:46 PM EDT:.
(git-annex)lena:/tmp/testds[master]
$> ls -l d0/d1/r0/deep               
lrwxrwxrwx 1 yoh yoh 178 Apr  1 23:43 d0/d1/r0/deep -> .git/annex/objects/zm/2W/SHA256E-s8--434728a410a78f56fc1b5899c3593436e61ab0c731e9072d95e96db290205e53/SHA256E-s8--434728a410a78f56fc1b5899c3593436e61ab0c731e9072d95e96db290205e53


$> datalad create-sibling --annex-wanted anything -r localhost:/tmp/mybackup         
[INFO   ] Connecting ... 
[INFO   ] Considering to create a target dataset /tmp/testds at /tmp/mybackup of localhost 
[INFO   ] Fetching updates for <Dataset path=/tmp/testds> 
.: localhost(+) [localhost:/tmp/mybackup (git)]                                                                                                                                                                                    
[INFO   ] Adjusting remote git configuration 
[INFO   ] Considering to create a target dataset /tmp/testds/d0/d1/r0 at /tmp/mybackup/d0/d1/r0 of localhost 
[INFO   ] Fetching updates for <Dataset path=/tmp/testds/d0/d1/r0> 
.: localhost(+) [localhost:/tmp/mybackup/d0/d1/r0 (git)]                                                                                                                                                                           
[INFO   ] Adjusting remote git configuration 
[INFO   ] Considering to create a target dataset /tmp/testds/d0/d1/d2/r1 at /tmp/mybackup/d0/d1/d2/r1 of localhost 
[INFO   ] Fetching updates for <Dataset path=/tmp/testds/d0/d1/d2/r1> 
.: localhost(?) [localhost:/tmp/mybackup/d0/d1/d2/r1 (git)]
[INFO   ] Adjusting remote git configuration 
[INFO   ] Running post-update hooks in all created siblings 
create_sibling(ok): d0/d1/d2/r1 (dataset)
create_sibling(ok): d0/d1/r0 (dataset)
create_sibling(ok): . (dataset)
action summary:
  create_sibling (ok: 3)
(dev3) 1 13462.....................................:Wed 01 Apr 2020 11:44:10 PM EDT:.
(git-annex)lena:/tmp/testds[master]
$> datalad publish --to localhost -r                                        
[INFO   ] Publishing <Dataset path=/tmp/testds/d0/d1/r0> data to localhost 
publish(ok): d0/d1/r0/deep (file)                                                                                                                                                                                                  
[INFO   ] Publishing <Dataset path=/tmp/testds/d0/d1/r0> to localhost 
publish(ok): d0/d1/r0 (dataset) [pushed to localhost: ['5a0b036..c8c3ac6', '[new branch]']]                                                                                                                                        
[INFO   ] Publishing <Dataset path=/tmp/testds/d0/d1/d2/r1> to localhost 
publish(ok): d0/d1/d2/r1 (dataset) [pushed to localhost: ['[new branch]']]                                                                                                                                                         
[INFO   ] Publishing <Dataset path=/tmp/testds> data to localhost 
[INFO   ] Publishing <Dataset path=/tmp/testds> to localhost 
publish(ok): . (dataset) [pushed to localhost: ['fea39e5..215745f', '[new branch]']]                                                                                                                                               
action summary:
  publish (ok: 4)
(dev3) 1 13463.....................................:Wed 01 Apr 2020 11:44:17 PM EDT:.
(git-annex)lena:/tmp/testds[master]
$> ls -l /tmp/mybackup/d0/d1/r0/deep
lrwxrwxrwx 1 yoh yoh 178 Apr  1 23:44 /tmp/mybackup/d0/d1/r0/deep -> .git/annex/objects/zm/2W/SHA256E-s8--434728a410a78f56fc1b5899c3593436e61ab0c731e9072d95e96db290205e53/SHA256E-s8--434728a410a78f56fc1b5899c3593436e61ab0c731e9072d95e96db290205e53
(dev3) 1 13464.....................................:Wed 01 Apr 2020 11:44:31 PM EDT:.
(git-annex)lena:/tmp/testds[master]
$> cat /tmp/mybackup/d0/d1/r0/deep
content

(git-annex)lena:/tmp/testds[master]
$> datalad publish --to=localhost -r --since= --missing=inherit
# did nothing
```
but then if I do change:
```
$> echo here > mynewfile; datalad save -m "added a new file" -r
add(ok): mynewfile (file)                                                                                                                                                                                                          
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (notneeded: 2, ok: 1)
(dev3) 1 13472.....................................:Wed 01 Apr 2020 11:50:55 PM EDT:.
(git-annex)lena:/tmp/testds[master]
$> datalad publish --to=localhost -r --since= --missing=inherit
[INFO   ] Publishing <Dataset path=/tmp/testds> data to localhost 
publish(ok): mynewfile (file)                                                                                                                                                                                                      
[INFO   ] Publishing <Dataset path=/tmp/testds> to localhost 
publish(ok): . (dataset) [pushed to localhost: ['0fd1114..fc6b1eb', '4b903c5..7fd247d']]                                                                                                                                           
action summary:
  publish (ok: 2)
```
published only modified current dataset...
and here is with a new subdataset and content deep within:
```
$> datalad create -d . d0/d1/r0/deepds
[INFO   ] Creating a new annex repo at /tmp/testds/d0/d1/r0/deepds 
add(ok): deepds (file)                                                                                                                                                                                                             
add(ok): .gitmodules (file)
save(ok): d0/d1/r0 (dataset)
add(ok): d0/d1/r0 (file)
save(ok): . (dataset)
create(ok): d0/d1/r0/deepds (dataset)
action summary:
  add (ok: 3)
  create (ok: 1)
  save (ok: 2)
(dev3) 1 13475.....................................:Wed 01 Apr 2020 11:52:01 PM EDT:.
(git-annex)lena:/tmp/testds[master]
$> echo "more content" > d0/d1/r0/deepds/newfile
(dev3) 1 13476.....................................:Wed 01 Apr 2020 11:52:09 PM EDT:.
(git-annex)lena:/tmp/testds[master]
$> datalad save -r -m "added some deep annexed content"        
add(ok): newfile (file)
save(ok): d0/d1/r0/deepds (dataset)
add(ok): deepds (file)
save(ok): d0/d1/r0 (dataset)
add(ok): d0/d1/r0 (file)
save(ok): . (dataset)                                                                                                                                                                                                              
action summary:
  add (ok: 3)
  save (notneeded: 1, ok: 3)
(dev3) 1 13477.....................................:Wed 01 Apr 2020 11:52:16 PM EDT:.
(git-annex)lena:/tmp/testds[master]
$> datalad publish --to=localhost -r --since= --missing=inherit
[INFO   ] Will try to create a sibling inheriting settings from <Dataset path=/tmp/testds/d0/d1/r0> 
[INFO   ] Connecting ... 
[INFO   ] Considering to create a target dataset /tmp/testds/d0/d1/r0/deepds at /tmp/mybackup/d0/d1/r0/deepds of localhost 
[INFO   ] Fetching updates for <Dataset path=/tmp/testds/d0/d1/r0/deepds> 
[INFO   ] Inherited annex config from <Dataset path=/tmp/testds/d0/d1/r0> wanted = anything                                                                                                                                        
.: localhost(+) [localhost:/tmp/mybackup/d0/d1/r0/deepds (git)]
[INFO   ] Adjusting remote git configuration 
[INFO   ] Running post-update hooks in all created siblings 
[INFO   ] Publishing <Dataset path=/tmp/testds/d0/d1/r0/deepds> data to localhost 
publish(ok): d0/d1/r0/deepds/newfile (file)                                                                                                                                                                                        
[INFO   ] Publishing <Dataset path=/tmp/testds/d0/d1/r0/deepds> to localhost 
publish(ok): d0/d1/r0/deepds (dataset) [pushed to localhost: ['0105056..1fb3545', '[new branch]']]                                                                                                                                 
[INFO   ] Publishing <Dataset path=/tmp/testds/d0/d1/r0> data to localhost 
[INFO   ] Publishing <Dataset path=/tmp/testds/d0/d1/r0> to localhost 
publish(ok): d0/d1/r0 (dataset) [pushed to localhost: ['[up to date]', '6ada329..392cf3f']]                                                                                                                                        
[INFO   ] Publishing <Dataset path=/tmp/testds> data to localhost 
[INFO   ] Publishing <Dataset path=/tmp/testds> to localhost 
publish(ok): . (dataset) [pushed to localhost: ['[up to date]', '7fd247d..9a96e61']]                                                                                                                                               
action summary:
  publish (ok: 4)
datalad publish --to=localhost -r --since= --missing=inherit  4.23s user 1.91s system 88% cpu 6.960 total
(dev3) 1 13478.....................................:Wed 01 Apr 2020 11:52:25 PM EDT:.
(git-annex)lena:/tmp/testds[master]
$> cat /tmp/mybackup/d0/d1/r0/deepds/newfile
more content
```

Similar `publish` invocation is used for publishing updates to datasets.datalad.org which has now a few hundred of subdatasets

**Comment by dorianps** [comment] 2020-04-02 18:40
Many thank's for the thorough example @yarikoptic . I will try it soon and let you know how it works. To make sure I understand, I don't need anything installed in the target ssh/linux server, right? Neither git/datalat/git-annex?

**Comment by kyleam** [comment] 2020-04-02 19:19
> To make sure I understand, I don't need anything installed in the target ssh/linux server, right? Not even git/datalat/git-annex?

Quickly scanning @yarikoptic's reply, no, I think that recipe would require those on the server.  For servers that don't have these installed, you could use [a special remote][0] such as ria (now available in datalad master, but under the name "ora" IIRC), directory, or rsync.

[0]: https://git-annex.branchable.com/special_remotes/

**Comment by dorianps** [comment] 2020-04-03 00:48
@kyleam , from what I read on special remotes, they can't hold git history at all. My aim is to have an identical datalad backup, including the ability to checkout a past commit and have past annex versions of a certain file.

What I will need to test (unless you can give me a quick answer) is whether @yarikoptic solution saves all past versions of annexed files. And maybe what happens  to the remote when I drop certain files from certain commits, will the annex deletions be propagated in the backup or not.

Thanks, keep up the work everyone, datalad is and will be a great solution. I already noticed the benefit of my suggestion, that is, being able to get the files even in a clone of a clone of a clone, so the locations of where the data could be is propagated in clones.

**Comment by kyleam** [comment] 2020-04-03 01:04
> from what I read on special remotes, they can't hold git history at all. My aim is to have an identical datalad backup, including the ability to checkout a past commit and have past annex versions of a certain file.

I see.  My recommendation would be to look into general backup solutions rather than trying to back up git/git-annex repositories with git/git-annex/datalad, especially given the constraint of a backup server that lacks git/git-annex/datalad.

**Comment by dorianps** [comment] 2020-04-03 01:10
In my case it's just another Linux server, and I think I can put the required software in there :)

**Comment by yarikoptic** [comment] 2020-04-03 01:42
if an x86 linux server, the whole setup could be quite easy using miniconda: http://handbook.datalad.org/en/latest/intro/installation.html#linux-machines-with-no-root-access-e-g-hpc-systems 

just would need to make them available in your PATH for non-interactive sessions as well.

> My recommendation would be to look into general backup solutions rather than trying to back up git/git-annex repositories with git/git-annex/datalad

Depending on underlying filesystem/solution it might actually be more expansive if would require full file tree traversal etc.  I do love BTRFS and ability to snapshot and send differences between them -- very handy. But I also ran into many bottlenecks with backuppc, rdiff-backup, etc as the number of files grew.

**Comment by dorianps** [comment] 2020-04-03 02:45
@yarikoptic , is the solution you proposed initially going to backup git history, past annex file versions, etc., just like in the original location. Or will it push/publish only the annex content of the latest commit?

**Comment by yarikoptic** [comment] 2020-04-03 03:38
With --annex-wanted anything should be "just like in the original location. ". Note though, that by default only current branch is published. Iirc there is an option to set refs to push, so you could set all refs, I would be too check if inherit copies those settings too - iirc it should

**Comment by adswa** [comment] 2020-04-03 10:54
(I will steal this an put it in a gist in the handbook :) thanks @dorianps for raising these questions! Also: your usecase for DataLad sounds gigantic. If you ever want to describe it/have it described in a usecase let me know)

**Comment by yarikoptic** [comment] 2020-04-03 15:10
FWIW, verified that adding ` --publish-by-default "refs/*"` to `create-sibling` makes all references being published as well, and `publish --missing=inherit` then inherits those settings from the parent superdataset.

**Comment by yarikoptic** [comment] 2020-04-03 20:15
hm, @kyleam - thank you for checking and all the scripts!   that violates my beliefs as well.  Given your "pure git annex" script, it is only `annex get` but not `annex copy` which respects `wanted` properly... strange, we should RTFM and/or ask @joeyh  ;)

**Comment by yarikoptic** [comment] 2020-04-03 20:23
FWIW, even replacing 
```
    git annex sync sib
    git annex copy --to sib --auto
```
with
```
    git annex sync --content sib
```
gives the same result...

crap -- we might need to use the dedicated option!:
```
$> git annex copy --help | grep version
  -A,--all                 operate on all versions of all files

$> git annex sync --help | grep version
  -A,--all                 operate on all versions of all files
```
**BUT** it cannot be used with `--auto`:
```
+ git annex copy --to sib --auto -A
git-annex: Cannot use --auto with --all or --branch or --unused or --key or --incomplete
```

**Comment by kyleam** [comment] 2020-04-03 20:27
> it is only `annex get` but not `annex copy` which respects `wanted` properly.

Sorry, my script with no commentary was probably confusing.  `annex get --auto` doesn't.  I followed up with `git annex get --all` just to show I could get the old file if I forced it.

**Comment by kyleam** [comment] 2020-04-03 20:30
>  we might need to use the dedicated option!

No, I think using `--auto` and preferred content _should_ work.  If you look at the description of `backup`/`anything` at <https://git-annex.branchable.com/preferred_content/standard_groups/>, it explicitly mentions old files:

```
backup

All content is wanted. Even content of old/deleted files.

anything
```

**Comment by yarikoptic** [comment] 2020-04-03 20:52
Yeah, smells like a bug in git-annex to me

**Comment by dorianps** [comment] 2020-04-04 17:19
@yarikoptic Thanks for suggesting the rootless approach for installing datalad via miniconda, it was a piece of cake to install.

I am not ready to try the remote backup you suggested. P.s. I currently don't have old annex versions to be worried about, but looks like you have found an annex bug. I can try my backup solution for now and will keep an eye for your updates here on the bug. Fyi, miniconda has annex 8.2 with datalad 0.12.3, while I have locally annex 7.2 with datalad 0.12.4.

**Comment by yarikoptic** [comment] 2020-04-05 17:22
We kept chasing regressions or incompatibilities introduced either by newer git or git-annex versions.  There is still some test hanging issue we haven't fully traced down - so I am keeping good old annex 7.20190819+git2-g908476a9b-1~ndall+1 to be the one to come from neurodebian.
I just merged (forgotten) https://github.com/conda-forge/datalad-feedstock/pull/28 so conda should get 0.12.5 now, I would recommend upgrading.

**Comment by yarikoptic** [comment] 2020-04-05 17:25
Dear @kyleam , would you be so kind to communicate our discovered issue of `anything` not covering previous versions to @joeyh on git-annex bugs pages with your [lovely script to reproduce](https://github.com/datalad/datalad/issues/4369#issuecomment-608603732),  or may be you could propose a patch? ;)

**Comment by kyleam** [comment] 2020-04-06 16:53
I've created [a bug report][0] on git-annex's site.

[0]: https://git-annex.branchable.com/bugs/Deleted_files_not_considered_with_wanted__61____34__anything__34__/

**Comment by dorianps** [comment] 2020-04-07 03:54
Quick report on @yarikoptic 's solution.

I updated datalad in the remote server, now it's at 0.12.5.

I ran some tests and ran into errors and weird behavior. When pushing the first time on the remote, I see an error:
```
$ datalad publish --to=myserver -r                                                      [INFO   ] Publishing <Dataset path=/DATA/dorian/dataladtest/subtest> data to myserver
Total:   0%|                                                                         | 0.00/414M [00:00<?, ?B/s]username@111.111.111.111's password:
Total (241 ok, 1 failed out of 319): 100%|██████████████████████████████████▉| 414M/414M [00:15<00:00, 43.4MB/s]username@111.111.111.111's password:
Total (318 ok, 1 failed out of 319): 100%|██████████████████████████████████▉| 414M/414M [00:28<00:00, 1.26MB/s][WARNING] Running copy resulted in stderr output: git-annex: <stdin>: hGetChar: illegal operation (handle is closed)git-annex-shell: p2pstdio: 1 failedgit-annex: copy: 1 failed
```
But when I run the same command again, there is no error anymore. The data in the remote is all there.

However...

I tried locally to (1) drop a binary file and (2) replace it with another ad hoc text file. Now the local repository has a new annex content for that file, and the old one is not there. I reran the push with missing=inherit as suggested. However, the remote dataset still has old file content in it, so it's not deleted. In other words, if I have a 5Gb file and want to replace it with a new 5Gb file, the remote will take double the amount of the local. Is this part of the bug reported by @kyleam ?

**Comment by yarikoptic** [comment] 2020-04-08 19:47
> hGetChar: illegal operation

What git-annex version do you have?  Last time we saw those particular ones were I believe a [year or so ago](https://www.google.com/search?sitesearch=http://git-annex.branchable.com&q=hGetChar:%20illegal%20operation) although some fixes in git-annex somewhere in Dec 2019 might have also addressed some of those.  They are related to parallel file transfers over ssh... when "redone" - would just reupload what managed to error out before, and all should be good.

> I tried locally to (1) drop a binary file and (2) replace it with another ad hoc text file. Now the local repository has a new annex content for that file, and the old one is not there. I reran the push with missing=inherit as suggested. However, the remote dataset still has old file content in it, so it's not deleted. In other words, if I have a 5Gb file and want to replace it with a new 5Gb file, the remote will take double the amount of the local. Is this part of the bug reported by @kyleam ?

What Kyle has reported is the opposite -- that remote would not get that previous version if you hadn't transferred it to remote whenever it was still in the working tree.  In your case it seems it operates as expected.  Yes -- you will get two 5 Gb files (for both versions) on remote if you transferred both versions.  If changes to files small/localized, for backup you might like to establish a collection of special remotes with chunking, so any part(s) of file which hadn't changed between versions would not need to be reuploaded.  But that could add burden on your inodes on the backup server side... trade offs trade offs

**Comment by kyleam** [comment] 2020-04-13 19:01
@yarikoptic

> crap -- we might need to use the dedicated option!:
> 
> ```
> $> git annex copy --help | grep version
>   -A,--all                 operate on all versions of all files
> 
> $> git annex sync --help | grep version
>   -A,--all                 operate on all versions of all files
> ```
> 
> **BUT** it cannot be used with `--auto`

Sorry for stalling this line of thought.  You are correct.  See Joey's reply in the git-annex thread.

**Comment by yarikoptic** [comment] 2020-04-13 22:23
hm, so for the "full" backup, it should use `sync --all --content`, probably also with `--no-pull` to avoid merging changes from the remote... 

<details>
<summary>FWIW here is a modified version of Kyle's script showing it. I also added `--only-annex` to completely avoid dealing with worktree, but might be undesired</summary> 

```shell
#!/bin/bash
# https://git-annex.branchable.com/bugs/Deleted_files_not_considered_with_wanted__61____34__anything__34__/
# tuned to check if goes one way

set -eu

cd "$(mktemp -d ${TMPDIR:-/tmp}/gx-XXXXXXX)"

git init a
(
    cd a
    git annex init a
    >foo && git annex add foo && git commit -m"add foo"
    git rm foo && git commit -m"delete foo"
)

mkdir b
(
	cd b
	git init
	git annex init b
    git annex wanted here anything
)

# initial sync
(
    cd a
    git remote add remote-b ../b
    git annex sync --all --content remote-b
)

(
    cd b
    echo foo2 > foo2 && git annex add foo2 && git commit -m"add foo2"
)


# 2nd sync -- only work on annex
(
    cd a
    git annex sync --all --content --only-annex --no-pull remote-b
    echo "a:"
    find .git/annex/objects -type f | nl
    test `find .git/annex/objects -type f | wc -l` = 1
    # we should have only 1 file of our own, no 2nd
)

(
    cd b
    echo "b:"
    find .git/annex/objects -type f | nl
    test `find .git/annex/objects -type f | wc -l` = 2
    # here we should get both
)

```
</details>

**Comment by mih** [comment] 2020-05-17 15:04
Just FTR: I don't know where @dorianps would draw the line between backup and archiving, but we are approaching the latter with a combinations of solutions that have been named here. There is no comprehensive write-up yet, but I started collection notes at https://github.com/datalad-handbook/book/issues/487 So far I am exploring the possibilities with the present set of functionality (upcoming 0.13) and I am fairly pleased.

**Comment by dorianps** [comment] 2020-05-17 15:27
@mih  Thanks for making the distinction. The original intent was to simply have a one-to-one backup copy, not an archiving solution. This would be the same is done with rsync or  rclone (which I am currently using).

My idea of archiving is not about past file versions, but subdatasets. That is, at any moment I need all past versions available to checkout. Instead, some subdatasets containing old data not in use will be parked in some archiving solution (i.e., external usb drive) and uninstalled from the main location. This is, for example, for data that become obsolete and were created with old software.

Hope this is more clearer, at least for my use case plan.

**Comment by yarikoptic** [comment] 2020-11-12 02:18
some discussion happened, some annex bugs were fixed, no ultimate (if there is one) answer was given but some possibilities discussed etc.  I will consider this topic exhausted for now.  If disagree, feel welcome to reopen or file a new issue @dorianps

**Closed by yarikoptic** 2020-11-12 02:18 UTC
Labels: question
