### ISSUE TITLE
`datalad.local.tests.test_foreach_dataset.test_basic_resilience` not resilient

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6482] opened 2022-02-22 06:45 UTC
From https://ci.appveyor.com/project/mih/datalad/builds/42653693/job/bj1sa5ow0st1ketd testing https://github.com/datalad/datalad/pull/6424
```
======================================================================
4066ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000021B32B80040>,)
4067----------------------------------------------------------------------
4068Traceback (most recent call last):
4069  File "c:\projects\datalad\datalad\support\parallel.py", line 368, in _iter_threads
4070    raise _FinalShutdown()
4071datalad.support.parallel._FinalShutdown
4072
4073During handling of the above exception, another exception occurred:
4074
4075Traceback (most recent call last):
4076  File "C:\Python39-x64\lib\site-packages\nose\case.py", line 198, in runTest
4077    self.test(*self.arg)
4078  File "c:\projects\datalad\datalad\tests\utils.py", line 874, in _wrap_with_tempfile
4079    return t(*(arg + (filename,)), **kw)
4080  File "c:\projects\datalad\datalad\local\tests\test_foreach_dataset.py", line 50, in check_basic_resilience
4081    res_python = ds.foreach_dataset("ds.path", cmd_type='eval', **kwargs)
4082  File "c:\projects\datalad\datalad\distribution\dataset.py", line 502, in apply_func
4083    return f(*args, **kwargs)
4084  File "c:\projects\datalad\datalad\interface\utils.py", line 447, in eval_func
4085    return return_func(*args, **kwargs)
4086  File "c:\projects\datalad\datalad\interface\utils.py", line 439, in return_func
4087    results = list(results)
4088  File "c:\projects\datalad\datalad\interface\utils.py", line 357, in generator_func
4089    for r in _process_results(
4090  File "c:\projects\datalad\datalad\interface\utils.py", line 544, in _process_results
4091    for res in results:
4092  File "c:\projects\datalad\datalad\local\foreach_dataset.py", line 387, in __call__
4093    yield from pc_class(
4094  File "c:\projects\datalad\datalad\support\parallel.py", line 265, in __iter__
4095    yield from self._iter_threads(self._jobs)
4096  File "c:\projects\datalad\datalad\support\parallel.py", line 417, in _iter_threads
4097    self.shutdown(force=True, exception=self._producer_exception or interrupted_by_exception)
4098  File "c:\projects\datalad\datalad\support\parallel.py", line 233, in shutdown
4099    raise exception
4100  File "c:\projects\datalad\datalad\support\parallel.py", line 401, in _iter_threads
4101    done_useful |= self._pop_done_futures(lgr)
4102  File "c:\projects\datalad\datalad\support\parallel.py", line 463, in _pop_done_futures
4103    raise exception
4104  File "C:\Python39-x64\lib\concurrent\futures\thread.py", line 58, in run
4105    result = self.fn(*self.args, **self.kwargs)
4106  File "c:\projects\datalad\datalad\support\parallel.py", line 329, in consumer_worker
4107    for r in res:
4108  File "c:\projects\datalad\datalad\local\foreach_dataset.py", line 286, in run_cmd
4109    if not ds.is_installed():
4110  File "c:\projects\datalad\datalad\distribution\dataset.py", line 368, in is_installed
4111    self.repo is not None
4112  File "c:\projects\datalad\datalad\distribution\dataset.py", line 273, in repo
4113    self._repo = repo_from_path(self._path)
4114  File "c:\projects\datalad\datalad\core\local\repo.py", line 61, in repo_from_path
4115    repo = cls(path, create=False, **kw)
4116  File "c:\projects\datalad\datalad\dataset\repo.py", line 152, in __call__
4117    instance = type.__call__(cls, *new_args, **new_kwargs)
4118  File "c:\projects\datalad\datalad\support\annexrepo.py", line 303, in __init__
4119    self._allow_local_urls()
4120  File "c:\projects\datalad\datalad\support\annexrepo.py", line 324, in _allow_local_urls
4121    self.config.add(
4122  File "c:\projects\datalad\datalad\config.py", line 108, in wrapper
4123    return func(*args, **kwargs)
4124  File "c:\projects\datalad\datalad\config.py", line 945, in add
4125    self._run(['--add', var, value], scope=scope, reload=reload,
4126  File "c:\projects\datalad\datalad\config.py", line 899, in _run
4127    self.reload()
4128  File "c:\projects\datalad\datalad\config.py", line 469, in reload
4129    self._stores[store_id] = self._reload(runargs)
4130  File "c:\projects\datalad\datalad\config.py", line 497, in _reload
4131    stdout, stderr = self._run(
4132  File "c:\projects\datalad\datalad\config.py", line 878, in _run
4133    out = self._runner.run(self._config_cmd + args, **kwargs)
4134  File "c:\projects\datalad\datalad\runner\runner.py", line 201, in run
4135    raise CommandError(
4136datalad.runner.exception.CommandError: CommandError: '"git" "config" "-z" "-l" "--show-origin"' failed with exitcode 128 under C:\DLTMP\datalad_temp_a_stnzy4\subds_modified [out: 'file:C:/Program Files/Git/etc/gitconfigdiff.astextplain.textconv
4137astextplainfile:C:/Program Files/Git/etc/gitconfighttp.sslbackend
4138opensslfile:C:/Program Files/Git/etc/gitconfighttp.sslcainfo
4139C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crtfile:C:/Program Files/Git/etc/gitconfigcore.autocrlf
4140truefile:C:/Program Files/Git/etc/gitconfigcore.fscache
4141truefile:C:/Program Files/Git/etc/gitconfigcore.symlinks
4142falsefile:C:/Program Files/Git/etc/gitconfigpull.rebase
4143falsefile:C:/Program Files/Git/etc/gitconfigcredential.https://dev.azure.com.usehttppath
4144truefile:C:/Program Files/Git/etc/gitconfiginit.defaultbranch
4145masterfile:C:/Program Files/Git/etc/gitconfigfilter.annex.process
4146git-annex filter-processfile:C:\DLTMP\datalad_temp_m8ot8b7_\.gitconfiguser.name
4147DataLad Testerfile:C:\DLTMP\datalad_temp_m8ot8b7_\.gitconfiguser.email
4148test@example.comfile:C:\DLTMP\datalad_temp_m8ot8b7_\.gitconfigcore.askpass
4149file:C:\DLTMP\datalad_temp_m8ot8b7_\.gitconfigdatalad.log.exc
41501command line:init.defaultbranch
4151dl-test-branchcommand line:clone.defaultremotename
4152dl-test-remote'] [err: 'warning: unable to access '.git/config': Permission denied
4153fatal: error processing config file(s)']
```

**Comment by mih** [comment] 2022-02-22 11:54
Does not replicate on a crippled FS.

**Comment by yarikoptic** [comment] 2022-02-22 13:37
FWIW, also happened on master on 21st, so I guess before #6424 was merged?
```
$> grep -aR 'ERROR: datalad.local.tests.test_foreach_dataset' *        
21/push/master/acdcd04/appveyor-7553-failed/hvs9e4y67c8fty8n.txt:[00:37:40] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000027EFFF39E50>,)
21/pr/6424/66cf2b4/appveyor-7557-failed/bj1sa5ow0st1ketd.txt:[00:39:17] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000021B32B80040>,)
22/pr/6424/66cf2b4/appveyor-7557-failed/mhync5cmfsy0s9q9.txt:[00:37:19] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x00000218EC0C2040>,)
```

**Comment by yarikoptic** [comment] 2022-02-22 13:57
thought to submit a PR which would delay calling `self._allow_local_urls` until annex is invoked, but I think it would not be of much help if anything, and anyways it feels to be some  git inflicted issue, not really datalad, but then I do not see any recent change in git version on windows:

```
$> grep -a -e '- cmd:git.*windows' [12]*/pr/*/*/appveyor-*/*.txt | f4 | sort | uniq -c
    158 2.33.1.windows.1
```
so -- dunno

**Comment by bpoldrack** [comment] 2022-02-25 17:41
FTR: Happened here again: https://ci.appveyor.com/project/mih/datalad/builds/42709530/job/4hsol6qt1jmm5997#L3678

**Comment by mih** [comment] 2022-03-12 09:56
This seems to become a frequent companion now.

**Comment by yarikoptic** [comment] 2022-03-22 18:00
indeed it is quite a regular one now
```
(git)smaug:/mnt/datasets/datalad/ci/logs/2022[master]git
$> grep -aR 'ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience.*deepl' 0{2,3}/*
02/21/push/master/acdcd04/appveyor-7553-failed/hvs9e4y67c8fty8n.txt:[00:37:40] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000027EFFF39E50>,)
02/21/pr/6424/66cf2b4/appveyor-7557-failed/bj1sa5ow0st1ketd.txt:[00:39:17] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000021B32B80040>,)
02/22/push/master/e878445/appveyor-7566-failed/brkcm9c3q22ot3g5.txt:[00:37:33] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x000001D04E0E3040>,)
02/22/pr/6424/66cf2b4/appveyor-7557-failed/mhync5cmfsy0s9q9.txt:[00:37:19] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x00000218EC0C2040>,)
02/23/pr/6495/c9dec43/appveyor-7580-failed/esm5oeeb10g9rjiw.txt:[00:40:52] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x000001F97F95D940>,)
02/25/push/master/4befd2d/appveyor-7598-failed/omjv325cts0nj8q0.txt:[00:39:12] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000019E0BB8B940>,)
02/25/pr/6493/93bc0c0/appveyor-7609-failed/4hsol6qt1jmm5997.txt:[00:38:50] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000020324541CA0>,)
02/25/pr/6493/ec0b638/appveyor-7612-failed/8l7dwegm6gyoehuo.txt:[00:38:37] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x000001D2B2370CA0>,)
02/25/pr/6489/a05d628/appveyor-7604-failed/gam7fm1stw9u8ki8.txt:[00:38:59] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000019970F62CA0>,)
03/08/pr/6529/d2b4643/appveyor-7642-failed/885mq0q55m2m937a.txt:[00:37:56] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000026F43FC8820>,)
03/08/pr/6529/b28f6b8/appveyor-7641-failed/40j3883o3et6u8p4.txt:[00:04:11] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x7fb08ef09700>,)
03/08/pr/6529/b28f6b8/appveyor-7641-failed/y3id3y0hcwv9ygwl.txt:[00:05:15] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000021790868820>,)
03/08/pr/6529/b28f6b8/appveyor-7641-failed/jedmtvoh24yq2cko.txt:[00:02:30] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x109685790>,)
03/08/pr/6529/b28f6b8/appveyor-7641-failed/n1vxw18ht2b0thgg.txt:[00:04:23] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x7ff04752d710>,)
03/08/pr/6529/b28f6b8/travis-13622-failed/1.txt:ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x7f2f51f01a60>,)
03/08/pr/6529/b28f6b8/travis-13622-failed/2.txt:ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x7f5388ff29d0>,)
03/08/pr/6529/b28f6b8/travis-13622-failed/3.txt:ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x7f1edd614a60>,)
03/08/pr/UNK/b28f6b8/github-CrippledFS-2821-failed/test/8_Run tests.txt:2022-03-08T21:12:40.7322403Z ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x7f11886dacb0>,)
03/08/pr/UNK/b28f6b8/github-CrippledFS-2821-failed/1_test (1).txt:2022-03-08T21:12:40.7322407Z ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x7f11886dacb0>,)
03/11/pr/6537/51afde7/appveyor-7657-failed/k06c5pi8e51b8ogb.txt:[00:41:01] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x000001DCAC3DAA60>,)
03/14/pr/6543/ac95f2f/appveyor-7661-failed/4hy85yllb2btbrkn.txt:[00:39:46] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000023E17E19B80>,)
03/15/pr/6546/6c6ce1f/appveyor-7688-failed/jg7665pt2684pioi.txt:[00:39:27] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x000001EE0BA5FF70>,)
03/18/pr/6555/24d9906/appveyor-7728-failed/b11xqxaoet410lnw.txt:[00:37:58] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x00000269F8075280>,)
03/18/pr/6550/17711f0/appveyor-7724-failed/5dbdyak8cle7rha7.txt:[00:40:11] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x000001A96E125040>,)
03/21/pr/6550/01e9a71/appveyor-7741-failed/ekh9ix8mwmx5fxkq.txt:[00:41:36] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x000001AC463E50D0>,)
03/22/pr/6550/18c1ade/appveyor-7749-failed/rpaw0n1ya2ighpa9.txt:[00:39:23] ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x000002713E0E50D0>,)
```
I maintain the [idea](https://github.com/datalad/datalad/issues/6482#issuecomment-1047823294) that it might  be a git issue ... the question is either we should strive to identify/report it or just workaround somehow -- e.g. re-do `git config` call upon exit 128 .  I wish I had it reproduced first, will try to do that.  @bpoldrack did you have any success reproducing it ? e.g. running smth like
```
{ set -e; for s in {1..100}; do python -m nose -s -v datalad/local/tests/test_foreach_dataset.py:test_basic_resilience; done }
```
on windows?

**Comment by yarikoptic** [comment] 2022-03-23 15:21
FWIW I did reproduce a "hit" while running smth like  (without `--pdb` which doing now also after set'ing env var to keep temp dirs)

```shell
(datalad) C:\Users\DataLad\PycharmProjects\datalad>for /l %x in (1, 1, 100) do python -m nose --pdb  -v datalad\local\tests\test_foreach_dataset.py:test_basic_resilience
```

**Comment by yarikoptic** [comment] 2022-03-23 22:22
probably obvious somewhat but more confirmation that it is some kind of a race condition... if I end up in that location of an original error, I can then easily run that command in a terminal or even in the same process.  so it might be that some `git` process may be still "working" on that file or smth like that, and that causes race condition leading to permissions denied

**Comment by yarikoptic** [comment] 2022-03-23 22:43
I am giving up on chasing it to death, but I think that #6587 works around it as a side-effect -- might be worth considering/merging ;)

**Comment by yarikoptic** [comment] 2022-03-23 23:57
while testing #6587 in a loop ran into a scary crash due to

<details>
<summary>git-annex: getMBlocks: VirtualAlloc MEM_COMMIT failed: The paging file is too small for this operation to complete.</summary> 

```shell
(datalad) C:\Users\DataLad\PycharmProjects\datalad-clone2>python -m nose --pdb  -v datalad\local\tests\test_foreach_dataset.py:test_basic_resilience
datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function Create.__call__ at 0x000001FB29CB1940>,) ... C:\Users\DataLad\AppData\Local\Temp\datalad_temp_hzjq2eka
Removing dirt
ok
datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x000001FB2ADA8CA0>,) ... C:\Users\DataLad\AppData\Local\Temp\datalad_temp_5a4zg1uh
C:\Users\DataLad\AppData\Local\Temp\datalad_temp_5a4zg1uh\subds_modified
C:\Users\DataLad\AppData\Local\Temp\datalad_temp_5a4zg1uh\subds_modified\subds_lvl1_modified
Removing dirt
Removing dirt
Removing dirt
ok

----------------------------------------------------------------------
Ran 2 tests in 47.664s

OK

(datalad) C:\Users\DataLad\PycharmProjects\datalad-clone2>python -m nose --pdb  -v datalad\local\tests\test_foreach_dataset.py:test_basic_resilience
datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function Create.__call__ at 0x0000019680E81940>,) ... C:\Users\DataLad\AppData\Local\Temp\datalad_temp_fuj3j6_f
Removing dirt
ok
datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000019681F77CA0>,) ... > c:\users\datalad\pycharmprojects\datalad-clone2\datalad\runner\runner.py(201)run()
-> raise CommandError(
(Pdb)
(Pdb) l
196             if results.get('code', True) not in [0, None]:
197                 # the runner has a better idea, doc string warns Protocol
198                 # implementations not to return these
199                 results.pop('cmd', None)
200                 results.pop('cwd', None)
201  ->             raise CommandError(
202                     # whatever the results were, we carry them forward
203                     cmd=cmd,
204                     cwd=self.cwd,
205                     **results,
206                 )
(Pdb) p results
*** NameError: name 'results' is not defined
(Pdb) p results
*** NameError: name 'results' is not defined
(Pdb) p cmd
*** NameError: name 'cmd' is not defined
(Pdb) up
> c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\annexrepo.py(941)_call_annex()
-> return runner.run(
(Pdb) down
> c:\users\datalad\pycharmprojects\datalad-clone2\datalad\runner\runner.py(201)run()
-> raise CommandError(
(Pdb) p cmd
*** NameError: name 'cmd' is not defined
(Pdb) p results
*** NameError: name 'results' is not defined
(Pdb) bt
  c:\users\datalad\miniconda3\envs\datalad\lib\unittest\case.py(60)testPartExecutor()
-> yield
  c:\users\datalad\miniconda3\envs\datalad\lib\unittest\case.py(676)run()
-> self._callTestMethod(testMethod)
  c:\users\datalad\miniconda3\envs\datalad\lib\unittest\case.py(633)_callTestMethod()
-> method()
  c:\users\datalad\miniconda3\envs\datalad\lib\site-packages\nose\case.py(197)runTest()
-> self.test(*self.arg)
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\tests\utils.py(874)_wrap_with_tempfile()
-> return t(*(arg + (filename,)), **kw)
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\local\tests\test_foreach_dataset.py(43)check_basic_resilience()
-> ds = populator(path)
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\tests\utils.py(1916)get_deeply_nested_structure()
-> ds.save()
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\distribution\dataset.py(502)apply_func()
-> return f(*args, **kwargs)
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\interface\utils.py(447)eval_func()
-> return return_func(*args, **kwargs)
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\interface\utils.py(439)return_func()
-> results = list(results)
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\interface\utils.py(357)generator_func()
-> for r in _process_results(
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\interface\utils.py(544)_process_results()
-> for res in results:
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\core\local\save.py(390)__call__()
-> yield from ProducerConsumerProgressLog(
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\parallel.py(535)__iter__()
-> for res in super().__iter__():
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\parallel.py(265)__iter__()
-> yield from self._iter_threads(self._jobs)
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\parallel.py(417)_iter_threads()
-> self.shutdown(force=True, exception=self._producer_exception or interrupted_by_exception)
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\parallel.py(233)shutdown()
-> raise exception
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\parallel.py(401)_iter_threads()
-> done_useful |= self._pop_done_futures(lgr)
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\parallel.py(463)_pop_done_futures()
-> raise exception
  c:\users\datalad\miniconda3\envs\datalad\lib\concurrent\futures\thread.py(57)run()
-> result = self.fn(*self.args, **self.kwargs)
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\parallel.py(329)consumer_worker()
-> for r in res:
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\core\local\save.py(309)save_ds()
-> for res in pds_repo.save_(
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\gitrepo.py(3467)save_()
-> self._save_post(message, status, need_partial_commit, amend=amend,
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\annexrepo.py(3437)_save_post()
-> self.localsync(managed_only=True)
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\annexrepo.py(3521)localsync()
-> self.call_annex(cmd)
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\annexrepo.py(1187)call_annex()
-> return self._call_annex(
  c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\annexrepo.py(941)_call_annex()
-> return runner.run(
> c:\users\datalad\pycharmprojects\datalad-clone2\datalad\runner\runner.py(201)run()
-> raise CommandError(
(Pdb) up
> c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\annexrepo.py(941)_call_annex()
-> return runner.run(
(Pdb) l
978                 )
979                 if in_subm_re:
980                     raise e
981
982                 # we don't know how to handle this, just pass it on
983  ->             raise
984
985         def _call_annex_records(self, args, files=None, jobs=None,
986                                 git_options=None,
987                                 stdin=None,
988                                 merge_annex_branches=True,
(Pdb) l 960
955                 # dealing with stdout
956                 out_of_space_re = re.search(
957                     "not enough free space, need (.*) more", e.stderr
958                 )
959                 if out_of_space_re:
960                     raise OutOfSpaceError(cmd=['annex'] + args,
961                                           sizemore_msg=out_of_space_re.groups()[0])
962
963                 # RemoteNotAvailableError:
964                 remote_na_re = re.search(
965                     "there is no available git remote named \"(.*)\"", e.stderr
(Pdb)
966                 )
967                 if remote_na_re:
968                     raise RemoteNotAvailableError(cmd=['annex'] + args,
969                                                   remote=remote_na_re.groups()[0])
970
971                 # TEMP: Workaround for git-annex bug, where it reports success=True
972                 # for annex add, while simultaneously complaining, that it is in
973                 # a submodule:
974                 # TODO: For now just reraise. But independently on this bug, it
975                 # makes sense to have an exception for that case
976                 in_subm_re = re.search(
(Pdb)
977                     "fatal: Pathspec '(.*)' is in submodule '(.*)'", e.stderr
978                 )
979                 if in_subm_re:
980                     raise e
981
982                 # we don't know how to handle this, just pass it on
983  ->             raise
984
985         def _call_annex_records(self, args, files=None, jobs=None,
986                                 git_options=None,
987                                 stdin=None,
(Pdb) l 900
895                 cmd += ['-c', 'annex.merge-annex-branches=false']
896
897             # annex portion of the command
898             cmd.append('annex')
899             cmd += args
900
901             if lgr.getEffectiveLevel() <= 8:
902                 cmd.append('--debug')
903
904             if self._annex_common_options:
905                 cmd += self._annex_common_options
(Pdb)
906
907             if jobs == 'auto':
908                 # Limit to # of CPUs (but at least 3 to start with)
909                 # and also an additional config constraint (by default 1
910                 # due to https://github.com/datalad/datalad/issues/4404)
911                 jobs = self._n_auto_jobs or min(
912                     self.config.obtain('datalad.runtime.max-annex-jobs'),
913                     max(3, cpu_count()))
914                 # cache result to avoid repeated calls to cpu_count()
915                 self._n_auto_jobs = jobs
916             if jobs and jobs != 1:
(Pdb)
917                 cmd.append('-J%d' % jobs)
918
919             runner = self._git_runner
920             env = None
921             if self.fake_dates_enabled:
922                 env = self.add_fake_dates(runner.env)
923
924             try:
925                 if files:
926                     if issubclass(protocol, GeneratorMixIn):
927                         return runner.run_on_filelist_chunks_items_(
(Pdb)
928                             cmd,
929                             files,
930                             protocol=protocol,
931                             env=env,
932                             **kwargs)
933                     else:
934                         return runner.run_on_filelist_chunks(
935                             cmd,
936                             files,
937                             protocol=protocol,
938                             env=env,
(Pdb)
939                             **kwargs)
940                 else:
941  >>                 return runner.run(
942                         cmd,
943                         stdin=stdin,
944                         protocol=protocol,
945                         env=env,
946                         **kwargs)
947             except CommandError as e:
948                 # Note: A call might result in several 'failures', that can be or
949                 # cannot be handled here. Detection of something, we can deal with,
(Pdb) p cmd
*** NameError: name 'cmd' is not defined
(Pdb) p stdin
*** NameError: name 'stdin' is not defined
(Pdb) up
> c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\annexrepo.py(1187)call_annex()
-> return self._call_annex(
(Pdb) l
1182
1183            Raises
1184            ------
1185            See `_call_annex()` for information on Exceptions.
1186            """
1187 ->         return self._call_annex(
1188                args,
1189                files=files,
1190                protocol=StdOutErrCapture)['stdout']
1191
1192        def call_annex_items_(self, args, files=None, sep=None):
(Pdb) p args
*** NameError: name 'args' is not defined
(Pdb) up
> c:\users\datalad\pycharmprojects\datalad-clone2\datalad\support\annexrepo.py(3521)localsync()
-> self.call_annex(cmd)
(Pdb) p cmd
*** NameError: name 'cmd' is not defined
(Pdb) c
ERROR

======================================================================
ERROR: datalad.local.tests.test_foreach_dataset.test_basic_resilience(<function get_deeply_nested_structure at 0x0000019681F77CA0>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\parallel.py", line 368, in _iter_threads
    raise _FinalShutdown()
datalad.support.parallel._FinalShutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DataLad\miniconda3\envs\datalad\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\tests\utils.py", line 874, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\local\tests\test_foreach_dataset.py", line 43, in check_basic_resilience
    ds = populator(path)
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\tests\utils.py", line 1916, in get_deeply_nested_structure
    ds.save()
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\distribution\dataset.py", line 502, in apply_func
    return f(*args, **kwargs)
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\interface\utils.py", line 447, in eval_func
    return return_func(*args, **kwargs)
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\interface\utils.py", line 439, in return_func
    results = list(results)
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\interface\utils.py", line 357, in generator_func
    for r in _process_results(
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\interface\utils.py", line 544, in _process_results
    for res in results:
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\core\local\save.py", line 390, in __call__
    yield from ProducerConsumerProgressLog(
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\parallel.py", line 535, in __iter__
    for res in super().__iter__():
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\parallel.py", line 265, in __iter__
    yield from self._iter_threads(self._jobs)
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\parallel.py", line 417, in _iter_threads
    self.shutdown(force=True, exception=self._producer_exception or interrupted_by_exception)
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\parallel.py", line 233, in shutdown
    raise exception
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\parallel.py", line 401, in _iter_threads
    done_useful |= self._pop_done_futures(lgr)
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\parallel.py", line 463, in _pop_done_futures
    raise exception
  File "C:\Users\DataLad\miniconda3\envs\datalad\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\parallel.py", line 329, in consumer_worker
    for r in res:
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\core\local\save.py", line 309, in save_ds
    for res in pds_repo.save_(
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\gitrepo.py", line 3467, in save_
    self._save_post(message, status, need_partial_commit, amend=amend,
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\annexrepo.py", line 3437, in _save_post
    self.localsync(managed_only=True)
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\annexrepo.py", line 3521, in localsync
    self.call_annex(cmd)
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\annexrepo.py", line 1187, in call_annex
    return self._call_annex(
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\support\annexrepo.py", line 941, in _call_annex
    return runner.run(
  File "C:\Users\DataLad\PycharmProjects\datalad-clone2\datalad\runner\runner.py", line 201, in run
    raise CommandError(
datalad.runner.exception.CommandError: CommandError: '"git" "-c" "diff.ignoreSubmodules=none" "annex" "sync" "--no-push" "--no-pull" "--no-commit" "--no-resolvemerge" "--no-content" "-c" "annex.dotfiles=true"' failed with exitcode 251 under C:\Users\DataLad\AppData\Local\Temp\datalad_temp_9bga6vc2 [err: 'git-annex: getMBlocks: VirtualAlloc MEM_COMMIT failed: The paging file is too small for this operation to complete.']
```
</details>

for `annex sync` operation... never saw that before and I hope never will, but may be those two are connected somehow???? similar issue found elsewhere https://github.com/haskell/haskell-ide-engine/issues/1701 where they also just closed their eyes and blamed stack...  git-annex version I have in VM is quite old: 8.20201008-g3be4731

**Comment by yarikoptic** [comment] 2022-03-25 12:23
Ran into [that other error](https://github.com/datalad/datalad/issues/6482#issuecomment-1076484326) again -- keeping that pdb open, awaiting for @christian-monch instructions.  FWIW -- that error didn't happen with https://github.com/datalad/datalad/pull/6587 workaround

**Comment by yarikoptic** [comment] 2022-03-25 12:41
FWIW in both cases the error happening while `git config` call, originally : `"git" "config" "-z" "-l" "--show-origin"` now for `'config', '-z', '-l', '--file', '.gitmodules'` -- but might be just a coincidence since `git config` most popular call, but might be something in that...

**Closed** 2022-03-28 12:57 UTC
Labels: platform-windows, spurious-test-failure, cmd-foreach-dataset
