### ISSUE TITLE
install/get: ideally should add to candidates a URL based on super's 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5033] opened 2020-10-14 02:46 UTC
If I clone/install a super-dataset, which has **only** immediate subdatasets installed, but not subdatasets (although available from their original location with "relative path URLs", `datalad install` in such a clone would fail since it nohow considers urls "built up" from the url present (only) in super dataset's .gitmodules

<details>
<summary>full dump from an example</summary> 

```shell
> git remote show origin
* remote origin
  Fetch URL: /tmp/tttt
  Push  URL: /tmp/tttt
  HEAD branch: master
  Remote branches:
    git-annex tracked
    master    tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local refs configured for 'git push':
    git-annex pushes to git-annex (fast-forwardable)
    master    pushes to master    (up to date)
(dev3) 1 29608 [1].....................................:Tue 13 Oct 2020 10:42:04 PM EDT:.
(git-annex)lena:/tmp/tttt-clone[master]
$> cat .gitmodules 
[submodule "haxby"]
	path = haxby
	url = smaug:/mnt/btrfs/datasets/datalad/crawl/labs/haxby
	datalad-id = 01cfb952-8439-11e6-af53-002590f97d84
[submodule "abide"]
	path = abide
	url = falkor.datalad.org:/srv/datasets.datalad.org/www/abide/
	datalad-id = 064527ea-92b3-11e7-8836-002590f97d84
(dev3) 1 29609 [1].....................................:Tue 13 Oct 2020 10:42:08 PM EDT:.
(git-annex)lena:/tmp/tttt-clone[master]
$> datalad install haxby
(dev3) 1 29610 [1].....................................:Tue 13 Oct 2020 10:42:25 PM EDT:.
(git-annex)lena:/tmp/tttt-clone[master]
$> ls haxby
total 16
4 attention/  4 dataset_description.json  4 life/  4 raiders/
(dev3) 1 29611 [1].....................................:Tue 13 Oct 2020 10:42:27 PM EDT:.
(git-annex)lena:/tmp/tttt-clone[master]
$> cat haxby/.gitmodules 
[submodule "raiders"]
	path = raiders
	url = ./raiders
[submodule "attention"]
	path = attention
	url = ./attention
[submodule "life"]
	path = life
	url = ./life
(dev3) 1 29612 [1].....................................:Tue 13 Oct 2020 10:42:49 PM EDT:.
(git-annex)lena:/tmp/tttt-clone[master]
$> datalad install -r haxby
[INFO   ] Installing Dataset(/tmp/tttt-clone/haxby) to get /tmp/tttt-clone/haxby recursively 
[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were:                   
| - /tmp/tttt/haxby/attention
  CommandError: 'git clone --progress /tmp/tttt/haxby/attention /tmp/tttt-clone/haxby/attention' failed with exitcode 128 [err: 'fatal: repository '/tmp/tttt/haxby/attention' does not exist'] [install(/tmp/tttt-clone/haxby/attention)] 
install(error): /tmp/tttt-clone/haxby/attention (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:
- /tmp/tttt/haxby/attention
  CommandError: 'git clone --progress /tmp/tttt/haxby/attention /tmp/tttt-clone/haxby/attention' failed with exitcode 128 [err: 'fatal: repository '/tmp/tttt/haxby/attention' does not exist']]
[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were:                   
| - /tmp/tttt/haxby/life
  CommandError: 'git clone --progress /tmp/tttt/haxby/life /tmp/tttt-clone/haxby/life' failed with exitcode 128 [err: 'fatal: repository '/tmp/tttt/haxby/life' does not exist'] [install(/tmp/tttt-clone/haxby/life)] 
install(error): /tmp/tttt-clone/haxby/life (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:
- /tmp/tttt/haxby/life
  CommandError: 'git clone --progress /tmp/tttt/haxby/life /tmp/tttt-clone/haxby/life' failed with exitcode 128 [err: 'fatal: repository '/tmp/tttt/haxby/life' does not exist']]
[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were:                   
| - /tmp/tttt/haxby/raiders
  CommandError: 'git clone --progress /tmp/tttt/haxby/raiders /tmp/tttt-clone/haxby/raiders' failed with exitcode 128 [err: 'fatal: repository '/tmp/tttt/haxby/raiders' does not exist'] [install(/tmp/tttt-clone/haxby/raiders)] 
install(error): /tmp/tttt-clone/haxby/raiders (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:
- /tmp/tttt/haxby/raiders
  CommandError: 'git clone --progress /tmp/tttt/haxby/raiders /tmp/tttt-clone/haxby/raiders' failed with exitcode 128 [err: 'fatal: repository '/tmp/tttt/haxby/raiders' does not exist']]
action summary:
  get (notneeded: 1)
  install (error: 3)

```
</details>

**Comment by mih** [comment] 2020-10-14 08:19
I didn't check the details, but I will leave the note that we have means to configure subdataset source candidate URLs:

```
    Additional candidate URLs can be generated based on templates specified as
    configuration variables with the pattern

      `datalad.get.subdataset-source-candidate-<name>`

    where `name` is an arbitrary identifier. If name starts with three digits
    (e.g. '400myserver') these will be interpreted as a cost, and the
    respective candidate will be sorted into the generated candidate list
    according to this cost. If no cost is given, a default of 700
    is used.

    A template string assigned to such a variable can utilize the Python format
    mini language and may reference a number of properties that are inferred
    from the parent dataset's knowledge about the target subdataset. Properties
    include any submodule property specified in the respective `.gitmodules`
    record. For convenience, an existing `datalad-id` record is made available
    under the shortened name `id`.
```

Possibly needs extension, but the framework is an place, and should avoid general strategy changes.

**Comment by adswa** [comment] 2020-10-14 08:22
FWIW there is a (yet unreviewed) section in the handbook about this: https://datalad-handbook--548.org.readthedocs.build/en/548/beyond_basics/101-148-clonepriority.html

**Comment by yarikoptic** [comment] 2020-10-15 02:46
Thank you @adswa  but I do not see really how to "apply" it here:
-  I think it is not about "priority" (since we would try them all) but rather about not even adding .gitmodules-based candidate of the superdataset if there is an original remote candidate?  I might be missing it though

<details>
<summary>Here is a reproducer which does 2 failing attempts and then "mitigation" via "uninstall them all and remove remote"</summary> 

```shell
#!/bin/bash

export PS4='> '
set -x
set -eu
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"

datalad create origin
(
cd origin
datalad install -d . ///labs
)

datalad clone origin clone
(
cd clone
: this would not work!
datalad install labs/haxby/raiders && { echo should have failed; exit 1; } || { echo "the issue, proceeding"; }
: and if I uninstall labs -- not enough
datalad uninstall -r labs
datalad install labs/haxby/raiders && { echo should have failed; exit 1; } || { echo "the issue, proceeding"; }

: but if I uninstall and remove origin remote...
datalad uninstall -r labs
git remote remove origin
: this would since it would be basing on .gitmodules to discover url
datalad install labs/haxby/raiders
)

```
</details>

<details>
<summary>output</summary> 

```shell
$> bash sl-get-sub                                      
> set -eu
>> mktemp -d /home/yoh/.tmp/dl-XXXXXXX
> cd /home/yoh/.tmp/dl-2KdR1ME
> datalad create origin
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-2KdR1ME/origin 
create(ok): /home/yoh/.tmp/dl-2KdR1ME/origin (dataset)
> cd origin
> datalad install -d . ///labs
install(ok): /home/yoh/.tmp/dl-2KdR1ME/origin/labs (dataset)                                                     
add(ok): /home/yoh/.tmp/dl-2KdR1ME/origin/labs (file)                                                            
add(ok): /home/yoh/.tmp/dl-2KdR1ME/origin/.gitmodules (file)
save(ok): /home/yoh/.tmp/dl-2KdR1ME/origin (dataset)
action summary:
  add (ok: 2)
  install (ok: 1)
  save (ok: 1)
> datalad clone origin clone
install(ok): /home/yoh/.tmp/dl-2KdR1ME/clone (dataset)                                                           
> cd clone
> : this would not 'work!'
> datalad install labs/haxby/raiders
install(ok): /home/yoh/.tmp/dl-2KdR1ME/clone/labs (dataset) [Installed subdataset in order to get /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby/raiders]
[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were:                   
| - /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby
  CommandError: 'git clone --progress /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby' failed with exitcode 128 [err: 'fatal: repository '/home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby' does not exist'] [install(/home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby)] 
install(error): /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:
- /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby
  CommandError: 'git clone --progress /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby' failed with exitcode 128 [err: 'fatal: repository '/home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby' does not exist']]
get(impossible): /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby/raiders [path does not exist]
[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were:                   
| - /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby
  CommandError: 'git clone --progress /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby' failed with exitcode 128 [err: 'fatal: repository '/home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby' does not exist'] [install(/home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby)] 
install(error): /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:
- /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby
  CommandError: 'git clone --progress /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby' failed with exitcode 128 [err: 'fatal: repository '/home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby' does not exist']]
get(impossible): /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby/raiders [path does not exist]
action summary:
  get (impossible: 2)
  install (error: 2, ok: 1)
> echo 'the issue, proceeding'
the issue, proceeding
> : and if I uninstall labs -- not enough
> datalad uninstall -r labs
uninstall(ok): /home/yoh/.tmp/dl-2KdR1ME/clone/labs (dataset)
action summary:
  drop (notneeded: 1)
  uninstall (ok: 1)
> datalad install labs/haxby/raiders
install(ok): /home/yoh/.tmp/dl-2KdR1ME/clone/labs (dataset) [Installed subdataset in order to get /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby/raiders]
[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were:                   
| - /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby
  CommandError: 'git clone --progress /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby' failed with exitcode 128 [err: 'fatal: repository '/home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby' does not exist'] [install(/home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby)] 
install(error): /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:
- /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby
  CommandError: 'git clone --progress /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby' failed with exitcode 128 [err: 'fatal: repository '/home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby' does not exist']]
get(impossible): /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby/raiders [path does not exist]
[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were:                   
| - /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby
  CommandError: 'git clone --progress /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby' failed with exitcode 128 [err: 'fatal: repository '/home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby' does not exist'] [install(/home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby)] 
install(error): /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:
- /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby
  CommandError: 'git clone --progress /home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby' failed with exitcode 128 [err: 'fatal: repository '/home/yoh/.tmp/dl-2KdR1ME/origin/labs/haxby' does not exist']]
get(impossible): /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby/raiders [path does not exist]
action summary:
  get (impossible: 2)
  install (error: 2, ok: 1)
> echo 'the issue, proceeding'
the issue, proceeding
> : but if I uninstall and remove origin remote...
> datalad uninstall -r labs
uninstall(ok): /home/yoh/.tmp/dl-2KdR1ME/clone/labs (dataset)
action summary:
  drop (notneeded: 1)
  uninstall (ok: 1)
> git remote remove origin
> : this would since it would be basing on .gitmodules to discover url
> datalad install labs/haxby/raiders
install(ok): /home/yoh/.tmp/dl-2KdR1ME/clone/labs (dataset) [Installed subdataset in order to get /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby/raiders]                                                                             
install(ok): /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby (dataset) [Installed subdataset in order to get /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby/raiders]                                                                       
install(ok): /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby/raiders (dataset) [Installed subdataset in order to get /home/yoh/.tmp/dl-2KdR1ME/clone/labs/haxby/raiders]                                                               
action summary:
  install (ok: 3)
bash sl-get-sub  12.56s user 5.60s system 98% cpu 18.462 total

```
</details>

**Comment by yarikoptic** [comment] 2021-01-05 22:20
just a refresher ping for @mih as it relates (although not exactly the same) issue we briefly touched upon today -- candidate installation urls.  It should be nothing for user to configure, but rather for datalad to "keep track of" IMHO

**Comment by mih** [comment] 2021-05-31 11:58
I could reproduce this, and I agree that it should be fixed -- I don't think the machinery is working as intended.

**Comment by mih** [comment] 2021-06-14 20:12
So the effective candiate URL set (just one item) is:

```
[{'cost': 500, 'name': 'origin', 'url': '/tmp/origin/labs/haxby'}]
```

Which means the title is not 100% accurate. The candidate URL *is* based on the superdataset, but based on the superdataset's origin URL in the clone. What would be needed to address the issue at hand, is a candidate URL based on the *submodule* configuration of the *superdataset* in *its superdataset*.

```
/tmp/clone (git)-[master] % cat .gitmodules
[submodule "labs"]
        path = labs
        url = http://datasets.datalad.org/labs/.git
        datalad-id = 72e7a148-7af4-11e6-af5a-002590f97d84
        datalad-url = ///labs
```

**Comment by mih** [comment] 2021-06-15 05:51
Uh, just had the thought that we are pretty much causing the original situation by ranking a clone from a superdataset's origin higher than the configured subdataset location from `.gitmodules`. Because of this, the `labs` dataset is cloned from underneath `origin` and not from datasets.d.o. Switching the priorities makes the issue go away too, without expensive lookups of potentially existing super-superdatasets.

**Comment by mih** [comment] 2021-06-22 18:44
Confirmed. Full diff of a fix is:

```diff
diff --git a/datalad/distribution/get.py b/datalad/distribution/get.py
index b43d786d4..da37a1dfc 100644
--- a/datalad/distribution/get.py
+++ b/datalad/distribution/get.py
@@ -273,7 +273,7 @@ def _get_flexible_source_candidates_for_submodule(ds, sm):
     # to be consumed by git:
     if sm_datalad_url:
         clone_urls.append(
-            dict(cost=590, name='dl-url', url=sm_datalad_url)
+            dict(cost=490, name='dl-url', url=sm_datalad_url)
         )
 
     # sort all candidates by their label, thereby allowing a
```
1. original URL given to datalad
2. previous "best-guess" URL (but wrong in this case)
3. URL from gitmodules
4. the rest

This sorts the URL that was originally given to datalad (by intelligent design) to register the subdataset first.

An alternative fix is

```diff
diff --git a/datalad/distribution/get.py b/datalad/distribution/get.py
index b43d786d4..8a5825ac5 100644
--- a/datalad/distribution/get.py
+++ b/datalad/distribution/get.py
@@ -218,7 +218,7 @@ def _get_flexible_source_candidates_for_submodule(ds, sm):
                 sm_path_url = sm_path
 
             clone_urls.extend(
-                dict(cost=500, name=remote, url=url)
+                dict(cost=650, name=remote, url=url)
                 for url in _get_flexible_source_candidates(
                     # alternate suffixes are tested by `clone` anyways
                     sm_path_url, remote_url, alternate_suffix=False)

```

which sorts the failing auto-generated URL last. It would turn the order into:

1. original URL given to datalad
2. URL from .gitmodules
3. the rest

I am leaning towards preferring the second solution, because it makes sense to me to honor what is configured in the dataset first, and only then start guessing.

**Closed** 2021-07-11 14:30 UTC
Labels: UX
