### ISSUE TITLE
datalad save ideally shouldn't explore entire hierarchy and rely on "git status" output may be?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1699] opened 2017-08-09 20:41 UTC
save -r seems to traverse full hierarchy, which is slower than just to query git status first for what paths might be needed saving.

initially encountered when had only one dataset known to be modified but datalad was oldish so decided to test current master and 
```shell
$> datalad save -m "Added initial subdataset with sherlock for MIND-2017" -r
save(notneeded): /mnt/btrfs/datasets/datalad/crawl/workshops/nipype-2017/ds000114 (dataset)
save(notneeded): /mnt/btrfs/datasets/datalad/crawl/workshops/nipype-2017 (dataset)
save(notneeded): /mnt/btrfs/datasets/datalad/crawl/workshops/nih-2017/ds000114/derivatives/freesurfer (dataset)
save(notneeded): /mnt/btrfs/datasets/datalad/crawl/workshops/nih-2017/ds000114/derivatives/fmriprep (dataset)
save(notneeded): /mnt/btrfs/datasets/datalad/crawl/workshops/nih-2017/ds000114 (dataset)
save(notneeded): /mnt/btrfs/datasets/datalad/crawl/workshops/nih-2017 (dataset)
save(notneeded): /mnt/btrfs/datasets/datalad/crawl/workshops/mind-2017/sherlock (dataset)
save(notneeded): /mnt/btrfs/datasets/datalad/crawl/workshops/mind-2017 (dataset)
save(notneeded): /mnt/btrfs/datasets/datalad/crawl/workshops (dataset)
action summary:
  save (notneeded: 9)
(dev)2 14833.....................................:Wed 09 Aug 2017 04:38:01 PM EDT:.
(git)smaug:/mnt/btrfs/datasets/datalad/crawl/workshops[master]git
$> git status
On branch master
nothing to commit, working directory clean
(dev)2 14834.....................................:Wed 09 Aug 2017 04:38:32 PM EDT:.
(git)smaug:/mnt/btrfs/datasets/datalad/crawl/workshops[master]git
$> datalad --version
datalad 0.8.0.dev1
```

so -- it does get through the entire sub-hierarchy one by one, although could just see that all is clean according to fast "git status"

**Comment by mih** [comment] 2017-08-11 06:40
Just an idea, without much thinking: It should be possible to amend the AnnotatePaths call in `save` with a `since=HEAD` argument. This should have the desired effect automatically. Internally, this will call `diff` which figures out the paths that were changed.

I have no good intuition how that plays together with provided explicit paths to save (should work), and we would need to take a close at the value that is send to the `ignore_subdatasets` argument of the `diff` call performed by `AnnotatePaths` -- that might need an RF. But otherwise it should be fairly painless with a substantial potential for speed-ups.

**Comment by mih** [comment] 2017-08-16 07:23
I still believe this is possible. However, the first two hours trying to make it happen where spent figuring out WTF...

FTR: I think the culprit to make it work in general is to check our approach to find modified paths during path annotation. Currently, we would check for a diff against the provided revision, but not using `diff --staged` https://github.com/datalad/datalad/blob/dev-master/datalad/interface/annotate_paths.py#L188

Consequently, we fail to discover staged changes, and due to that are unable to `save -r` a dataset tree to get it clean, if anywhere anything is staged. Naturally, changing this call to use `staged=True` is the next step. However, I feel it wasn't a random choice, so I think a close look at the respective tests comes first.

to be continued...

**Comment by mih** [comment] 2017-08-16 08:07
I think I got it. We did not cover the special case of a subdataset coming up in a diff output with source and destination commit being identical -- which is the case when a subdataset has uncommitted change. Fixed that, brings `save` to life!

**Comment by mih** [comment] 2017-08-16 09:42
I think I nailed it -- tests are running.

**Comment by bpoldrack** [comment] 2017-08-16 11:33
As far as I can see, tests confirmed you nailed it. ;-)

**Comment by mih** [comment] 2017-08-16 12:31
LOL -- I even wrote the tests to confirm that I nailed it ;-)

**Comment by bpoldrack** [comment] 2017-08-16 12:34
See - you nailed the tests, too, obviously. :-D

**Comment by bpoldrack** [comment] 2017-08-16 12:43
Well, since a close is supposed to take place only when the fix is in master - reopening.

**Closed** 2017-08-17 12:38 UTC
Labels: enhancement, fix-implemented
