### ISSUE TITLE
'git annex drop' on NFS mount doesn't free up space

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3929] opened 2019-12-16 11:05 UTC
Demo:

```
mkdir nfsdrop
cd nfsdrop
git init
git annex init
echo 123 > file1
git annex add file1
git commit -m dummy
git annex drop --force file1
```

which reliably gives me something like (across different machines and NFS setups)

```
% tree -a .git/annex/objects
.git/annex/objects
└── G6
    └── qW
        └── SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b
            └── .nfs0000000000141e900001531a

% cat .git/annex/objects/G6/qW/SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b/.nfs0000000000141e900001531a 
123
```

So in essence, git-annex has dropped the file (repo integrity is fine), but effectively no data has left the system. This was discovered in https://github.com/datalad/datalad/issues/3921 where a drop was supposed to prevent the disk from filling up, but did not.

**Comment by mih** [comment] 2019-12-16 11:08
http://nfs.sourceforge.net/#faq_d2 is possibly related, but at least one machine was running NFS 4.2

**Comment by aqw** [comment] 2019-12-16 11:17
Adding to what @mih posted. This looks like what NFS called "silly rename". All machines are running NFS 4.2, and `/proc/mounts` confirms it.

NFS 4.1 adds "[OPEN4_RESULT_PRESERVE_UNLINKED](https://tools.ietf.org/html/rfc5661#section-18.16)", but I believe both the client and server need to support it. And searching Torvald's linux tree only results in [one hit](https://github.com/torvalds/linux/blob/master/fs/nfs/unlink.c). So I don't this this supported on either side in Linux.

I don't know the traditional ways of mitigating "silly renames", btu I think that's going to have to be the starting point.

**Comment by aqw** [comment] 2019-12-16 11:23
I forgot to mention that `lsof` shows that no process, on either the client or server, have these files open.

**Comment by mih** [comment] 2020-02-21 09:57
It seems that a viable (though not desirable) approach would be to check if the key directory still exists after a drop, and have datalad clean it up.

**Comment by yarikoptic** [comment] 2020-02-21 15:53
wow -- I have missed this "fun" issue.
I think it is something to address on git-annex side -- on a normal file system KEY directory is removed, while on NFS it keeps that KEY directory...

<details><summary>
With annex 7.20200204+git62-gcc4521068-1~ndall+1  I do not observe `.nfs*` crap being left behind, but KEY directory remains
</summary>

```shell
$> bash ~datalad/trash/nfsdrop
+ git annex version
+ head -n 1
git-annex version: 7.20200204+git62-gcc4521068-1~ndall+1
+ '[' -e nfsdrop ']'
+ chmod +w -R nfsdrop
+ rm -rf nfsdrop
+ mkdir nfsdrop
+ cd nfsdrop
+ git init
Initialized empty Git repository in /tmp/nfsmount/nfsdrop/.git/
+ git annex init
init  (scanning for unlocked files...)
ok
(recording state in git...)
+ echo 123
+ git annex add file1
add file1 
ok                                
(recording state in git...)
+ git commit -m dummy
[master (root-commit) b8bca26] dummy
 1 file changed, 1 insertion(+)
 create mode 120000 file1
+ tree -a .git/annex/objects
.git/annex/objects
└── G6
    └── qW
        └── SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b
            └── SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b

3 directories, 1 file
+ git annex drop --force file1
drop file1 ok
(recording state in git...)
+ tree -a .git/annex/objects
.git/annex/objects
└── G6
    └── qW
        └── SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b

3 directories, 0 files
```
</details>
but I also do not see reflection of  https://git-annex.branchable.com/bugs/regression__58___fails_to_detect_need_for_pidlock_on_an_NSF_mount/ fix, that pidlock is not set ... 

<details>
<summary>and if I set it explicitly, the issue seems to be gone:</summary> 

```shell
$> bash ~datalad/trash/nfsdrop
+ git annex version
+ head -n 1
git-annex version: 7.20200204+git62-gcc4521068-1~ndall+1
+ '[' -e nfsdrop ']'
+ chmod +w -R nfsdrop
+ rm -rf nfsdrop
+ mkdir nfsdrop
+ cd nfsdrop
+ git init
Initialized empty Git repository in /tmp/nfsmount/nfsdrop/.git/
+ git config --add annex.pidlock true
+ git annex init
init  (scanning for unlocked files...)
ok
(recording state in git...)
+ echo 123
+ git annex add file1
add file1 
ok                                
(recording state in git...)
+ git commit -m dummy
[master (root-commit) 043c689] dummy
 1 file changed, 1 insertion(+)
 create mode 120000 file1
+ tree -a .git/annex/objects
.git/annex/objects
└── G6
    └── qW
        └── SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b
            └── SHA256E-s4--181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b

3 directories, 1 file
+ git annex drop --force file1
drop file1 ok
(recording state in git...)
+ tree -a .git/annex/objects
.git/annex/objects

0 directories, 0 files

```
</details>

<details>
<summary>here is my script you could try</summary> 

```shell
#!/bin/bash

set -xeu

git annex version 2>&1 | head -n 1

if [ -e nfsdrop ]; then
    chmod +w -R nfsdrop
    rm -rf nfsdrop
fi

mkdir nfsdrop
cd nfsdrop
git init
git config --add annex.pidlock true
git annex init
echo 123 > file1
git annex add file1
git commit -m dummy
tree -a .git/annex/objects 
git annex drop --force file1
tree -a .git/annex/objects 
```
</details>

When I downgrade to "stock neurodebian" git annex version 7.20190819+git2-g908476a9b-1~ndall+1,  setting pidlock also resolves the problem.  So IMHO it was incomplete fix within git-annex, which we still cannot progress to due to other new regressions

(attn @joeyh and I will leave original author of the issue to report it properly on https://git-annex.branchable.com)

**Comment by mih** [comment] 2020-02-25 14:57
Workaround as identified by @yarikoptic setting

`git config --add annex.pidlock true`

can make the problem go away until git-annex deals with it specifically.

**Comment by mih** [comment] 2020-07-16 09:55
We have `git-annex-standalone 7.20190819+git2-g908476a9b-1~ndall+1`, and this is an issue -- now at a larger scale. @yarikoptic do you suggest switching to `git-annex 8.20200330-1~bpo10+1`?

**Comment by yarikoptic** [comment] 2020-07-16 16:26
That newer version could surface other problems up (stalling ssh etc) -- those (and other issues) is what prevented us to have more recent version in neurodebian for a while. @kyleam might have a more specific information of deficiencies of various git annex versions (and interaction with ssh) up to this point in time.  If you decide to "upgrade", I would have first done it on some host and ran all the datalad + extensions tests with SSH enabled to make sure that your particular system setup is not affected.
I also typically run them with TMPDIR pointing to some NFS (or whatever) mounted partition on the system to see what resurfaces.

**Comment by yarikoptic** [comment] 2020-10-06 00:24
FTR: reported against git-annex -- https://git-annex.branchable.com/bugs/drop_on_NFS___40__no_pidlock_need_detected__41___leaves_annex__47__objects__47__XX__47__YY__47__KEY_dir_behind_/ and it was "done" by "merging" the issue into   https://git-annex.branchable.com/bugs/huge_multiple_copies_of___39__.nfs__42____39___and___39__.panfs__42____39___being_created/  which is still open (reported initially against git-annex 5.20140818-g10bf03a ) . Altogether it seems that despite a number of fixes to pidlock necessity detection annex might still miss some cases where it is needed... so the issue might not be fully resolved yet.

**Comment by yarikoptic** [comment] 2022-08-24 13:26
well, I do 
- not think we can do anything to completely address this issue on DataLad level anyhow
- [the issue](https://git-annex.branchable.com/bugs/huge_multiple_copies_of___39__.nfs__42____39___and___39__.panfs__42____39___being_created/) was closed in git-annex with reasoning that anything which could be done at that level was done although not addressing it entirely:
  - setting `annex.pidlock` addresses the issue
  - `git-annex` might fail to detect that it is running on NFS, thus not set `pidlock`

Thus, I will close it with 'wontfix' label, and would only encourage anyone coming up with ideas on how to improve this detection to report it against git-annex.

**Closed by yarikoptic** 2022-08-24 13:26 UTC
Labels: severity-normal, annex, UX, cmd-drop
