### ISSUE TITLE
Cannot add subdataset at a location that was in the index previously

### ISSUE THREAD

**Issue by mih** [datalad/datalad#811] opened 2016-09-13 07:50 UTC
Here is the respective test: https://github.com/datalad/datalad/pull/788/commits/fc7e6334b5cd8c772bc791ed6cac445d788c92bf

At this point I think this is a bug.

**Comment by mih** [comment] 2016-09-13 07:51
FTR: Parts of PR #788

**Comment by bpoldrack** [comment] 2016-09-13 13:34
I tried to reproduce this manually and to look into it. At first I failed with the approach to `unannex` and then proceed, too. Found a more or less complicated solution to get from this point to a submodule with missing mapping in `.gitmodules`, which is a situation, we learned to deal with. But when reproducing my solution, it suddenly seemed to work right away. May be I confused myself, while trying different things ... ;-)

Setting up the situation:
```
 % mkdir test
 % cd test
 % git init
Initialized empty Git repository in /home/ben/Development/testing/test/.git/
 % git annex init
init  ok
(recording state in git...)
 % touch top_load.dat
 % git annex add top_load.dat 
add top_load.dat ok
(recording state in git...)
 % mkdir sub
 % touch sub/somefile.dat
 % git annex add sub/somefile.dat 
add sub/somefile.dat ok
(recording state in git...)
 % git commit -m"Initial state"
[master (root-commit) 5cff685] Initial state
 2 files changed, 2 insertions(+)
 create mode 120000 sub/somefile.dat
 create mode 120000 top_load.dat
 % git status
On branch master
nothing to commit, working directory clean
 % git ls-files
sub/somefile.dat
top_load.dat
 % git annex info
repository mode: indirect
trusted repositories: 0
semitrusted repositories: 3
	00000000-0000-0000-0000-000000000001 -- web
 	00000000-0000-0000-0000-000000000002 -- bittorrent
 	ae5b25ec-a2cc-44ae-b9d0-88463e683c0e -- ben@tree:~/Development/testing/test [here]
untrusted repositories: 0
transfers in progress: none
available local disk space: 108.74 gigabytes (+1 megabyte reserved)
local annex keys: 1
local annex size: 0 bytes
annexed files in working tree: 2
size of annexed files in working tree: 0 bytes
bloom filter size: 32 mebibytes (0% full)
backend usage: 
	SHA256E: 2
 % git annex find
sub/somefile.dat
top_load.dat
```
And solve it:

```
% git annex unannex sub/somefile.dat 
unannex sub/somefile.dat ok
 % git ls-files
top_load.dat
 % git annex find
top_load.dat
 % git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	sub/

nothing added to commit but untracked files present (use "git add" to track)

% cd sub
.../sub % git init
Initialized empty Git repository in /home/ben/Development/testing/test/sub/.git/
.../sub % git annex init
init  ok
(recording state in git...)
.../sub % git annex add somefile.dat 
add somefile.dat ok
(recording state in git...)
.../sub % git commit -m "sub initialized"
[master (root-commit) bbf9ae2] sub initialized
 1 file changed, 1 insertion(+)
 create mode 120000 somefile.dat
.../sub % git status
On branch master
nothing to commit, working directory clean
.../sub % git log
commit bbf9ae2e1e04358f1b27cb33a5cdfc9866890fed
Author: Benjamin Poldrack <benjaminpoldrack@gmail.com>
Date:   Tue Sep 13 15:11:56 2016 +0200

    sub initialized
.../sub % git annex info
repository mode: indirect
trusted repositories: 0
semitrusted repositories: 3
	00000000-0000-0000-0000-000000000001 -- web
 	00000000-0000-0000-0000-000000000002 -- bittorrent
 	58f1cd59-ddce-4c55-a4bd-b8999776418c -- ben@tree:~/Development/testing/test/sub [here]
untrusted repositories: 0
transfers in progress: none
available local disk space: 108.74 gigabytes (+1 megabyte reserved)
local annex keys: 1
local annex size: 0 bytes
annexed files in working tree: 1
size of annexed files in working tree: 0 bytes
bloom filter size: 32 mebibytes (0% full)
backend usage: 
	SHA256E: 1
.../sub % git ls-files
somefile.dat
.../sub % git annex find
somefile.dat
.../sub % cd ..
 % git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	sub/

nothing added to commit but untracked files present (use "git add" to track)
 % git log
commit 93b057c662b1bb1d99e46b33d7901798acf5a75d
Author: Benjamin Poldrack <benjaminpoldrack@gmail.com>
Date:   Tue Sep 13 15:09:39 2016 +0200

    content removed from git annex

commit 72a8241fc5ae7f637061d384cdb82777180f1060
Author: Benjamin Poldrack <benjaminpoldrack@gmail.com>
Date:   Tue Sep 13 15:09:34 2016 +0200

    content removed from git annex

commit b1e748c7def347f1039a39bbed251ada18628821
Author: Benjamin Poldrack <benjaminpoldrack@gmail.com>
Date:   Tue Sep 13 15:08:45 2016 +0200

    Initial state
 % git annex info
repository mode: indirect
trusted repositories: 0
semitrusted repositories: 3
	00000000-0000-0000-0000-000000000001 -- web
 	00000000-0000-0000-0000-000000000002 -- bittorrent
 	7d978937-7285-420c-a22d-abee4d64f734 -- ben@tree:~/Development/testing/test [here]
untrusted repositories: 0
transfers in progress: none
available local disk space: 108.74 gigabytes (+1 megabyte reserved)
local annex keys: 1
local annex size: 0 bytes
annexed files in working tree: 1
size of annexed files in working tree: 0 bytes
bloom filter size: 32 mebibytes (0% full)
backend usage: 
	SHA256E: 1
 % git ls-files
top_load.dat
 % git annex find
top_load.dat
 % git submodule add ./sub sub
Adding existing repo at 'sub' to the index
% git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .gitmodules
	new file:   sub

 % git commit -m "Submodule added"
[master c36e66e] Submodule added
 2 files changed, 4 insertions(+)
 create mode 100644 .gitmodules
 create mode 160000 sub
 % git version
git version 2.7.0
```

That thing is now clean, clonable, etc. ...

What did I do different than you, @mih ?

**Comment by yarikoptic** [comment] 2016-09-20 13:42
#788 was merged and I see those tests in code base so I guess this one is resolved (use ```Closes #``` in your commits fixing issues please)

**Closed by yarikoptic** 2016-09-20 13:42 UTC
Labels: bug

**Comment by bpoldrack** [comment] 2016-09-21 07:56
I doubt it is solved. The test just shows, what the issue is about.
