### ISSUE TITLE
Boto dependency

### ISSUE THREAD

**Issue by TheChymera** [datalad/datalad#7572] opened 2024-03-20 21:06 UTC
### What is the problem?

Boto seems to have been deprecated in favour of boto3 for a few years now → https://github.com/boto/boto?tab=readme-ov-file#deprecation-notice

Is there any reason for sticking to the old one, is anybody even using this?

**Comment by yarikoptic** [comment] 2024-03-21 23:32
duplicate of https://github.com/datalad/datalad/issues/5597 .  Chime in there or on linked there (closed) PR

I do use whenever I need to get data from S3 with authentication. don't remember when it was last time though

**Closed by yarikoptic** 2024-03-21 23:32 UTC
