### ISSUE TITLE
docstring doesn't propagate into @datasetmethod ?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#620] opened 2016-07-07 18:57 UTC
```ipython
In [7]: ds = Dataset('/tmp/ds1/ds2')

In [8]: ds.create?
Type:        instancemethod
String form: <bound method Dataset.__call__ of <Dataset path=/tmp/ds1/ds2>>
File:        /home/yoh/proj/datalad/datalad/datalad/distribution/dataset.py
Definition:  ds.create(*args, **kwargs)
Docstring:   <no docstring>
```

**Comment by hanke** [comment] 2016-07-08 05:18
Duplicate of #601

**Closed** 2016-07-08 05:20 UTC
