### ISSUE TITLE
ORA does not support authenticated HTTP(S) access

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5024] opened 2020-10-13 06:44 UTC
It performs a plain GET requests using the `requests` package and bypasses any internal helper. In contrast to #5023 this is not trivial to fix, because ORA reads chunks of bytes from a stream.

Alternatively, we should explore using an internal downloader that has its own progress reporting, and utilizes datalad's credential capabilties.

**Comment by mih** [comment] 2020-10-13 07:12
I tried something simple:

```diff
diff --git a/datalad/distributed/ora_remote.py b/datalad/distributed/ora_remote.py
index 7b8a3547c..14bd48053 100644
--- a/datalad/distributed/ora_remote.py
+++ b/datalad/distributed/ora_remote.py
@@ -556,15 +556,8 @@ class HTTPRemoteIO(object):
         # to annexremote.dirhash from within IO classes
 
         url = self.base_url + "/annex/objects/" + str(key_path)
-        response = requests.get(url, stream=True)
-
-        with open(filename, 'wb') as dst_file:
-            bytes_received = 0
-            for chunk in response.iter_content(chunk_size=self.buffer_size,
-                                               decode_unicode=False):
-                dst_file.write(chunk)
-                bytes_received += len(chunk)
-                progress_cb(bytes_received)
+        from datalad.utils import download_url
+        download_url(url, filename, overwrite=True)
```

This makes `git annex get` work

```
% git -C atj3 annex get readme.docx
get readme.docx (from inm7-storage...) 
[INFO] Downloading 'https://archive.ds.inm7.de/00e/0c610-0f27-41bb-9626-157ec8815bfe/annex/objects/xk/vw/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx' into '.git/annex/tmp/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx' 
[INFO] http session: Authenticating into session for https://archive.ds.inm7.de/00e/0c610-0f27-41bb-9626-157ec8815bfe/annex/objects/xk/vw/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx 
(checksum...) ok
(recording state in git...)
```

but strangely fails with `datalad get`

```
% datalad -C atj3 -l debug get readme.docx
[Level 11] CommandError: 'git annex get -c annex.dotfiles=true -c annex.retry=3 --json --json-error-messages --json-progress -- readme.docx' failed with exitcode 1 under /tmp/atj3 [out: '{"command":"get","wanted":[{"here":false,"uuid":"4440db2d-7f87-46a7-bd14-8e4dbab9c799","description":"[inm7-storage]"}],"note":"from inm7-storage...\nUnable to access these remotes: inm7-storage\nTry making some of these repositories available:\n\t4440db2d-7f87-46a7-bd14-8e4dbab9c799 -- [inm7-storage]\n\n(Note that these git remotes have annex-ignore set: origin)","skipped":[],"success":false,"key":"MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx","error-messages":["  verification of content failed"],"file":"readme.docx"}'] [err: 'git-annex: get: 1 failed'] 
[WARNING] Running get resulted in stderr output: git-annex: get: 1 failed
 
[DEBUG  ] received JSON result from annex: {'command': 'get', 'wanted': [{'here': False, 'uuid': '4440db2d-7f87-46a7-bd14-8e4dbab9c799', 'description': '[inm7-storage]'}], 'note': 'from inm7-storage...\nUnable to access these remotes: inm7-storage\nTry making some of these repositories available:\n\t4440db2d-7f87-46a7-bd14-8e4dbab9c799 -- [inm7-storage]\n\n(Note that these git remotes have annex-ignore set: origin)', 'skipped': [], 'success': False, 'key': 'MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx', 'error-messages': ['  verification of content failed'], 'file': 'readme.docx'} 
[ERROR  ] verification of content failed [get(/tmp/atj3/readme.docx)] 
get(error): /tmp/atj3/readme.docx (file) [verification of content failed]
[DEBUG  ] could not perform all requested actions: Command did not complete successfully. 1 failed:
[{'action': 'get',
  'annexkey': 'MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx',
  'message': 'verification of content failed',
  'path': '/tmp/atj3/readme.docx',
  'refds': '/tmp/atj3',
  'status': 'error',
  'type': 'file'}] [utils.py:generator_func:469] 
```

**Comment by bpoldrack** [comment] 2020-10-13 08:02
Looking at it, `download_url` seems to generate output:

> [INFO] Downloading 'https://archive.ds.inm7.de/00e/0c610-0f27-41bb-9626-157ec8815bfe/annex/objects/xk/vw/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx' into '.git/annex/tmp/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx'
> [INFO] http session: Authenticating into session for https://archive.ds.inm7.de/00e/0c610-0f27-41bb-9626-157ec8815bfe/annex/objects/xk/vw/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx 

I suspect this is spitting into stdout of the special remote, which is why I find it strange that it works with plain annex. However, I suspect that you can see the failure using `git annex get --json --json-error-messages`, too.

**Comment by mih** [comment] 2020-10-13 08:06
No failure:

```
% git -C atj3 annex get --json --json-error-messages readme.docx
[INFO] Downloading 'https://archive.ds.inm7.de/00e/0c610-0f27-41bb-9626-157ec8815bfe/annex/objects/xk/vw/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx' into '.git/annex/tmp/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx' 
[INFO] http session: Authenticating into session for https://archive.ds.inm7.de/00e/0c610-0f27-41bb-9626-157ec8815bfe/annex/objects/xk/vw/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx 
{"command":"get","note":"from inm7-storage...\nchecksum...","success":true,"key":"MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx","error-messages":[],"file":"readme.docx"}
```

**Comment by bpoldrack** [comment] 2020-10-13 08:08
That's weird. This never worked for me, when I tried to use logging from within a special remote.

**Comment by bpoldrack** [comment] 2020-10-13 10:42
Just to keep a record here rather than a disconnected chat only:

Tried to reproduce and succeeded. However, the issue seems very different.
Running git-annex get succeeds, and it's output suggests it's using your implementation:

```
[snip]
[2020-10-13 12:29:29.33674072] git-annex-remote-ora[1] <-- VALUE inm7-storage
[2020-10-13 12:29:29.33690246] git-annex-remote-ora[1] --> GETCONFIG url
[2020-10-13 12:29:29.33697212] git-annex-remote-ora[1] <-- VALUE ria+https://archive.ds.inm7.de
[2020-10-13 12:29:29.357810705] git-annex-remote-ora[1] --> GETCONFIG archive-id
[2020-10-13 12:29:29.358018325] git-annex-remote-ora[1] <-- VALUE 00e0c610-0f27-41bb-9626-157ec8815bfe
[2020-10-13 12:29:29.358174024] git-annex-remote-ora[1] --> GETCONFIG force-write
[2020-10-13 12:29:29.358248904] git-annex-remote-ora[1] <-- VALUE 
[2020-10-13 12:29:29.358425934] git-annex-remote-ora[1] --> PREPARE-SUCCESS
[2020-10-13 12:29:29.358502264] git-annex-remote-ora[1] <-- TRANSFER RETRIEVE MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx .git/annex/tmp/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx
[2020-10-13 12:29:29.358683504] git-annex-remote-ora[1] --> DIRHASH MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx
[2020-10-13 12:29:29.358799393] git-annex-remote-ora[1] <-- VALUE xk/vw/
[INFO] Downloading 'https://archive.ds.inm7.de/00e/0c610-0f27-41bb-9626-157ec8815bfe/annex/objects/xk/vw/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx' into '.git/annex/tmp/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx' 
[INFO] http session: Authenticating into session for https://archive.ds.inm7.de/00e/0c610-0f27-41bb-9626-157ec8815bfe/annex/objects/xk/vw/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx 
[2020-10-13 12:29:29.953334151] git-annex-remote-ora[1] --> TRANSFER-SUCCESS RETRIEVE MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx
(checksum...) ok
[snip]
```

The failing datalad-get, however, looks like this:
```
[snip]
 [2020-10-13 12:27:40.118875438] git-annex-remote-ora[1] <-- VALUE inm7-storage
| [2020-10-13 12:27:40.119079678] git-annex-remote-ora[1] --> GETCONFIG url
| [2020-10-13 12:27:40.119204618] git-annex-remote-ora[1] <-- VALUE ria+https://archive.ds.inm7.de
| [2020-10-13 12:27:40.138628256] git-annex-remote-ora[1] --> GETCONFIG archive-id
| [2020-10-13 12:27:40.138817076] git-annex-remote-ora[1] <-- VALUE 00e0c610-0f27-41bb-9626-157ec8815bfe
| [2020-10-13 12:27:40.138954615] git-annex-remote-ora[1] --> GETCONFIG force-write
| [2020-10-13 12:27:40.139010185] git-annex-remote-ora[1] <-- VALUE 
| [2020-10-13 12:27:40.139171115] git-annex-remote-ora[1] --> PREPARE-SUCCESS
| [2020-10-13 12:27:40.139231875] git-annex-remote-ora[1] <-- TRANSFER RETRIEVE MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx .git/annex/tmp/MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx
| [2020-10-13 12:27:40.139463265] git-annex-remote-ora[1] --> DIRHASH MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx
| [2020-10-13 12:27:40.139643904] git-annex-remote-ora[1] <-- VALUE xk/vw/
| [2020-10-13 12:27:40.163231866] git-annex-remote-ora[1] --> PROGRESS 381
| [2020-10-13 12:27:40.165319233] git-annex-remote-ora[1] --> TRANSFER-SUCCESS RETRIEVE MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx
| [2020-10-13 12:27:40.195253014] process done ExitSuccess
| [2020-10-13 12:27:40.195901532] process done ExitSuccess
| [2020-10-13 12:27:40.196278212] process done ExitSuccess
| git-annex: get: 1 failed'] 
[WARNING] Running get resulted in stderr output: [2020-10-13 12:27:39.901007994] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.dotfiles=true","-c","annex.retry=3","symbolic-ref","-q","HEAD"]
[2020-10-13 12:27:39.90386661] process done ExitSuccess
[2020-10-13 12:27:39.903953449] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.dotfiles=true","-c","annex.retry=3","show-ref","refs/heads/master"]
[2020-10-13 12:27:39.907386534] process done ExitSuccess
[2020-10-13 12:27:39.907510634] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.dotfiles=true","-c","annex.retry=3","ls-files","--cached","-z","--","readme.docx"]
[2020-10-13 12:27:39.921307241] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.dotfiles=true","-c","annex.retry=3","show-ref","git-annex"]
[2020-10-13 12:27:39.926792332] process done ExitSuccess
[2020-10-13 12:27:39.926872362] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.dotfi... 
[DEBUG  ] received JSON result from annex: {'command': 'get', 'wanted': [{'here': False, 'uuid': '4440db2d-7f87-46a7-bd14-8e4dbab9c799', 'description': '[inm7-storage]'}], 'note': 'from inm7-storage...\nUnable to access these remotes: inm7-storage\nTry making some of these repositories available:\n\t4440db2d-7f87-46a7-bd14-8e4dbab9c799 -- [inm7-storage]\n\n(Note that these git remotes have annex-ignore set: origin)', 'skipped': [], 'success': False, 'key': 'MD5E-s12060--9a9019561007e616e328cd15e87863a3.docx', 'error-messages': ['  verification of content failed'], 'file': 'readme.docx'} 
[ERROR  ] verification of content failed [get(/home/bpoldrack/atj3/readme.docx)] 
[snip]
```

Note, that there's a `PROGRESS` message from the special remote that shouldn't be there after your change and that there's no logging from `download_url`. To me it seems datalad is using the wrong special remote implementation (system installation rather than venv).

**Comment by bpoldrack** [comment] 2020-10-13 10:59
Confirmed. Just missed that part in the log:

```
 [2020-10-13 12:51:19.576643107] chat: /usr/bin/git-annex-remote-ora []
```

So, something (likely runner related) leads to the wrong env for git-annex to be called in, when invoked via datalad-get.

**Comment by kyleam** [comment] 2020-10-30 19:02
Closed by gh-5026.

**Closed by kyleam** 2020-10-30 19:02 UTC
