### ISSUE TITLE
Windows: datalad-archives special remote issues

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#5015] opened 2020-10-11 18:49 UTC
When adding content to a datalad-archives special remote, the process hangs for hours (so far, without any outcome). ~The debug output also displays some funkily messed up paths~:

```bash
# create a dataset
(base) C:\Users\datalad\testing>datalad create anotherone
[INFO] Creating a new annex repo at C:\Users\datalad\testing\anotherone
[INFO] Detected a filesystem without fifo support.
[INFO] Disabling ssh connection caching.
[INFO] Detected a crippled filesystem.
[INFO] Scanning for unlocked files (this may take some time)
[INFO] Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.
[INFO] Switched to branch 'adjusted/master(unlocked)'
create(ok): C:\Users\datalad\testing\anotherone (dataset)

(base) C:\Users\datalad\testing>cd anotherone
# create a zip archive
(base) C:\Users\datalad\testing\anotherone>7z a -tzip files.zip ../file1 ../file2
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
Scanning the drive:
2 files, 31 bytes (1 KiB)
Creating archive: files.zip
Add new data to archive: 2 files, 31 bytes (1 KiB)
Files read from disk: 2
Archive size: 297 bytes (1 KiB)
Everything is Ok

# save the archive
(base) C:\Users\datalad\testing\anotherone>datalad save
add(ok): C:\Users\datalad\testing\anotherone\files.zip (file)
save(ok): C:\Users\datalad\testing\anotherone (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)

# call add-archive-content
(base) C:\Users\datalad\testing\anotherone>datalad -l debug add-archive-content files.zip
[DEBUG] Command line args 1st pass. Parsed: Namespace() Unparsed: ['add-archive-content', 'files.zip']
[DEBUG] Discovering plugins
[DEBUG] Building doc for <class 'datalad.interface.add_archive_content.AddArchiveContent'>
[DEBUG] Parsing known args among ['C:\\Users\\datalad\\miniconda3\\Scripts\\datalad', '-l', 'debug', 'add-archive-content', 'files.zip']
[DEBUG] Query status of AnnexRepo('C:\\Users\\datalad\\testing\\anotherone') for all paths
[DEBUG] AnnexRepo("C:\Users\datalad\testing\anotherone").get_content_info(...)
[DEBUG] Query repo: ['git', 'ls-files', '--stage', '-z', '-d', '-m', '--exclude-standard', '-o']
[DEBUG] Done query repo: ['git', 'ls-files', '--stage', '-z', '-d', '-m', '--exclude-standard', '-o']
[DEBUG] Done AnnexRepo("C:\Users\datalad\testing\anotherone").get_content_info(...)
[DEBUG] AnnexRepo("C:\Users\datalad\testing\anotherone").get_content_info(...)
[DEBUG] Query repo: ['git', 'ls-tree', 'HEAD', '-z', '-r', '--full-tree', '-l']
[DEBUG] Done query repo: ['git', 'ls-tree', 'HEAD', '-z', '-r', '--full-tree', '-l']
[DEBUG] Done AnnexRepo("C:\Users\datalad\testing\anotherone").get_content_info(...)
[DEBUG] Process file list chunk 0 (length 1)
[DEBUG] Async run ['git', 'annex', 'lookupkey', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', '--', 'files.zip']
[DEBUG] Launching process ['git', 'annex', 'lookupkey', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', '--', 'files.zip']
[DEBUG] Process 7632 started
[DEBUG] Waiting for process 7632 to complete
[DEBUG] Process 7632 exited with return code 0
[DEBUG] Async run ['git', 'annex', 'contentlocation', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', 'MD5E-s297--d13aea6f91275a01cd774e750889c075.zip']
[DEBUG] Launching process ['git', 'annex', 'contentlocation', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', 'MD5E-s297--d13aea6f91275a01cd774e750889c075.zip']
[DEBUG] Process 5088 started
[DEBUG] Waiting for process 5088 to complete
[DEBUG] Process 5088 exited with return code 0
[INFO] Adding content of the archive files.zip into annex AnnexRepo("C:\Users\datalad\testing\anotherone")
[DEBUG] Initiating clean cache for the archives under C:\Users\datalad\testing\anotherone\.git\datalad\tmp\archives
[DEBUG] Cache initialized
[DEBUG] Cached directory for archive C:\Users\datalad\testing\anotherone\.git\annex\objects\100\188\MD5E-s297--d13aea6f91275a01cd774e750889c075.zip\MD5E-s297--d13aea6f91275a01cd774e750889c075.zip is 22f0104991
[INFO] Initiating special remote datalad-archives
[DEBUG] Async run ['git', 'annex', 'initremote', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', 'datalad-archives', 'encryption=none', 'type=external', 'autoenable=true', 'externaltype=datalad-archives', 'uuid=c04eb54b-4b4e-5755-8436-866b043170fa']
[DEBUG] Launching process ['git', 'annex', 'initremote', '-c', 'annex.dotfiles=true', '-c', 'annex.retry=3', 'datalad-archives', 'encryption=none', 'type=external', 'autoenable=true', 'externaltype=datalad-archives', 'uuid=c04eb54b-4b4e-5755-8436-866b043170fa']
[DEBUG] Process 11220 started
[DEBUG] Waiting for process 11220 to complete
[DEBUG] Process 11220 exited with return code 0
[DEBUG] Acquiring a lock C:\Users\datalad\testing\anotherone\.git\datalad\tmp\archives\22f0104991.extract-lck
[DEBUG] Acquired? lock C:\Users\datalad\testing\anotherone\.git\datalad\tmp\archives\22f0104991.extract-lck: True
[DEBUG] Extracting C:\Users\datalad\testing\anotherone\.git\annex\objects\100\188\MD5E-s297--d13aea6f91275a01cd774e750889c075.zip\MD5E-s297--d13aea6f91275a01cd774e750889c075.zip under C:\Users\datalad\testing\anotherone\.git\datalad\tmp\archives\22f0104991
[DEBUG] Releasing lock C:\Users\datalad\testing\anotherone\.git\datalad\tmp\archives\22f0104991.extract-lck
[DEBUG] Adding C:\Users\datalad\testing\anotherone\file1 to annex pointing to dl+archive:MD5E-s297--d13aea6f91275a01cd774e750889c075.zip#path=file1&size=9 and with options None
##### this one is messed up ########
[DEBUG] Initiating a new process for BatchedAnnex(cmd=<<['git', 'annex++70 chars++ch']>>, output_proc=<function>, path=<<'C:\\Users\\da++23 chars++one'>>)
[DEBUG] Adding C:\Users\datalad\testing\anotherone\file2 to annex pointing to dl+archive:MD5E-s297--d13aea6f91275a01cd774e750889c075.zip#path=file2&size=22 and with options None
[INFO] Finished adding files.zip: Files processed: 2, +annex: 2
[DEBUG] Closing stderr of <subprocess.Popen object at 0x00000159BFD47C40>
[DEBUG] Closing stdin of <subprocess.Popen object at 0x00000159BFD47C40> and waiting process to finish
```

it is stuck here, for as long as 4 hours so far.

**Comment by mih** [comment] 2020-10-12 05:04
If, with messed paths, you are talking about this `path=<<'C:\\Users\\da++23 chars++one'>>` -- I think that is intentionally done to make the output shorter. Although one could question the utility of the shortened output, indeed.

**Comment by mih** [comment] 2020-10-12 05:06
Ping #5013

**Comment by yarikoptic** [comment] 2020-10-12 18:09
Adina -- is there a way for some minimal reproducer or it is due to this specific archive which cannot be re-shared?  It seems to be the released datalad version, could you try with `master`?

**Comment by adswa** [comment] 2020-10-12 18:17
In the code above, I'm zipping two files I have echoed something along the lines of "12345" into. Originally, I observed it with the [imagenette dataset (i.e., the example from that DVC tutorial)](http://handbook.datalad.org/en/latest/beyond_basics/101-168-dvc.html#setup), and I also tried with a random subset of files from that larger archive.
I *think* I ran this on top of master and 0.13.4, but let me take a look and try again, just to make sure.

**Comment by adswa** [comment] 2020-10-12 18:40
This takes longer than I thought, sorry. I forgot that Windows doesn't clean up temp files, and even after restarting, the add-archive-content won't run twice because of errors like this:
```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\datalad\\AppData\\Local\\Temp\\tmp9sqg9swt'
```
(grrr... installing CCleaner...)

**Comment by adswa** [comment] 2020-10-12 19:17
Ah, Windows joys. I have to return to this tomorrow. The computer is one strike, and I can't pinpoint where it is coming from at this time of the day. Permission denied errors despite cleaned temp directories all over the place, and previously working clone commands not working anymore.

But: Yesterdays attempts must have all been on master, since I needed to be on top of my changes in #5001 for anything with git-annex to function at all.

**Comment by adswa** [comment] 2020-10-13 06:17
Something is a bit fishy here. On first sight, it seems as if ``add-archive-content`` not only fails, but it leaves behind running processes that hold temp files hostage (leading to the permission denied errors I pasted above). I'm trying to find out what is happening, but it is a bit cumbersome - even after ctrl-c'ing I need to close git, git-annex, and git-annex-datalad-archives processes via the task manager, clean out temp files by hand, and restart?? (haven't figured it out yet) to observe the actual error and not the "Permission denied" errors on the temp files held hostage by running processes. I'll add bits and pieces into this comment.

System setup:
<details><summary>WTF</summary>

```
(base) C:\Users\datalad>datalad wtf
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - Windows WinVaultKeyring
      - Windows RegistryKeyring
      - EncryptedKeyring with not defined v.1.0 at C:\Users\datalad\AppData\Local\Python Keyring\wincrypto_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at C:\Users\datalad\AppData\Local\Python Keyring\keyring_pass.cfg
    - config_file: C:\Users\datalad\.config\python_keyring\keyringrc.cfg
    - data_root: C:\Users\datalad\AppData\Local\Python Keyring
## datalad
  - full_version: 0.13.4.dev245-gd3f0
  - version: 0.13.4.dev245
## dependencies
  - annexremote: 1.4.3
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 19.00
  - cmd:annex: 8.20200815-g335aae266
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.28.0.windows.1
  - cmd:system-git: 2.28.0.windows.1
  - cmd:system-ssh: for
  - humanize: 3.0.1
  - iso8601: 0.1.13
  - keyring: 21.4.0
  - keyrings.alt: 4.0.0
  - msgpack: 1.0.0
  - requests: 2.23.0
  - wrapt: 1.12.1
## environment
  - PATH: C:\Users\datalad\miniconda3;C:\Users\datalad\miniconda3\Library\mingw-w64\bin;C:\Users\datalad\miniconda3\Library\usr\bin;C:\Users\datalad\miniconda3\Library\bin;C:\Users\datalad\miniconda3\Scripts;C:\Users\datalad\miniconda3\bin;C:\Users\datalad\miniconda3\condabin;.;C:\Users\datalad\miniconda3\Library\ImageMagick-7.0.10-Q16-HDRI;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Users\datalad\AppData\Local\Microsoft\WindowsApps;C:\ProgramFiles\7-Zip;.
## extensions
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - TorrentParser
    - Feeds
    - Testsuite
  - dependency versions:
    - aws-0.21.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.4
    - feed-1.2.0.1
    - ghc-8.6.5
    - http-client-0.5.14
    - persistent-sqlite-2.9.3
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0.1
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: mingw32 x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions:
    - 8
  - upgrade supported from repository versions:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200815-g335aae266
## location
  - path: C:\Users\datalad
  - type: directory
## metadata_extractors
  - annex:
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio:
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite:
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif:
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage:
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image:
    - load_error: No module named 'PIL' [image.py:<module>:16]
    - module: datalad.metadata.extractors.image
  - xmp:
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python
  - implementation: CPython
  - version: 3.8.3
## system
  - distribution: msys_nt-10.0/2.5.0  10/10.0.19041/SP0/Multiprocessor Free
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp1252
  - max_path_length: 259
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.19041
```
</details>

<details><summary> How I create a minimal zip archive and dataset </summary>

```

(base) C:\Users\datalad>echo "here is content of one file" > thefirstfile
(base) C:\Users\datalad>echo "here is content of the second file" > thesecondfile
## zip everything
(base) C:\Users\datalad>7z a -tzip thearchive.zip thefirstfile thesecondfile

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive:
2 files, 71 bytes (1 KiB)

Creating archive: thearchive.zip

Add new data to archive: 2 files, 71 bytes (1 KiB)


Files read from disk: 2
Archive size: 367 bytes (1 KiB)
Everything is Ok

## create a new dataset
(base) C:\Users\datalad>datalad create testingarchive && cd testingarchive
[INFO] Creating a new annex repo at C:\Users\datalad\testingarchive
[INFO] Detected a filesystem without fifo support.
[INFO] Disabling ssh connection caching.
[INFO] Detected a crippled filesystem.
[INFO] Scanning for unlocked files (this may take some time)
[INFO] Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.
[INFO] Switched to branch 'adjusted/master(unlocked)'
create(ok): C:\Users\datalad\testingarchive (dataset)

## save the archive to the dataset
(base) C:\Users\datalad\testingarchive>cp ../thearchive.zip . && datalad save -m "Added the archive"
add(ok): C:\Users\datalad\testingarchive\thearchive.zip (file)
save(ok): C:\Users\datalad\testingarchive (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
```
</details>

Here is what happens after I
- CCcleaned my computer
- closed all git/datalad/git-annex related processes in the task manager
- removed all temp files in `C:\\Users\datalad\AppData\Local\Temp`

Here is how  `C:\\Users\datalad\AppData\Local\Temp` looks before I run `datalad-add-archive-content`:
<img width="490" alt="notempfiles" src="https://user-images.githubusercontent.com/29738718/95822063-81f4f000-0d2b-11eb-92b2-4abe027f5495.png">

When adding the archive, a new temp file is created, but a process seems to use it while another one tries, too:

```

(base) C:\Users\datalad\testingarchive>datalad add-archive-content thearchive.zip
[INFO] Adding content of the archive thearchive.zip into annex AnnexRepo("C:\Users\datalad\testingarchive")
[INFO] Initiating special remote datalad-archives
[INFO] Finished adding thearchive.zip: Files processed: 2, +annex: 2
[WARNING] Caught Command '['git', 'annex', 'addurl', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1360] on trial #1. Sleeping 1.000000 and retrying
[WARNING] Caught Command '['git', 'annex', 'addurl', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1360] on trial #2. Sleeping 1.000000 and retrying
[WARNING] Batched process <subprocess.Popen object at 0x0000019A98776E20> did not finish, abandoning it without killing it
[ERROR] [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\datalad\\AppData\\Local\\Temp\\tmpyemni2gl' [utils.py:unlink:2030] (PermissionError)
Exception ignored in: <finalize object at 0x19a983f6ba0; dead>
Traceback (most recent call last):
  File "C:\Users\datalad\miniconda3\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "c:\users\datalad\repos\datalad\datalad\support\annexrepo.py", line 391, in _cleanup
    batched.close()
  File "c:\users\datalad\repos\datalad\datalad\support\annexrepo.py", line 3609, in close
    p.close()
  File "c:\users\datalad\repos\datalad\datalad\cmd.py", line 1385, in close
    unlink(self._stderr_out_fname)
  File "c:\users\datalad\repos\datalad\datalad\utils.py", line 2000, in _wrap_try_multiple_dec
    return f(*args, **kwargs)
  File "c:\users\datalad\repos\datalad\datalad\utils.py", line 2030, in unlink
    return os.unlink(f)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\datalad\\AppData\\Local\\Temp\\tmpyemni2gl'
Exception ignored in: <function SafeDelCloseMixin.__del__ at 0x0000019A97C62C10>
Traceback (most recent call last):
  File "c:\users\datalad\repos\datalad\datalad\cmd.py", line 1193, in __del__
    self.close()
  File "c:\users\datalad\repos\datalad\datalad\support\annexrepo.py", line 3609, in close
    p.close()
  File "c:\users\datalad\repos\datalad\datalad\cmd.py", line 1385, in close
    unlink(self._stderr_out_fname)
  File "c:\users\datalad\repos\datalad\datalad\utils.py", line 2000, in _wrap_try_multiple_dec
    return f(*args, **kwargs)
  File "c:\users\datalad\repos\datalad\datalad\utils.py", line 2030, in unlink
    return os.unlink(f)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\datalad\\AppData\\Local\\Temp\\tmpyemni2gl'
Exception ignored in: <function SafeDelCloseMixin.__del__ at 0x0000019A97C62C10>
Traceback (most recent call last):
  File "c:\users\datalad\repos\datalad\datalad\cmd.py", line 1193, in __del__
    self.close()
  File "c:\users\datalad\repos\datalad\datalad\cmd.py", line 1385, in close
    unlink(self._stderr_out_fname)
  File "c:\users\datalad\repos\datalad\datalad\utils.py", line 2000, in _wrap_try_multiple_dec
    return f(*args, **kwargs)
  File "c:\users\datalad\repos\datalad\datalad\utils.py", line 2030, in unlink
    return os.unlink(f)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\datalad\\AppData\\Local\\Temp\\tmpyemni2gl'
```

This is how  `C:\\Users\datalad\AppData\Local\Temp` looks afterwards:

<img width="478" alt="suddendlytempfiles" src="https://user-images.githubusercontent.com/29738718/95822309-f29c0c80-0d2b-11eb-8025-77343ddd4873.png">

And even though the command exited, the task manager reports that a range of processes involved in ``add-archive-content`` are sill up and running.

<img width="746" alt="taskmanager" src="https://user-images.githubusercontent.com/29738718/95822550-6e965480-0d2c-11eb-909b-5a2661356866.png">

**Comment by adswa** [comment] 2020-10-14 11:26
Additional observation: Removing any of the datasets I have tried to add archive content to is either not working or incredibly slow. Here is the debug log of a removal that I started 20 minutes ago:

```
(base) C:\Users\datalad\testing>datalad -l debug remove -d anotherone
[DEBUG] Command line args 1st pass for DataLad 0.13.4.dev271-gf60b-dirty. Parsed: Namespace() Unparsed: ['remove', '-d', 'anotherone']
[DEBUG] Discovering plugins
[DEBUG] Building doc for <class 'datalad.interface.annotate_paths.AnnotatePaths'>
[DEBUG] Building doc for <class 'datalad.core.local.status.Status'>
[DEBUG] Building doc for <class 'datalad.core.local.save.Save'>
[DEBUG] Building doc for <class 'datalad.distribution.drop.Drop'>
[DEBUG] Building doc for <class 'datalad.local.subdatasets.Subdatasets'>
[DEBUG] Building doc for <class 'datalad.distribution.uninstall.Uninstall'>
[DEBUG] Building doc for <class 'datalad.distribution.remove.Remove'>
[DEBUG] Parsing known args among ['C:\\Users\\datalad\\miniconda3\\Scripts\\datalad', '-l', 'debug', 'remove', '-d', 'anotherone']
[DEBUG] Async run ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin']
[DEBUG] Launching process ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin']
[DEBUG] Process 10344 started
[DEBUG] Waiting for process 10344 to complete
[DEBUG] Process 10344 exited with return code 0
[DEBUG] Determined class of decorated function: <class 'datalad.distribution.remove.Remove'>
[DEBUG] Async run ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin']
[DEBUG] Launching process ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin']
[DEBUG] Process 2536 started
[DEBUG] Waiting for process 2536 to complete
[DEBUG] Process 2536 exited with return code 0
[DEBUG] Async run ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG] Launching process ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG] Process 10972 started
[DEBUG] Waiting for process 10972 to complete
[DEBUG] Process 10972 exited with return code 0
[DEBUG] Async run ['git', 'config', '-z', '-l', '--show-origin', '--file', 'C:\\Users\\datalad\\testing\\anotherone\\.datalad\\config']
[DEBUG] Launching process ['git', 'config', '-z', '-l', '--show-origin', '--file', 'C:\\Users\\datalad\\testing\\anotherone\\.datalad\\config']
[DEBUG] Process 7816 started
[DEBUG] Waiting for process 7816 to complete
[DEBUG] Process 7816 exited with return code 0
[DEBUG] Determined class of decorated function: <class 'datalad.interface.annotate_paths.AnnotatePaths'>
[DEBUG] Async run ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG] Launching process ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG] Process 8860 started
[DEBUG] Waiting for process 8860 to complete
[DEBUG] Process 8860 exited with return code 0
[DEBUG] Async run ['git', 'config', '-z', '-l', '--show-origin', '--file', 'C:\\Users\\datalad\\testing\\anotherone\\.datalad\\config']
[DEBUG] Launching process ['git', 'config', '-z', '-l', '--show-origin', '--file', 'C:\\Users\\datalad\\testing\\anotherone\\.datalad\\config']
[DEBUG] Process 7528 started
[DEBUG] Waiting for process 7528 to complete
[DEBUG] Process 7528 exited with return code 0
[DEBUG] Async run ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG] Launching process ['git', 'config', '-z', '-l', '--show-origin']
[DEBUG] Process 11152 started
[DEBUG] Waiting for process 11152 to complete
[DEBUG] Process 11152 exited with return code 0
[DEBUG] Async run ['git', 'config', '-z', '-l', '--show-origin', '--file', 'C:\\Users\\datalad\\testing\\anotherone\\.datalad\\config']
[DEBUG] Launching process ['git', 'config', '-z', '-l', '--show-origin', '--file', 'C:\\Users\\datalad\\testing\\anotherone\\.datalad\\config']
[DEBUG] Process 7740 started
[DEBUG] Waiting for process 7740 to complete
[DEBUG] Process 7740 exited with return code 0
[DEBUG] Async run ['git', 'annex', 'version', '--raw']
[DEBUG] Launching process ['git', 'annex', 'version', '--raw']
[DEBUG] Process 2700 started
[DEBUG] Waiting for process 2700 to complete
[DEBUG] Process 2700 exited with return code 0
[DEBUG] Process file list chunk 0 (length 1)

[doesn't do anything]
```

**Comment by yarikoptic** [comment] 2020-10-14 13:12
re "stall" and "slow" -- `py-spy top -p PID` might be of great help to discover "what the heck it is doing ATM" at least at the level of datalad (if it does not produce any logging even with `-l 2` ;)).

Re "cannot remove file", since there is "abandon batched process" and we know that it is slow there, please try running with #5013 -- it will not abandon batched process, and will wait or it to complete (howlong it takes) -- will it eventually finish then?

**Comment by adswa** [comment] 2020-10-14 13:58
will try that - thx!

**Comment by adswa** [comment] 2020-10-14 15:15
I forgot that I can't put a pdb trace into a special remote :( do you have a tip on how I can listen more closely to the special remote? 

Btw: on top of #5013 the git-annex/datalad-archives-special-remote process at least seems to close after failing - I'm not observing "Permission denied errors" when restarting.

**Comment by yarikoptic** [comment] 2020-10-14 17:33
Quick one: Either it just used to work as is or I did some additional magic to prevent epdb printing when starting to serve, but you could try to epdb (instructions in contributing.md file)

But otherwise just DATALAD_LOG_LEVEL=2 DATALAD_LOG_TARGET=/filename and check that log, add more log debug lines into code if needed. Depending on the issue enabling protocoling of the remote could help, check that contributing file for envvar

**Comment by yarikoptic** [comment] 2020-10-15 13:09
> that line is l = self.fin.readline().rstrip(os.linesep), -- we seem to be stuck reading a message from git-annex?

yes

**Comment by yarikoptic** [comment] 2020-10-15 15:34
FWIW: on my attempt, seems somehow boiling down to `AnnexRepo.add` not adding, although `annex add` failing, no error is raised, proceeding to `git.commit(filename` which then blows since file was not yet `git add`ed  .  Here is a screenshot with log on the left (do not know which line from main process or special remote -- should have added PID) and some traceback on the right

![image](https://user-images.githubusercontent.com/39889/96151696-b6a6aa00-0ed9-11eb-9eee-e18abb34cdad.png)

when I just went to that directory (I kept TEMP directories) and issued exactly the same command, it worked and staged that file

will try to check later how come we let CommandError "slip through"

PS this is with 7za from conda `ln -s`ed as `7z`

**Comment by yarikoptic** [comment] 2020-10-15 16:18
new revelations from digging deeper (not yet acted upon)

## annex fail
```
{920}[Level 5] CommandError: '"git" "annex" "add" "-c" "annex.dotfiles=true" "-c" "annex.retry=3" "--json" "--json-error-messages" "--debug" "--" "file.dat"' failed with exitcode 1 under C:\Users\DataLad\AppData\Local\Temp\datalad_temp_tree_q4wxn05d [out: '{"command":"add","success":false,"error-messages":["  file.dat failed to link to annex"],"file":"file.dat"}'] [err: '[2020-10-15 11:57:07.4657537] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.dotfiles=true","-c","annex.retry=3","show-ref","git-annex"]
| [2020-10-15 11:57:07.4813787] process done ExitSuccess
| [2020-10-15 11:57:07.4813787] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.dotfiles=true","-c","annex.retry=3","show-ref","--hash","refs/heads/git-annex"]
...
| [2020-10-15 11:57:07.6376287] call: cp ["--reflink=auto","-a","file.dat",".git\\annex\\objects\\6f0\\fbd\\SHA256E-s7--ed7002b439e9ac845f22357d822bac1444730fbdb6016d3ec9432297b9ec9f73.dat\\SHA256E-s7--ed7002b439e9ac845f22357d822bac1444730fbdb6016d3ec9432297b9ec9f73.dat"]
| "cp": unrecognized option `--reflink=auto'
| Try `"cp" --help' for more information.
| [2020-10-15 11:57:07.6532537] process done ExitFailure 1
``` 

```
C:\tmp>cp --help | grep ref
  -d                           same as --no-dereference --preserve=link
  -L, --dereference            always follow symbolic links
  -P, --no-dereference         never follow symbolic links

C:\tmp>cp --version
cp (GNU coreutils) 5.97
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund, David MacKenzie, and Jim Meyering.

C:\tmp>git annex version
git-annex version: 8.20200815-g335aae266
build flags: Assistant Webapp Pairing S3 WebDAV TorrentParser Feeds Testsuite
dependency versions: aws-0.21.1 bloomfilter-2.0.1.0 cryptonite-0.25 DAV-1.3.4 feed-1.2.0.1 ghc-8.6.5 http-client-0.5.14
persistent-sqlite-2.9.3 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.0.1
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SH
A3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512
BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLA
KE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM UR
L X*
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs hook external
operating system: mingw32 x86_64
supported repository versions: 8
upgrade supported from repository versions: 2 3 4 5 6 7
```
so -- `cp` on Windows has no `--reflink` option, that causes internal git-annex error.  Probably annex should check on version of `cp` to decide to consider adding `reflink`

TODO: see when was added and report to joeyh


## not raising

```
            # in a more general way:
            # first check stdout:
            if all([line.startswith('{') and line.endswith('}')
                    for line in e.stdout.splitlines()]):
                # we have the usual json output on stdout. Therefore we can
                # probably return and don't need to raise; so get stdout
                # for json loading:
                out = e.stdout
            else:
                out = None
```
and we do have
```
(Pdb) p e.stdout
'{"command":"add","success":false,"error-messages":["  file.dat failed to link to annex"],"file":"file.dat"}\r\n'
```
and thus
```
(Pdb) p out
'{"command":"add","success":false,"error-messages":["  file.dat failed to link to annex"],"file":"file.dat"}\r\n'
```
but we do not analyze it for `success` and just let it return instead of reraising.

TODO: old code, so we should "thread carefully" but I feel that we do need to analyze those records since we do parse them and then (re-)raise exception in case of `.add` (and possible many other directly used Repo.method) failing... I guess there was an RF to make those deep methods to just yield records instead of raising exceptions, but we still have around 60 direct invocations of `.repo.add(` alone throughout the code and tests where they do not take care about processing those results, so any of those points would just "progress forward" and lead to confusing failures (or just incorrect operation) later

**Comment by adswa** [comment] 2020-10-15 16:48
Oh cool, you found it! This was an infuriating black box for me!

**Comment by yarikoptic** [comment] 2020-10-15 16:56
it remains a black box for me too ;-)

**Comment by yarikoptic** [comment] 2020-10-15 16:59
Re `cp` -- apparently "it is not new to me": https://github.com/conda-forge/coreutils-feedstock/issues/8  .  So -- there is no newer coreutils for windows from conda-forge, so we need a fix in git-annex

**Comment by yarikoptic** [comment] 2020-10-16 01:44
@adswa what is `cp --version` in your windows environment?  and if you are in bash, what is output of `which cp`?

**Comment by adswa** [comment] 2020-10-16 05:59
I got 
```
>cp --version
cp (GNU coreutils) 8.25
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbj"orn Granlund, David MacKenzie, and Jim Meyering.
```

and 

```
datalad@latitude-e7440  /c/Users/datalad/testing/blablabla
$ which cp
/usr/bin/cp
```

However (sorry, only looked at it in detail now) my cp *has* a ``reflink`` option. I got it via conda's ``m2base`` package, which has all coreutils: https://www.oliversherouse.com/2017/01/03/unix-anaconda-m2.html
So maybe there are more problems than just cp. I will try to look as deep as you did to see what happens on my computer.

**Comment by yarikoptic** [comment] 2020-10-16 11:45
Yeap, reflink is there from version 8. Second issue might still be pertinent to your case. I will try with that cp later today as well

**Comment by yarikoptic** [comment] 2020-11-04 00:22
issues AFAIK fixed within very very recent git-annex and in #5119

**Closed by yarikoptic** 2020-11-04 00:22 UTC
Labels: windows

**Comment by adswa** [comment] 2020-11-04 06:13
thank you!!!
