### ISSUE TITLE
Crawling with datalad on public s3 bucket point to `addurl` error

### ISSUE THREAD

**Issue by htwangtw** [datalad/datalad#5427] opened 2021-02-19 11:31 UTC
Datalad version: 0.14.0
System distribution: debian/10.8
Python version: 3.7.3

I tried to crawl the enhanced NKI-Rockland sample with the instructions in [this post on Neurostars] (https://neurostars.org/t/how-to-crawl-with-datalad/2754) but it was unsuccessful. I also tried two other option.
The successful one isn't really doing what I want.

I was stuck with the following warning: 
```
$ datalad crawl-init --save --template=simple_s3 bucket=fcp-indi prefix=data/Projects/RocklandSample/RawDataBIDSLatest/ exclude=derivatives
$ datalad crawl
[WARNING] Caught AnnexBatchCommandError: 'addurl' [Error, annex reported failure for addurl (url='s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/.bidsignore?versionId=U2ydFcRBZRBGbEPlqI_LvizDj50Syp7j'): {'command': 'addurl', 'success': False, 'error-messages': [''], 'file': '.bidsignore'}] [annexrepo.py:add_url_to_file:2117] on trial #1. Sleeping 3.000000 and retrying 
```
If I use `add-urls`, I encounter the same `AnnexBatchCommandError`. The difference is that, instead of stuck with rerun attempts and labeled as __Warning__, it's just an error and the operation fails. 

Content of my `URL-FILE`:
```
bidsroot   subject   filename   ext
s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest   sub-A00010893   sub-A00010893_sessions   tsv
```
Command and trimmed output:
```
$ datalad -l debug addurls ../sub-A00010893_table.tsv '{bidsroot}' '{subject}/{filename}.{ext}'
...
[DEBUG  ] Adding URLs to sub-A00010893/ses-BAS1/func/sub-A00010893_ses-BAS1_task-CHECKERBOARD_acq-1400RR_bold.json in /home/user/projects/testds                                                                                                                                                  
[DEBUG  ] Initiating a new process for BatchedAnnex(cmd=<<['git', 'annex++70 chars++ch']>>, output_proc=<function>, path='/home/user/projects/testds')                                                                                                                                            
addurls(error): /home/user/projects/testds/sub-A00010893/ses-BAS1/func/sub-A00010893_ses-BAS1_task-CHECKERBOARD_acq-1400RR_bold.json (file) [AnnexBatchCommandError: 'addurl' [Error, annex reported failure for addurl (url='s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest'): {'command': 'addurl', 'success': False, 'error-messages': [''], 'file': 'sub-A00010893/ses-BAS1/func/sub-A00010893_ses-BAS1_task-CHECKERBOARD_acq-1400RR_bold.json'}] [annexrepo.py:add_url_to_file:2117]]
```

However, if I use `download-url` command on some files in the same bucket, I can download the file along with a confusing error message _after_ a successful download. Most important of all, I don't want to download all the files for data curation.
```
$ datalad -l debug download-url s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00010893/sub-A00010893_sessions.tsv .
...
[INFO   ] S3 session: Connecting to the bucket fcp-indi anonymously 
download_url(ok): /home/user/projects/testds/sub-A00010893_sessions.tsv (file)                                                                  
[DEBUG  ] Initializing default provider for  
[DEBUG  ] No dedicated provider, returning default one for : Provider(authenticator=None, credential=None, name='', url_res=['://.*']) 
download_url(error): /home/user/projects/testds/ (file) [Do not know how to handle url . for scheme . Known: dict_keys(['http', 'https', 'shub', 'ftp', 's3']) [providers.py:_get_downloader_class:125]]
```

If similar probelm has been addressed, please feel free to point me to the related discussion.
Thank you.

**Comment by kyleam** [comment] 2021-02-19 14:29
Thanks for the detailed issue.

[Just focusing on the `datalad addurls` error for the moment]

It looks like the constructed URL doesn't point to the individual file because it is set to just `{bidsroots}`.  (Note your url file and cli invocation disagree on the trailing 's'.)  So that ends up with a `git annex addurl` call like this:

```
$ git annex addurl --file test s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest
[INFO] S3 session: Connecting to the bucket fcp-indi anonymously 
addurl s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest 
  CHECKURL failed with no reason given
failed
git-annex: addurl: 1 failed
```

Here's a successful call with an individual file:

```
$ git annex addurl --file test s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00010893/sub-A00010893_sessions.tsv
[INFO] S3 session: Connecting to the bucket fcp-indi anonymously 
addurl s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00010893/sub-A00010893_sessions.tsv (from datalad) (to test) 
[INFO] Downloading 's3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00010893/sub-A00010893_sessions.tsv' into '.git/annex/tmp/URL-s196--s3&c%%fcp-indi%data%Projects%Roc-b633b388ebcf6c9847681b617c2e37d0' 
100%  196 B             2 KiB/s 0s[INFO] Successfully downloaded s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00010893/sub-A00010893_sessions.tsv into .git/annex/tmp/URL-s196--s3&c%%fcp-indi%data%Projects%Roc-b633b388ebcf6c9847681b617c2e37d0 
ok
(recording state in git...)
```

---

I'm not sure what the underlying problem is, or if it's the same across the different commands, but it's worth checking that you have the datalad special remote enabled:

```
$ git annex info | grep datalad
 	e0fa5203-ddb2-4a80-b551-b35cb750e2bf -- [datalad]
```

If it's not, you can enable it with

```
$ git annex initremote datalad type=external externaltype=datalad encryption=none
```

**Comment by yarikoptic** [comment] 2021-02-19 14:45
re `download-url` - remove trailing `.` (and that is what datalad complains about that it doesn't know how to download `.` ;)), to make it
```
datalad -l debug download-url s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00010893/sub-A00010893_sessions.tsv
```

**Comment by htwangtw** [comment] 2021-02-19 14:46
Thanks for your comment! 
>(Note your url file and cli invocation disagree on the trailing 's'.)

This is an error introduced when creating the issue. I have corrected it now. Thanks for pointing out!
However, without the typo the issue seem to be the same as use said, the URL passed to `git-annex` was not correctly constructed. Taking inspiration from this reply, I got a partial success after modifying the input to `addurls` like this:

original_path | bidsroot | subject | filename | ext
-- | -- | -- | -- | --
s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00010893/ses-BAS1/func/sub-A00010893_ses-BAS1_task-CHECKERBOARD_acq-1400RR_bold.json | s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest | sub-A00010893 | ses-BAS1/func/sub-A00010893_ses-BAS1_task-CHECKERBOARD_acq-1400RR_bold | json
```
datalad -l debug addurls ../sub-A00010893_table.tsv '{original_path}' '{subject}/{filename}.{ext}'
```
BIDS structure would be completely ignored from this one.

I think a the very least, the documentation of `addurls` can be improved?

**Comment by yarikoptic** [comment] 2021-02-19 14:54
re crawl etc -- (somehow the actual error didn't bubble up) the issue is that permissions on that file are not allowing for its download:

```
$> datalad download-url 's3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/.bidsignore?versionId=U2ydFcRBZRBGbEPlqI_LvizDj50Syp7j'
[INFO   ] Downloading 's3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/.bidsignore?versionId=U2ydFcRBZRBGbEPlqI_LvizDj50Syp7j' into '/tmp/' 
[INFO   ] S3 session: Connecting to the bucket fcp-indi anonymously 
download_url(error): /tmp/ (file) [S3 refused to provide the key for data/Projects/RocklandSample/RawDataBIDSLatest/.bidsignore from url s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/.bidsignore?versionId=U2ydFcRBZRBGbEPlqI_LvizDj50Syp7j: S3ResponseError: 403 Forbidden
 [s3.py:get_downloader_session:352]]
(dev3) 1 59191 ->1.....................................:Fri 19 Feb 2021 09:53:00 AM EST:.
lena:/tmp
$> datalad ls -aL 's3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/.bidsignore'                                      
Connecting to bucket: fcp-indi
[INFO   ] S3 session: Connecting to the bucket fcp-indi anonymously 
Bucket info:
  Versioning: S3ResponseError: 403 Forbidden
     Website: S3ResponseError: 403 Forbidden
         ACL: S3ResponseError: 403 Forbidden
data/Projects/RocklandSample/RawDataBIDSLatest/.bidsignore 2019-10-31T14:16:12.000Z 24 ver:U2ydFcRBZRBGbEPlqI_LvizDj50Syp7j  acl:AccessDenied  http://fcp-indi.s3.amazonaws.com/data/Projects/RocklandSample/RawDataBIDSLatest/.bidsignore?versionId=U2ydFcRBZRBGbEPlqI_LvizDj50Syp7j [E: 403]
```

I will ping fcp-indi folks

**Comment by kyleam** [comment] 2021-02-19 14:55
> I think a the very least, the documentation of `addurls` can be improved?

Feel free to make suggestions/PRs.  As the one that wrote it, I'm certainly not the best person to identify what isn't clear.

**Comment by htwangtw** [comment] 2021-02-19 14:57
I will do so once I have better idea and some more successful attempts with `addurls`! 
Thanks a lot for replying.

**Comment by htwangtw** [comment] 2021-02-22 11:58
To follow up this thread - I have now had some success with my local machine, but not the HPC of my university. The `addurls` function stalls and it's the same if I use `git annex addurl` on a single file. I tried files from fcp-indi bucket as well as openneuro (which should work) but the result.
From datalad debug message:
```
[DEBUG  ] Acquiring a currently existing lock to establish download session. If stalls - check which process holds /its/home/user/.cache/datalad/locks/downloader-auth.lck 
```
The referenced file is blank. 
I am not sure if this is a git annex side issue or datalad. If this is a know issue, please point me to some relevant discussion. It will be good to know if this is something worth talking to my sysadmin about or find an alternative solution (i.e. run my script on some other HPC)

**Comment by kyleam** [comment] 2021-02-22 14:17
> `addurls` function stalls and it's the same if I use `git annex addurl` on a single file

If `git annex addurl` stalls underneath, then `addurls` will stall too, so I'd recommend starting to debug directly with git-annex.  Does `git annex addurl --debug ...` show anything helpful?

**Comment by yarikoptic** [comment] 2021-02-22 14:23
re `/its/home/user/.cache/datalad/locks/downloader-auth.lck` -- it is datalad's.  If you are sure that you are not having another stuck process somewhere (e.g. on another node on HPC) downloading it with datalad, just remove it.

**Comment by yarikoptic** [comment] 2021-02-22 14:29
and since `s3://` urls are not handled by git annex natively, it will go through datalad external special remote, so not sure if direct `git annex addurl` would help much . Best to try direct `datalad download-url`

**Comment by htwangtw** [comment] 2021-02-22 15:31
So far I have tried:
1. `git annex addurl` -> stall
2.  `datalad addurls` -> stall
3. `datalad download-url` -> stall
4. direct download with AWS -> normal
I have asked our sysadmin to check if there are existing jobs running. 

Thanks for being so patients wit my questions. It was not immediately clear to me if the issue was our HPC or datalad.

**Comment by yarikoptic** [comment] 2021-02-22 18:47
re `3. datalad download-url -> stall` -- did you `rm /its/home/user/.cache/datalad/locks/downloader-auth.lck` first?

**Comment by htwangtw** [comment] 2021-02-22 20:38
No, and I will try that!

**Comment by yarikoptic** [comment] 2021-02-24 00:05
@htwangtw please let us know

**Comment by htwangtw** [comment] 2021-02-24 09:50
I have hunt down all process related to datalad and make sure all were killed, deleted the `.lck` file, but the process still stall.
One thing that I can check on my end without the sysadmin is whether my custom procedure is sufficient. Right now it has one line that enables the datalad special remote:
```
git annex initremote datalad type=external externaltype=datalad encryption=none
```
This was enough when I was testing on my local machine

**Comment by Furciferi** [comment] 2021-02-24 10:27
Hi,

Sysadmin mentioned above :)

The issue is arising from the users home directory being on an NFS mount that does not allow file locking.

Does datalad have an env var to point the file lock location to a drive that allows local locking and not tied to the executing users home directory cache?

**Comment by kyleam** [comment] 2021-02-24 14:14
> Does datalad have an env var to point the file lock location to a drive that allows local locking and not tied to the executing users home directory cache?

You should be able to control that by setting `DATALAD_LOCATIONS_CACHE` (or more generally the `datalad.locations.cache` configuration option).

**Comment by htwangtw** [comment] 2021-02-26 11:40
So now I have resolved 
 - typo in my commands
 - understand how to structure the `URL-FILE` for ` datalad addurls` - possiblility of improving docs here
 - cache directory setting and it should not be on a NFS mount (thank @Furciferi for the help!)
 - `datalad download-url` and `datalad addurls` works as expected
My cluster job is basic running and doing what I need!  
This issue is resolved on my end (other than `datalad crawl` that I am not intending on exploring further).
The only one remaining issue doesn't seem to effect my cluster job, and not relevant to downloading stuff from s3. Please advice if it's better to open a separate issue on it.
 
It is the `dataset containing given paths is not underneath the reference dataset` error at the end of runing dataladurls, and I have noticed several existing issues with this error already: https://github.com/datalad/datalad/issues/3928, https://github.com/datalad/datalad-ukbiobank/issues/64
From a brief look the scenario are very similar to mine, and it's probably out of the scope of this issue.
I am happy to follow up on that. Here are the relevant part of my job script that create the error:
<details>
  <summary>commands</summary>
```bash
# filename='ses-BAS1/func/sub-A00008399_ses-BAS1_task-rest_acq-645_physio.json'
# sub='sub-A00008399'
cd ${PROJECT_PATH}/data  # `data` is a datalad dataset created outside of the script
datalad -l warning addurls -d ${sub} -c public_s3 --ifexists skip \
    ${PROJECT_PATH}/scratch/sub_table/${sub}.tsv '{original_path}' '{filename}'
```
</details>

**Comment by kyleam** [comment] 2021-02-26 14:54
> Please advice if it's better to open a separate issue on it.

Yes, please.

If you're able to come up with one, a minimal reproducer would be very helpful, but perhaps the debugging output will be enough to guess what's going on.

**Comment by yarikoptic** [comment] 2021-02-26 15:08
agree with @kyleam .  Meanwhile I will close this issue.  Feel free to reopen if something yet to be done about initial problem/error

**Closed by yarikoptic** 2021-02-26 15:08 UTC

**Comment by htwangtw** [comment] 2021-02-26 16:58
It was a case that I can't read. All good now.

**Comment by YumekaMengjiaLYU** [comment] 2021-10-01 21:48
> Thanks for the detailed issue.
> 
> [Just focusing on the `datalad addurls` error for the moment]
> 
> It looks like the constructed URL doesn't point to the individual file because it is set to just `{bidsroots}`. (Note your url file and cli invocation disagree on the trailing 's'.) So that ends up with a `git annex addurl` call like this (ignoring the destination file name):
> 
> ```
> $ git annex addurl --file test s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest
> [INFO] S3 session: Connecting to the bucket fcp-indi anonymously 
> addurl s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest 
>   CHECKURL failed with no reason given
> failed
> git-annex: addurl: 1 failed
> ```
> 
> Here's a successful call with an individual file:
> 
> ```
> $ git annex addurl --file test s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00010893/sub-A00010893_sessions.tsv
> [INFO] S3 session: Connecting to the bucket fcp-indi anonymously 
> addurl s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00010893/sub-A00010893_sessions.tsv (from datalad) (to test) 
> [INFO] Downloading 's3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00010893/sub-A00010893_sessions.tsv' into '.git/annex/tmp/URL-s196--s3&c%%fcp-indi%data%Projects%Roc-b633b388ebcf6c9847681b617c2e37d0' 
> 100%  196 B             2 KiB/s 0s[INFO] Successfully downloaded s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00010893/sub-A00010893_sessions.tsv into .git/annex/tmp/URL-s196--s3&c%%fcp-indi%data%Projects%Roc-b633b388ebcf6c9847681b617c2e37d0 
> ok
> (recording state in git...)
> ```
> 
> I'm not sure what the underlying problem is, or if it's the same across the different commands, but it's worth checking that you have the datalad special remote enabled:
> 
> ```
> $ git annex info | grep datalad
>  	e0fa5203-ddb2-4a80-b551-b35cb750e2bf -- [datalad]
> ```
> 
> If it's not, you can enable it with
> 
> ```
> $ git annex initremote datalad type=external externaltype=datalad encryption=none
> ```

Thank you so much for this comment. It literally saved my day!! After realizing that my datalad special remote was not enabled and enabling it with 
```
$ git annex initremote datalad type=external externaltype=datalad encryption=none
```
I was able to create the datalad datasets successfully with `datalad addurls`... Thank you @kyleam !!!
