### ISSUE TITLE
test_clone.test_reckless fails with -devel annex: .lck remains group writeable

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4916] opened 2020-09-09 17:33 UTC
Ran into while testing master against annex https://github.com/datalad/datalad/pull/4915 
https://travis-ci.org/github/datalad/datalad/jobs/725619122 and https://travis-ci.org/github/datalad/datalad/jobs/725619124 and https://travis-ci.org/github/datalad/datalad/jobs/725619118 have following clone fail:

```
======================================================================
FAIL: datalad.core.distributed.tests.test_clone.test_reckless(True,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/datalad/core/distributed/tests/test_clone.py", line 364, in check_reckless
    & stat.S_IWGRP)
AssertionError: 16 is not false
```

<details>
<summary>WTF</summary> 

# WTF
## datalad 
  - full_version: 0.13.3
  - version: 0.13.3
## dataset 
  - id: None
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /home/travis/build/datalad/datalad
  - repo: GitRepo
## dependencies 
  - annexremote: 1.4.3
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20200810+git143-gdee38c54d-1~ndall+1
  - cmd:bundled-git: 2.24.0
  - cmd:git: 2.24.0
  - cmd:system-git: 2.27.0
  - cmd:system-ssh: 7.2p2
  - exifread: 2.3.1
  - humanize: 2.6.0
  - iso8601: 0.1.12
  - keyring: 21.4.0
  - keyrings.alt: 3.4.0
  - msgpack: 1.0.0
  - mutagen: 1.45.1
  - requests: 2.24.0
  - tqdm: 4.48.2
  - wrapt: 1.12.1
## environment 
  - GIT_ASKPASS: echo
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US.UTF-8
  - LC_ALL: en_US.UTF-8
  - LC_CTYPE: en_US.UTF-8
  - PATH: /home/travis/virtualenv/python3.6.7/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v10.22.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.3/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin
  - PYTHON_CFLAGS: -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security
  - PYTHON_CONFIGURE_OPTS: --enable-unicode=ucs4 --with-wide-unicode --enable-shared --enable-ipv6 --enable-loadable-sqlite-extensions --with-computed-gotos
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200810+git143-gdee38c54d-1~ndall+1
## location 
  - path: /home/travis/build/datalad/datalad
  - type: dataset
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp: 
    - load_error: None
    - module: datalad.metadata.extractors.xmp
    - version: None
## python 
  - implementation: CPython
  - version: 3.6.7
## system 
  - distribution: debian/stretch/sid
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 290
  - name: Linux
  - release: 4.15.0-1077-gcp
  - type: posix
  - version: #87~16.04.1-Ubuntu SMP Sat Jun 6 01:51:20 UTC 2020

</details>

Test code is

```python
        # the standard setup keeps the annex locks accessible to the user only
        nok_((ds.pathobj / '.git' / 'annex' / 'index.lck').stat().st_mode \
             & stat.S_IWGRP)
```

so far failed to reproduce locally using 3.6 in conda and with `DATALAD_REPO_VERSION=6` as was in one of those runs. but only on that test:
```
DATALAD_REPO_VERSION=6 python -m nose -s -v datalad/core/distributed/tests/test_clone.py:test_reckless
```
and since not observed before I wonder if that is a regression in annex. Could it relate to umask settings? (cannot reproduce also with umask 022).

**Comment by kyleam** [comment] 2020-12-07 21:19
gh-5206, which is set to be closed by gh-5212, was a duplicate of this one.

**Closed by kyleam** 2020-12-07 21:19 UTC

**Comment by yarikoptic** [comment] 2020-12-07 21:45
eh, and I thought I searched.  thanks @kyleam!
