### ISSUE TITLE
question: organizational standards for research data?:

### ISSUE THREAD

**Issue by vsoch** [datalad/datalad#2814] opened 2018-09-12 10:56 UTC
hey Datalad (hey @yarikoptic !) 

We are putting together an organizational and data movement strategy for research computing and the libraries at Stanford, and are looking at standards and tooling to help with versioning, organization and movement. See [this description](https://github.com/schemaorg/schemaorg/issues/2059) to get an overview of an "ideal flow." I am thinking that DataLad could be a really good solution to handle the versioning and general interaction of a dataset! I'm wondering, how is the community creating definitions for organization, and then having datalad be able to plug into them? (You can talk about BIDS as an example!) We would want to be able to have a set of organizational templates that define formats and file structure/organization, and then plug that into use via datalad across Google Cloud storage, compute locations, and then archive. Your wisdom / thoughts / all of the above would be greatly appreciated - very excited to chat about this!

@cmh2166 @hannahfrost @rmarinshaw

**Comment by yarikoptic-gitmate** [comment] 2018-09-12 10:58
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/2303 (Info on metadata standards), https://github.com/datalad/datalad/issues/719 (CRCNS meta-data), https://github.com/datalad/datalad/issues/717 (BALSA meta-data), https://github.com/datalad/datalad/issues/618 (Embrace meta data), and https://github.com/datalad/datalad/issues/2059 (Support GigaDB as a data provider).

**Comment by mih** [comment] 2018-09-12 11:42
Hey @vsoch 
DataLad tries to be agnostic re the metadata you are putting in its datasets. Here are the basic principles:

- any metadata source needs to have an *extractor* implementation
  - extractors read metadata from whatever it is stored in, in whatever format and yield python datatypes    (arbitrary structure, incl. nesting) that can be serialized as JSON
  - extractors can report on two entities: a dataset as a whole, a file (within these units anything goes)
  - extractors can (optionally) also report a vocabulary context (turning JSON into JSON-LD), such a context can identify schema.org as the vocabulary (and possibly extend it)
  - see here for a few examples implementations: https://github.com/datalad/datalad/tree/master/datalad/metadata/extractors

- extractors/metadata sources need to be enabled in a dataset's configuration

- when enabled, an extractor is invoked during metadata aggregation (command `aggregate-metadata`). This lifts the metadata stored in its native form into a representation that DataLad uses internally. This extracted metadata can be placed in superdatasets to enable metadata access for an absent subdataset

- the `metadata` command provides an API to make DataLad report the extracted metadata back to a user (individual pieces or a full dump). The original dataset does not need to be present for this (see aggregation)

- DataLad aims to fulfill the following promises
  - whatever an extractor produces will be reported via the `metadata` command, there should be no limits on size or structure (within reason, I hope)
  - multiple metadata sources will not interact with each other, but leave side-by-side in DataLad's internal representation
  - if it can be JSON-serialized it should work

In conclusion, you should be completely free to do whatever you think is best within these limits. I'd consider anything that breaks a bug.

Notes: 

Beyond being able to "put anything in" the metadata, structure matters a lot, if you care about the size of the software stack that is needed to be able to do anything with these data. In https://github.com/datalad/datalad/issues/2753 we are exploring a useful (nested) structure with a manageable JSON-LD context that could be processed by a query tool that is only able to process tables (not graphs). That may or may not be an issue in your context, but is worth thinking about.

ATM the semantic aspects of working with DataLad's metadata are sketchy (as in it is hard and impractical to work with metadata of an unknown structure and meaning). That is because the existing extractors produce oversimplified metadata without the necessary markup, and by extension DataLad's own query support does not use this information.

However, it sounds like you would not be affected by that, as you are interested in using proper semantic markup, and you want to feed Google's tools with it.

**Comment by yarikoptic** [comment] 2018-09-12 14:03
Besides metadata aspect (even though it might be the main one in your discussion and outlined above by @mih), it would indeed be nice if datalad could interact seamlessly with data archives for data transfer in/out.  The question there would be also how much flexibility you have on your side and what you want to accomplish -- to provide a 
- "data publication" platform (similar to zenodo, figshare - only released versions) or
- "data hosting" (OSF etc - be a part of the research/data exchange process even before "releases").

FWIW, as you might know, we were in touch with some nice folks from Stanford library (from sdr-support group) while preparing a basic [crawler pipeline](https://github.com/datalad/datalad-crawler/pull/17) to provide access to the datasets from the library.  With that you can
```shell
$> datalad create 2012-Mark-Plates
[INFO   ] Creating a new annex repo at /mnt/btrfs/datasets/datalad/crawl-misc/stanford/2012-Mark-Plates 
create(ok): /mnt/btrfs/datasets/datalad/crawl-misc/stanford/2012-Mark-Plates (dataset)

$> cd 2012-Mark-Plates

$> datalad crawl-init --save --template=stanford_lib doc_id=jn023kf3320       
[INFO   ] Creating a pipeline to crawl data files from None 
[INFO   ] Initiating special remote datalad-archives 

$> datalad crawl
...  # still waiting for downloads to finish. I already complained about slow speeds
...  # but I think it remains the issue. Try e.g. on 
...  # https://stacks.stanford.edu/file/druid:qd938sk1220/neurovault_snapshot_2016_05_16.tar
...   # on which I am getting only 800-900 kBps
```
and here you go -- you have git/git-annex repository which would access data from the Stanford library, while if desired publishing to github etc.  Outstanding questions are if we were to crawl the entire library:
  - how to organize datasets - how to name, what possible hierarchy if any
  - and then the question of metadata extraction @mih was talking about, so people could easily find

But that is only for "consumption" of datasets people "publish" there.  Even it is even only a "data publication" platform, ideally there should also be the way to upload datasets there from datalad itself.  One of the possible solutions is a custom exporter like we did for figshare: [export-to-figshare](http://docs.datalad.org/en/latest/generated/man/datalad-export-to-figshare.html) which prepares an archive (Figshare doesn't support subdirectories) of the entire dataset, uploads it to figshare, and backreferences within git-annex so later people could fetch those files via datalad.  Cons: it is a tarball, so to access a subset of files, full tarball needs to be obtained.

An ideal "data publishing/hosting" should allow both push/pull (download/publish) for any of the files while retaining original directory structure.  Then interactions could be established back at the level of git-annex itself, like it does e.g. for S3 now.  And if download of a full or subset is needed - would generate (reproducibly, so sorting the files and injecting consistent archive header) a zipball on the fly.

**Comment by vsoch** [comment] 2018-09-13 13:00
This is hugely helpful! Here is what I understand so far:

 - Datalad is a wrapper of sorts around git-annex - and git-annex is a tool to basically add everything to git minus the files. Meaning I can have version control of metadata for very large datasets. It also means I could have git-annex (controlled via datalad if I like) alongside a traditional git repo.
 - This means that datalad could get deprecated, and the repos I have would still be usable with git-annex (and other tools supporting it)

## Install
When I do datalad search, or datalad install, I'm interacting with datasets [here](http://datasets.datalad.org/) given that I don't specify a URI (e..g., `install //<dataset-name>` and it appears that this "superdataset" is just a github repository, --> https://github.com/datalad/datasets.datalad.org is that correct?  
 - What happens when this single repo gets very large? Is the assumption, for example, that these superdatasets should be organized on the level of groups with specific permissions (e.g., one per lab at Stanford and not one for the entire of Stanford) and then compared or stated to be similar by way of collections? (e.g., Lab A has superdataset turkeys-laba, Lab B has superdataset Lab B, both are under collection "turkeys." I ask because I see a folder called "labs" And a follow up ...
 - What determines the naming of the superdataset? The datasets within?
 - How do I make a superdataset and interact with it?
 - How do I change some default location from /home/vanessa/datalad? If I create it there, does this mean that I cannot install another superdataset without overriding that one?
 - Just as a note, it doesn't give good instructions for installing git-annex. I'm linked to the git-annex page (if I read the docs, period) and then the traditional install page isn't easy to find, I search on Google, I'm taken to it and then install with a package manager, but I still get an error that the version is too old and to "use neurodebian" - I would guess many users don't know what that means.

## Workflow
Okay so now I'm going to pretend to use it for my use case - moving files from some local place to Google Cloud Storage and then archive. I'd start with some folder of data.

 1. First I'd ensure that it conforms to an organizational standard by way of a validator. 
 - Does datalad have validators for structure, or rely on third party (e.g.., BIDS validator). I would want to have a general definition of the structure in a file and then run it over the directories starting at the root, and tell the user what's not right.
 2. When I'm validated, I would want datalad to install a dataset there. The level of dataset can be determined based on my use case. Let's say it's just one big folder with subfolders, each subfolder corresponding to one subject in my study (de-identified).
 3. Adding the datasets to the folder, period, I can commit in the same way with Github. But the validation is up to me? I am able to add a metadata template of sorts, is that checked against the data or just "I trust you" sort of deal? These seem to be the [extractors](https://github.com/datalad/datalad/tree/master/datalad/metadata/extractors). And they tell datalad how to parse files in a dataset, but not ensure they follow the format. What if I need multiple extractors within a single dataset?
 4. Assuming I've added data and have metadata defined, I then want to get it onto Google Cloud. There doesn't seem to be a "put" action - is there an integration with Google Cloud Storage to "put" data there? Based on a version? I would then want to be able to do the equivalent "datalad get <gc://> for that version - this is what the library would do, get the metadata (and organizational) and create an archive on their server.

Thanks for answering my questions! Apologies for the noobness, I'm still reading a lot and getting the hang of the bigger ideas.

**Comment by yarikoptic** [comment] 2018-09-13 13:19
uff... what a nice list of questions/concerns!  I only wonder how should we proceed, since
- replying here is difficult to associate/inline with the questions
- it will grow too long/hard to manage too quick
I wonder if we should try doing it on https://neurostars.org so each question is a separate subthread?  or may be you see a better way? (e.g. a google doc)

**Comment by mih** [comment] 2018-09-13 14:00
@yarikoptic +1 for neurostars or something equally public (not gdocs, please)

**Comment by vsoch** [comment] 2018-09-13 14:51
haha ok, you got it! I'm going for a quick run before the storm comes in, but I'll be on this later today. +1 for a location where the questions can be made modular and preserved until the end of time... or until the database blows up @brainstorm :wink:

**Comment by yarikoptic** [comment] 2018-09-13 15:00
@vsoch would you be so kind to repost it on neurostars with each question into a separate subthread?  I promise to reply promptly ;-)

**Comment by brainstorm** [comment] 2018-09-13 17:56
@vsoch you mean @INCF blowing the neurostars database up since I wasn't working there anymore and warned them **repeatedly** that they should have taken care of it and make snapshots and proper AWS backups? ;)

**Comment by vsoch** [comment] 2018-09-13 21:00
Hmm, neurostars doesn't like me I think :( What should I try? I removed all special links, I'm trying to post to "Uncategorized" with the tag "datalad"

![image](https://user-images.githubusercontent.com/814322/45515539-731b6800-b776-11e8-8776-1471a894b8dc.png)

**Comment by vsoch** [comment] 2018-09-13 21:03
It looks like my EEG container post got flagged as spam by the community a few months back:

![image](https://user-images.githubusercontent.com/814322/45515690-d86f5900-b776-11e8-9afc-8fb61a95e2ef.png)

I guess neurostars isn't going to work. Shall I open issues here instead?

**Comment by vsoch** [comment] 2018-09-13 21:06
Welp, I take what I said back about neurostars... he's turned into a mean phoenix. :/ 
![image](https://user-images.githubusercontent.com/814322/45515849-5fbccc80-b777-11e8-92ef-a88682d371ee.png)

**Comment by vsoch** [comment] 2018-09-13 21:10
I will be opening separate issues here instead. Apologies for the delay!

**Comment by vsoch** [comment] 2018-09-13 21:30
@yarikoptic a clarifying question - what does the crawler give, discovery of what exactly? Couldn't you just do 

```
git annex init
git annex add .
```
or something like to to add all files to a git-annex? You are saying for datalad to generate it's metadata files, it needs to do additional parsing over the git-annex. And this is done basically via running the extractor over the newly added files?

And then if it's the case that you don't crawl (you start from an empty directory) the extractor is called piecewise as you add things to datalad? So something like:

```
git annex add <file> --> datalad add <file> + [ run extractor on file ? ]
```

**Comment by vsoch** [comment] 2018-09-13 21:56
By the way, git-annex and datalad are just... in a word... awesome. These are tools that need to be used / embraced and integrated into daily life because it's by time we have better organization and definition of data and not "the land of the lost scratch space on sherlock where I have no idea where my graduate school data went to be created and die."

**Comment by yarikoptic** [comment] 2018-09-13 22:17
@satra could you help Vanessa to get rid of her illegal status on neurostars? See above https://github.com/datalad/datalad/issues/2814#issuecomment-421152303

PS I guess it is my bad influence which makes my friends inadmissable to sacred places

**Comment by yarikoptic** [comment] 2018-09-13 22:20
crawler is just to automate generation and updates of the datasets from websites and databases like xnat. It is just an addition/extension now, although was the seed for the entire datalad Enterprise - to make available datasets under git/git-annex. That is how we couldn't produce and update those hundreds of datasets we have already.

**Comment by yarikoptic** [comment] 2018-09-13 22:27
There are multiple ways metadata could be stored, provided. Eg you can assign arbitrary simple key/value pairs and tags using git-annex metadata command which will store it within git-annex branch.
Then metadata could be extracted from various files and datasets stored in various formats (PDF, exif in jpeg, bids, etc and also those simple ones stored in git annex branch as I noted above) and placed into files to be kept under git or git-annex. That is the purpose of various metadata extractors in datalad, which are used by datalad aggregate-metadata, which also collects them from subdatasets. Then the topmost superdataset ends up having access to all such aggregated metadata, and you can `datalad search` (did you try it already?) to locate specific datasets and files which might not even yet be installed.

**Comment by yarikoptic** [comment] 2018-09-13 22:29
crawler - yeah, it is a tool you could put on a Cron job ;-) We rerun it manually from time to time ATM

**Comment by yarikoptic** [comment] 2018-09-13 22:29
It is now like git pull ;-)

**Comment by vsoch** [comment] 2018-09-13 22:30
I did try search! It was very cool, but then I realized how many questions I had about what was actually going on. I have to understand details of things otherwise I’m incapable of functioning.

**Comment by yarikoptic** [comment] 2018-09-13 22:31
I think it might be best to just have interactive hangout some time so we could answer all the questions without swyping on the phone too much ;-)

**Comment by yarikoptic** [comment] 2018-09-13 22:34
Would you mind if I add your above praise to https://github.com/datalad/datalad/wiki/Testimonials ? Or best would be if you add it (so we could also discover if that is possible ;-))

**Comment by rmarinshaw** [comment] 2018-09-14 01:26
I note that all institutions have processes, procedures and rules around endorsements.  We of course cannot provide endorsements with attribution as institutional employees.    What we are doing right now is exploring options and capabilities.  It's wonderful that the assessments so far are so positive.  Using open source tooling, when supported by a vibrant community, makes great sense, as Vanessa noted!


Please phone me if you have questions about this or would like to discuss further.


Best regards,


Ruth Marinshaw

Research Computing
Stanford


________________________________

**Comment by yarikoptic** [comment] 2018-09-14 04:00
yikes,  @vsoch - I must not hear any other nice word from you -- I want you to have a healthy relationship with your employer!
so should we remove [that comment](https://github.com/datalad/datalad/issues/2814#issuecomment-421166024) from @vsoch in the thread?  I wonder how many heads we put under the sharp blade with this [page](http://neuro.debian.net/testimonials.html#testimonials) ;-)

**Comment by yarikoptic** [comment] 2018-10-15 20:15
@vsoch I wonder if you are still interested and working on it, and either we could answer any further questions?

**Comment by vsoch** [comment] 2018-10-15 20:28
@yarikoptic work is still hugely underway to define the schema.org Container definitions here --> https://github.com/schemaorg/schemaorg/issues/2059 and on the OCI list. Unfortunately it's a slow process so I can't make it go any faster!

**Comment by yarikoptic** [comment] 2018-10-15 20:38
cool, just wanted to make sure that nothing we could address on our end what  slows you down ;-)

**Comment by satra** [comment] 2018-10-15 21:35
also i should say while every digital blob is data there are different kinds of "data". the dataset descriptor in schema.org and W3C are both reasonably well defined.

**Comment by vsoch** [comment] 2018-10-15 22:18
@satra noted! I technically could use Dataset to describe Dockerfiles, but the more important (harder problem) is including the representation of "Container." So I'm trying that first, because, well, it's what I really want. I can fallback to Dataset if this effort :boom:

**Comment by mih** [comment] 2019-10-05 09:07
Closing "question"-type issue with a response, and no further activity.

**Closed by mih** 2019-10-05 09:07 UTC
Labels: question
