### ISSUE TITLE
publishing: git annex reports lots of failures but publishing seems to "succeed" -- feature or a bug?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#264] opened 2015-10-13 03:17 UTC
```
(git)hopa:~datalad/datalad-debian[master]docs/examples
$> datalad publish-collection ssh://datalad.org/srv/collections.datalad.org/www/demo demo_collection
2015-10-12 23:13:58,866 [ERROR  ] DEBUG: ssh -o "ControlMaster=yes" -o "ControlPath=/var/run/user/47521/datalad/datalad.org" -o "ControlPersist=yes" datalad.org exit (publish_collection.py:153)
bind: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 3389
Could not request local forwarding.
ControlSocket /var/run/user/47521/datalad/datalad.org already exists, disabling multiplexing
2015-10-12 23:13:59,257 [ERROR  ] stderr| Switched to a new branch 'TEMP'
| Switched to a new branch 'TEMP'
| Switched to a new branch 'TEMP' (cmd.py:319)
2015-10-12 23:14:01,079 [ERROR  ] stderr| Switched to a new branch 'publish2' (cmd.py:319)
2015-10-12 23:14:02,743 [ERROR  ] stderr| To ssh://datalad.org/srv/collections.datalad.org/www/demo/demo_handle2
|  * [new branch]      publish2 -> master (cmd.py:319)
2015-10-12 23:14:06,327 [ERROR  ] stderr| To ssh://datalad.org/srv/collections.datalad.org/www/demo/demo_handle2
|  + 6d07677...3b7ed34 git-annex -> git-annex (forced update) (cmd.py:319)
2015-10-12 23:14:08,105 [ERROR  ] stderr| Switched to branch 'master' (cmd.py:319)
2015-10-12 23:14:08,243 [ERROR  ] stderr| Switched to a new branch 'publish2' (cmd.py:319)
2015-10-12 23:14:08,366 [ERROR  ] stderr| To ssh://datalad.org/srv/collections.datalad.org/www/demo/demo_handle1
|  * [new branch]      publish2 -> master (cmd.py:319)
2015-10-12 23:14:08,419 [ERROR  ] stderr| To ssh://datalad.org/srv/collections.datalad.org/www/demo/demo_handle1
|  + 7eba0e1...7292c30 git-annex -> git-annex (forced update) (cmd.py:319)
2015-10-12 23:14:09,418 [ERROR  ] stderr| bind: Address already in use
| channel_setup_fwd_listener_tcpip: cannot listen to port: 3389
 (cmd.py:319)equest local forwarding.
2015-10-12 23:14:09,423 [ERROR  ] stderr| Switched to branch 'master' (cmd.py:319)
2015-10-12 23:14:09,428 [ERROR  ] stderr| Switched to a new branch 'publish_whkONS' (cmd.py:319)
2015-10-12 23:14:09,665 [ERROR  ] stderr| To ssh://datalad.org/srv/collections.datalad.org/www/demo/DATALAD_COL_demo_collection
|  * [new branch]      publish_whkONS -> master (cmd.py:319)
2015-10-12 23:14:09,678 [ERROR  ] stderr| Switched to branch 'master' (cmd.py:319)
2015-10-12 23:15:38,792 [ERROR  ] stderr| Switched to branch 'master'
| Switched to branch 'master'
| git-annex: get: 14684 failed
| Switched to branch 'master' (cmd.py:319)
 (cmd.py:319):15:38,799 [ERROR  ] stderr| Stop listening request sent.
datalad publish-collection  demo_collection  6.08s user 1.05s system 7% cpu 1:40.29 total
(venv-tests)2 13394.....................................:Mon 12 Oct 2015 11:15:38 PM EDT:.
```

so no error exit code but note annex reporting lots of failures for get (why should it get stuff anyways????)

**Comment by bpoldrack** [comment] 2015-10-13 08:55
Well, two things:
1. Whether or not a published annex should try to get things in order to be an actual data source is open to discussion of course. That is just what I assumed to be reasonable. Obviously it's not ;)
So we can change that, of course. 
But, yes, the publishing still kind of succeeds in case the get fails. By now it's intended. The entire publishing strategy is just experimental. We should have a dedicated hangout or sth. on that topic. There is no "definition" of what the publishing "should" do under what circumstances. At least none, that is obvious to me. ;)

2. I can't reproduce why the socket binding doesn't work for you, i.e. what the "bind: Address already in use" is referring to.

**Comment by yarikoptic** [comment] 2015-10-13 16:02
Sucking in all the data should be an option for publishing indeed.  Most common use-case though would be to push in only new/derived data which is not available from other sources... how we do it -- yet to discuss/figure out.

"bind: Address already..." -- I believe because I do use those in my .ssh/config:
```
Host smaug* drogon* falkor*
 ControlMaster yes
 ControlPath ~/.ssh/controls/%r@%h:%p
```
and probably because I had already ongoing connection, but this is just a warning which could be ignored AFAIK... or may be you should change the script to have ControlMaster=auto as well, instead of 'yes'?

**Comment by bpoldrack** [comment] 2015-10-14 05:31
Ah - okay. That's it, yes.
Re: ControlMaster=auto
May be the better option - yes.

**Comment by mih** [comment] 2017-02-09 18:31
The world is a different place now, believe me!


I'll close this as the situation has changed so much that even if a problem of the same description still exists, the content of this issue would not provide relevant guidance for a solution for today's implementation.

**Closed by mih** 2017-02-09 18:31 UTC
