### ISSUE TITLE
Datalad publish ERROR:  stderr: 'error: RPC failed; curl 55 Failed sending data to the peer | fatal: the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by gi114** [datalad/datalad#3632] opened 2019-08-30 20:16 UTC
#### What is the problem and steps
This issue here is in the context of creating and populating a new dataset, creating a github sibling and finally publishing/pushing to github

So I create a sibling after populating my dataset. Everything is tracked so my ```datalad status``` has no output. Here it is my sibling information:

```
$ datalad siblings query -d . --url FRDR-multimodal-dataset
.: here(+) [git]
.: github(-) [https://gi114@github.com/conpdatasets/FRDR-multimodal-dataset.git (git)]
```
Therefore I want to push my changes to github
```
$ datalad publish -r --to github

[INFO   ] Publishing <Dataset path=/data/conp/FRDR-multimodal-dataset> to github 
[ERROR  ] Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(1)                                                                                                                                   
|   cmdline: /usr/lib/git-annex.linux/git -c receive.autogc=0 -c gc.auto=0 push --porcelain --progress github FRDR-dataset git-annex
|   stderr: 'error: RPC failed; curl 55 Failed sending data to the peer
| fatal: the remote end hung up unexpectedly
```

I wonder what it is going on as I cannot fix the problem. I tried to increase the http.postBuffer to 35Gb, which is just above the size of my dataset, but it did not work.

Datalad version: ```datalad 0.12.0rc2```
OS: Linux, Ubuntu 18.04

Thanks you for your help,
Giulia

**Comment by kyleam** [comment] 2019-08-30 20:31
If you run the displayed command from the command line, do you see the same issue?

```
/usr/lib/git-annex.linux/git -c receive.autogc=0 -c gc.auto=0 push --porcelain --progress github FRDR-dataset git-annex
```

If that fails, you can check whether a none bundled git fails (i.e. drop "/usr/lib/git-annex.linux/" from above).  Setting the environment variable GIT_CURL_VERBOSE may also give you something to go on.

**Comment by kyleam** [comment] 2019-08-30 20:43
> I tried to increase the http.postBuffer to 35Gb, which is just above the size of my dataset, but it did not work.

Presumably the bulk of this is content tracked by git-annex rather than git (i.e., files in .git/annex/objects)?

**Comment by gi114** [comment] 2019-09-04 13:57
Hi @kyleam,

Thank you for your answer. I did see the same issue when running the bundle git. I will update you tomorrow after trying the non-bundle and setting the verbose env variable as I will be into work. And yes, the content bulk is tracked by git-annex, that is right

**Comment by gi114** [comment] 2019-09-05 13:56
Hi,

I run the following command 
```
$ GIT_CURL_VERBOSE=1 git -c receive.autogc=0 -c gc.auto=0 push --porcelain --progress github FRDR-dataset git-annex
```
and got this error: 
```
* Couldn't find host github.com in the .netrc file; using defaults
*   Trying 192.30.253.113...
* Connected to github.com (192.30.253.113) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 596 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: github.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: businessCategory=Private Organization,jurisdictionOfIncorporationCountryName=US,jurisdictionOfIncorporationStateOrProvinceName=Delaware,serialNumber=5157550,C=US,ST=California,L=San Francisco,O=GitHub\, Inc.,CN=github.com
* 	 start date: Tue, 08 May 2018 00:00:00 GMT
* 	 expire date: Wed, 03 Jun 2020 12:00:00 GMT
* 	 issuer: C=US,O=DigiCert Inc,OU=www.digicert.com,CN=DigiCert SHA2 Extended Validation Server CA
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /conpdatasets/FRDR-multimodal-dataset.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
User-Agent: git/2.7.4
Accept: */*
Accept-Encoding: gzip
Accept-Language: en-CA, en;q=0.9, *;q=0.8
Pragma: no-cache

< HTTP/1.1 401 Authorization Required
< Server: GitHub Babel 2.0
< Content-Type: text/plain
< Content-Length: 26
< WWW-Authenticate: Basic realm="GitHub"
< X-GitHub-Request-Id: BCE0:44CF:5FAD4B:AFC52A:5D710F43
< X-Frame-Options: DENY
< 
* Ignoring the response-body
* Connection #0 to host github.com left intact
* Issue another request to this URL: 'https://gi114@github.com/conpdatasets/FRDR-multimodal-dataset.git/info/refs?service=git-receive-pack'
* Couldn't find host github.com in the .netrc file; using defaults
* Found bundle for host github.com: 0xb59250 [can pipeline]
* Re-using existing connection! (#0) with host github.com
* Connected to github.com (192.30.253.113) port 443 (#0)
* Server auth using Basic with user 'gi114'
> GET /conpdatasets/FRDR-multimodal-dataset.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
Authorization: Basic Z2kxMTQ6
User-Agent: git/2.7.4
Accept: */*
Accept-Encoding: gzip
Accept-Language: en-CA, en;q=0.9, *;q=0.8
Pragma: no-cache

< HTTP/1.1 401 Authorization Required
< Server: GitHub Babel 2.0
< Content-Type: text/plain
< Content-Length: 29
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic realm="GitHub"
< X-GitHub-Request-Id: BCE0:44CF:5FAD5E:AFC545:5D710F44
< X-Frame-Options: DENY
< 
* Connection #0 to host github.com left intact
* Couldn't find host github.com in the .netrc file; using defaults
* Found bundle for host github.com: 0xb59250 [can pipeline]
* NTLM-proxy picked AND auth done set, clear picked!
* Hostname github.com was found in DNS cache
*   Trying 192.30.253.113...
* Connected to github.com (192.30.253.113) port 443 (#1)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 596 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL re-using session ID
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: github.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: businessCategory=Private Organization,jurisdictionOfIncorporationCountryName=US,jurisdictionOfIncorporationStateOrProvinceName=Delaware,serialNumber=5157550,C=US,ST=California,L=San Francisco,O=GitHub\, Inc.,CN=github.com
* 	 start date: Tue, 08 May 2018 00:00:00 GMT
* 	 expire date: Wed, 03 Jun 2020 12:00:00 GMT
* 	 issuer: C=US,O=DigiCert Inc,OU=www.digicert.com,CN=DigiCert SHA2 Extended Validation Server CA
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
* Server auth using Basic with user 'gi114'
> GET /conpdatasets/FRDR-multimodal-dataset.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
Authorization: Basic Z2kxMTQ6cGFzc3dvcmRvZnRoZWdyb3Vw
User-Agent: git/2.7.4
Accept: */*
Accept-Encoding: gzip
Accept-Language: en-CA, en;q=0.9, *;q=0.8
Pragma: no-cache

< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-receive-pack-advertisement
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: BCE2:2DC9:4D7DB7:96387B:5D710F45
< X-Frame-Options: DENY
< 
* Connection #1 to host github.com left intact
Counting objects: 1116, done.
Compressing objects: 100% (614/614), done.
* Couldn't find host github.com in the .netrc file; using defaults
* Found bundle for host github.com: 0xb59250 [can pipeline]
* Re-using existing connection! (#1) with host github.com
* Connected to github.com (192.30.253.113) port 443 (#1)
* Server auth using Basic with user 'gi114'
> POST /conpdatasets/FRDR-multimodal-dataset.git/git-receive-pack HTTP/1.1
Host: github.com
Authorization: Basic Z2kxMTQ6cGFzc3dvcmRvZnRoZWdyb3Vw
User-Agent: git/2.7.4
Content-Type: application/x-git-receive-pack-request
Accept: application/x-git-receive-pack-result
Content-Length: 4

* upload completely sent off: 4 out of 4 bytes
< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-receive-pack-result
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: BCE2:2DC9:4D8887:9638B2:5D710F45
< X-Frame-Options: DENY
< 
* Connection #1 to host github.com left intact
* Couldn't find host github.com in the .netrc file; using defaults
* Found bundle for host github.com: 0xb59250 [can pipeline]
* Re-using existing connection! (#1) with host github.com
* Connected to github.com (192.30.253.113) port 443 (#1)
* Server auth using Basic with user 'gi114'
> POST /conpdatasets/FRDR-multimodal-dataset.git/git-receive-pack HTTP/1.1
Host: github.com
Authorization: Basic Z2kxMTQ6cGFzc3dvcmRvZnRoZWdyb3Vw
User-Agent: git/2.7.4
Accept-Encoding: gzip
Content-Type: application/x-git-receive-pack-request
Accept: application/x-git-receive-pack-result
Transfer-Encoding: chunked

< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-receive-pack-result
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: BCE2:2DC9:4D88A4:964CDA:5D710F65
< X-Frame-Options: DENY
< 
* Closing connection 1(443/1116), 2.00 GiB | 16.58 MiB/s     
error: RPC failed; curl 55 The requested URL returned error: 401
fatal: The remote end hung up unexpectedly | 16.14 MiB/s   
Writing objects: 100% (1116/1116), 31.27 GiB | 67.90 MiB/s, done.
Total 1116 (delta 344), reused 1083 (delta 337)
fatal: The remote end hung up unexpectedly
Done
```

I am not sure exactly of what is causing the problem

So, let me know what you think

Best
Giulia

**Comment by kyleam** [comment] 2019-09-05 14:15
>  And yes, the content bulk is tracked by git-annex, that is right

I think something is off here.  Even if most the heavy content is now tracked by git-annex, were they included as regular git objects at some point?  If I'm reading the output correctly, it looks like the connection is getting closed at a 2 GiB limit and that Git sees your objects as around 30 GiB.

* What does `git count-objects -vH` report for the repository?

  This should not be in the GiB range.

* What is the `local annex size` line when you run `git annex info` in the repository?

  This should be where the bulk of the size is reported.  This content isn't pushed to GitHub, so it won't cause you to hit into any of their size limits.

**Comment by gi114** [comment] 2019-09-05 18:30
Hi @kyleam,

Thanks for your help, really appreciate it

I run:
```
$ git count-objects -vH
```
And got the following output:
```
count: 209
size: 818.31 MiB
in-pack: 33
packs: 1
size-pack: 30.47 GiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```
Then
```
git annex info
```
```
repository mode: indirect
trusted repositories: 0
semitrusted repositories: 3
	00000000-0000-0000-0000-000000000001 -- web
 	00000000-0000-0000-0000-000000000002 -- bittorrent
 	887fe4cf-571b-4503-94f1-c453416e0c67 -- giuly@giuly-ThinkPad-T480s:~/Documents/NeuroHub/conp-dataset/projects/FRDR-multimodal-dataset [here]
untrusted repositories: 0
transfers in progress: none
available local disk space: 832.87 gigabytes (+1 megabyte reserved)
local annex keys: 0
local annex size: 0 bytes
annexed files in working tree: 0
size of annexed files in working tree: 0 bytes
bloom filter size: 32 mebibytes (0% full)
backend usage: 
```

**Comment by kyleam** [comment] 2019-09-05 19:05
Thanks for reporting back.

> ```
> $ git count-objects -vH
> [...]
> size-pack: 30.47 GiB
> ```

This is why GitHub is rejecting your push.  Your repo has ~30 GiB stored as regular git objects.  You have no files tracked by git-annex:

> ```
> git annex info
> [...]
> local annex keys: 0
> local annex size: 0 bytes
> annexed files in working tree: 0
> size of annexed files in working tree: 0 bytes
> ```

The only solution to make this work with GitHub is removing those large git objects from the repo (throughout the entire history of the branch you're trying to push) and then track those large files with git-annex instead.  You could rewrite the history to do this, but unless there's important information in the history, it'd be easiest to back up the current repo (just in case), wipe out the .git/ directory, and start fresh.  Make sure those large files get added to the annex, not git.

---

In terms of the original error reported, I don't think there's much to be done on DataLad's end, so I'll close this issue, but feel free to follow up with questions.

**Closed by kyleam** 2019-09-05 19:05 UTC

**Comment by gi114** [comment] 2019-09-05 20:52
Hi,

Thanks a lot for your help,

I had the suspect it was something like this when I saw annex size 0 bytes
but I wonder, I thought github would accept ~50GiB and I was sure that
datalad commands would trigger git-annex automatically to add those files.

Maybe this can be implemented if the file content is higher than a certain
threshold.

Best
Giulia



Il giorno gio 5 set 2019 alle ore 15:05 Kyle Meyer <notifications@github.com>
ha scritto:

**Comment by kyleam** [comment] 2019-09-05 22:10
> I had the suspect it was something like this when I saw annex size 0 bytes but I wonder, I thought github would accept ~50GiB

I'm not clear on all the details of their size restrictions, but I do think it is much less than that.  [Here's a page][0] that mentions a 2GB push limit, which is consistent with what you're seeing.

[0]: https://github.community/t5/Support-Protips/Working-with-large-files-and-repositories/ba-p/9343

> and I was sure that datalad commands would trigger git-annex automatically to add those files. 

`datalad add` and `datalad save` will typically add the files to annex, but here are some cases where they'll add files to git directly:

  * They are called with the `--to-git` flag.

  * git-annex is configured to store the content directly in git (more on that below).

  * The repository isn't an annex repository.  This will happen if you call `datalad {add,save}` in a repository that was created with `git init` and `git annex init` has *not* been called.  If you're creating the repository with `datalad create`, you don't have to worry about this because by default it will create an annex repo (i.e, it will call `git annex init` for you).

> Maybe this can be implemented if the file content is higher than a certain threshold.

Continuing from the second point above, git-annex [has a way][1] for configuring which files go where.  You can use this to implement the cutoff.  To use the example at that page, a `.gitattributes` file with

```
* annex.largefiles=(largerthan=100kb)
```

would mean to put files larger than 100kb into annex.

DataLad can configure .gitattributes one common case for you: track text files with git and put everything else into the annex.  You can run `datalad run-procedure cfg_text2git` in an existing annex repo (or use `datalad create -c text2git` when creating a new repo).  That will add the following line to the .gitattributes file:

```
* annex.largefiles=(not(mimetype=text/*))
```

[1]: https://git-annex.branchable.com/tips/largefiles/

**Comment by gi114** [comment] 2019-09-06 14:37
Hi,

Thank you for your message - This is why I got confused as I used a
*datalad create *

I tried adding a file to annex with  *git annex add file* and I looks like
it adds the file but gives this error:





*add 2015-11-18-6-9electrodein-iso0.5.tif ok
 (recording state in git...)fatal: in unpopulated submodule
'projects/FRDR-multimodal'git-annex: user error (xargs
["-0","git","--git-dir=../../../../.git","--work-tree=../../../..","--literal-pathspecs","add","--"]
exited 123)*

Files seem to be tracked by annex and I would now want to clean it. This
brings a question:

What is the difference between all these? If I clean my repository now,
kind of an un-annex operation, am I supposed to see the both back to 0?

1) local annex keys
2) annexed files in working tree

Thanks a lot!!

Giulia



Il giorno gio 5 set 2019 alle ore 18:10 Kyle Meyer <notifications@github.com>
ha scritto:

**Comment by kyleam** [comment] 2019-09-06 15:29
> I tried adding a file to annex with  *git annex add file* and I looks like
> it adds the file but gives this error:
>
> *add 2015-11-18-6-9electrodein-iso0.5.tif ok
>  (recording state in git...)fatal: in unpopulated submodule
> 'projects/FRDR-multimodal'git-annex: user error (xargs
> ["-0","git","--git-dir=../../../../.git","--work-tree=../../../..","--literal-pathspecs","add","--"]
> exited 123)*

The "fatal: in unpopulated submodule" is worrying, but it's hard to
troubleshoot without being able to reproduce the issue.  (Quickly making
an unpopulated submodule, I'm unable to trigger it.)  If you can share a
reliable and minimal recipe for triggering that error, please post it as
a separate issue.  In that issue, it'd be helpful to provide information
on your OS and versions of git, git-annex, and datalad.

> Files seem to be tracked by annex and I would now want to clean it.

I'm guessing for cleaning you're talking about removing the large files
as git objects.  Even if you move those files over to annex now, they
are still present in the repo's history as git objects, so it won't
help.  As I mentioned above, the easiest way to get your repo down to a
size GitHub will take is to start a new repo.

> This brings a question:
>
> What is the difference between all these?  If I clean my repository
> now, kind of an un-annex operation, am I supposed to see the both back
> to 0?
>
> 1) local annex keys
> 2) annexed files in working tree

"local annex keys" reports the number of keys you have in
.git/annex/objects.

"annexed files in working tree" refers to the number of annex files in
the Git working tree.  In the typical case, this is the number of
symlinks to .git/annex/objects that are present in your current branch
plus/minus any uncommitted changes you've made that add/remove annex
files.
