### ISSUE TITLE
Documentation nit...

### ISSUE THREAD

**Issue by dnkennedy** [datalad/datalad#3179] opened 2019-02-25 17:17 UTC
#### What is the problem?
I'm working through a couple of the examples.
On the getting started page (http://docs.datalad.org/en/latest/gettingstarted.html), First Steps section. I was in ~/ for the initial "datalad search NSF" command.
When doing the next suggested command, "datalad install ///openfmri/ds000002" is seems I should have "cd datalad/openfmri" first.

#### What steps will reproduce the problem?
If, from your home directory, you run "datalad search NSF"
and then "datalad install ///openfmri/ds000002"
the 'ds000002' directory will be in the incorrect place...

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.10.2
## system 
  - distribution:  10.12.6/x86_64
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 292
  - name: Darwin
  - release: 16.7.0
  - type: posix
  - version: Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64

**Comment by kyleam** [comment] 2019-02-25 18:07
I find that section confusing too.

> When doing the next suggested command, "datalad install ///openfmri/ds000002" is seems I should have "cd datalad/openfmri" first.

I don't think the second command was intended as follow-up to the first, and the first command certainly isn't needed to run the second.  In the second command's description, "any known dataset can now be installed inside the local superdataset [...]", "local superdataset" would more accurately be "current directory".

Another confusing bit is that this introduces two different flavors of `///`: the [local variant][l] (mentioned in output of the first command) and the [remote variant][r] used in the second install command.

[l]: http://docs.datalad.org/en/latest/basics.html#dataset-argument
[r]: http://docs.datalad.org/en/latest/basics.html#downloading-datalad-s-default-superdataset

**Comment by yarikoptic** [comment] 2019-02-26 02:19
yeah, could be improved.  I guess we could RF that **First steps** to operate on that local clone of `///`, thus adjusting the install command to be `datalad install ~/datalad/openfmri/ds000002`.  And then just adding a remark that in principle every such (sub)dataset is a full featured dataset and could be installed independently into an arbitrary other location (e.g. via `datalad install ///openfmri/ds000002`).
But then someone (voices of revolution are in my head!)  could chime in that "First steps" is not even about search/install but should be about "create/add/save" ;-)
side-topic:
Overall docs clearly could be cleaned up and improved. For starters I think the ["Data management use cases"](http://docs.datalad.org/en/latest/usecases/index.html#chap-usecases) should be one way or another integrated or replaced by [DataLad Features](https://www.datalad.org/features) from the main webpage

**Comment by mih** [comment] 2019-09-20 06:26
This has now been fixed by obliteration ;-)

Better introductory docs are now available in the handbook at http://handbook.datalad.org and the docs at http://docs.datalad.org will (and do) cover more technical aspects and API.

**Closed by mih** 2019-09-20 06:26 UTC
Labels: documentation
