### ISSUE TITLE
publish should 'git annex init' on remote end so it would get 'git config annex.uuid'

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#432] opened 2016-05-10 14:14 UTC
we guess only in case of non-bare repos, e.g. as published to http

**Comment by hanke** [comment] 2016-05-11 13:25
We should have a dedicated publishing "mode" for this. My internal label for this one is "publish as is" -- meaning we aim to create a more-or-less duplicate of a local dataset (with subdatasets) at a remote location. The difference from a plain rsync is that the result should be a fully connected git repository.

**Comment by yarikoptic** [comment] 2016-05-11 13:38
On Wed, 11 May 2016, Michael Hanke wrote:

>    We should have a dedicated publishing "mode" for this. My internal label
>    for this one is "publish as is" -- meaning we aim to create a more-or-less
>    duplicate of a local dataset (with subdatasets) at a remote location. The
>    difference from a plain rsync is that the result should be a fully
>    connected git repository.

but as is means to me that remote location should be as potent annex as
local one.  All annexes should have different uuid's, so something
should init it on the remote end.

**Comment by hanke** [comment] 2016-05-11 13:39
Yes, that is implied.

**Comment by bpoldrack** [comment] 2016-05-24 14:08
Not sure, whether this should be a part of `datalad publish` command, since this functionality is depending on the kind of target you want to publish to. (needs SSH)
So, may be there should be some "post-publish" command instead?

**Comment by bpoldrack** [comment] 2016-05-24 14:11
Alternatively, we may provide a post-update hook for the target via `create-publication-target`, that checks for a git-annex branch, that was created by a push? Something like this ....?

**Comment by yarikoptic** [comment] 2016-05-24 14:19
that is why I kept `*` in the name -- choose the most appropriate point ;)  But I don't think hooks (intended for re-doing things on each push/pull/whatever) is really worth messing with for this -- this is as far as I see it a one time action to perform.

**Closed** 2016-08-08 16:34 UTC
Labels: bug, enhancement
