### ISSUE TITLE
datalad save - no error for inexistent file

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#3925] opened 2019-12-14 07:48 UTC
#### What is the problem?
` datalad save inexistentfile` returns the prompt without any hint that the file does not exist and was not saved/committed.

#### What steps will reproduce the problem?
Simply `datalad save inexistentfile` inside a dataset.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.12.rc6

#### Is there anything else that would be useful to know in this context?
Git instead informs the user there is nothing to commit
```
[dorian@mri newset]$  datalad save inexistentfile
[dorian@mri newset]$ git commit -i inexistentfile -m 'test'
On branch master
nothing to commit, working tree clean
```

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
N/A

**Comment by kyleam** [comment] 2019-12-14 16:23
Thanks for the report.  I'm closing this as a duplicate of gh-3844, but please reopen if I'm mistaken.

**Closed by kyleam** 2019-12-14 16:23 UTC
