### ISSUE TITLE
datalad update -r fails with "AttributeError() [dataset.py:_flyweight_id_from_args:123]"

### ISSUE THREAD

**Issue by soichih** [datalad/datalad#3973] opened 2019-12-29 23:21 UTC
I am running `datalad update -r .` on previously installed datalad superset root directory. It ran for a while and eventually ran into the following error message.

```
update(ok): /mnt/datalad/datasets.datalad.org/workshops/repronim-sfn-2017/challenge (dataset)
[ERROR  ] AttributeError() [dataset.py:_flyweight_id_from_args:123] (AttributeError) 
```

I am using running datalad 0.11.8 on Ubuntu 18.04

**Comment by yarikoptic** [comment] 2019-12-30 01:13
Haven't seen such errors (from flyweight) for a while... Given that update without merge is just a git fetch - strange. Could you try with current master?

**Comment by soichih** [comment] 2020-01-03 22:13
I just ran this again and it finished successfully this time. I didn't update any client or the environment..  Has anything changed on datasets.datalad.org end that fixed it?

**Comment by yarikoptic** [comment] 2020-01-03 23:19
hm... I did re "publish" earlier today to add more datasets.  It should have not been related, but oh well -- bugs are tricky some times ;)  Did you try multiple times originally? if it just crashed once and then you didn't try second time -- I would say that the update I did today is unlikely to relate. 
FWIW, I have created a "manual" (guaranteed to not disappear) snapshot of the entirety of `/srv` on the server, so in principle we could try to reproduce, if the issue was reproducible originally (and if you somehow also got a snapshot of original issue, or remember the state from which you originally installed it).
BTW, in future, if you get into such a crash, rerun with `datalad --dbg` so if it crashes, you end up in `pdb` :  in this particular case 

- code could be improved to provide at least some information in the exception message, and currently it is just
```python
        if path is None:
            raise AttributeError
```
and could have been
```python
        if path is None:
            raise AttributeError("path must not be None. args: %s, kwargs: %s" % (args, kwargs))
```
(I am not even sure why it is AttributeError and not e.g. ValueError, not familiar with this code path).
and then investigate traceback (`bt`) and actual values which lead to this crashing scenario

**Comment by soichih** [comment] 2020-01-03 23:35
I ran 3, 4 times on both Dev and prod instances and I was seeing the same problem. Thank you for looking into this!

**Comment by yarikoptic** [comment] 2020-01-04 00:10
> I ran 3, 4 times on both Dev and prod instances and I was seeing the same problem. Thank you for looking into this!

oh cool.  Then it might be worthwhile trying to reproduce it.   So you had a full `install -r` clone of the entire datasets.datalad.org?  could you check in reflog when you did it.  Then I would use some older snapshot and try to update to the snapshot from yesterday.

Re exception: submitted https://github.com/datalad/datalad/pull/3986

**Comment by soichih** [comment] 2020-01-04 01:23
The problem started happening again. Maybe it was just a fluke that it worked earlier? It's happening when it try to update ds002078.

```
[INFO   ] Fetching updates for <Dataset path=/mnt/datalad/datasets.datalad.org/openneuro/ds002078> 
update(ok): /mnt/datalad/datasets.datalad.org/openneuro/ds002078 (dataset)
Traceback (most recent call last):
  File "/home/hayashis/.local/bin/datalad", line 8, in <module>
    main()
  File "/home/hayashis/.local/lib/python3.6/site-packages/datalad/cmdline/main.py", line 494, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/hayashis/.local/lib/python3.6/site-packages/datalad/interface/base.py", line 628, in call_from_parser
    ret = list(ret)
  File "/home/hayashis/.local/lib/python3.6/site-packages/datalad/interface/utils.py", line 435, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/hayashis/.local/lib/python3.6/site-packages/datalad/interface/utils.py", line 529, in _process_results
    for res in results:
  File "/home/hayashis/.local/lib/python3.6/site-packages/datalad/distribution/update.py", line 196, in __call__
    for r in Dataset(refds_path).add(
  File "/home/hayashis/.local/lib/python3.6/site-packages/datalad/support/repo.py", line 140, in __call__
    id_, new_args, new_kwargs = cls._flyweight_id_from_args(*args, **kwargs)
  File "/home/hayashis/.local/lib/python3.6/site-packages/datalad/distribution/dataset.py", line 123, in _flyweight_id_from_args
    raise AttributeError
AttributeError

> /home/hayashis/.local/lib/python3.6/site-packages/datalad/distribution/dataset.py(123)_flyweight_id_from_args()
-> raise AttributeError
(Pdb) args
cls = <class 'datalad.distribution.dataset.Dataset'>
args = ()
kwargs = {}

```

**Comment by yarikoptic** [comment] 2020-01-04 02:42
oh, not really a fix, but run without '.' in your command!  in other words - not restricting to "itself" ;)  

and now (that I spotted `.`) the mystery for (forgotten behind) https://github.com/datalad/datalad/issues/3097 is "resolved"!  And I think this issue is a duplicate of the elderly #3097, so let's follow up there!

**Closed by yarikoptic** 2020-01-04 02:42 UTC

**Comment by bpoldrack** [comment] 2020-01-06 15:00
@yarikoptic : Just FTR, since you seem to be working on this:

> (I am not even sure why it is AttributeError and not e.g. ValueError, not familiar with this code path).

Probably should be `TypeError`, since it tries to mimic a real call to the respective classes ´__init__`, which should complain with a `TypeError` if you fail to provide a mandatory argument.
