### ISSUE TITLE
datalad save could use parallelism more

### ISSUE THREAD

**Issue by notestaff** [datalad/datalad#2880] opened 2018-09-27 18:52 UTC
I have a repo with many submodules.   datalad save takes a while.  It'd be faster if saving of submodules under independent dirs was done in parallel.

**Comment by notestaff** [comment] 2018-09-27 20:02
Also nested, though not that deeply (2-3 levels?)   Basically I'm trying to consolidate all my projects in one place.

So, I understand that if I have datasets A, A/B, A/B/C, A/D, A/D/E, then C has to be saved before B and E before D; but the A/B/* and A/D/* branches can be done in parallel.

**Comment by notestaff** [comment] 2018-09-30 14:30
" None of the code though is written with thread safety in mind AFAIK" -- at least for read-only operations like diff, this shouldn't be a concern?
git-annex itself is said to be thread-safe; on the other hand, this isn't currently tested ( https://git-annex.branchable.com/git-annex-test/#comment-7315b575dc4c77ac5abf7186423584ec )...
I tend to work on machines with at least 8 cores, often more, so parallelizing would certainly help.

**Comment by mih** [comment] 2018-09-30 14:36
This is already on my list. ATM I am working one level deeper, once this is done, I'll come up for this (ping #2428)

**Comment by notestaff** [comment] 2018-09-30 14:37
@mih thanks a lot!

**Comment by mih** [comment] 2018-10-02 10:42
Q on parallelization within datalad vs in git-annex:

Many relevant annex command can take a `--jobs` argument. In many cases we do not expose this in datalad ATM. If we are adding parallelization in datalad no, we have to think about avoiding oversubscription of resources.

A standard paradigm would be to use a pool of "workers", where the number of workers is limited by hardware specs and/or config. However, if we manage this pool in datalad, we would likely have no other choice but to limit git-annex to `--jobs 1`.

I wonder what is more advantageous: keep datalad single-threaded and (more opportunistically) use git-annexes features, or vice versa? Leaving it to git-annex certainly seems simpler. Any intuitions on how these two might compare re speed-up potential?

**Comment by bpoldrack** [comment] 2018-10-03 09:28
Not really sure either. My intuition is in favor of using annex' parallelization as much as possible. Simply because it's done at a low-level. Let's say we have to add files in a number of datasets. It still seems unlikely to me, that the sheer number of datasets is what is limiting speed, but the number of files involved. If that number actually is low, I wouldn't expect parallelization to matter at all. Annex can do the parallelization on file level anyway, speeding up the time per dataset. The only thing annex can't do but we can is determining which datasets can be dealt with in parallel. The part we have to contribute here is certainly less critical. So, in order to be actually faster we would need to replicate annex' parallelization in addition. Being able to do both should perform best, but takes a lot of effort to figure what number of jobs to assign per call. The factor with higher impact is the one annex already provides though.

**Comment by mih** [comment] 2020-07-31 09:59
I have a dataset with many thousand datasets in it (not yet proper subdatasets/modules, just placed inside). There is no nesting.

`datalad save` (0.13.1) is slow. My starting point was a superdataset with about 700 subdatasets (saved at a rate of 4-5 datasets per second). Next batch with 7k additional subdatasets saves at a rate of just shy over 1/s. The `datalad save` process runs with 25-33% CPU on a quite fast SSD array. The major thing happening seems to be the `git submodule add` subprocesses spawning "occasionally".

**Comment by yarikoptic** [comment] 2020-07-31 14:20
Since we embraced "run git" instead of "use GitPython's internal in memory representation", I see two orthogonal aspects we could look into to speed operations up:
- again checking if we cannot improve speed of running/communication with the commands we run (we have tried many times, but did not get major advance AFAIK, since may be none could be achieved;  startup time of each command contributes, thus I keep pestering Joey to "make standalone fast again")
- embrace `async` more. I believe in many places we run a sequence of external commands which could be`*` ran asynchronously. E.g. looking at the flamegraph, e.g. first  two invocations within `add_submodule` are 

```python
            if not subm.get_hexsha():
                raise InvalidGitRepositoryError(
                    'cannot add subdataset {} with no commits'.format(subm))
            # make an attempt to configure a submodule source URL based on the
            # discovered remote configuration
            remote, branch = subm.get_tracking_branch()
```
so in principle we could async run `get_hexsha` and `get_tracking_branch`. Whenever `get_hexsha` returns None we would raise and I would assume that it would interrupt the `get_tracking_branch` async run as well (or we just need to code for that specifically).  Specifically in this use case - may be we could just avoid `get_hexsha` at all assuming that `get_tracking_branch` would fail with some informative exception of its own so we could just raise `InvalidGitRepositoryError` while handling it?

Another considerable time sink in any datalad call remains `.config` handling (and it needs even more reloads as suggested in https://github.com/datalad/datalad/issues/4364 to fix a still open https://github.com/datalad/datalad/issues/4363).  So, looking again specifically into config handling (e.g. asyncing its multiple invocations of `git`) could provide immediate overall speedup. Also may be config reading could be done "pre-emptively" (right away for any new GitRepo, on timer, etc) thus making it available for possible future use later on.

`*` or could be pre-emptively made to run if we see that in typical use cases earlier commands e.g. used for checking should not fail

**Comment by yarikoptic** [comment] 2020-07-31 14:34
re the first bullet point above -- in the flame graph I see that `__init__` of subprocess doing something for a notable empty period between times it spends in `_execute_child` (for some reason line numbers do not correspond to what I see in subprocess.py even after upgrading to python 3.8.5-1 -- what was yours?)...  if only we had flamegraph with underlying processes also participating -- we could see when/how long the actual underlying command is doing smth useful - may be it is that "blank" period and the rest is just python doing its things to setup all needed machinery?

**Comment by vsoch** [comment] 2020-07-31 14:40
Just a naive question - why can't this be done with a multiproessing queue to speed it up? Are there dependencies between the calls?

**Comment by yarikoptic** [comment] 2020-07-31 15:25
@vsoch : some times yes (like in above -- we might raise exception after the first call) some times not really (like in a config case) - so they could indeed be ran in parallel.

Difficulty somewhat is a "complexity" of datalad code which grew organically through the years. Even though execution helpers are largely centralized within https://github.com/datalad/datalad/blob/master/datalad/cmd.py (older `Runner` and newer async inside `WitlessRunner`), there are more of shims on top of them and some other Popen invocations - introducing changes might be "tricky".  
If interested -- try to accomplish what you are suggesting for config. Around this point
https://github.com/datalad/datalad/blob/master/datalad/config.py#L297
you see two `._run` invocations which could in principle if I see it correctly be done in parallel, and then just logic of processing their outputs need to be streamlined accordingly.  You could test by `python -m nose -s -v datalad/tests/test_config.py` to start with, and if passes those -- try `python -m nose -s -v datalad/support/tests/test_annexrepo.py datalad/support/tests/test_gitrepo.py datalad/distribution/tests/test_dataset.py` to get "fuller" picture of (not)breaking anything ;)

**Comment by yarikoptic** [comment] 2020-07-31 15:31
@mih could you provide a bit more details about setup/invocation for your profiling?  I am trying smth as basic as 

```
$> which py-spy
/tmp/venvs/dev3/bin/py-spy
(dev3) 1 11697.....................................:Fri 31 Jul 2020 11:27:05 AM EDT:.
lena:/tmp
$> which datalad
/usr/bin/datalad
(dev3) 1 11698.....................................:Fri 31 Jul 2020 11:27:09 AM EDT:.
lena:/tmp
$> datalad --version                                                                                                                                                                 
datalad 0.13.1
(dev3) 1 11699.....................................:Fri 31 Jul 2020 11:27:47 AM EDT:.
lena:/tmp
$> rm -rf test; datalad create test; ( cd test; datalad create subm; py-spy record --output /tmp/profile-save.svg --native --subprocesses -r 1000 -- datalad save -m adding; )
[INFO   ] Creating a new annex repo at /tmp/test 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /tmp/test (dataset)
[INFO   ] Creating a new annex repo at /tmp/test/subm 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /tmp/test/subm (dataset)
py-spy> Sampling process 1000 times a second. Press Control-C to exit.

add(ok): /tmp/test/subm (file)
add(ok): /tmp/test/.gitmodules (file)
save(ok): /tmp/test (dataset)
action summary:
  add (ok: 2)
  save (ok: 1)

py-spy> Stopped sampling because process exitted
py-spy> Wrote flamegraph data to '/tmp/profile-save.svg'. Samples: 1690 Errors: 0
Error: No child process (os error 10)
```
with result on http://www.onerussian.com/tmp/profile-save.svg . Even if I zoom in into what I think is the relevant piece

http://www.onerussian.com/tmp/profile-save.svg?x=69.0167%25&y=132

picture is quite different from yours, so I guess I would need a closer reproduction of the use case

**Comment by mih** [comment] 2020-07-31 17:41
I simply attached to the running process. I guess the main difference is that you are sampling all the overhead, while I captured the slow iteration over the submodules (for many more datasets than two).

**Comment by mih** [comment] 2020-08-02 12:23
`datalad saved`ed (added) an additional 8533 clean subdatasets (total of 16k). Now down to rate of 0.6/s

**Comment by mih** [comment] 2020-08-02 12:45
While I agree that parallelization can help in some cases, it is not *that* easy (keep in mind https://github.com/datalad/datalad/pull/4182 and https://github.com/datalad/datalad/pull/4434). Moreover, it hardly helps in my specific case (all subdatasets added straight to a single superdataset).

Given that within `save` our needs regarding `submodule add` are rather minimal (subdataset is in the right place already, we just need to place a subproject commit and the .gitmodules entry, plus do a fake init), we might be able to gain a little speed-up from implementing a dedicated method, rather than going through standard `add_submodule()`. I thought I remembered that @kyleam figured out how a subproject commit was created manually, but I didn't find the code, yet.

Also: at 16k subdatasets, we are looking at a 3MB `.gitmodules` file that is repeatedly opened for incremental modification per each added subdataset.

**Comment by mih** [comment] 2020-08-02 16:50
So something like this should be sufficient to add a subdataset at `./sub` in-place:

```
% git update-index --add --replace --cacheinfo 160000 $(git -C sub log -1 --pretty='%H') sub
% cat << EOT >> .gitmodules      :( 
[submodule "mysub"]
path = sub
url = ./sub
EOT
```
 and to "init" it:

```
% git config --add submodule.mysub.active true
% git config --add submodule.mysub.url /tmp/super/sub
```

**Comment by mih** [comment] 2020-08-03 07:48
Update: With `0.13.1` it takes around 5s to save each additional subdataset when there are already 32k subdataset. This is net cost within a `save` call that saves a lot of subdatasets, hence no `status` or other offset costs included in that time.

**Comment by yarikoptic** [comment] 2020-10-20 02:57
@notestaff may get interested to try https://github.com/datalad/datalad/pull/5022 ? Note: you need python 3.8 or later

**Comment by mih** [comment] 2020-11-11 07:23
#5022 is merged and we are in a different league re speed now.

**Closed by mih** 2020-11-11 07:23 UTC
