### ISSUE TITLE
datalad add subds  adds files within subds to subds

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3232] opened 2019-03-16 23:14 UTC
Relates to #3230, but filed separately since might be obsolete with the revolution's "save does it all" semantic, which if I got it right would replace `add` altogether.
```
(git-annex)hopa:/tmp/superds[master]git-annex
$> datalad create subds1; cd subds1; touch 123; cd ..; datalad add subds1
[INFO   ] Creating a new annex repo at /tmp/superds/subds1 
create(ok): /tmp/superds/subds1 (dataset)
123@  dir/  subdir/  subds1/
add(ok): /tmp/superds/subds1/123 (file)
add(ok): /tmp/superds/subds1 (dataset)
save(ok): /tmp/superds/subds1 (dataset)
action summary:
  add (ok: 2)
  save (ok: 1)
```
so even though current dataset is superds, and IMHO most logical effect would be just adding `subds`   to `superds` (even without `-d`) we instead disregard that we are not under `subds` and perform recursive addition within it.

**Comment by mih** [comment] 2019-03-17 08:03
FTR I think the behavior requested by this issue is implemented in `rev-save`

```
(datalad3-dev) mih@meiner /tmp % dl rev-create this
[INFO   ] Creating a new annex repo at /tmp/this 
create(ok): /tmp/this (dataset)                                                              
(datalad3-dev) mih@meiner /tmp % cd this
(datalad3-dev) mih@meiner /tmp/this (git)-[master] % datalad rev-create subds1
[INFO   ] Creating a new annex repo at /tmp/this/subds1 
create(ok): /tmp/this/subds1 (dataset)                                                       
(datalad3-dev) mih@meiner /tmp/this (git)-[master] % cd subds1; touch 123; cd ..
(datalad3-dev) mih@meiner /tmp/this (git)-[master] % dl rev-status -r
untracked: subds1 (directory)
(datalad3-dev) mih@meiner /tmp/this (git)-[master] % dl rev-save
save(ok): . (dataset)                                                                        
(datalad3-dev) mih@meiner /tmp/this (git)-[master] % dl rev-status -r
 modified: subds1 (dataset)
untracked: subds1/123 (file)
```

**Comment by yarikoptic** [comment] 2019-03-17 14:34
> Please hit merge #3225 ;-)

done

I think that revolution also exhibits the same aspect:

```
$> datalad rev-save subds2
add(ok): 123 (file)
save(ok): subds2 (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)

$> git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	subds2/
```

and that relates to #3230 - while being in a dataset, but not specifying `-d` explicitly, we ignore knowledge of current directory/dataset if path points to subdataset (but sure thing rely on it if dealing with files).  Like here `rev-save subds` became identical to `rev-save -d subds` instead of `rev-save -d . subds`.

**Comment by mih** [comment] 2019-03-18 06:10
Yet to look into it, but please clarify how `subds2` was created, and were it is located wrt the demo above.

**Comment by mih** [comment] 2019-03-20 13:36
Ping @yarikoptic

**Comment by kyleam** [comment] 2019-03-20 13:51
>  but please clarify how `subds2` was created, and were it is located wrt the demo above.

I think it's like this (or at least it shows matching output):

```sh
#!/bin/sh

set -exu

cd $(mktemp -dt dl-3232-XXXX)
datalad rev-create
datalad create subds
touch subds/123
datalad rev-save subds
```

**Comment by mih** [comment] 2019-03-20 13:59
Ah, yes. A path is given to save. That path points to a dataset. No reference dataset is given, hence the indicated dataset will be saved, not the record of the subdataset in the parent -- of which we don't t know that it exists.

**Comment by mih** [comment] 2020-01-10 19:59
I am closing this one. I still think everything is working as intended.

**Closed by mih** 2020-01-10 19:59 UTC
