### ISSUE TITLE
`remove <file>` gives surprising behavior -- should maybe consider PATH argument

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6656] opened 2022-04-27 07:28 UTC
```
% datalad remove myfile.txt
uninstall(error): . (dataset) [to-be-deleted local annex not declared 'dead' at the following siblings. Announce death (`git annex dead here` + `datalad push --to ...`), or ignore via `--reckless undead`: ['fz-juelich.sciebo.de']]
```

I "clearly" wanted to remove a file, but given the default of `--drop=datasets` it aims to drop the containing dataset (undesired), and fails at that (expected).

Ether `drop` isn't called properly to enable the correct discovery of (sub)datasets that would need (or here not need) to be dropped, or there is a different logic error.

**Comment by adswa** [comment] 2022-04-28 11:02
```
❱ datalad --version
datalad 0.16.1+3.gb79037d62.dirty
(handbook) adina@muninn in /tmp
❱ datalad create testing
[INFO   ] Creating a new annex repo at /tmp/testing 
cd tecreate(ok): /tmp/testing (dataset)
(handbook) adina@muninn in /tmp
❱ cd testing
(handbook) adina@muninn in /tmp/testing on git:master
❱ echo 245342 > file1; echo 234653413 > file2
(handbook) adina@muninn in /tmp/testing on git:master
❱ datalad save file2 --to-git
add(ok): file2 (file)                                                           
save(ok): . (dataset)                                                           
action summary:                                                                 
  add (ok: 1)
  save (ok: 1)
(handbook) adina@muninn in /tmp/testing on git:master
❱ datalad save file1         
add(ok): file1 (file)                                                           
save(ok): . (dataset)                                                           
action summary:                                                                 
  add (ok: 1)
  save (ok: 1)
(handbook) adina@muninn in /tmp/testing on git:master
❱ datalad clone -d . \
 https://gin.g-node.org/adswa/bids-data \
 input

install(ok): input (dataset)                                                    
add(ok): input (file)                                                           
add(ok): .gitmodules (file)                                                     
save(ok): . (dataset)                                                           
add(ok): .gitmodules (file)                                                     
save(ok): . (dataset)                                                           
action summary:                                                                 
  add (ok: 3)
  install (ok: 1)
  save (ok: 2)
(handbook) adina@muninn in /tmp/testing on git:master
❱ datalad remove file1 
remove(ok): file1 (file)                                                        
save(ok): . (dataset)                                                           
action summary:                                                                 
  remove (ok: 1)
  save (ok: 1)
(handbook) adina@muninn in /tmp/testing on git:master
❱ datalad remove file2
remove(ok): file2 (file)                                                        
save(ok): . (dataset)                                                           
action summary:                                                                 
  remove (ok: 1)
  save (ok: 1)
(handbook) adina@muninn in /tmp/testing on git:master
❱ datalad remove input 
uninstall(ok): input (dataset)
remove(ok): input (file)                                                        
save(ok): . (dataset)                                                           
action summary:                                                                 
  remove (ok: 1)
  save (ok: 1)
  uninstall (ok: 1)
```

**Comment by adswa** [comment] 2022-05-20 17:03
I'm closing this issue because I couldn't reproduce - please open if you see it happen again!

**Closed by adswa** 2022-05-20 17:03 UTC
Labels: UX, cmd-remove
